- src/System.Text.Formatting/src/System/ReadOnlySpan.cs
- src/System.Text.Formatting/src/System/Span.cs
> Added public Span.CreateArray

- src/System.Text.Formatting/src/System/ReadOnlySpan.cs
Just realized it's not implemented, but I need it for an experiment I am doing.
> Implemented ReadOnlySpan.Slice

- src/System.Text.Formatting/src/System/Text/Formatting/PrimitiveFormatters_uuid.cs
- src/System.Text.Formatting/src/packages.config
- src/System.Text.Formatting/tests/PerformanceTests.cs
Also, added a perf test for Guid formatting
Lastly, removed some packages that were not needed.
> Removed the last alocation from Guid formatting

- demos/CoreClrConsoleApplications/NuGetTasks/NuGetTasks/NuGetTasks.cs
The NuGetTasks.cs file had a mix of tabs and spaces.  This made made the code difficult to
read on GitHub as the formatting was visible incorrect (code shifted left / right).
> Removed tabs

- nuget/System.Text.Formatting.nuspec
- src/System.Text.Formatting/src/System/Text/Formatting/ParsedFormat.cs
- src/System.Text.Formatting/tests/PrimitiveFormattingTests-Guid.cs
Also updated nuspec so I can upload a new nuget package
> Removed Format.Parsed.Symbol completly

- src/System.Text.Formatting/src/System/Text/Formatting/CompositeFormat.cs
Before this change, buffers were flushed (commited) every time a character
of a substring was written. Now the commit happens once per substring.
> Optimized appending substrings

- demos/CoreClrConsoleApplications/HelloWorld/HelloWorld.cs
Basically pay full respects to the original console screen-saver.
Word on the street is that there's this "build"-conference going on soon and some people (like @richlander ) mentioned it would be nice to have this committed before then :)
> HelloWorld: Pimp up the FreeBSD daemon to have colors.

- demos/CoreClrConsoleApplications/HelloWorld/HelloWorld.cs
Closes https://github.com/dotnet/corefxlab/issues/84
> HelloWorld: Add license for BSD Daemon.

- src/System.IO.FileSystem.Watcher.Polling/src/System/IO/Datastructures.cs
- src/System.IO.FileSystem.Watcher.Polling/src/System/IO/FileChange.cs
- src/System.IO.FileSystem.Watcher.Polling/src/System/IO/PathToFileStateHashtable.cs
- src/System.IO.FileSystem.Watcher.Polling/src/System/IO/PollingWatcher.cs
> Added ability to get full path of changed files

- src/System.Text.Formatting/src/System/Text/Parsing/InvariantParser.cs
Also, refactored string->uint parser to now use the ByteSpan parser
> Assed support for UTF16 to ByteSpan parser

- src/System.Drawing.Graphics/src/System/Drawing/Graphics/DLLImports.cs
1. Added copyrights
2. Added namespace
3. Made the class internal
> Cleaned up DLLImports.cs

- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Image.cs
- src/System.Drawing.Graphics/tests/System.Drawing.Graphics.Tests.csproj
Trying to resolve NuGet package build errors
> Removed references to Fluent Assertions(were causing errors)

- src/System.Drawing.Graphics/src/System/Drawing/Graphics/DLLImports.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Image.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/ImageExtensions.cs
- src/System.Drawing.Graphics/tests/UnitTests.cs
Implemented Resize
Tests work for empty images
Implemented Creating an empty image
Tests pass for correct parameters
Would appreciate a code review, @axxu @t-roblo @KrzysztofCwalina especially in unsafe portions in Resize
> Implemented Resize and Create

- src/System.Drawing.Graphics/src/System/Drawing/Graphics/DLLImports.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Image.cs
- src/System.Drawing.Graphics/tests/UnitTests.cs
Also started gdImageCreate working
> Rolling back to making gdImageStruct accessible

- src/System.Drawing.Graphics/src/System/Drawing/Graphics/DLLImports.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Image.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/ImageExtensions.cs
- src/System.Drawing.Graphics/tests/UnitTests.cs
Time to ~party~
Create, Load, Resize., Load all working.
Load, and Resize need more tests.
Making a pull request now so everyone can move forward.
> All basic wrapper methods working

- src/System.Drawing.Graphics/src/System/Drawing/Graphics/DLLImports.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Image.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/ImageExtensions.cs
- src/System.Drawing.Graphics/tests/UnitTests.cs
> Updated some tests and stuff

- src/System.Drawing.Graphics/src/System/Drawing/Graphics/DLLImports.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Image.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/ImageExtensions.cs
- src/System.Drawing.Graphics/tests/UnitTests.cs
commit so we can all get working
> Dalbanhi master

- src/System.Drawing.Graphics/src/System.Drawing.Graphics.csproj
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Image.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/ImageExtensions.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Jpg.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Png.cs
- src/System.Drawing.Graphics/tests/UnitTests.cs
Refactored classes according to Krzysztof's original design for more extensibility.
Figured out how to effectively use alpha blending and the alpha saving flag.
> Alpha Blending and Refactored Classes

- src/System.Drawing.Graphics/src/System/Drawing/Graphics/DLLImports.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Image.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/ImageExtensions.cs
Because there is a file type called bitmap and this will get confusing later on
> Changed bitmap back to image

- src/System.Drawing.Graphics/src/System.Drawing.Graphics.csproj
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Image.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/ImageExtensions.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/LibGDLinuxImports.cs
- src/System.Drawing.Graphics/src/project.lock.json
- src/System.Drawing.Graphics/tests/UnitTests.cs
- src/System.Drawing.Graphics/tests/project.lock.json
- added Linux binaries for LibGD
- created a temporary second copy of the imports using the new binaries (will replace with partial classes later)
- the Create method's basic tests are passing.
- added directive if/elses to Image to separate Windows and Linux versions (Windows temporary doesn't work because I hardcoded a directive in)
> Starting Linux

- src/System.Drawing.Graphics/src/System.Drawing.Graphics.csproj
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/DLLImports.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Image.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/ImageExtensions.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Jpg.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/LibGDLinuxImports.cs
- src/System.Drawing.Graphics/src/System/Drawing/Graphics/Png.cs
- src/System.Drawing.Graphics/tests/UnitTests.cs
>  Fixed memory leak and added better testing routine  

- src/System.Numerics.Matrices/src/System/Numerics/Matrix1x2.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix1x3.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix1x4.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix2x1.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix2x2.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix2x3.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix2x4.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix3x1.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix3x2.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix3x3.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix3x4.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix4x1.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix4x2.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix4x3.cs
- src/System.Numerics.Matrices/src/System/Numerics/Matrix4x4.cs
- src/System.Numerics.Matrices/src/System/Numerics/MatrixTemplate.tt
> Removed C# 6.0 features

- src/System.Drawing.Graphics/src/System/Drawing/Graphics/ImageExtensions.cs
- src/System.Drawing.Graphics/tests/UnitTests.cs
Added image filters for our stretch goal
-iterate through image for each pixel and manipulate using matrix multiplication
-added some default filter matrices (greyscale, sepia, negative)
standing issue: is math for changing alpha value backwards or just counterintuitive?
> Added image filters

- demos/dotnet/dotnet.sln
- demos/dotnet/dotnet/dotnet.cs
- demos/dotnet/dotnet/dotnet.csproj
Added a simple tool to help with command line console application development.
> Added a simple tool for writing console apps 

- demos/dotnet/dotnet/Log.cs
- demos/dotnet/dotnet/dotnet.cs
@ahsonkhan could you review? Thanks.
> Fixed a couple of bugs

- demos/dotnet/dotnet/ProjectProperties.cs
- demos/dotnet/dotnet/dotnet.cs
@KrzysztofCwalina can you please review?
> Adding support for building dlls

- demos/dotnet/dotnet/Log.cs
- demos/dotnet/dotnet/dotnet.cs
This is to shield the tool from unexpected settings in ambient config files
> Added support for explicit nuget.config

- demos/dotnet/dotnet/dotnet.cs
Use the /unsafe compiler option to compile unsafe code.
> Add the ability to compile unsafe code .

- demos/dotnet/dotnet/dotnet.cs
> Remove support for cscoptions.txt

- demos/LibuvWithNonAllocatingFormatters/sample/Program.cs
- demos/LibuvWithNonAllocatingFormatters/sample/Sample.csproj
- demos/LibuvWithNonAllocatingFormatters/sample/packages.config
- demos/LibuvWithNonAllocatingFormatters/src/System.Net.Libuv.csproj
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Handle.cs
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Stream.cs
- demos/LibuvWithNonAllocatingFormatters/src/packages.config
- src/System.Buffers/src/System/Buffers/ArrayBufferPool.cs
In addition, this optimizes allocations in main and fixes an API design issue that sneaked in a previous commit.
> Fixed a bug in BufferPool that caused unecessary allocations 

- demos/LibuvWithNonAllocatingFormatters/sample/Program.cs
- demos/LibuvWithNonAllocatingFormatters/src/System.Net.Libuv.csproj
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Buffer.cs
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Handle.cs
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Idle.cs
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Interop.cs
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Listener.cs
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Loop.cs
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Request.cs
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Stream.cs
- demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Tcp.cs
This is an approach I am trying to enable multithreading. Not sure it's supported by libuv though. Need to test.
> Playing with multithreading

- src/System.Buffers/tests/BasicUnitTests.cs
> Fixed a bug

- src/System.Time/src/System/DateTimeExtensions.cs
- src/System.Time/src/System/TimeZoneOffsetResolvers.cs
- src/System.Time/tests/DateFormattingTests.cs
- src/System.Time/tests/TimeOfDayFormattingTests.cs
> Fix time zone and culture issues

- src/System.Buffers/src/System/ByteSpan.cs
- src/System.Buffers/tests/BasicUnitTests.cs
- src/System.CommandLine/src/project.lock.json
- src/System.CommandLine/tests/project.lock.json
- src/System.Drawing.Graphics/tests/project.lock.json
- src/System.Slices/README.txt
- src/System.Slices/System.Slices.sln
- src/System.Slices/src/System.Slices.csproj
- src/System.Slices/src/System/Contract.cs
- src/System.Slices/src/System/PrimitiveAttribute.cs
- src/System.Slices/src/System/PtrUtils.il
- src/System.Slices/src/System/Span.cs
- src/System.Slices/src/System/SpanExtensions.cs
- src/System.Slices/src/System/SpanHelpers.cs
- src/System.Slices/src/build_module.bat
- src/System.Slices/src/project.json
- src/System.Slices/src/project.lock.json
- src/System.Slices/tests/Harness.cs
- src/System.Slices/tests/System.Slices.tests.csproj
- src/System.Slices/tests/Tests.cs
- src/System.Text.Formatting.Globalization/tests/project.lock.json
- src/System.Text.Formatting/tests/project.lock.json
There are several competing implementation we are considering for slices.
This one is what we call "three field" implementation.
> Adding yet another Slice<T>

- src/System.Slices/src/System/PtrUtils.il
The spelling error made me feel slightly more dirty.
> Coerced some dirtiness out of the comments.

- src/System.Slices/src/System/Span.cs
- src/System.Slices/src/System/SpanExtensions.cs
This is based on @sharwell's feedback
> changed APIs to use start/length instead of start/end

- demos/LowAllocationWebServer/main.cs
- src/System.Text.Formatting.Globalization/src/System/Text/Formatting/FormattingDataProvider.cs
Also, opportunistically changed one of the server demos to prepare it for perf lab.
> Made the Globalization APIs more resilient to silent filures

- demos/LowAllocationWebServer/HttpRequestParser.cs
- demos/LowAllocationWebServer/HttpServer.cs
- demos/LowAllocationWebServer/LowAllocationServer.csproj
- demos/LowAllocationWebServer/SampleServer.cs
- demos/LowAllocationWebServer/SocketInterop.cs
- demos/LowAllocationWebServer/main.cs
- demos/LowAllocationWebServer/packages.config
Also, started to prepare to implement keep alive
> Updated to new packages

- demos/LowAllocationWebServer/HttpRequestParser.cs
And replaced all usage with Utf8String
> removed Utf8Span

- src/System.Text.Formatting/src/System.Text.Formatting.csproj
- src/System.Text.Formatting/src/System/Text/Parsing/InvariantParser.cs
- src/System.Text.Json/src/System.Text.Json.csproj
- src/System.Text.Json/src/System/Text/Json/JsonReader.cs
- src/System.Text.Json/src/project.json
- src/System.Text.Json/tests/JsonReaderTests.cs
- src/System.Text.Json/tests/System.Text.Json.Tests.csproj
Initial implementation.
Please provide feedback.
@krwq @KrzysztofCwalina 
There is a TODO to use SubstringFrom and SubstringTo once it is completed.
> Adding JsonReader and InvariantParser.TryParse uint from Utf8String

- README.md
I am not sure about the wording but this seems like a useful information to have on readme.
> add MyGet feed details to readme

- src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.BoundedChannel.cs
- src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.SerializationChannel.cs
- src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.SpscUnboundedChannel.cs
- src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.UnboundedChannel.cs
- src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.UnbufferedChannel.cs
- src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.cs
- src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/IChannel.cs
- src/System.Threading.Tasks.Channels/tests/ChannelTestBase.cs
- src/System.Threading.Tasks.Channels/tests/ChannelTests.cs
- src/System.Threading.Tasks.Channels/tests/SerializationChannelTests.cs
- Improved XML documentation in a few places
- Changed IWritableChannel.Complete to be IWritableChannel.TryComplete and layered a new Complete extension method on top of it.
> Address some initial PR feedback on System.Threading.Tasks.Channels

- src/System.Buffers/src/System/ByteSpan.cs
- src/System.Buffers/tests/System.Buffers.Tests.csproj
- src/System.Buffers/tests/UsageScenarioTests.cs
- src/System.Slices/src/System/Contract.cs
- src/System.Slices/src/System/PtrUtils.cs
- src/System.Slices/src/System/Span.cs
- src/System.Slices/src/System/SpanExtensions.cs
- src/System.Slices/tests/BasicUnitTests.cs
- src/System.Slices/tests/System.Slices.tests.csproj
- src/System.Slices/tests/UsageScenarioTests.cs
Getting closer with similar public surface. Making sure that scenarios covered by the others tests are working (Span<T> tests work with ByteSpan and reverse)
> Making Spans similar

- .gitignore
- demos/LowAllocationWebServer.Tests/GivenAByteArrayWithHttpHeaders.cs
- demos/LowAllocationWebServer.Tests/LowAllocationWebServer.Tests.csproj
- demos/LowAllocationWebServer.Tests/Properties/AssemblyInfo.cs
- demos/LowAllocationWebServer.Tests/packages.config
- demos/LowAllocationWebServer/ByteSpanExtensions.cs
- demos/LowAllocationWebServer/HttpHeaders.cs
- demos/LowAllocationWebServer/HttpRequestParser.cs
- demos/LowAllocationWebServer/HttpServer.cs
- demos/LowAllocationWebServer/LowAllocationServer.csproj
- demos/LowAllocationWebServer/LowAllocationServer.sln
- demos/LowAllocationWebServer/nuget.config
Added a parser for Headers and implemented HttpHeaders
> Headers parser

- src/System.Buffers/src/System/Buffers/ArrayBufferPool.cs
Small simplification to SelectBinIndex in buffers
> Small simplification to SelectBinIndex in buffers

- demos/QotdService/Service/Program.cs
- demos/QotdService/Service/QotdService.csproj
- src/System.Net.Libuv/src/System/Net/Libuv/Stream.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.cs
- src/System.Text.Utf8/tests/RandomTests.cs
> Removed unsafe code from QOTD service

- src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.cs
See https://github.com/dotnet/corefx/pull/3615 on why this is better.
> Use faster Buffer.BlockCopy

- src/System.Buffers/src/System.Buffers.csproj
- src/System.Buffers/src/System/Buffers/BufferBucket.cs
- src/System.Buffers/src/System/Buffers/BufferPool.cs
- src/System.Buffers/src/System/Buffers/NativeBufferPool.cs
Adding initial, prototype implementation for a value type BufferPool.
/cc @KrzysztofCwalina
> Adding initial, prototype implementation for a value type BufferPool

- nuget/System.CommandLine.nuspec
- nuget/pack.bat
- nuget/push.bat
@KrzysztofCwalina, please take a look.
@ahsonkhan, I've pushed System.CommandLine.0.1.0-d101215-1 to: https://www.myget.org/F/netcore-package-prototyping/api/v2/package.
> Add NuGet package for System.CommandLine

- src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.cs
We need to also add a tests for it. Unfortunately I cannot write unit tests as there is no
way to get RuntimeFiledHandles in .NET Core apps (and the tests are .NET Core apps)
> Adding a ctor to be called by the compiler when it creates literals

- README.md
> Updated "night" to "might"

- src/System.Text.Utf8/src/System.Text.Utf8.csproj
- src/System.Text.Utf8/src/System/Text/Utf16/Utf16LittleEndianEncoder.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8EncodedCodePoint.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8Encoder.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.CodePointEnumerable.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.CodePointEnumerator.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.CodePointReverseEnumerator.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.Enumerator.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.cs
- src/System.Text.Utf8/src/project.lock.json
- src/System.Text.Utf8/tests/PerformanceTests.cs
- src/System.Text.Utf8/tests/RandomTests.cs
- src/System.Text.Utf8/tests/System.Text.Utf8.Tests.csproj
This review is to check if there isn't anything stupid error when converting. After this let's measure perf and merge.
> Convert Utf8String to use Span<byte>

- netci.groovy
Adding groovy script to run the corefxlab build on PR and daily
/cc @mmitche
> Adding groovy script to run the corefxlab build on PR and daily

- src/System.Drawing.Graphics/src/System.Drawing.Graphics.csproj
- src/System.Drawing.Graphics/tests/System.Drawing.Graphics.Tests.csproj
- src/System.Drawing.Graphics/tests/UnitTests.cs
- src/System.Drawing.Graphics/tests/project.json
- src/System.Numerics.Matrices/test/System.Numerics.Matrices.Tests.csproj
- src/System.Slices/tests/UsageScenarioTests.cs
- src/System.Text.Json/src/System.Text.Json.csproj
- src/System.Text.Json/tests/PerfSmokeTests.cs
- src/System.Text.Json/tests/project.json
- src/System.Threading.Tasks.Channels/src/System.Threading.Tasks.Channels.csproj
- src/System.Threading.Tasks.Channels/tests/System.Threading.Tasks.Channels.Tests.csproj
Fixing build breaks due to non-CLS compliant code and proj files
/cc @KrzysztofCwalina
> Fixing build breaks due to non-CLS compliant code and proj files

- samples/CoreApp.sln
- samples/CoreApp/CoreApp.csproj
- samples/CoreApp/Program.cs
- samples/CoreApp/Properties/AssemblyInfo.cs
- samples/CoreApp/project.json
- samples/NetCoreLibrary/Class1.cs
- samples/NetCoreLibrary/NetCoreLibrary.csproj
- samples/NetCoreLibrary/Properties/AssemblyInfo.cs
- samples/NetCoreLibrary/project.json
- samples/NetCoreSample/CoreApp.sln
- samples/NetCoreSample/CoreApp/CoreApp.csproj
- samples/NetCoreSample/CoreApp/Program.cs
- samples/NetCoreSample/CoreApp/Properties/AssemblyInfo.cs
- samples/NetCoreSample/CoreApp/project.json
- samples/NetCoreSample/NetCoreLibrary/Class1.cs
- samples/NetCoreSample/NetCoreLibrary/NetCoreLibrary.csproj
- samples/NetCoreSample/NetCoreLibrary/Properties/AssemblyInfo.cs
- samples/NetCoreSample/NetCoreLibrary/project.json
/cc @Petermarcu, @weshaggard, @davidfowl, @martinwoodward
> Add sample for porting to .NET Core

- netci.groovy
- package.cmd
- src/System.Buffers/src/System.Buffers.csproj
- src/System.Buffers/src/System.Buffers.nuspec
- src/publish-nuget.target
Adding files to generate a NuGet package for the System.Buffers on every official build
/cc @mmitche @chcosta 
/fyi @KrzysztofCwalina
> Adding files to generate a NuGet package for the System.Buffers on every official build

- src/System.Net.Libuv/src/System/Net/Libuv/Stream.cs
- src/System.Net.Libuv/src/project.json
- src/System.Net.Libuv/src/project.lock.json
This change changes the UVStream.IsUnix property from always returning false to returning
the real thing.
> Implement real IsUnix check in the LibUV

- nuget/System.Text.Utf8.nuspec
- package.cmd
Fixing package.cmd to generate and push nuget packages to our myget feed
> Fixing package.cmd to generate and push nuget packages to our myget feed

- src/System.Slices/src/System/PtrUtils.cs
- src/System.Slices/src/System/Span.cs
This looks quite ugly, does this happen automatically perhaps? If it does I don't want these monsters in here.
> add aggressive inlinining attribute on some span getters

- README.md
Fixing README.md to point to the official myget feed
> Fixing README.md to point to the official myget feed

- nuget/System.Buffers.nuspec
- nuget/System.Net.Libuv.nuspec
- nuget/System.Text.Formatting.nuspec
- nuget/System.Text.Json.nuspec
- nuget/System.Text.Utf8.nuspec
Fixing nuspec files to re-add the dependency version numbers
/cc @davidfowl @KrzysztofCwalina
> Fixing nuspec files to re-add the dependency version numbers

- samples/NetCoreSample/CoreApp/CoreApp.csproj
This cleans up a few more things in the sample project.
> Update sample project

- demos/LowAllocationWebServer/HttpServer.cs
- demos/LowAllocationWebServer/Log.cs
- demos/LowAllocationWebServer/LowAllocationServer.csproj
- demos/LowAllocationWebServer/SampleServer.cs
- demos/LowAllocationWebServer/TcpServer.cs
> Refactored/Simplified LowAllocationsServer

- nuget/System.Time.nuspec
This will allow building a nuget package for System.Time library
> Add nuspec file for System.Time library

- nuget/System.Text.Http.nuspec
- nuget/System.Time.nuspec
Fixing up issues with Http nuspec where a typo made it overwrite the Text.Formatting nuspec, creating a cyclical dependency; also, fixing the Time nuspec to place the binaries in the lib folder
> Fixing up issues with nuspec files

- src/System.Buffers/src/project.lock.json
- src/System.Buffers/tests/project.lock.json
- src/System.Collections.Generic.MultiValueDictionary/src/project.lock.json
- src/System.Collections.Generic.MultiValueDictionary/tests/project.lock.json
- src/System.CommandLine/src/project.lock.json
- src/System.CommandLine/tests/project.lock.json
- src/System.Drawing.Graphics/src/project.lock.json
- src/System.Drawing.Graphics/tests/project.lock.json
- src/System.IO.FileSystem.Watcher.Polling/src/project.lock.json
- src/System.IO.FileSystem.Watcher.Polling/tests/project.lock.json
- src/System.Net.Libuv/src/project.lock.json
- src/System.Net.Libuv/tests/project.lock.json
- src/System.Numerics.Matrices/test/project.lock.json
- src/System.Slices/tests/project.lock.json
- src/System.Text.Formatting.Globalization/src/project.lock.json
- src/System.Text.Formatting.Globalization/tests/project.lock.json
- src/System.Text.Formatting/src/project.lock.json
- src/System.Text.Formatting/tests/project.lock.json
- src/System.Text.Http/src/project.lock.json
- src/System.Text.Http/tests/project.lock.json
- src/System.Text.Json/src/project.lock.json
- src/System.Text.Json/tests/project.lock.json
- src/System.Text.Utf8/src/project.lock.json
- src/System.Text.Utf8/tests/project.lock.json
- src/System.Threading.Tasks.Channels/src/project.lock.json
- src/System.Threading.Tasks.Channels/tests/project.lock.json
- src/System.Time/src/project.lock.json
- src/System.Time/tests/project.lock.json
Updating project.json.lock files to be updated to the newest packages and also locking the files to have stable builds.
/cc @livarcocc
> Updating project.json.lock files to be updated to the newest packages and also locking the files to have stable builds.

- samples/NetCoreSample/CoreApp.sln
- samples/NetCoreSample/CoreApp/CoreApp.csproj
- samples/NetCoreSample/CoreApp/project.json
- samples/NetCoreSample/CoreApp/project.lock.json
- samples/NetCoreSample/NetCoreLibrary/project.json
- samples/NetCoreSample/NetCoreLibrary/project.lock.json
- samples/NetCoreSample/NetCoreXunitTestLibrary/NetCoreXunitTestLibrary.csproj
- samples/NetCoreSample/NetCoreXunitTestLibrary/NetCoreXunitTestLibrary.nuget.props
- samples/NetCoreSample/NetCoreXunitTestLibrary/Properties/AssemblyInfo.cs
- samples/NetCoreSample/NetCoreXunitTestLibrary/UnitTest1.cs
- samples/NetCoreSample/NetCoreXunitTestLibrary/project.json
- samples/NetCoreSample/NetCoreXunitTestLibrary/project.lock.json
This adds another sample project that use the .NET Core version of xunit.
> Add sample .NET Core xunit library

- nuget/System.Threading.Tasks.Channels.nuspec
> Add .nuspec for System.Threading.Tasks.Channels

- build.cmd
Fix link to developer guide documentation in build script
> Fix link to developer guide documentation

- nuget/System.Slices.nuspec
- src/System.Slices/src/System/Contract.cs
- src/System.Slices/src/project.json
- src/System.Slices/src/project.lock.json
- src/System.Slices/tests/BasicUnitTests.cs
- src/System.Slices/tests/EqualityTests.cs
- src/System.Slices/tests/UsageScenarioTests.cs
> cleaned up dependencies of System.Slices

- src/System.Text.Formatting/GenerateCompatibilityTests/Program.cs
- src/System.Text.Formatting/src/System/InternalHelpers/IntegerFormatter.cs
- src/System.Text.Formatting/tests/NumberFormattingTests.Generated.cs
- src/System.Text.Formatting/tests/TimeSpanFormattingTests.Generated.cs
Fixes #47 for System.Text.Formatting
> Fix number formatting N format

- src/System.Time/src/Resources/Strings.resx
- src/System.Time/src/System/Date.cs
- src/System.Time/src/System/TimeOfDay.cs
> Add message text to all thrown exceptions in System.Time

- README.md
1. Fix typo.
2. Improve link to Wiki for System.Text.Formatting.
> Add minor improvements for repository README

- README.md
Add description of System.CommandLine component to the main README
> Add description of System.CommandLine component

- src/System.Text.Formatting/src/System/Text/Formatting/CompositeFormat.cs
- src/System.Text.Formatting/tests/CompositeFormattingTests.cs
> Add escaping support for System.Text.Formatting

- nuget/System.Net.Libuv.nuspec
> added native dependency to libuv package nuspec

- src/System.Text.Formatting.Globalization/src/System/Text/Formatting/FormattingDataProvider.cs
1. Wrapped stream in using statement just to make sure the resources are released properly
2. Creation of new Utf8String without usage of CreateArray method, which was unnecessary allocating memory
@KrzysztofCwalina I believe you are the right person to approve this PR ;)
> Formatting.Globalization: memory: less allocations + stream Dispose

- src/System.Text.Formatting/src/System/Text/Formatting/BufferFormatter.cs
- src/System.Text.Formatting/src/System/Text/Formatting/ParsedFormat.cs
- src/System.Text.Formatting/src/System/Text/Formatting/StreamFormatter.cs
- src/System.Text.Formatting/src/System/Text/Formatting/StringFormatter.cs
- src/System.Text.Formatting/src/project.json
- src/System.Text.Formatting/src/project.lock.json
- src/System.Text.Formatting/tests/CompositeFormattingTests.cs
- src/System.Text.Formatting/tests/CustomCulture.cs
- src/System.Text.Formatting/tests/CustomTypeFormatting.cs
- src/System.Text.Formatting/tests/ParsedFormatUnitTests.cs
- src/System.Text.Formatting/tests/PerformanceTests.cs
- src/System.Text.Formatting/tests/PrimitiveFormattingTests.cs
- src/System.Text.Formatting/tests/project.json
- src/System.Text.Formatting/tests/project.lock.json
Trying to fix build breaks after the recent move to the new build system and nuget sources.
> Fixed build breaks in formatting

- src/dirs.proj
Removing text.json.tests and text.formatting test projects from the build to unblock the repo
> Removing text.json.tests and text.formatting test projects from the build

- src/System.Slices/src/System/MemoryUtils.cs
- src/System.Slices/src/System/ReadOnlySpan.cs
- src/System.Slices/src/System/ReadOnlySpanEnumerators.cs
- src/System.Slices/src/System/SpanEqualsExtensions.cs
- src/System.Slices/src/System/SpanExtensions.cs
- src/System.Slices/src/System/SpanExtensionsTemplate.tt
- src/System.Slices/tests/BasicUnitTests.cs
- src/System.Slices/tests/EqualityTests.cs
- src/System.Slices/tests/Tests.cs
- src/System.Slices/tests/UsageScenarioTests.cs
This is mainly copy-paste and some small tweaks from the existing r/w implementation.
@krwq
> Added ReadOnlySpan

- src/System.CommandLine/README.md
Make minor corrections found while reading System.CommandLine's README.md
> Fix a missing word and a couple typos

- dotnet.targets
Making the product build also generate nuget packages
@KrzysztofCwalina @livarcocc
> Making the product build also generate nuget packages

- package.ps1
Fixing the package script to not fail totally on one failure
@KrzysztofCwalina
> Fixing the package script to not fail totally on one failure

- src/System.Slices/src/System/ReadOnlySpan.cs
It is about [this change](https://github.com/dotnet/corefxlab/pull/540).
> Slices: Apply the recent changes of Span to ReadOnlySpan.

- package.ps1
Fixing the publish script to push to the new myget feed
/cc @KrzysztofCwalina @eerhardt
> Fixing the publish script to push to the new myget feed

- NuGet.Config
- dir.props
- dotnet-test.targets
- src/System.Numerics.Matrices/test/project.json
- src/System.Text.Formatting/tests/CompositeFormattingTests.cs
- src/System.Text.Http/tests/GivenIFormatterExtensionsForHttp.cs
- src/dirs.proj
> Re-enabling tests as part of the build and the CI

- NuGet.Config
- dir.props
Changing dir.props to use the new dotnet myget and adding the nuget build feed.
> Changing dir.props to use the new dotnet myget

- src/System.Text.Utf8/src/System/Text/Utf16/Utf16LittleEndianEncoder.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8Encoder.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.Enumerator.cs
- src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.cs
> Utf8: Some optimizations of usage of Spans

- src/System.Slices/src/System/SpanEnumerators.cs
This fruit was hanging very low.
To let  JIT enregister all the fields I've "inlined" Span into Span enumerator.
It makes it almost equal (in codegen and perf) to for loop over a local copy of the Slice.
[Code](https://gist.github.com/omariom/5c54b85eb747f5b46b58)
**Results**: 
BenchmarkDotNet-Dev=v0.8.0+
OS=Microsoft Windows NT 6.9200.0
Processor=Intel(R) Core(TM) i7-3537U CPU @ 00GHz, ProcessorCount=4
HostCLR=MS.NET 0.30319.42000, Arch=64-bit  [RyuJIT]
Type=BenchmarksEnumerator  Mode=Throughput  Platform=X64  Jit=HostJit  .NET=HostFramework  toolchain=Classic  Runtime=Clr  Warmup=2  Target=2  
Method | IntParam |       AvrTime |      StdDev |        op/s |
---------------------- |--------- |-------------- |------------ |------------ |
OLD Slice enumerate |    **8** |    68.0764 ns | …
> Slices: Optimize SpanEnumerator

- src/System.Text.Utf8/src/project.json
This change lowers std library version and dependency contract versions.
> Lowering versions of dependencies

- build.proj
- demos/dotnet/dotnet/dotnet-core/project.lock.json
- dotnet-test.targets
- dotnet.targets
> Stopped doing dnu restore and replaced it with dotnet restore

- tests/System.Buffers.Experimental.Tests/project.json
- tests/System.Collections.Generic.MultiValueDictionary.Tests/project.json
- tests/System.CommandLine.Tests/project.json
- tests/System.Drawing.Graphics.Tests/project.json
- tests/System.IO.FileSystem.Watcher.Polling.Tests/project.json
- tests/System.Net.Libuv.Tests/project.json
- tests/System.Numerics.Matrices.Tests/project.json
- tests/System.Reflection.Metadata.Cil.Tests/project.json
- tests/System.Slices.Tests/project.json
- tests/System.Text.Formatting.Globalization.Tests/project.json
- tests/System.Text.Formatting.Tests/project.json
- tests/System.Text.Http.Tests/project.json
- tests/System.Text.Json.Tests/project.json
- tests/System.Text.Utf8.Tests/project.json
- tests/System.Threading.Tasks.Channels.Tests/project.json
- tests/System.Time.Tests/project.json
> Updating the netstandard version for the tests so that they can run again

- src/System.Collections.Generic.MultiValueDictionary/project.json
- src/System.CommandLine/project.json
- src/System.Drawing.Graphics/project.json
- src/System.IO.FileSystem.Watcher.Polling/project.json
- src/System.Net.Libuv/project.json
- src/System.Reflection.Metadata.Cil/project.json
- src/System.Text.Formatting.Globalization/project.json
- src/System.Text.Formatting/project.json
- src/System.Text.Json/project.json
- src/System.Threading.Tasks.Channels/project.json
cc @KrzysztofCwalina @stephentoub
> Updating dependencies to versions that work with our Tfms

- demos/dotnet/dotnet/dotnet-core/project.lock.json
- src/System.Net.Libuv/project.json
- src/System.Text.Formatting/project.json
- src/System.Text.Json/project.json
- tests/System.Buffers.Experimental.Tests/project.json
- tests/System.Collections.Generic.MultiValueDictionary.Tests/project.json
- tests/System.CommandLine.Tests/project.json
- tests/System.IO.FileSystem.Watcher.Polling.Tests/project.json
- tests/System.Net.Libuv.Tests/project.json
- tests/System.Numerics.Matrices.Tests/project.json
- tests/System.Reflection.Metadata.Cil.Tests/project.json
- tests/System.Slices.Tests/project.json
- tests/System.Text.Formatting.Globalization.Tests/project.json
- tests/System.Text.Formatting.Tests/project.json
- tests/System.Text.Http.Tests/project.json
- tests/System.Text.Json.Tests/project.json
- tests/System.Text.Utf8.Tests/project.json
- tests/System.Threading.Tasks.Channels.Tests/project.json
- tests/System.Time.Tests/project.json
> updated tests to use netstandard

- src/System.Buffers.Experimental/System/Buffers/Multispan.cs
- src/System.Buffers.Experimental/project.json
- tests/System.Buffers.Experimental.Tests/MultispanUnitTests.cs
Very useful when dealing with I/O traffic coming in batches.
> Added Multispan<T>

- src/System.Slices/System/Span.cs
Ultimatelly, I think it will need to pin, but this is to unblock some experiments
I am doing now.
> Changed UnsafePointer to be able to use it with arrays.

- src/System.Binary/System/Binary/BigEndianReader.cs
- src/System.Buffers.Experimental/System/Buffers/Multispan.cs
- src/System.Collections.Generic.MultiValueDictionary/project.json
- src/System.Reflection.Metadata.Cil/CilTypeReference.cs
- tests/System.Binary.Tests/project.json
- tests/System.Buffers.Experimental.Tests/project.json
- tests/System.Collections.Generic.MultiValueDictionary.Tests/project.json
- tests/System.CommandLine.Tests/project.json
- tests/System.IO.FileSystem.Watcher.Polling.Tests/project.json
- tests/System.Net.Libuv.Tests/project.json
- tests/System.Numerics.Matrices.Tests/project.json
- tests/System.Reflection.Metadata.Cil.Tests/project.json
- tests/System.Slices.Tests/project.json
- tests/System.Text.Formatting.Globalization.Tests/project.json
- tests/System.Text.Formatting.Tests/project.json
- tests/System.Text.Http.Tests/project.json
- tests/System.Text.Json.Tests/project.json
- tests/System.Text.Utf8.Tests/project.json
- tests/System.Threading.Tasks.Channels.Tests/project.json
- tests/System.Time.Tests/project.json
The repo no builds with no warnings. Let's keep it as such.
> Fixed build warnings

- scripts/build.ps1
The build script right now is set up to check the `$?` variable after each `dotnet` invocation. Instead, we should check `$lastexitcode` to determine if the invocation failed. The build should still be clean, and CI should automatically catch errors now.
> Actually check the exit code of dotnet commands

- src/System.Binary/System/Binary/BigEndianWriter.cs
- tests/System.Binary.Tests/BasicUnitTests.cs
For now just UInt32. We will add more at some point.
> Added WriteUInt32 to System.Binary

- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.BoundedChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.EnumerableChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.SerializationChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.SpscUnboundedChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.TaskChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.UnboundedChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.UnbufferedChannel.cs
> Handle fallout of removing ValueTask<T> implicit casts

- src/System.Text.Formatting/System/Text/Parsing/InvariantParser_byte.cs
- src/System.Text.Formatting/System/Text/Parsing/InvariantParser_int.cs
- src/System.Text.Formatting/System/Text/Parsing/InvariantParser_long.cs
- src/System.Text.Formatting/System/Text/Parsing/InvariantParser_sbyte.cs
- src/System.Text.Formatting/System/Text/Parsing/InvariantParser_short.cs
- src/System.Text.Formatting/System/Text/Parsing/InvariantParser_uint.cs
- src/System.Text.Formatting/System/Text/Parsing/InvariantParser_ushort.cs
- tests/System.Text.Formatting.Tests/Parsing/ParserTests.cs
Squashed commits from #698. See that PR for full info.
> Parsing for all integer types + tests.

- demos/LowAllocationWebServer/LowAllocationServer.csproj
- demos/LowAllocationWebServer/SampleServer.cs
Eliminated the need to instantiate MemoryStream when writing JSON.
> Updated LowAllocServer to use non-allocating JsonWriter<T>

- demos/LowAllocationWebServer/Framework/HttpServer.cs
- demos/LowAllocationWebServer/SampleServer.cs
> Fixed a small typo

- samples/NetCoreSample/CoreApp/project.json
- samples/NetCoreSample/NetCoreLibrary/project.json
- samples/NetCoreSample/NetCoreXunitTestLibrary/project.json
> Update Sample to use RTM v1.0.0 packages

- tests/System.Text.Primitives.Tests/PrimitivesPerfTests.cs
- tests/System.Text.Primitives.Tests/README.md
New perf tests added to show off server scenario perf increases. Updated tests to remove setup from foreach loop.
> Added new perf tests to show off a few more scenarios.

- src/System.Text.Primitives/System/Text/InvariantParser_byte.cs
- src/System.Text.Primitives/System/Text/InvariantParser_int.cs
- src/System.Text.Primitives/System/Text/InvariantParser_long.cs
- src/System.Text.Primitives/System/Text/InvariantParser_sbyte.cs
- src/System.Text.Primitives/System/Text/InvariantParser_short.cs
- src/System.Text.Primitives/System/Text/InvariantParser_uint.cs
- src/System.Text.Primitives/System/Text/InvariantParser_ulong.cs
- src/System.Text.Primitives/System/Text/InvariantParser_ushort.cs
- tests/System.Text.Primitives.Tests/ParserTests.cs
- tests/System.Text.Primitives.Tests/PrimitivesPerfTests.cs
Significant perf gains by removing dependency on exception handling. Also added new tests to test edge cases.
> Perf Improvement for InvariantParser

- src/System.Text.Formatting/project.json
- src/System.Text.Http/project.json
- src/System.Text.Json/project.json
There were some warnings related to package upgrades. They are causing reporting issues in nightly builds.
> Fixed all warnings in corfxlab build

- src/System.Text.Primitives/System/Text/InvariantParser_float.cs
- tests/System.Text.Primitives.Tests/ParserTests.cs
This is the prototype of the float parsing method. As discussed, this is a "cheat" method for now; we will double back to enhance perf after completing higher priority tasks.
> Added prototype float parsing method.

- corefxlab.sln
- src/System.Numerics.Dec64/System.Numerics.Dec64.xproj
- src/System.Numerics.Dec64/System/Numerics/Dec64.Comparable.cs
- src/System.Numerics.Dec64/System/Numerics/Dec64.Formattable.cs
- src/System.Numerics.Dec64/System/Numerics/Dec64.Maths.cs
- src/System.Numerics.Dec64/System/Numerics/Dec64.Operators.cs
- src/System.Numerics.Dec64/System/Numerics/Dec64.cs
- src/System.Numerics.Dec64/project.json
Ref: https://github.com/dotnet/corefx/issues/10951
See: https://github.com/douglascrockford/DEC64
cc @terrajobst
> Initial interface for Dec64

- src/System.Net.Libuv/project.json
- src/System.Text.Primitives/System/Text/InvariantParser_bool.cs
- src/System.Text.Utf8/System/Text/Utf8/Utf8CodeUnit.cs
- tests/System.Text.Primitives.Tests/ParserTests.cs
- tests/System.Text.Primitives.Tests/ParserTests.tt
For now, just for boolean; I am trying to settle on the right overloads/signatures.
Similar work needs to be done for parsing other types (e.g. int)
> Adding support for parsing string and Utf8String

- tests/System.Binary.Base64.Tests/PerformanceTests.cs
- tests/System.Binary.Base64.Tests/project.json
Early results are that Decode is on par with System.Convert and Encode is 50% slower (when outputting char[])
I will optimize the code in subsequent PRs.
> Added performance tests

- src/System.Binary.Base64/System/Binary/Base64.cs
... at least when destination is aligned.
> Base64.Encode performance improvements

- src/System.Slices/System/ReadOnlySpan.cs
- src/System.Slices/System/Span.cs
- src/System.Text.Utf8/System/Text/Utf8/Utf8String.cs
@KrzysztofCwalina this should fix #832
> added implicit ArraySegment->Spans and explicit ArraySegment<byte>->Utf8String

- Base64.playlist
- src/System.Binary.Base64/System/Binary/Base64.cs
- tests/System.Binary.Base64.Tests/BasicUnitTests.cs
- tests/System.Binary.Base64.Tests/project.json
cc: @mgravell, @davidfowl, @joshfree
> Added Base64 encoding in place

- src/System.Slices/System/Buffers/Bytes.cs
> Moved Bytes to System.Slices

- samples/LowAllocationWebServer/Framework/TcpServer.cs
> Fixed usages of UnsafePointer

- src/System.Text.Formatting/System/Text/Formatting/CompositeFormat.cs
- src/System.Text.Primitives/System/Text/Formatting/PrimitiveFormatter.cs
- tests/System.Text.Formatting.Tests/CompositeFormattingTests.cs
DateTimeOffset, Guid, and Utf8String
Fixes #477
> Added composite formatting support for some missing types

- corefxlab.sln
- src/System.Text.Encodings.Web.Utf8/Properties/AssemblyInfo.cs
- src/System.Text.Encodings.Web.Utf8/System.Text.Encodings.Web.Utf8.xproj
- src/System.Text.Encodings.Web.Utf8/UrlEncoder.cs
- src/System.Text.Encodings.Web.Utf8/project.json
/cc @KrzysztofCwalina @troydai
> Made a stub project to port code from ASP.NET

- src/System.Slices/System/MemoryUtils.cs
- src/System.Slices/System/ReadOnlySpan.cs
- src/System.Slices/System/Span.cs
- src/System.Slices/System/SpanExtensions.cs
- src/System.Slices/System/UnsafeUtilities.cs
- src/System.Slices/project.json
- tests/System.Slices.Tests/OverflowTests.cs
Note I've left  `TryCopyTo` as that needs some additional input rather than just fixing; raised as #848
> Fix multiple 2GiB overflow issues in Span<T>; fixes #846

- samples/LibuvWithNonAllocatingFormatters/Program.cs
- src/System.Buffers.Experimental/System/Buffers/Multispan.cs
- src/System.Buffers.Experimental/System/Buffers/MultispanExtensions.cs
- src/System.Collections.Sequences/System/Collections/Sequences/ISequence.cs
- src/System.Collections.Sequences/System/Collections/Sequences/Position.cs
- src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs
- src/System.Slices/System/SpanSequence.cs
- src/System.Slices/project.json
- src/System.Text.Formatting/System/Text/Formatting/BufferFormatter.cs
- tests/System.Buffers.Experimental.Tests/MultispanUnitTests.cs
- tests/System.Collections.Sequences.Tests/BasicUnitTests.cs
- tests/System.Collections.Sequences.Tests/SampleCollections/ArrayList.cs
- tests/System.Collections.Sequences.Tests/SampleCollections/Hashtable.cs
- tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs
- tests/System.Text.Http.Tests/GivenIFormatterExtensionsForHttp.cs
I am not sure if I am happy with the interface.
It is quite complex to implement. 
I had to change it from the TryGetNext design, as span enumerator cannot store Span<T> between calls to MoveNext and Current.
> Added SpanSequence

- src/System.Buffers.Experimental/System/Buffers/Multispan.cs
- src/System.Buffers.Experimental/System/Buffers/MultispanExtensions.cs
- src/System.Collections.Sequences/System/Collections/Sequences/ISequence.cs
- src/System.Collections.Sequences/System/Collections/Sequences/Position.cs
- src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs
- src/System.Collections.Sequences/System/Collections/Sequences/SequenceEnumerator.cs
- src/System.Slices/System/SpanSequence.cs
- tests/System.Buffers.Experimental.Tests/MultispanUnitTests.cs
- tests/System.Collections.Sequences.Tests/BasicUnitTests.cs
- tests/System.Collections.Sequences.Tests/SampleCollections/ArrayList.cs
- tests/System.Collections.Sequences.Tests/SampleCollections/Hashtable.cs
- tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs
The previous design was a bit faster, but very difficult to reason about and implement correctly.
The Position was carrying two pieces of information (success & position).
Now, success is returned from TryGet and the items is an out parameter.
> Simplified Sequences

- corefxlab.sln
- src/System.Text.Encodings.Web.Utf8/UrlEncoder.cs
- tests/System.Text.Encodings.Web.Utf8.Tests/Properties/AssemblyInfo.cs
- tests/System.Text.Encodings.Web.Utf8.Tests/System.Text.Encodings.Web.Utf8.Tests.xproj
- tests/System.Text.Encodings.Web.Utf8.Tests/UnescapeUrlPathInPlaceTests.cs
- tests/System.Text.Encodings.Web.Utf8.Tests/UnescapeUrlPathTests.cs
- tests/System.Text.Encodings.Web.Utf8.Tests/UrlEncoderTests.cs
- tests/System.Text.Encodings.Web.Utf8.Tests/project.json
> Add Url Unescape 

- samples/LowAllocationWebServer/SampleRestServer.cs
- src/System.Buffers.Experimental/System/Buffers/ManagedBufferPool.cs
- src/System.Slices/System/Buffers/Memory.cs
- src/System.Text.Json.Dynamic/System/Text/Json/JsonLazyDynamicObject.cs
- src/System.Text.Json/System/Text/Json/JsonParseObject.cs
- src/System.Text.Json/System/Text/Json/JsonParser.cs
- src/System.Text.Json/project.json
- tests/System.Text.Json.Tests/JsonObjectTests.cs
Also, made JsonObject and others disposable to return the scratch buffer to the pool
> Added ability to resize JsonParser's db

- docs/Span.md
> Fix typo in Span.md

- docs/Span.md
Added formatting scenario, some clarification the the conversions section, and some notes on language support.
> Added formatting scenario and clarifications

- docs/Span.md
Changed ".Substring()" to ".Slice()"
> (minor edit)

- docs/Span.md
> Moved some open issues to language support section

- src/System.Slices/System/Buffers/OwnedMemory.cs
> Added the ability to subscribe to ref count changes

- src/System.Slices/System/Buffers/Memory.cs
- src/System.Slices/System/Buffers/ReadOnlyMemory.cs
The people have spoken and they did not like the void* parameter. 
cc: @davidfowl; fixes #913
> Made TryGetArray great again

- src/System.Slices/System/Buffers/OwnedMemory.cs
- tests/System.Slices.Tests/MemoryTests.cs
> Callbackparameter and OwnedMemory<T>.Id

- src/System.Slices/System/Buffers/Memory.cs
- src/System.Slices/System/Buffers/MemoryManagers.cs
- src/System.Slices/System/Buffers/OwnedMemory.cs
- src/System.Slices/System/Buffers/ReadOnlyMemory.cs
- tests/System.Slices.Tests/MemoryTests.cs
@davidfowl 
See test for an example of copy-on-reserve.
> Made memory reservation virtual to enable copy-on-reserve

- src/System.Buffers.Experimental/System/Buffers/NativeBufferPool.cs
- src/System.Slices/System/Buffers/Memory.cs
- src/System.Slices/System/Buffers/MemoryManagers.cs
- src/System.Slices/System/Buffers/OwnedMemory.cs
- tests/System.Slices.Tests/MemoryTests.cs
Second attempt at the non-virtual Memory<T>.Span
The other PR got really out of date, and so I will close it.
> Made Memory<T>.Span non-virtual

- src/System.Slices/System/Buffers/MemoryManagers.cs
- src/System.Slices/System/Buffers/OwnedMemory.cs
Fixes #937 
@benaadams, thanks for filing the issue.
> Made OwnerMemory field setters private

- src/System.Binary.Base64/project.json
- src/System.Binary/project.json
- src/System.Collections.Sequences/project.json
- src/System.Slices/project.json
- src/System.Text.Encodings.Web.Utf8/project.json
- src/System.Text.Formatting/project.json
- src/System.Text.Json/project.json
- src/System.Text.Primitives/System/Text/EncodingData.cs
- src/System.Text.Primitives/project.json
- src/System.Text.Utf8/project.json
Some small changes that I accumulated in my "random TODO" list.
> Small changes

- src/System.Binary.Base64/project.json
- src/System.Binary/project.json
- src/System.Buffers.Experimental/System/Buffers/OwnedMemory.cs
- src/System.Buffers.Experimental/project.json
- src/System.Collections.Sequences/project.json
- src/System.Slices/System/Buffers/OwnedArray.cs
- src/System.Slices/project.json
- src/System.Text.Encodings.Web.Utf8/Properties/AssemblyInfo.cs
- src/System.Text.Encodings.Web.Utf8/project.json
- src/System.Text.Formatting/project.json
- src/System.Text.Json/project.json
- src/System.Text.Primitives/project.json
- src/System.Text.Utf8/project.json
- tests/System.Buffers.Experimental.Tests/MemoryTests.cs
- tests/System.Buffers.Experimental.Tests/project.json
- tests/System.Slices.Tests/MemoryTests.cs
plus, myget or nuget don't seem to be handling https icons?
> Moved NativeMemory and PinnedMemory to System.Buffers.Experimental

- samples/LowAllocationWebServer/Framework/HttpServer.cs
- samples/LowAllocationWebServer/Framework/SharedData.cs
- samples/LowAllocationWebServer/SampleRestServer.cs
- src/System.Collections.Sequences/System/Collections/Sequences/SequenceEnumerator.cs
- src/System.Slices/System/Buffers/Memory.cs
- src/System.Slices/System/Buffers/ReadOnlyMemory.cs
The model is now much closer to channels, e.g. using linked list of buffers.
> cleaned shared data after removing multispan.

- src/System.CommandLine/System/CommandLine/ArgumentSyntax.cs
- tests/System.CommandLine.Tests/System/CommandLine/Tests/ArgumentSyntaxTests.cs
> CommandLine: Allow extra arguments

- src/System.IO.Pipelines.Text.Primitives/ReadableBufferExtensions.cs
- src/System.Text.Formatting/System/Text/Parsing/SequenceParser.cs
- src/System.Text.Json/System/Text/Json/JsonParseObject.cs
- src/System.Text.Primitives/System/Text/ParsedFormat.cs
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_bool.cs
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_decimal.cs
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_double.cs
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_float.cs
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_signed.cs
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_signed.tt
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_uint.cs
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_ulong.cs
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_unsigned.cs
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_unsigned.tt
- src/System.Text.Primitives/System/Text/Parsing/Internal/PrimitiveParser_uri.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_Int16.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_Int32.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_Int64.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_SByte.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_UInt16.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_UInt32.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_UInt64.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_bool.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_byte.cs
- tests/System.Text.Primitives.Tests/ParserTests.cs
- tests/System.Text.Primitives.Tests/ParserTests.tt
- tests/System.Text.Primitives.Tests/PrimitiveParserPerfTests.cs
- tests/System.Text.Primitives.Tests/PrimitiveParserTests.cs
cc: @botaberg, @AtsushiKan, @joshfree
> Moved old parsing APIs to InternalParser

- docs/specs/memory.md
@botaberg, @terrajobst, @jkotas, @joshfree, @davidfowl
> Memory spec

- docs/specs/memory.md
@davidfowl, @jkotas, @benaadams, @jaredpar, @joshfree, @botaberg, @vancem, @AtsushiKan
> Added OwnedMemory<T> Pooling to the Specification

- docs/specs/memory.md
cc @davidfowl, @jkotas, @benaadams, @jaredpar, @joshfree, @botaberg, @vancem, @AtsushiKan
> Added Memory.md section on safety

- README.md
@KrzysztofCwalina, thoughts? I've updated the text based on your suggestions.
Skip CI please
> Add link to roadmap and set expectations

- docs/specs/parsing.md
> Record some more of the thinking for parsing

- corefxlab.sln
- scripts/PerfHarness/PerfHarness.cs
- scripts/PerfHarness/project.json
- src/System.Text.Http/System/Text/Http/HttpRequestParser.cs
- tests/Benchmarks/Benchmarks.xproj
- tests/Benchmarks/E2EPipelineNoIO.cs
- tests/Benchmarks/Helpers/Connection.cs
- tests/Benchmarks/Helpers/Listener.cs
- tests/Benchmarks/Helpers/Server.cs
- tests/Benchmarks/Properties/AssemblyInfo.cs
- tests/Benchmarks/project.json
This project will contain a set of benchmarks testsing components in the context of simulated pipelines.
cc: @davidfowl, @joshfree, @ahsonkhan, @botaberg,
> Added End-2-End Perfromance Benchmarks Project

- docs/specs/parsing.md
@terrajobst, @davidfowl, @botaberg, @ahsonkhan, @jkotas, @vancem, @shiftylogic
> Added more details to Parsing design document

- src/System.Slices/System/Buffers/OwnedMemory.cs
- tests/System.Buffers.Experimental.Tests/MemoryTests.cs
- tests/System.Slices.Tests/MemoryTests.cs
This design alters the synchronization to catch a race between
Dispose and AddReference.
By making Dispose of a OwnedMemory first invalidates the _id,
and then check for a zero reference count, and making
AddReference validate the id after increasing the count,
we guarantee that parallel calls to Dispose and Reserve at
least one will fail.
This change also detects some instances of double dispose.
> Improve race detection in OwnedMemory 

- src/System.IO.Pipelines/SeekExtensions.cs
- tests/System.IO.Pipelines.Tests/SeekTests.cs
@davidfowl @halter73 @benaadams
> Port Seek methods from kestel

- docs/specs/encoding.md
cc: @ahsonkhan, @joshfree, @terrajobst, @davidfowl, @shiftylogic
> Added Requirements section to encoding spec

- src/System.Text.Primitives/System/Text/TextEncoding.cs
This *should* be fine AFAIK.
/cc @jkotas
> Remove unncessary stackalloc

- src/System.IO.Pipelines/ReadCursor.cs
- src/System.IO.Pipelines/ReadableBuffer.cs
- src/System.IO.Pipelines/SpanExtensions.cs
> Make Buffer/Cursor ToString output control characters

- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/BoundedChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/ChannelUtilities.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Interactor.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/SingleConsumerUnboundedChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/UnboundedChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/UnbufferedChannel.cs
- src/System.Threading.Tasks.Channels/TODO.md
- tests/System.Threading.Tasks.Channels.Tests/BoundedChannelTests.cs
- tests/System.Threading.Tasks.Channels.Tests/ChannelTests.cs
- tests/System.Threading.Tasks.Channels.Tests/UnboundedChannelTests.cs
Main changes:
- Synchronous continuations are now enabled in more places
- Channel.Create methods now all accept a ChannelOptimizations optional argument
- Waiters have been simplified; cancellation is now pay-for-play, with multiple concurrent waiters all sharing the same task and cancellation as an add-on to that
> More channel improvements

- src/System.Slices/System/SpanExtensions.cs
- src/System.Slices/System/SpanExtensions_array.cs
- src/System.Slices/System/SpanExtensions_binary.cs
- src/System.Slices/System/SpanExtensions_comparisons.cs
- src/System.Slices/System/SpanExtensions_text.cs
- src/System.Text.Http/System/Text/Http/HttpHeaderBuffer.cs
- src/System.Text.Http/System/Text/Http/HttpRequestParser.cs
These updates make the repo build again.
> Ported corfxlab to new System.Memory IndexOf APIs

- samples/LowAllocationWebServer/Framework/RoutingTable.cs
Hi, 
This is simplified fix for routing issue in demo http server
> Routing issue simplified fix

- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/HttpServer.cs
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/ReadWriteBytes.cs
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/SharedData.cs
- samples/LowAllocationWebServer/Shared/SampleServer.cs
And using ReadOnlyBytes instead.
> Removed Linked Buffer

- src/System.IO.Pipelines/FlushAsyncAwaitable.cs
- src/System.IO.Pipelines/IReadableBufferAwaiter.cs
- src/System.IO.Pipelines/Pipe.cs
- src/System.IO.Pipelines/PipelineFactory.cs
- src/System.IO.Pipelines/ReadCursor.cs
- src/System.IO.Pipelines/ReadableBuffer.cs
- src/System.IO.Pipelines/ThrowHelper.cs
- src/System.IO.Pipelines/WritableBuffer.cs
- tests/System.IO.Pipelines.Tests/BackpressureTests.cs
- tests/System.IO.Pipelines.Tests/PipeLenghtTests.cs
- tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
- tests/System.IO.Pipelines.Tests/ReadableBufferFacts.cs
Still not sure about Flush returning bool
@davidfowl @halter73
> [WIP] Add backpressure to pipelines

- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/HttpResponse.cs
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/HttpServer.cs
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/RoutingTable.cs
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/SharedData.cs
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/TcpServer.cs
- samples/LowAllocationWebServer/Shared/SampleServer.cs
Instead the formatter/writer sends the data once it runs out of buffer space. 
I can do it now as I switched to chunked transfer.
> Sample: changed response writer to not use multi-segment buffers

- src/System.CommandLine/System.CommandLine.csproj
The System.resx file was getting built with the wrong namespace.
> Fix System.CommandLine build issue.

- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/HttpServer.cs
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/OwnedBuffer.cs
- src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs
- src/System.Slices/System/Buffers/Memory.cs
- src/System.Slices/System/Buffers/OwnedMemory.cs
- src/System.Slices/System/Buffers/ReadOnlyMemory.cs
- src/System.Slices/System/Runtime/DebuggerViews.cs
Optimized some more base data structures, mainly ReadOnlyBytes.Slice(int)
This change resulted in ~10% improvement in the E2EPipelineTests benchmarks.
cc: @pakrym, @davidfowl, @shiftylogic, @ahsonkhan
> Optimized ReadOnlyBytes

- samples/System.IO.Pipelines.Samples/HttpServer/HttpConnection.cs
- samples/System.IO.Pipelines.Samples/HttpServer/HttpRequestParser.cs
- samples/System.IO.Pipelines.Samples/RawLibuvHttpServerSample.cs
- src/System.IO.Pipelines.Networking.Libuv/UvTcpConnection.cs
- src/System.IO.Pipelines/TaskRunScheduler.cs
- tests/System.IO.Pipelines.Tests/Properties/AssemblyInfo.cs
- tests/System.IO.Pipelines.Tests/SocketsFacts.cs
- Support pipelined http requests in the sample parser
- Added Default to TaskRunScheduler
- Fixes to libuv transport
> Several fixes

- src/System.Buffers.Experimental/System/Buffers/BytesReader.cs
- tests/Benchmarks/BytesReaderBench.cs
- tests/System.Buffers.Experimental.Tests/BytesReader.cs
And fixed a small bug in bytes reader
> Added BytesReader benchmark

- tests/System.Buffers.Experimental.Tests/BytesReader.cs
- tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs
> Skip different tests

- src/System.IO.Pipelines/PipeOptions.cs
> Make limits long-er

- scripts/package.ps1
cc: @mellinoe, @crummel, @shiftylogic, @joshfree, @ahsonkhan, @davidfowl
> Reenabled publishing PDB packages

- src/System.IO.Pipelines/Pipe.cs
/cc @pakrym @halter73 @benaadams
> Don't use tasks to track completion of the pipe

- src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs
- tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs
cc: @ahsonkhan, @shiftylogic, @joshfree
> Added ReadOnlyBytes.CopyTo tests and fixed bugs

- src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs
- tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs
cc: @ahsonkhan, @shiftylogic, @joshfree
> Added more ROB tests

- src/System.IO.Pipelines/Pipe.cs
- src/System.IO.Pipelines/PipeAwaitable.cs
Locking only around commit head and index.
@davidfowl @halter73 thoughts?
> Unlock some parts of pipes

- src/System.IO.Pipelines.Compression/CompressionPipelineExtensions.cs
- src/System.IO.Pipelines/PipeFactory.cs
- src/System.IO.Pipelines/PipelineConnectionExtensions.cs
- src/System.IO.Pipelines/StreamExtensions.cs
> Fix ExecuteCopyToAsync to not return void

- src/System.IO.Pipelines/PipelineConnectionExtensions.cs
- src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8String.cs
> Get span of the heap

- src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs
> Vector IndexOf feedback

- src/System.IO.Pipelines/Pipe.cs
- src/System.IO.Pipelines/PipeAwaitable.cs
> Lock around awaitable state

- src/System.Slices/System/SpanExtensions_binary.cs
- tests/System.Slices.Tests/CastTests.cs
These two APIs will allow us to optimize some code currently using Read/Write
> Added TryWrite and TryRead

- corefxlab.sln
- scripts/build.ps1
- tests/System.IO.Pipelines.Performance.Tests/Enumerators.cs
- tests/System.IO.Pipelines.Performance.Tests/PipeThroughput.cs
- tests/System.IO.Pipelines.Performance.Tests/columns/RpsColumn.cs
- tests/System.IO.Pipelines.Performance.Tests/configs/CoreConfig.cs
Fixes: https://github.com/dotnet/corefxlab/issues/1252
@ahsonkhan
> Fix performance project

- tests/System.IO.Pipelines.Performance.Tests/Program.cs
- tests/System.IO.Pipelines.Performance.Tests/ReadCursorOperationsThroughput.cs
> Added seek performance tests

- src/System.IO.Pipelines/PipeCompletion.cs
- src/System.IO.Pipelines/PipelineConnectionExtensions.cs
- tests/System.IO.Pipelines.Performance.Tests/PipeThroughput.cs
Is busy on the async
Valid change?
/cc @pakrym @davidfowl @halter73
> Only await non-complete writes

- src/System.IO.Pipelines/ReadableBufferReader.cs
- tests/System.IO.Pipelines.Tests/ReadableBufferReaderFacts.cs
- This allows us to write simpler code to handle single
and multispan cases without too much special casing
- Added tests
> Exposed the span and index from ReadableBufferReader

- src/System.IO.Pipelines/ReadableBufferReader.cs
- Don't inline MoveNext()
- Don't call Peek from Take
- Use locals in MoveNext()
> Minor changes to ReadableBufferReader

- src/System.Slices/System/SpanExtensions_binary.cs
- src/System.Slices/System/SpanExtensions_comparisons.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser_Boolean.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser_Decimal.cs
- src/System.Text.Primitives/System/Text/Parsing/Signed.cs
- src/System.Text.Primitives/System/Text/Parsing/Signed.tt
- src/System.Text.Primitives/System/Text/Parsing/Unsigned.cs
- src/System.Text.Primitives/System/Text/Parsing/Unsigned.tt
- tests/System.Slices.Tests/CastTests.cs
- tests/System.Slices.Tests/OverflowTests.cs
- tests/System.Text.Primitives.Tests/PrimitiveParserIntegerTests.cs
- tests/System.Text.Primitives.Tests/PrimitiveParserIntegerTests.tt
> Replace Cast extension method with either NonPortableCast or Unsafe

- samples/System.IO.Pipelines.Samples/HttpServer/HttpRequestStream.cs
- src/System.IO.Pipelines.Extensions/PipelineConnectionStream.cs
- src/System.IO.Pipelines.Extensions/PipelineReaderExtensions.cs
- src/System.IO.Pipelines/PipelineReaderExtensions.cs
- tests/System.IO.Pipelines.Tests/PipelineWriterFacts.cs
- tests/System.IO.Pipelines.Tests/UnownedBufferReaderFacts.cs
- Move extensions to Pipelines.Extensions assembly for now
#1282
> Change async extension methods that take span to take ArraySegment

- src/System.Buffers.Primitives/System/Buffers/MemoryHandle.cs
- src/System.IO.Pipelines.Networking.Libuv/UvTcpConnection.cs
See discusion in #1312.
(CC @KrzysztofCwalina @davidfowl @Drawaes @KodrAus @pdeligia)
> Made MemoryHandle Free Idempotent

- src/System.IO.Pipelines.File/FileReader.cs
- src/System.IO.Pipelines.Networking.Libuv/UvTcpConnection.cs
- src/System.IO.Pipelines.Networking.Sockets/SocketConnection.cs
- src/System.IO.Pipelines/FlushResult.cs
- src/System.IO.Pipelines/IPipeWriter.cs
- src/System.IO.Pipelines/IWritableBufferAwaiter.cs
- src/System.IO.Pipelines/Pipe.cs
- src/System.IO.Pipelines/WritableBufferAwaitable.cs
- tests/System.IO.Pipelines.Tests/BackpressureTests.cs
- tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
- tests/System.IO.Pipelines.Tests/PipelineWriterFacts.cs
> Add FlushAsync cancellation support

- src/System.Buffers.Experimental/System/Buffers/OwnedNativeMemory.cs
- src/System.Buffers.Experimental/System/Buffers/OwnedPinnedArray.cs
- Added OwnedNativeMemory and OwnedPinnedArray class files
> Move classes out of the same file

- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/OwnedBuffer.cs
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/ReadWriteBytes.cs
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/RoutingTable.cs
- src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs
- src/System.Collections.Sequences/System/Collections/Sequences/ArrayList.cs
- src/System.Collections.Sequences/System/Collections/Sequences/ISequence.cs
- src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs
- src/System.IO.Pipelines/ReadableBuffer.cs
- src/System.Text.Http/System/Text/Http/HttpRequest.cs
- tests/System.Collections.Sequences.Tests/SampleCollections/Hashtable.cs
- tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs
The property is/was not really used.
> Removed Length:int? property from ISequence

- tests/Benchmarks/ComparisonBench.cs
> Adding a simple performance test for Span+Slice vs Slice+Span

- src/System.IO.Pipelines/Pipe.cs
- src/System.IO.Pipelines/PipeAwaitable.cs
- src/System.IO.Pipelines/ThrowHelper.cs
- tests/System.IO.Pipelines.Tests/BackpressureTests.cs
- tests/System.IO.Pipelines.Tests/WritableBufferFacts.cs
> Throw if advancing past the Memory size

- src/System.Buffers.Primitives/System/Buffers/Buffer.cs
- src/System.Buffers.Primitives/System/Buffers/BufferPool.cs
- src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs
- src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs
- src/System.Buffers.Primitives/System/Internal/ManagedBufferPool.cs
- src/System.Buffers.Primitives/System/Internal/OwnedArray.cs
- src/System.IO.Pipelines/MemoryPool.cs
The only public change is OwnedBuffer.ReadOnlyMemory -> OwnedBuffer.ReadOnlyBuffer.
> Cleanup of System.Buffers.Primitives

- src/System.IO.Pipelines/WritableBufferWriter.cs
- tests/System.IO.Pipelines.Tests/WritableBufferWriterFacts.cs
> Add ensure to WritableBufferWriter

- src/System.IO.Pipelines/ThrowHelper.cs
- src/System.IO.Pipelines/WritableBufferWriter.cs
- tests/System.IO.Pipelines.Tests/WritableBufferWriterFacts.cs
Resolves https://github.com/dotnet/corefxlab/issues/1366
/cc @pakrym @davidfowl
> Fix WritableBufferWriter.Write bounds check

- src/System.IO.Pipelines/MemoryEnumerator.cs
> (BufferEnumerator) Don't use Empty for discardable result 

- src/System.IO.Pipelines/WritableBufferWriter.cs
- tests/System.IO.Pipelines.Tests/WritableBufferWriterFacts.cs
> Fix Write(source, offset, length) fast path check

- src/System.Text.Http.Parser/HttpParser.cs
- tests/System.Text.Http.Parser.Tests/BadHttpRequestTests.cs
- tests/System.Text.Http.Parser.Tests/HttpParsingData.cs
- tests/System.Text.Http.Parser.Tests/StringExtensions.cs
Added first batch of parser validation tests from Kestrel codebase.
Will add second batch in a subsequent PR
> Added HTTP parser tests

- src/System.IO.Pipelines/WritableBufferExtensions.cs
- tests/System.IO.Pipelines.Performance.Tests/PipeThroughput.cs
> Turn FastWrite into another WB.Write extension overload

- src/System.Buffers.Primitives/System/Buffers/BufferHandle.cs
- src/System.IO.Pipelines/UnownedBuffer.cs
> Changes to simplify kestrel bysource injestion of corefxlab

- src/System.IO.Pipelines.Extensions/PipelineConnectionStream.cs
- src/System.IO.Pipelines/PipelineWriterExtensions.cs
- src/System.IO.Pipelines/WritableBufferExtensions.cs
- tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
- tests/System.IO.Pipelines.Tests/PipelineWriterFacts.cs
- tests/System.IO.Pipelines.Tests/SocketsFacts.cs
- tests/System.IO.Pipelines.Tests/UnownedBufferReaderFacts.cs
> Remove WriteAsync overloads that take span

- src/System.IO.Pipelines/Pipe.cs
- src/System.IO.Pipelines/PipeAwaitable.cs
- tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
> Try read no longer checks the awaiter, tests included

- src/System.IO.Pipelines.Extensions/UnownedBufferReader.cs
- src/System.IO.Pipelines/IPipeReader.cs
- src/System.IO.Pipelines/Pipe.cs
- src/System.IO.Pipelines/PipeAwaitable.cs
- src/System.IO.Pipelines/WritableBuffer.cs
- tests/System.IO.Pipelines.Tests/BackpressureTests.cs
- tests/System.IO.Pipelines.Tests/FlushAsyncCancellationTests.cs
- tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
- tests/System.IO.Pipelines.Tests/ReadAsyncCancellationTests.cs
- tests/System.IO.Pipelines.Tests/UnownedBufferReaderFacts.cs
> Add cancellation token support to FlushAsync and ReadAsync

- src/System.IO.Pipelines/Pipe.cs
- src/System.IO.Pipelines/ThrowHelper.cs
- tests/System.IO.Pipelines.Tests/BackpressureTests.cs
Fixes: https://github.com/dotnet/corefxlab/issues/1381
> Prevent deadlock when advancing

- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/OwnedBuffer.cs
- src/System.Buffers.Experimental/System/Buffers/BufferManager.cs
- src/System.Buffers.Experimental/System/Buffers/OwnedNativeBuffer.cs
- src/System.Buffers.Experimental/System/Buffers/OwnedPinnedBuffer.cs
- src/System.Buffers.Experimental/System/Buffers/ThrowHelper.cs
- src/System.Buffers.Primitives/System/Buffers/Buffer.cs
- src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs
- src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs
- src/System.Buffers.Primitives/System/Internal/ManagedBufferPool.cs
- src/System.Buffers.Primitives/System/Internal/OwnedArray.cs
- src/System.Buffers.Primitives/System/Internal/OwnerEmptyMemory.cs
- src/System.Buffers.Primitives/System/Runtime/ThrowHelper.cs
- src/System.IO.Pipelines/MemoryPoolBlock.cs
- src/System.IO.Pipelines/ThrowHelper.cs
- src/System.IO.Pipelines/UnownedBuffer.cs
- tests/System.Buffers.Primitives.Tests/MemoryTests.cs
- tests/System.IO.Pipelines.Tests/MemoryPoolTests.cs
- tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
cc @KrzysztofCwalina, @pakrym, @davidfowl
Addressing comments:
https://github.com/dotnet/corefxlab/pull/1465#discussion_r112050277
https://github.com/dotnet/corefxlab/pull/1465#discussion_r112050352
> Adding IsDisposed checks to Span getter and GetArray/Pointer Internal

- src/System.Text.Primitives/System/Text/Encoding/Utf16/Utf16LittleEndianEncoder.cs
- src/System.Text.Primitives/System/Text/Encoding/Utf16/Utf16TextEncoderLE.cs
- src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8Encoder.cs
- src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8TextEncoder.cs
- src/System.Text.Primitives/System/Text/TextEncoder.cs
- tests/System.Text.Primitives.Tests/Encoding/RandomTests.cs
- tests/System.Text.Primitives.Tests/Encoding/Utf8EncoderTests.cs
> TextEncoder: expose TryComputeEncodedBytes on the public API

- scripts/update-dependencies/Program.cs
- src/System.Buffers.Experimental/System.Buffers.Experimental.csproj
- src/System.Buffers.Primitives/System.Buffers.Primitives.csproj
- tests/System.Text.Formatting.Tests/System.Text.Formatting.Tests.csproj
- tools/dependencies.props
... that is auto-updated by Maestro.
> Version tag for System.Numerics.Vectors

- docs/specs/nativesized.md
> Small update based on feedback from @jfrijters :-)

- scripts/PerfHarness/PerfHarness.csproj
- scripts/PerfHarness/README.md
- tools/dependencies.props
Also removing unnecessary restore step.
+ Updating xunit.perf.api
> Updating perf harness readme to include correct dotnet cli path.

- netci.groovy
cc @joshfree, @shiftylogic, @mellinoe 
Borrowed snippets from https://github.com/dotnet/corefx/blob/master/netci.groovy#L366-L441
> Adding Linux and Mac CI runs.

- README.md
> Adding Ubuntu and OSX build badges.

- src/System.Text.Json/System/Text/Json/JsonParseObject.cs
- src/System.Text.Json/System/Text/Json/JsonParser.cs
- tests/System.Text.Json.Tests/JsonObjectTests.cs
fixed bug in counting nested arrays
added and improved tests
> Added JsonObject.ArrayLength property

- src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs
- src/System.IO.Pipelines/UnownedBuffer.cs
- tests/System.Buffers.Primitives.Tests/BufferReferenceTesting.cs
- tests/System.IO.Pipelines.Tests/OwnedBuffersReferenceTests.cs
- tests/System.IO.Pipelines.Tests/System.IO.Pipelines.Tests.csproj
Now all OwnedBuffer subclasses are tested with the reference tests
@davidfowl, @ahsonkhan, @shiftylogic, @mjp41, @joshfree
> Added Tests for Pipeline OwnedBuffer Subclasses

- src/System.Buffers.Primitives/System/Buffers/Buffer.cs
- src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs
- src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs
cc: @davidfowl, @stephentoub, @jkotas, @ahsonkhan, @shiftylogic, @joshfree
> Buffer<T> now supports arrays without the need for OwnedBuffer<T>

- tests/System.Buffers.Primitives.Tests/BufferReferenceTesting.cs
- tests/System.Buffers.Primitives.Tests/BufferReferenceTests.cs
@ahsonkhan, @shiftylogic, @joshfree
> Added some more reference tests for Buffer<T> and ROBuffer<T>

- samples/System.IO.Pipelines.Samples/Framing/Codec.cs
- samples/System.IO.Pipelines.Samples/Rio/RawRioHttpClientSample.cs
- samples/System.IO.Pipelines.Samples/SampleBase/AspNetSampleBase.cs
- samples/System.IO.Pipelines.Samples/Socket/RawSocketHttpClientSample.cs
- samples/System.IO.Pipelines.Samples/Socket/RawSocketHttpServerSample.cs
Fix for #1453, sorry about that :) 
cc @ahsonkhan
> Fixed warnings in sample

- src/System.Binary.Base64/System.Binary.Base64.csproj
- src/System.Binary.Base64/System/Binary/Base64.cs
- src/System.Binary.Base64/System/Binary/Base64Decoder.cs
- src/System.Binary.Base64/System/Binary/Base64Encoder.cs
- src/System.Binary.Base64/System/Binary/BufferExtensions.cs
- src/System.Buffers.Primitives/System/Buffers/ITransformation.cs
- tests/System.Binary.Base64.Tests/Base64TestHelper.cs
- tests/System.Binary.Base64.Tests/BasicUnitTests.cs
- tests/System.Binary.Base64.Tests/PerformanceTests.cs
Ready for review.
- perf tests
- adding ITransformation
- adding test helper and minor bug fixes
cc @KrzysztofCwalina, @shiftylogic 
**Edit:** See below for updated results that are more accurate, along with conclusions.
> Adding ITransformation and changing Base64 to implement it

- samples/SimpleHttp/Program.cs
- samples/SimpleHttp/RequestParser.cs
- samples/SimpleHttp/Server.csproj
From Peter's prototype.
@davidfowl @KrzysztofCwalina
> Simple HTTP server for plaintext

- src/System.Threading.Tasks.Channels/AssemblyAttributes.cs
Fixes https://github.com/dotnet/corefxlab/issues/1548
cc: @muratg, @moozzyk
> Add NeutralResourcesLanguageAttribute to Channels lib

- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/BoundedChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/ChannelUtilities.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/ClosedChannelException.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/ReadableChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/SingleConsumerUnboundedChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/UnboundedChannel.cs
- src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/UnbufferedChannel.cs
- tests/System.Threading.Tasks.Channels.Tests/BoundedChannelTests.cs
- tests/System.Threading.Tasks.Channels.Tests/ChannelTestBase.cs
- tests/System.Threading.Tasks.Channels.Tests/System.Threading.Tasks.Channels.Tests.csproj
- tests/System.Threading.Tasks.Channels.Tests/UnboundedChannelTests.cs
- tests/System.Threading.Tasks.Channels.Tests/UnbufferedChannelTests.cs
cc: @davidfowl, @moozzyk, @anurse 
Discussed in https://github.com/aspnet/SignalR/pull/496
> Propagate channel exception from {WaitFor}Read/WriteAsync methods

- src/System.Buffers.Primitives/System/Buffers/Buffer.cs
- src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs
- tests/System.Buffers.Primitives.Tests/CopyTo.cs
- tests/System.Buffers.Primitives.Tests/CopyToReadOnlyBuffer.cs
- tests/System.Buffers.Primitives.Tests/CtorArraySegment.cs
- tests/System.Buffers.Primitives.Tests/CtorArraySegmentReadOnlyBuffer.cs
**Note:** This PR will only pass CI after https://github.com/dotnet/corefxlab/pull/1602 is merged.
> Adding implicit conversion from ArraySegment and TryCopyTo APIs.

- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/HttpServer.cs
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/Log.cs
- samples/LowAllocationWebServer/Shared/SampleServer.cs
- samples/QotdService/Program.cs
- src/System.IO.Pipelines/ReadableBufferReader.cs
- src/System.IO.Pipelines/System.IO.Pipelines.csproj
- src/System.IO.Pipelines/WritableBufferWriter.cs
- src/System.Text.Http/System.Text.Http.csproj
- src/System.Text.Http/System/Text/Http/Obsolete/HttpHeaderBuffer.cs
- src/System.Text.Http/System/Text/Http/Obsolete/HttpHeaders.cs
- src/System.Text.Http/System/Text/Http/Obsolete/HttpRequestParser.cs
- src/System.Text.Json.Dynamic/System.Text.Json.Dynamic.csproj
- src/System.Text.Json.Dynamic/System/Text/Json/JsonDynamicObject.cs
- src/System.Text.Json.Dynamic/System/Text/Json/JsonLazyDynamicObject.cs
- src/System.Text.Json/System.Text.Json.csproj
- src/System.Text.Json/System/Text/Json/JsonParseObject.cs
- src/System.Text.Json/System/Text/Json/JsonParser.cs
- src/System.Text.Json/System/Text/Json/JsonReader.cs
- src/System.Text.Utf8String/System.Text.Utf8String.csproj
- src/System.Text.Utf8String/System/Text/Utf8String.CodePointEnumerable.cs
- src/System.Text.Utf8String/System/Text/Utf8String.CodePointEnumerator.cs
- src/System.Text.Utf8String/System/Text/Utf8String.CodePointReverseEnumerator.cs
- src/System.Text.Utf8String/System/Text/Utf8String.Enumerator.cs
- src/System.Text.Utf8String/System/Text/Utf8String.cs
- tests/Benchmarks/Helpers/Server.cs
- tests/System.Text.Http.Tests/GivenAnHttpHeaders.cs
- tests/System.Text.Json.Tests/JsonObjectTests.cs
- tools/common.props
- tools/dependencies.props
The new version is: 2.6.0-rdonly-ref-61810-01
The corresponding VSIX (if need VS support) can be obtained at: 
https://dotnet.myget.org/feed/roslyn/package/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7/2.6.0.6181001
> New toolset compiler

- docs/specs/priority-queue.md
@safern @ianhays 
Adding API proposal. Link to the discussion (and specific request for this PR): [#574](https://github.com/dotnet/corefx/issues/574#issuecomment-308609496).
> Priority queue proposal

- src/System.IO.Compression.Brotli/System/IO/Compression/Brotli.cs
- tests/System.IO.Compression.Tests/BrotliPrimitivesTests.cs
Small changes and some test for Brotli base class.
> Brotli base tests2

- src/System.Text.Formatting/System/Text/Formatting/CompositeFormat.cs
- src/System.Text.Formatting/System/Text/Formatting/IOutputExtensions.cs
- src/System.Text.Formatting/System/Text/Formatting/ITextOutputExtensions.cs
- src/System.Text.Json.Dynamic/System/Text/Json/JsonDynamicObject.cs
- src/System.Text.Json/System/Text/Json/JsonConstants.cs
- src/System.Text.Primitives/System/Text/Formatting/FloatFormatter.cs
- src/System.Text.Primitives/System/Text/Formatting/IBufferFormattable.cs
- src/System.Text.Primitives/System/Text/Formatting/Internal/GuidFormatter.Utf16.cs
- src/System.Text.Primitives/System/Text/Formatting/Internal/GuidFormatter.Utf8.cs
- src/System.Text.Primitives/System/Text/Formatting/Internal/IntegerFormatter.Utf16.cs
- src/System.Text.Primitives/System/Text/Formatting/Internal/IntegerFormatter.Utf8.cs
- src/System.Text.Primitives/System/Text/Formatting/Internal/IntegerFormatter.cs
- src/System.Text.Primitives/System/Text/Formatting/PrimitiveFormatter.Guid.cs
- src/System.Text.Primitives/System/Text/Formatting/PrimitiveFormatter.Integer.cs
- src/System.Text.Primitives/System/Text/Formatting/PrimitiveFormatter.Time.cs
- src/System.Text.Primitives/System/Text/Formatting/PrimitiveFormatter_float.cs
- src/System.Text.Primitives/System/Text/ParsedFormat.cs
- src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser.cs
- src/System.Text.Primitives/System/Text/Parsing/Signed.cs
- src/System.Text.Primitives/System/Text/Parsing/Unsigned.cs
- tests/System.Text.Formatting.Globalization.Tests/BasicTests.cs
- tests/System.Text.Formatting.Tests/CustomTypeFormatting.cs
- tests/System.Text.Formatting.Tests/NumberFormattingTests.Generated.cs
- tests/System.Text.Formatting.Tests/ParsedFormatUnitTests.cs
- tests/System.Text.Formatting.Tests/PerformanceTests.cs
- tests/System.Text.Formatting.Tests/PrimitiveFormattingTests.cs
- tests/System.Text.Formatting.Tests/TimeSpanFormattingTests.Generated.cs
- tests/System.Text.Primitives.Tests/Formatting/IntegerTests.cs
- tests/System.Text.Primitives.Tests/Formatting/TimeTests.cs
* TextFormat => ParsedFormat
* Removed properties that were not "general" from ParsedFormat
* Minor clean-up
> TextFormat rename + cleanup

- README.md
https://github.com/dotnet/corefxlab/issues/1660 resolved
> Add System.IO.Compression.Brotli to Readme

- src/System.IO.Compression.Brotli/README.md
@ahsonkhan we can continue conversation here. I think that I resolved all comments from previous pr.
> Brotli Update Readme

- src/System.Text.Primitives/System/Text/Parsing/InvariantSigned.cs
- tests/System.Text.Primitives.Tests/Parsing/PrimitiveParserIntegerTests.cs
- tests/System.Text.Primitives.Tests/Parsing/PrimitiveParserSBytePerfTests.cs
SByte Parser for UTF8 and tests for it.
> UTF8 SByte Parser

- src/System.Numerics.Tensors/System/Numerics/ArrayUtilities.cs
- src/System.Numerics.Tensors/System/Numerics/Tensor.Operations.cs
- src/System.Numerics.Tensors/System/Numerics/Tensor.Operations.tt
- src/System.Numerics.Tensors/System/Numerics/Tensor.cs
- src/System.Numerics.Tensors/System/Numerics/TensorArithmetic.cs
- src/System.Numerics.Tensors/System/Numerics/TensorArithmetic.tt
- src/System.Numerics.Tensors/System/Numerics/TensorTemplate.ttinclude
- tests/System.Numerics.Tensors.Tests/TensorTests.cs
Fixes #1681 
This adds Tensor contraction (the generic form of Matrix multiplication).
In doing this I came up with a simpler concept to encapsulate the offset calculation for the layout: *strides* for each dimension.  I refactored other non-arithmetic methods on Tensor to use the same *strides* concept.
/cc @mellinoe @migueldeicaza
> Tensor Contraction

- src/System.Azure.Experimental/System/Azure/Authentication.cs
- tests/System.Azure.Experimental.Tests/AuthenticationTests.cs
In the last PR, I added an API to generate CosmosDb auth header in a non-allocating way. This PR adds a similar API for Azure Storage. The API allows for non allocating generation of Azure Storage signatures
Here are the benchmark results, with the most interesting difference in GC allocations:
|   Method |     Mean |     Error |    StdDev |   Median | Scaled |  Gen 0 | Allocated |
|--------- |---------:|----------:|----------:|---------:|-------:|-------:|----------:|
| Corfxlab | 2.484 us | 0.0049 us | 0.0041 us | 2.484 us |   0.39 |      - |       0 B |
|   DotNet | 6.309 us | 0.1246 us | 0.1706 us | 6.423 us |   1.00 | 0.5646 |    2388 B |
@joshfree, @ahsonkhan. @shiftylogic, @danmosemsft, @AlexGhiondea, @JeffreyRichter
> Adding APIs to generate Azure Storage authentication signature

- src/System.Azure.Experimental/System/Azure/Authentication.cs
- src/System.Text.Encodings.Web.Utf8/UrlEncoder.cs
- tests/System.Azure.Experimental.Tests/AuthenticationTests.cs
@joshfree, @ahsonkhan, @shiftylogic
> Changed CosmosDB header generation to Try*

- src/System.IO.Pipelines.Extensions/StreamExtensions.cs
- tests/System.IO.Pipelines.Tests/PipelineWriterFacts.cs
@pakrym @davidfowl 
Need this for SSE in SignalR
> Add cancellation token to stream.CopyToAsync for IPipeWriter

- src/System.Azure.Experimental/System.Azure.Experimental.csproj
- src/System.Azure.Experimental/System/Azure/Sha256.Windows.cs
- src/System.Text.Http/System/Text/Http/IFormatterHttpExtensions.cs
- tests/System.Azure.Experimental.Tests/AuthenticationTests.cs
- tests/System.Azure.Experimental.Tests/System.Azure.Experimental.Tests.csproj
- tests/System.Text.Http.Tests/GivenIFormatterExtensionsForHttp.cs
@ahsonkhan, @shiftylogic, @joshfree
> Added Helpers to Write Http Request

- src/System.Buffers.Experimental/System/Buffers/Utf8BufferReader.cs
- tests/System.Buffers.Experimental.Tests/Utf8BufferReaderTests.cs
@joshfree, @ahsonkhan, @shiftylogic
> Added Utf8BufferReader

- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/OwnedBuffer.cs
- src/System.Buffers.Experimental/System/Buffers/BufferManager.cs
- src/System.Buffers.Experimental/System/Buffers/OwnedNativeBuffer.cs
- src/System.Buffers.Experimental/System/Buffers/OwnedPinnedBuffer.cs
- src/System.Buffers.Primitives/System/Buffers/Buffer.cs
- src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs
- src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs
- src/System.Buffers.Primitives/System/Internal/ManagedBufferPool.cs
- src/System.Buffers.Primitives/System/Internal/OwnedArray.cs
- src/System.IO.Pipelines/UnownedBuffer.cs
- tests/System.Buffers.Experimental.Tests/MemoryTests.cs
Resolves https://github.com/dotnet/corefxlab/issues/1529
> Removing OwnedBuffer.Add and using Unsafe.Add

- src/System.Text.Utf8String/System/Text/Utf8String.cs
- tests/System.Text.Utf8String.Tests/RandomTests.cs
Function and test implementation
> UTF8String TrimStart with prefix

- src/System.Text.Utf8String/System/Text/Utf8String.cs
- tests/System.Text.Utf8String.Tests/RandomTests.cs
Follow-up to PR #1712 . Testing and implementation of TrimEnd.
> Utf8 String TrimEnd 

- src/System.Numerics.Tensors/System.Numerics.Tensors.csproj
- src/System.Numerics.Tensors/System/Numerics/ArrayUtilities.cs
- src/System.Numerics.Tensors/System/Numerics/RefUtilities.cs
- src/System.Numerics.Tensors/System/Numerics/Tensor.cs
- src/System.Numerics.Tensors/System/Numerics/TensorArithmetic.cs
- src/System.Numerics.Tensors/System/Numerics/TensorArithmetic.tt
- src/System.Numerics.Tensors/System/Numerics/TensorTemplate.ttinclude
- tests/System.Numerics.Tensors.Tests/TensorTests.cs
Fixes #1695 
Still working through the details / design on this.  Submitting as a means for test coverage and feedback.
> Add support for column-major layout to tensor

- src/System.Text.Primitives/System/Text/Formatters/Utf16.cs
- src/System.Text.Primitives/System/Text/Formatters/Utf8.cs
- tests/System.Text.Primitives.Tests/Formatting/BooleanTests.cs
Chipping on #1755 
cc: @ahsonkhan, @joshfree , @shiftylogic
> Added support for Boolean formatting

- src/System.Text.Primitives/System/Text/Parsers/InvariantBool.cs
- src/System.Text.Primitives/System/Text/Parsers/InvariantSigned.cs
- src/System.Text.Primitives/System/Text/Parsers/InvariantSignedHex.cs
- src/System.Text.Primitives/System/Text/Parsers/InvariantUnsigned.cs
- src/System.Text.Primitives/System/Text/Parsers/InvariantUnsignedHex.cs
- src/System.Text.Primitives/System/Text/Parsers/PrimitiveParser_Guid.cs
- src/System.Text.Primitives/System/Text/Parsers/Signed.cs
- src/System.Text.Primitives/System/Text/Parsers/Unsigned.cs
- tests/System.Text.Primitives.Tests/Parsing/PrimitiveParserGuidTests.cs
In addition, the rest of the files have "charsConsumed" renamed to "charactersConsumed"
cc: @ahsonkhan, @shiftylogic, @joshfree
> Added Guid Parsing

- src/System.Binary/System/Binary/BufferReader.cs
- src/System.Binary/System/Binary/BufferReader_BE.cs
- src/System.Binary/System/Binary/BufferReader_LE.cs
- src/System.Binary/System/Binary/BufferWriter.cs
- src/System.IO.Pipelines.Extensions/DefaultReadableBufferExtensions.cs
- src/System.IO.Pipelines.Extensions/ReadWriteExtensions.cs
- src/System.Text.Http.Parser/HttpUtilities.cs
- src/System.Text.Json/System/Text/Json/JsonParseObject.cs
- src/System.Text.Json/System/Text/Json/JsonParser.cs
- tests/System.Binary.Tests/BufferReaderTests.cs
- tests/System.Binary.Tests/BufferWriterTests.cs
- tests/System.Buffers.Primitives.Tests/CastTests.cs
- tests/System.Buffers.Primitives.Tests/UsageScenarioTests.cs
- tests/System.IO.Pipelines.Extensions.Tests/ReadableBufferFacts.cs
- Cleaned up APIs
- Added Try* versions of endinanness-aware reading and writing APIs
cc: @joshfree, @ahsonkhan, @shiftylogic
> Binary reader writer

- src/System.Threading.Tasks.Channels/README.md
- Fix declaration of Channel<T> to match the actual metadata.
- Detabify the file to fix the wonky indentations in the code
samples
- Remove a stray "}"
- Switch the order of WaitToReadASync and TryComplete descriptions
so that the concept of "completing a channel" is introduced
before its first reference.
> Fixes for STT.Channels README.md

- src/System.Text.Primitives/System/Text/Encoders/EncodingHelper.cs
- src/System.Text.Primitives/System/Text/Encoders/Utf32.cs
- tests/System.Text.Primitives.Tests/Encoding/TextEncoderTestHelper.cs
- tests/System.Text.Primitives.Tests/Encoding/Utf8EncoderTests.cs
> IsSupportedCodePoint shouldn't reject private use or nonchars

- tests/System.Text.Primitives.Tests/System.Text.Primitives.Tests.csproj
Same deal as with HttpParser - fix the NU1605 errors.
> Fix errors on selfcontained publish on System.Text.Primitives tests.

- scripts/build.ps1
Shaves five minutes off my morning "sync and refresh
5 different repos") routine.
Defaults to "false" so this is opt-in.
> Add a -SkipTests:true option to build.cmd

- src/System.Azure.Experimental/System/Azure/Key.cs
- src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs
- src/System.Buffers.Experimental/System/Buffers/BytesReader.cs
- src/System.IO.Pipelines.Text.Primitives/ReadableBufferExtensions.cs
These were workarounds for deficiencies in the language/compiler that are now fixed.
> Removed no longer necessary hacks.

- src/System.Numerics.Tensors/System.Numerics.Tensors.csproj
- src/System.Numerics.Tensors/System/Numerics/ArrayTensorExtensions.cs
- src/System.Numerics.Tensors/System/Numerics/ArrayUtilities.cs
- src/System.Numerics.Tensors/System/Numerics/CompressedSparseTensor.cs
- src/System.Numerics.Tensors/System/Numerics/DenseTensor.cs
- src/System.Numerics.Tensors/System/Numerics/RefUtilities.cs
- src/System.Numerics.Tensors/System/Numerics/SparseTensor.cs
- src/System.Numerics.Tensors/System/Numerics/Tensor.cs
- tests/System.Numerics.Tensors.Tests/TensorTests.cs
Merging a number of API changes from FxDC review.
/cc @mellinoe @eerhardt
> API changes remaining from API review

- src/System.IO.Pipelines/System/IO/Pipelines/PipeCompletion.cs
- tests/System.IO.Pipelines.Tests/PipeTest.cs
- tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
https://github.com/dotnet/corefxlab/issues/1811
> Capture and rethrow completion exceptions using ExceptionDispatchInfo

- docs/specs/span.md
cc: @ahsonkhan, @VSadov, @ericstj
> Updated span.md with proper stackalloc syntax.

- scripts/package.ps1
Related to https://github.com/dotnet/corefxlab/pull/1826
Forgot to update the folder name in the package script.
> Rename dotnet cli folder in the package script.

- scripts/PerfHarness/PerfHarness.csproj
Related to https://github.com/dotnet/corefxlab/pull/1736
> Update perf harness project to netcoreapp 2.1

- samples/System.Numerics.Tensors.Samples/TensorSamples.native/TensorSamples.native.vcxproj
- samples/System.Numerics.Tensors.Samples/TensorSamples.native/TensorSamples.native.vcxproj.filters
- samples/System.Numerics.Tensors.Samples/TensorSamples.native/dllmain.cpp
- samples/System.Numerics.Tensors.Samples/TensorSamples.native/native.cpp
- samples/System.Numerics.Tensors.Samples/TensorSamples.native/stdafx.cpp
- samples/System.Numerics.Tensors.Samples/TensorSamples.native/stdafx.h
- samples/System.Numerics.Tensors.Samples/TensorSamples.native/targetver.h
- samples/System.Numerics.Tensors.Samples/TensorSamples/Access.cs
- samples/System.Numerics.Tensors.Samples/TensorSamples/MutateSparse.cs
- samples/System.Numerics.Tensors.Samples/TensorSamples/PreAllocate.cs
- samples/System.Numerics.Tensors.Samples/TensorSamples/Program.cs
- samples/System.Numerics.Tensors.Samples/TensorSamples/ReversePInvoke.Allocator.cs
- samples/System.Numerics.Tensors.Samples/TensorSamples/ReversePInvoke.cs
- samples/System.Numerics.Tensors.Samples/TensorSamples/TensorSamples.csproj
- samples/System.Numerics.Tensors.Samples/TensorSamples/WrapNativeMemory.NativeMemory.cs
- samples/System.Numerics.Tensors.Samples/TensorSamples/WrapNativeMemory.cs
- src/System.Numerics.Tensors/System.Numerics.Tensors.sln
- tests/System.Numerics.Tensors.Tests/NativeMemory.cs
Add some samples that illustrate how to interop with Tensor.
These are only part of the Tensor sln at the moment because I don't want the official build to take a dependency on having VC++ installed (nor can I for x-plat builds).
#1821
> Adding interop samples for Tensor

- src/System.Numerics.Tensors/System/Numerics/ArrayTensorExtensions.cs
- src/System.Numerics.Tensors/System/Numerics/CompressedSparseTensor.cs
- src/System.Numerics.Tensors/System/Numerics/DenseTensor.cs
- src/System.Numerics.Tensors/System/Numerics/SparseTensor.cs
- src/System.Numerics.Tensors/System/Numerics/Tensor.cs
/cc @eerhardt @sethjuarez @liqunfu
> Add XML docs to Tensor library

- samples/QotdService/Program.cs
- src/System.Net.Libuv/System/Net/Libuv/Stream.cs
- src/System.Text.Utf8String/System/Text/Utf8String.cs
> Simplified Utf8String usage in Qotd server sample

- src/System.Text.Utf8String/System/Text/Utf8Span.cs
- src/System.Text.Utf8String/System/Text/Utf8String.cs
- tests/System.Text.Utf8String.Tests/Comparisons.cs
- tests/System.Text.Utf8String.Tests/Utf8Span.RandomTests.cs
@ahsonkhan, @GrabYourPitchforks, @joshfree, @A-And 
These are not very optimized, but I am just making sure we have the basics working.
> Implemented bunch of Utf8String/Span APIs

- src/System.Text.Utf8String/System/Text/Utf8Span.cs
- src/System.Text.Utf8String/System/Text/Utf8String.cs
- tests/System.Text.Utf8String.Tests/Utf8Span.RandomTests.cs
- tests/System.Text.Utf8String.Tests/Utf8String.RandomTests.cs
cc: @ahsonkhan, @GrabYourPitchforks, @joshfree, @A-And
> Last batch of misc cleanup

- src/System.Numerics.Tensors/System/Numerics/DenseTensor.cs
- src/System.Numerics.Tensors/System/Numerics/Tensor.cs
- tests/System.Numerics.Tensors.Tests/TensorTests.cs
Implementing `IList<T>` on `Tensor<T>`.
/cc @KrzysztofCwalina @ahsonkhan
> Implement IList<T> on Tensor<T>

- docs/specs/span.md
> Updated some links in Span specification document.

- src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs
- src/System.Text.Http/System/Text/Http/HttpRequest.cs
cc: @davidfowl, @pakrym, @ahsonkhan, @terrajobst, @joshfree
> Added ReadOnlyBytes.CursorOf

- src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs
- tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs
Also, I added Slice that takes a cursor as @davidfowl was asking how the cursor would be used.
cc: @pakrym, @davidfowl, @benaadams, @ahsonkhan, @YohDeadfall, @joshfree
> Removed allocation when creating cursors to first segment

- src/System.Time/Properties/Strings.Designer.cs
- src/System.Time/Properties/Strings.resx
- src/System.Time/System.Time.csproj
- src/System.Time/System/Date.cs
- src/System.Time/System/Time.cs
- tests/System.Time.Tests/DateCastTests.cs
- tests/System.Time.Tests/DateTimeTests.cs
- tests/System.Time.Tests/TimeCastTests.cs
- tests/System.Time.Tests/TimeMathTests.cs
Several improvements per code review with @mconnew.
> Improvements to Date and Time

- src/System.Text.Primitives/System/Text/Encoders/Utf8.cs
- src/System.Text.Primitives/System/Text/Encoders/Utf8Util.Helpers.cs
- src/System.Text.Primitives/System/Text/Encoders/Utf8Util.Validation.cs
Updating corefxlab implementation to match the latest prototype bits. This results in smaller code size (both source and codegen) and significant improvements for two particular scenarios:
- A 30% improvement in the case of primarily ASCII text with some non-ASCII characters (such as smart quotes), and
- A 10% improvement in the case of Cyrillic, Greek, and other primarily 2-byte-per-char languages.
> UTF-8 validation performance improvements

- src/System.Text.Primitives/System/Text/Encoders/Utf8.cs
Consolidate the UTF-8 validation and character counting workhorse logic.
> Update Utf8.ToUtf16Length and Utf8.ToUtf32Length to use new workhorse APIs

- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/ReadWriteBytes.cs
- src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs
- src/System.Collections.Sequences/System/Collections/Sequences/Position.cs
Started to think how Position would be used as ReadCursor and discovered a few missing APIs.
@davidfowl, @ahsonkhan, @halter73
> Prepared Position for usage in Pipelines

- src/System.IO.Pipelines/System/IO/Pipelines/PipeCompletion.cs
- src/System.IO.Pipelines/System/IO/Pipelines/PipeCompletionCallbacks.cs
I should've believed you earlier, @davidfowl.
Fixes: https://github.com/dotnet/corefxlab/issues/1722
> Clear callback array when returning

- src/System.IO.Pipelines/System/IO/Pipelines/ReadableBufferReader.cs
- tests/System.IO.Pipelines.Tests/ReadableBufferReaderFacts.cs
- See https://github.com/aspnet/KestrelHttpServer/issues/2151 for more context on the original issue
> Fix cursor computation issue with empty segments

- docs/specs/span.md
I received some comments on parts of the spec being outdated. These are not comprehensive fixes, but rather those that become confusing at this point.
> Some small updates to the Span<T> design document

- src/System.IO.Pipelines/System/IO/Pipelines/Pipe.cs
- src/System.IO.Pipelines/System/IO/Pipelines/PreservedBuffer.cs
- src/System.IO.Pipelines/System/IO/Pipelines/ReadCursor.cs
- src/System.IO.Pipelines/System/IO/Pipelines/ReadableBuffer.cs
- tests/System.IO.Pipelines.Performance.Tests/PipeThroughput.cs
- tests/System.IO.Pipelines.Performance.Tests/System.IO.Pipelines.Performance.Tests.csproj
- tests/System.IO.Pipelines.Performance.Tests/configs/CoreConfig.cs
Does not affect the throughput.
> Readonly pipe structs and remove lenght

- src/System.IO.Pipelines/System/Buffers/MemoryPoolSlab.cs
I forgot to remove this field in the last PR
@davidfowl, @pakrym
> Removed leftover deallocationCallback

- src/System.Buffers.Experimental/System/Range.cs
- src/System.Numerics.Tensors/System/Numerics/Tensor.cs
- tests/System.Buffers.Experimental.Tests/RangeTests.cs
This is just the first stab.
cc: @terrajobst, @eerhardt, @jcouv, @joshfree, @ahsonkhan, @jaredpar, @khyperia, @MadsTorgersen
> Changed System.Range based on language discussions

- src/System.IO.Pipelines.Networking.Libuv/UvThread.cs
- src/System.IO.Pipelines/System/IO/Pipelines/Pipe.cs
- src/System.IO.Pipelines/System/Threading/InlineScheduler.cs
- src/System.IO.Pipelines/System/Threading/Scheduler.cs
- src/System.IO.Pipelines/System/Threading/TaskRunScheduler.cs
- tests/System.IO.Pipelines.Tests/PipeCompletionCallbacksTests.cs
- tests/System.IO.Pipelines.Tests/SchedulerFacts.cs
https://github.com/dotnet/corefxlab/issues/2000
> Add single argument Schedule overload

- corefxlab.sln
- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/BufferSequence.cs
- src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs
- src/System.Buffers.Experimental/System/Buffers/BufferReader_search.cs
- src/System.Buffers.Experimental/System/Buffers/Sequences/BufferList.cs
- src/System.Buffers.Experimental/System/Buffers/Sequences/ReadWriteBytes.cs
- src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs
- src/System.Buffers.Primitives/System/Buffers/ReadOnlyBufferReader.cs
- src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer_helpers.cs
- src/System.Buffers.Primitives/System/Collections/IMemoryList.cs
- src/System.IO.Pipelines/System/IO/Pipelines/BufferSegment.cs
- src/System.Text.Http.Parser/HttpParser.cs
- tests/System.Buffers.Experimental.Tests/SequenceExtensionsTests.cs
- tests/System.Buffers.Primitives.Tests/BufferSegment.cs
- tests/System.Buffers.Primitives.Tests/ReadableBufferReaderFacts.cs
- tests/System.IO.Pipelines.Performance.Tests/ReadCursorOperationsThroughput.cs
Also `RunningLength`  -> `RunningIndex`
> Rename IBufferList to IMemoryList

- src/System.Buffers.Experimental/System/Buffers/Native/OwnedPinnedBuffer.cs
- src/System.Buffers.Primitives/System/Buffers/OwnedArray.cs
- src/System.Buffers.Primitives/System/Buffers/Pooling/ArrayMemoryPool.cs
- tests/System.Buffers.Experimental.Tests/MemoryTests.cs
- tests/System.Buffers.Primitives.Tests/CustomMemoryForTest.cs
From https://github.com/dotnet/corefx/pull/26563#discussion_r163891173
cc @pakrym, @KrzysztofCwalina, @AtsushiKan
> Fix Pin byteOffset bounds checks

- src/System.IO.Pipelines/System/IO/Pipelines/ResetablePipe.cs
Race was between `if` in `GetMemory`, `Advance` returning the last segment and `Commit` that reset writing status.
What can happen is:
1. Producer calls commit, status is reset
2. Consumer advances to the end checks status and starts returning all blocks
3. GetMemory runs and reads _writingHead and returns it
4. Segment returned from GetMemory get's reset and returned to pool
> Fix _writingHead race introduced while making Writer IOutput

- build.sh
- scripts/build.ps1
**Note:** This is for preview1 branch - release/2.1. Master is up to preview2.
Related: https://github.com/dotnet/corefxlab/pull/2077
cc @dotnet/corefxlab-contrib, @pakrym, @davidfowl
> [release/2.1] Update package versions to preview1- from e-

- build.sh
- scripts/build.ps1
**Note:** This is for corefxlab master branch
Related: https://github.com/dotnet/corefxlab/pull/2076
cc @dotnet/corefxlab-contrib, @pakrym, @davidfowl
> [master] Update package versions to preview2- from e-

- scripts/package.ps1
- tools/common.props
**Note:** This is for corefxlab master branch
Related: https://github.com/dotnet/corefxlab/pull/2077
cc @joshfree
> [master] Leftover changes to update package versions to preview2

- scripts/build.ps1
> Disabling test runs

- src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer_helpers.cs
- src/System.IO.Pipelines/System/IO/Pipelines/Pipe.cs
- tests/System.Buffers.Primitives.Tests/ReadableBufferFacts.cs
- tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
Also simplify advance logic a bit
> Fix issue where GetPosition might cross outside of ROB

- src/System.IO.Pipelines/System/IO/Pipelines/FlushResult.cs
- tests/System.IO.Pipelines.Tests/FlushResultFacts.cs
- Added a constructor to allow setting IsCompleted and IsCancelled
#2087
> Make FlushResult constructable

- samples/AzCopyCore/AzCopyCore/AzCopyCore.csproj
- samples/AzCopyCore/AzCopyCore/Helpers/CommandLine.cs
- samples/AzCopyCore/AzCopyCore/Helpers/ConsoleTraceListener.cs
- samples/AzCopyCore/AzCopyCore/Helpers/PipelinesExtensions.cs
- samples/AzCopyCore/AzCopyCore/Program.cs
- samples/AzCopyCore/AzCopyCore/SocketClient.cs
- samples/AzCopyCore/AzCopyCore/StorageClient.cs
- samples/AzCopyCore/AzCopyCore/StorageRequests.cs
- Add option to pass the key from a file.
- Update to use ReadOnlySpan wherever possible instead of ReadOnlyMemory.
- Fix use of vars and formatting.
cc @KrzysztofCwalina
> Add option to pass key from a file and clean up formatting.

- samples/AzCopyCore/AzCopyCore/AzCopyCore.csproj
- samples/AzCopyCore/AzCopyCore/Program.cs
cc @KrzysztofCwalina, @morganbr, @sergiy-k
> Add CoreRT package reference and clean up csproj.

- samples/AzCopyCore/AzCopyCore/AzCopyCore.csproj
- samples/AzCopyCore/AzCopyCore/Program.cs
> Small fixes based on PR feedback

- samples/LowAllocationWebServer/LowAllocationWebServerLibrary/TcpConnectionFormatter.cs
- src/System.Buffers.Experimental/System/Buffers/Sequences/ReadWriteBytes.cs
- src/System.Numerics.Tensors/System/Numerics/DenseTensor.cs
- src/System.Text.Formatting.Globalization/System/Text/Formatting/FormattingDataProvider.cs
- src/System.Text.Formatting/System/Text/Formatting/CompositeFormat.cs
- src/System.Text.Utf8String/System/Text/Utf8String.cs
- tests/Benchmarks/BufferWriterBench.cs
- tests/System.Buffers.Experimental.Tests/BufferWriterTests_sequence.cs
- tests/System.Buffers.Experimental.Tests/StringSliceTests.cs
- tests/System.Buffers.Primitives.Tests/BasicUnitTests.cs
- tests/System.Buffers.Primitives.Tests/EqualityTests.cs
- tests/System.Buffers.Primitives.Tests/OverflowTests.cs
- tests/System.Buffers.Primitives.Tests/ReadableBufferReaderFacts.cs
- tests/System.Buffers.ReaderWriter.Tests/BasicUnitTests.cs
- tests/System.Text.Formatting.Tests/PrimitiveFormattingTests.cs
- tests/System.Text.Primitives.Tests/Encoding/EncodeIntoUtf8Tests.cs
See https://github.com/dotnet/corefxlab/pull/2206
cc @dotnet/corefxlab-contrib, @KrzysztofCwalina
> Collapse AsSpan().Slice(..) calls into AsSpan(..) (using code analyzer)

- build.sh
- scripts/build.ps1
By default, restore happens twice
> Remove second restore

- src/System.Text.Formatting/System/Text/Formatting/Formatters/SequenceFormatter.cs
- src/System.Text.Json/System/Text/Json/JsonParser.cs
- tests/System.Buffers.Experimental.Tests/MemoryTests.cs
- tests/System.Buffers.Primitives.Tests/BufferReferenceTesting.cs
See https://github.com/dotnet/corefxlab/pull/2236
cc @dotnet/corefxlab-contrib, @KrzysztofCwalina
> Swap the order of memory Slice(..).Span to be Span.Slice(..)

- tests/Benchmarks/Azure/CosmosDbBench.cs
``` ini
BenchmarkDotNet=v0.10.14.525-nightly, OS=Windows 10.0.16299.371 (1709/FallCreatorsUpdate/Redstone3)
Intel Core i7-6700K CPU 4.00GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
Frequency=3914067 Hz, Resolution=255.4887 ns, Timer=TSC
.NET Core SDK=2.2.0-preview1-007460
[Host]     : .NET Core 2.2.0-preview1-26424-02 (CoreCLR 4.6.26423.05, CoreFX 4.6.26423.04), 64bit RyuJIT
DefaultJob : .NET Core 2.2.0-preview1-26424-02 (CoreCLR 4.6.26423.05, CoreFX 4.6.26423.04), 64bit RyuJIT
```
|     Method |       Mean |     Error |    StdDev | Scaled |
|----------- |-----------:|----------:|----------:|-------:|
|       Msdn | 4,589.5 ns | 8.3402 ns | 6.5115 ns |   1.00 |
| Primitives |   996.0 ns | 3.4698 ns | 3.2457 ns |   0.22 |
|     Writer | 1,208.8 ns | 1.5025 ns | 1.2546 ns |   0.26 | …
> Ported CosmosDbBench to BenchmarkDotNet

- tests/Benchmarks/Azure/StorageBench.cs
``` ini
BenchmarkDotNet=v0.10.14.525-nightly, OS=Windows 10.0.16299.371 (1709/FallCreatorsUpdate/Redstone3)
Intel Core i7-6700K CPU 4.00GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
Frequency=3914067 Hz, Resolution=255.4887 ns, Timer=TSC
.NET Core SDK=2.2.0-preview1-007460
[Host]     : .NET Core 2.2.0-preview1-26424-02 (CoreCLR 4.6.26423.05, CoreFX 4.6.26423.04), 64bit RyuJIT
DefaultJob : .NET Core 2.2.0-preview1-26424-02 (CoreCLR 4.6.26423.05, CoreFX 4.6.26423.04), 64bit RyuJIT
```
|       Method |     Mean |     Error |    StdDev | Scaled |
|------------- |---------:|----------:|----------:|-------:|
|         Msdn | 2.927 us | 0.0068 us | 0.0060 us |   1.00 |
|    Primitive | 1.258 us | 0.0055 us | 0.0049 us |   0.43 |
|     TryWrite | 1.353 us | 0.0003 us | 0.0003 us |   0.46 | …
> Ported StorageBench to BenchmarkDotNet

- tests/Benchmarks/System.Text.Json/JsonWriterPerf.cs
Related PR: https://github.com/dotnet/corefxlab/pull/2254
cc @adamsitnik
> Use IParam to create custom ArrayFormatter for JsonWriterPerf Test

- clean.cmd
Windows only, for now.
cc @KrzysztofCwalina, @MisinformedDNA
> Add a script to easily clean the repository, on-demand.

- tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs
- tools/dependencies.props
Verifying the fix for https://github.com/dotnet/BenchmarkDotNet/issues/738 / https://github.com/dotnet/BenchmarkDotNet/issues/748
cc @KrzysztofCwalina
> Update BenchmarkDotNet to latest to consume recent fixes

- tests/System.IO.FileSystem.Watcher.Polling.Tests/UnitTests.cs
- tests/System.IO.FileSystem.Watcher.Polling.Tests/Utility/Utility.cs
It was failing to create a directory in the specified location.
> Fix test case failing in PR #2281

- build.sh
- scripts/build.ps1
+ Fixed indentation in build.sh
cc @MisinformedDNA
> Add a message to console if latest dotnet cli is already installed.

- README.md
Updated the steps to be more accurate. Added some clarifying details from recent changes to the wiki: https://github.com/dotnet/corefxlab/wiki
cc @karelz, @dotnet/corefxlab-contrib, @adamsitnik, @MisinformedDNA
>  Updating the building and testing steps within the README of the repo.

- src/System.Text.JsonLab/System/Text/Json/JsonConstants.cs
- src/System.Text.JsonLab/System/Text/Json/JsonWriterUtf16.cs
- src/System.Text.JsonLab/System/Text/Json/JsonWriterUtf8.cs
- tests/System.Text.JsonLab.Tests/JsonWriterTests.cs
https://github.com/dotnet/corefxlab/issues/2315
> Optimize JsonWriterUtf8 and JsonWriterUtf16 WriteNull() methods (#2315)

- src/System.Text.Encodings.Web.Utf8/UrlEncoder.cs
- tests/Benchmarks/System.Text.Encodings.Web.Utf8/UrlEncoderPerf.cs
- tests/System.Text.Encodings.Web.Utf8.Tests/UrlEncoderTests.cs
> Use Utf8Parser to unescape percent encoding

- README.md
Please refer to issue #2340.
/cc @joshfree
> Update Readme.md to include System.Devices.Gpio

- tests/Benchmarks/System.Text.Primitives/CodePoint.cs
- tests/Benchmarks/System.Text.Primitives/EncodeFromUtf16toUtf8.cs
- tests/Benchmarks/System.Text.Primitives/EncodeFromUtf32toUtf16.cs
- tests/Benchmarks/System.Text.Primitives/EncodeFromUtf32toUtf8.cs
- tests/Benchmarks/System.Text.Primitives/EncodeFromUtf8toUtf16.cs
- tests/Benchmarks/System.Text.Primitives/EncoderHelper.cs
This address feedback of @ahsonkhan after PR #2335 was merged
> Rename UtfEncoderHelper to EncoderHelper

- samples/LowAllocationWebServer/Shared/SampleServer.cs
- src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs
- tests/Benchmarks/System.IO.Pipelines/E2E.cs
- tests/Benchmarks/System.Text.JsonLab/JsonWriterPerf.cs
- tests/System.Text.JsonLab.Tests/JsonWriterTests.cs
Leftover from https://github.com/dotnet/corefxlab/pull/2348.
> Rename JsonWriterUtf8 to JsonWriter

- src/System.Text.JsonLab/System/Text/Json/JsonConstants.cs
- src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs
@GrabYourPitchforks
@ahsonkhan
> Address PR feedback from #2329

- tests/Benchmarks/Benchmarks.csproj
This address small nit picking from #2333
> Sort ProjectReferences alphabetically

- src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs
> CalculateStartAttributeBytesNeeded calc issue

- README.md
- docs/specs/gpio.md
Move the GPIO planning md file to the docs directory
> Move planning.md to ../docs/specs/gpio.md

- src/System.Reflection.Metadata.Cil/CilCustomAttribute.cs
- src/System.Reflection.Metadata.Cil/CilMethodDefinition.cs
- src/System.Reflection.Metadata.Cil/CilProperty.cs
- src/System.Reflection.Metadata.Cil/CilTypeDefinition.cs
- src/System.Reflection.Metadata.Cil/CilTypeReference.cs
- src/System.Reflection.Metadata.Cil/Decoder/CilDecoder.cs
- src/System.Reflection.Metadata.Cil/Decoder/CilTypeProvider.cs
- src/System.Reflection.Metadata.Cil/SignatureDecoder.cs
- src/System.Reflection.Metadata.Cil/System.Reflection.Metadata.Cil.csproj
- tests/System.Reflection.Metadata.Cil.Tests/CilTests.cs
- tests/System.Reflection.Metadata.Cil.Tests/System.Reflection.Metadata.Cil.Tests.csproj
I'm trying to bring this back to life on my spare time to be able to have a cross-plat kind of ildasm based on this.
cc: @ahsonkhan @nguerrera
> Fix System.reflecion.metadata.cil to use latest S.R.Metadata package

- src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs
- Reorder the properties slightly.
- Dial back var usage
- Change private MoveNext() to GetNextSegment()
- Make buffer argument for Peek in
I'm not sure why the constructor was public and the factory method doesn't do anything. For now I'm presuming we want the factory method and I've made the constructor private.
I'm looking at making the various BufferReaderExtensions methods into extension methods.
> Tidy up BufferReader a bit.

- src/System.Binary.Base64/System.Binary.Base64.csproj
- src/System.Buffers.Primitives/System.Buffers.Primitives.csproj
- src/System.Collections.Sequences/System.Collections.Sequences.csproj
- src/System.Devices.Gpio/System.Devices.Gpio/System.Devices.Gpio.csproj
- src/System.Text.Encodings.Web.Utf8/System.Text.Encodings.Web.Utf8.csproj
- src/System.Text.Formatting/System.Text.Formatting.csproj
- src/System.Text.JsonLab/System.Text.JsonLab.csproj
- src/System.Text.Primitives/System.Text.Primitives.csproj
- src/System.Text.Utf8String/System.Text.Utf8String.csproj
See https://github.com/dotnet/corefxlab/pull/2383#discussion_r202849635
> Remove out-dated PackageIconUrl property and fallback to the one in common.props

- src/System.Text.JsonLab.Dynamic/System/Text/Json/JsonDynamicObject.cs
- src/System.Text.JsonLab.Dynamic/System/Text/Json/JsonSerializer.cs
- src/System.Text.JsonLab/System/Text/Json/JsonReader.cs
- tests/Benchmarks/System.Text.JsonLab/Comparison/JsonReader/JsonReaderComparison.cs
- tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs
- tests/System.Text.JsonLab.Tests/JsonParserTests.cs
- tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
Following the JsonWriter rename from here: https://github.com/dotnet/corefxlab/pull/2399
> Rename JsonReader to Utf8JsonReader to match the Writer

- src/System.Devices.Gpio/System.Devices.Gpio.Samples/Bme280.cs
- src/System.Devices.Gpio/System.Devices.Gpio.Samples/Program.cs
- src/System.Devices.Gpio/System.Devices.Gpio/GpioController.cs
- src/System.Devices.Gpio/System.Devices.Gpio/GpioExtensions.cs
- src/System.Devices.Gpio/System.Devices.Gpio/I2cExtensions.cs
- src/System.Devices.Gpio/System.Devices.Gpio/Pin.cs
- src/System.Devices.Gpio/System.Devices.Gpio/PinNumberingScheme.cs
- src/System.Devices.Gpio/System.Devices.Gpio/RaspberryPiDriver.cs
- src/System.Devices.Gpio/System.Devices.Gpio/SpiExtensions.cs
- src/System.Devices.Gpio/System.Devices.Gpio/UnixDriver.cs
- src/System.Devices.Gpio/System.Devices.Gpio/UnixI2CDevice.cs
- src/System.Devices.Gpio/System.Devices.Gpio/UnixSpiDevice.cs
- src/System.Devices.Gpio/System.Devices.Gpio/Utils.cs
* Bme280 class bug fix when used with I2c serial protocol
* Spi and I2c API refactoring and improvements
> API improvements and bug fixes

- src/System.Reflection.TypeLoader/src/System/Reflection/TypeLoader.Resolving.cs
- src/System.Reflection.TypeLoader/src/System/Reflection/TypeLoading/General/NetStandardBridge.cs
- tests/System.Reflection.TypeLoader.Tests/src/Tests/Type/TypeTests.cs
Fixes https://github.com/dotnet/corefxlab/issues/2460
Fixes https://github.com/dotnet/corefxlab/issues/2443
Also fixed some comment bloopers I noticed in the last few days.
> Fast-path AttributeType and support signature types

- src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs
- src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs
- src/System.Text.Http/System/Text/Http/Parser/HttpParser.cs
- src/System.Text.JsonLab/System/Text/Json/JsonReader.cs
- tests/Benchmarks/System.Buffers/Reader.cs
- tests/Benchmarks/System.Buffers/Reader_Search.cs
- tests/System.Buffers.ReaderWriter.Tests/ReaderBasicTests.cs
- tests/System.Buffers.ReaderWriter.Tests/ReaderBytesTests.cs
Change all SkipPast methods to return skipped count
Collapse helpers into main method
> Change consumed to long

- src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_text.cs
- tests/System.Buffers.ReaderWriter.Tests/Reader_ParseStruct.cs
Add initial tests, tweak some comments
> Add Date and Guid parsing

- src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs
- src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs
- tests/System.Buffers.ReaderWriter.Tests/ReaderBytesTests.cs
- tests/System.Buffers.ReaderWriter.Tests/Reader_SkipDelimiter.cs
Leftover feedback from https://github.com/dotnet/corefxlab/pull/2506#discussion_r222156375
> Fix bug in TryReadTo, add tests, and optimize AdvanceToNextSpan for the common case

- src/System.Text.JsonLab/System/Text/Json/JsonParser.cs
- src/System.Text.JsonLab/System/Text/Json/Utf8JsonReader.cs
> Rename NoMoreData to ConsumedEverything and change access modifiers

- src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs
- src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_binary.cs
- src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs
- src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_text.cs
- src/System.Buffers.ReaderWriter/System/ThrowHelper.cs
- src/System.Text.Http/System/Text/Http/Parser/HttpParser.cs
- tests/Benchmarks/System.Buffers/Reader.cs
- tests/Benchmarks/System.Buffers/Reader_Advance.cs
- tests/Benchmarks/System.Buffers/Reader_Binary.cs
- tests/Benchmarks/System.Buffers/Reader_Construction.cs
- tests/Benchmarks/System.Buffers/Reader_ParseInt.cs
- tests/Benchmarks/System.Buffers/Reader_Search.cs
- tests/System.Buffers.ReaderWriter.Tests/ReaderBasicTests.cs
- tests/System.Buffers.ReaderWriter.Tests/ReaderBytesTests.cs
- tests/System.Buffers.ReaderWriter.Tests/Reader_IsNext.cs
- tests/System.Buffers.ReaderWriter.Tests/Reader_ParseFloatingPoint.cs
- tests/System.Buffers.ReaderWriter.Tests/Reader_ParseInteger.cs
- tests/System.Buffers.ReaderWriter.Tests/Reader_ParseStruct.cs
- tests/System.Buffers.ReaderWriter.Tests/Reader_ReadTo.cs
- tests/System.Buffers.ReaderWriter.Tests/Reader_Rewind.cs
- tests/System.Buffers.ReaderWriter.Tests/Reader_SkipDelimiter.cs
Tweak Advance to squeeze 15% improvement
Add / move around some perf tests
> Put reader in Buffers root namespace

- src/System.Text.JsonLab/System/Text/Json/Utf8JsonReader.cs
- src/System.Text.JsonLab/System/Text/Json/Utf8JsonReaderStream.cs
- tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
**Is it OK to disallow single token sizes larger than 1 GB?** The upper limit is 2 GB anyway (since spans can't be larger than 2 GB) even if a ReadOnlySequence contains several GB of data.
**This is because we grow the buffer by doubling.** So, if a single token is more than 1 GB, we overflow beyond 2 GB and throw. It is possible to implement it in a way such that we can support a single token between 1 and 2 GB, **if** we grow the buffer linearly beyond 1 GB (we could drop down to increment by 1/10/100MB instead of doubling).
> Grow the pooled buffer exponentially (double) rather than linearly.

- build.sh
- scripts/build.ps1
- src/System.Buffers.Experimental/System/Buffers/Native/NativeMemoryPool.cs
- tests/Benchmarks/Benchmarks.csproj
- tools/common.props
- tools/dependencies.props
Relates to https://github.com/dotnet/corefxlab/issues/2585
I also updated the BDN version so that `[DryRunJob]` works.
> Suppress some warnings

- src/Microsoft.Experimental.Collections/Microsoft/Collections/Extensions/OrderedDictionary.cs
- tests/Microsoft.Experimental.Collections.Tests/Microsoft/Collections/Extensions/OrderedDictionaryTests.cs
Fixes Insert and Remove bugs with the buckets linked list when there are collisions.
> Fix ordered dictionary bugs

- .azure-pipelines.yml
- pipelines/corefxlab-base.yml
> Move CI builds to azure devops

- .azure-pipelines.yml
> Fix build number format for correct package versions

- src/System.Azure.Experimental/System/Azure/Key.cs
> Revert "[Donot review]temp"

- src/System.Azure.Experimental/System/Azure/Key.cs
> Revert "temp"

- src/Microsoft.Data/BaseColumn.cs
- src/Microsoft.Data/DataFrame.BinaryOperations.cs
- src/Microsoft.Data/DataFrame.BinaryOperations.tt
- src/Microsoft.Data/DataFrame.cs
- src/Microsoft.Data/PrimitiveColumn.Sort.cs
- src/Microsoft.Data/PrimitiveColumn.cs
- src/Microsoft.Data/PrimitiveColumnContainer.cs
- src/Microsoft.Data/StringColumn.cs
- src/Microsoft.Data/strings.Designer.cs
- src/Microsoft.Data/strings.resx
- tests/Microsoft.Data.DataFrame.Tests/BufferTests.cs
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
Implements support for null values in columns. 
Updated the unit tests to include null values and added some new ones to test the more corner cases
> Implement support for Null values in columns

- src/Microsoft.Data/BaseColumn.cs
- src/Microsoft.Data/DataFrame.cs
- src/Microsoft.Data/DataFrameTable.cs
- src/Microsoft.Data/PrimitiveColumn.Sort.cs
- src/Microsoft.Data/PrimitiveColumn.cs
- src/Microsoft.Data/PrimitiveColumnContainer.cs
- src/Microsoft.Data/StringColumn.BinaryOperations.cs
- src/Microsoft.Data/StringColumn.cs
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
This should go in after the [Null](https://github.com/dotnet/corefxlab/pull/2686) patch
More work towards a [DataFrame](https://github.com/dotnet/corefx/issues/26845) type. "Merge" will follow after this patch.
> Implement "Join"

- src/Microsoft.Data/BaseColumn.Computations.cs
- src/Microsoft.Data/BaseColumn.Computations.tt
- src/Microsoft.Data/BaseColumn.cs
- src/Microsoft.Data/ColumnArithmeticTemplate.ttinclude
- src/Microsoft.Data/DataFrame.cs
- src/Microsoft.Data/DataFrameTable.cs
- src/Microsoft.Data/GroupBy.cs
- src/Microsoft.Data/Microsoft.Data.DataFrame.csproj
- src/Microsoft.Data/PrimitiveColumn.BinaryOperations.tt
- src/Microsoft.Data/PrimitiveColumn.Computations.cs
- src/Microsoft.Data/PrimitiveColumn.Computations.tt
- src/Microsoft.Data/PrimitiveColumn.cs
- src/Microsoft.Data/PrimitiveColumnComputations.cs
- src/Microsoft.Data/PrimitiveColumnComputations.tt
- src/Microsoft.Data/PrimitiveColumnContainer.cs
- src/Microsoft.Data/StringColumn.cs
- src/Microsoft.Data/strings.Designer.cs
- src/Microsoft.Data/strings.resx
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
More work towards dotnet/corefx#26845
> GroupBy implementation

- src/Microsoft.Data/BaseColumn.cs
- src/Microsoft.Data/DataFrame.IDataView.cs
- src/Microsoft.Data/DataFrame.cs
- src/Microsoft.Data/DataFrameTable.cs
- src/Microsoft.Data/Microsoft.Data.DataFrame.csproj
- src/Microsoft.Data/PrimitiveColumn.cs
- src/Microsoft.Data/StringColumn.cs
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.IDataView.cs
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
- tests/Microsoft.Data.DataFrame.Tests/Microsoft.Data.DataFrame.Tests.csproj
Implement a simple IDataView implementation on top of DataFrame. This allows for DataFrame to be passed into training and scoring using ML.NET.
> Implement IDataView on DataFrame.

- standalone/Microsoft.Private.Intellisense/Microsoft.Private.Intellisense.nuspec
- standalone/Microsoft.Private.Intellisense/xmldocs/netcoreapp/1033/PresentationFramework.xml
- standalone/Microsoft.Private.Intellisense/xmldocs/netcoreapp/1033/System.Collections.Immutable.xml
- standalone/Microsoft.Private.Intellisense/xmldocs/netcoreapp/1033/System.Data.Common.xml
- standalone/Microsoft.Private.Intellisense/xmldocs/netcoreapp/1033/System.IO.Pipelines.xml
- standalone/Microsoft.Private.Intellisense/xmldocs/netcoreapp/1033/System.Text.Encodings.Web.xml
- standalone/Microsoft.Private.Intellisense/xmldocs/netcoreapp/1033/System.Text.Json.xml
- standalone/Microsoft.Private.Intellisense/xmldocs/netcoreapp/1033/UIAutomationClient.xml
- standalone/Microsoft.Private.Intellisense/xmldocs/netcoreapp/1033/WindowsBase.xml
This PR contains the last batch of 3.0 APIs documented and merged on Friday 08/16.
> .NET Core 3.0 Preview8 IntelliSense (English) - Last batch

- src/Microsoft.Data/BaseColumn.BinaryOperations.cs
- src/Microsoft.Data/BaseColumn.BinaryOperations.tt
- src/Microsoft.Data/BaseColumn.Computations.cs
- src/Microsoft.Data/BaseColumn.Computations.tt
- src/Microsoft.Data/ColumnArithmeticTemplate.ttinclude
- src/Microsoft.Data/GroupBy.cs
- src/Microsoft.Data/PrimitiveColumn.BinaryOperations.cs
- src/Microsoft.Data/PrimitiveColumn.BinaryOperations.tt
- src/Microsoft.Data/PrimitiveColumn.Computations.cs
- src/Microsoft.Data/PrimitiveColumn.Computations.tt
- src/Microsoft.Data/PrimitiveColumn.cs
- src/Microsoft.Data/StringColumn.BinaryOperations.cs
- src/Microsoft.Data/StringColumn.cs
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
Making the API more consistent around whether it operates in place or not. Should be an easy review.
> Inplace computations and binary ops

- src/Microsoft.Data/DataFrame.Join.cs
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
Fix for https://github.com/dotnet/corefxlab/issues/2727
> Description: Column ordering fix

- archived_projects/src/System.CommandLine/README.md
Added commas and missing word.
> Grammatical errors

- src/Microsoft.Data/ArrowStringColumn.cs
- src/Microsoft.Data/BaseColumn.cs
- src/Microsoft.Data/DataFrame.BinaryOperations.cs
- src/Microsoft.Data/DataFrame.BinaryOperations.tt
- src/Microsoft.Data/DataFrame.cs
- src/Microsoft.Data/DataFrameTable.cs
- src/Microsoft.Data/PrimitiveColumn.cs
- src/Microsoft.Data/StringColumn.cs
- src/Microsoft.Data/strings.Designer.cs
- src/Microsoft.Data/strings.resx
- tests/Microsoft.Data.DataFrame.Tests/BufferTests.cs
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
Address feedback from https://github.com/dotnet/corefxlab/issues/2734 and other functions I found that could use an `inPlace` option.
> Make the API return a copy more consistently

- src/Microsoft.Data/DataFrame.cs
- src/Microsoft.Data/DataFrameColumn.cs
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
> Add strongly typed indexers

- src/Microsoft.Data/ArrowStringDataFrameColumn.cs
- src/Microsoft.Data/DataFrame.IO.cs
- src/Microsoft.Data/DataFrame.cs
- src/Microsoft.Data/DataFrameColumn.cs
- src/Microsoft.Data/GroupBy.cs
- src/Microsoft.Data/PrimitiveColumnContainer.cs
- src/Microsoft.Data/PrimitiveDataFrameColumn.Sort.cs
- src/Microsoft.Data/PrimitiveDataFrameColumn.cs
- src/Microsoft.Data/StringDataFrameColumn.cs
- src/Microsoft.Data/strings.Designer.cs
- src/Microsoft.Data/strings.resx
- tests/Microsoft.Data.DataFrame.Tests/DataFrame.IOTests.cs
> Minor changes to the API

- src/Microsoft.Data/StringDataFrameColumn.BinaryOperations.cs
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
Add StringDataFrameColumn specific APIs. I found these last week while trying to explore a dataset
> Add string specific APIs to StringDataFrameColumn

- src/Microsoft.Data/DataFrame.IO.cs
- src/Microsoft.Data/DataFrame.cs
- src/Microsoft.Data/DataFrameColumn.cs
- src/Microsoft.Data/PrimitiveDataFrameColumn.cs
- src/Microsoft.Data/StringDataFrameColumn.cs
- src/Microsoft.Data/strings.Designer.cs
- src/Microsoft.Data/strings.resx
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
Implements DataFrame.Append.
This is the second half of #2730 and also fixes one part of https://github.com/dotnet/corefxlab/issues/2719
> Implement Append on DataFrame

- src/Microsoft.Data/ArrowStringDataFrameColumn.cs
- src/Microsoft.Data/StringDataFrameColumn.BinaryOperations.cs
- tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
Fix for https://github.com/dotnet/corefxlab/issues/2754
> Add ElementwiseEquals for ArrowStringDataFrameColumn

- src/Microsoft.Data.Analysis/DataFrame.cs
- src/Microsoft.Data.Analysis/DataFrameColumnCollection.cs
- tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
> Params constructor on DataFrame

- tests/Microsoft.Data.Analysis.Tests/DataFrame.IOTests.cs
> Add additional tests for ReadCsv

- src/Microsoft.Data.Analysis/DataFrame.IO.cs
- src/Microsoft.Data.Analysis/DataFrame.cs
- tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
> Append rows to a DataFrame

- src/Microsoft.Data.Analysis/ArrowStringDataFrameColumn.cs
- src/Microsoft.Data.Analysis/DataFrame.BinaryOperators.cs
- src/Microsoft.Data.Analysis/DataFrame.BinaryOperators.tt
- src/Microsoft.Data.Analysis/DataFrame.IO.cs
- src/Microsoft.Data.Analysis/DataFrame.Join.cs
- src/Microsoft.Data.Analysis/DataFrame.cs
- src/Microsoft.Data.Analysis/DataFrameColumn.BinaryOperators.cs
- src/Microsoft.Data.Analysis/DataFrameColumn.BinaryOperators.tt
- src/Microsoft.Data.Analysis/DataFrameColumn.cs
- src/Microsoft.Data.Analysis/DataFrameColumnCollection.cs
- src/Microsoft.Data.Analysis/GroupBy.cs
- src/Microsoft.Data.Analysis/PrimitiveDataFrameColumn.cs
- src/Microsoft.Data.Analysis/StringDataFrameColumn.cs
- tests/Benchmarks/Microsoft.Data.Analysis.DataFrame/DataFrameFunctions.cs
- tests/Microsoft.Data.Analysis.Tests/ArrowIntegrationTests.cs
- tests/Microsoft.Data.Analysis.Tests/BufferTests.cs
- tests/Microsoft.Data.Analysis.Tests/DataFrame.IOTests.cs
- tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
All of these changes are from the API review. Pretty straightforward
> Address remaining concerns from the 2nd DataFrame API Review 

- src/Microsoft.Data.Analysis/DataFrameColumnCollection.cs
- src/Microsoft.Data.Analysis/strings.Designer.cs
- src/Microsoft.Data.Analysis/strings.resx
- tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
Add APIs to DataFrameColumnCollection to get the strongly typed columns
> Add APIs to get the strongly typed columns from a DataFrame

- src/Microsoft.Data.Analysis/ArrowStringDataFrameColumn.cs
- tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
Fixes 2 in https://github.com/dotnet/corefxlab/issues/2860
> Add Apply to ArrowStringDataFrameColumn

- src/Microsoft.Data.Analysis/DataFrame.Arrow.cs
- src/Microsoft.Data.Analysis/DataFrame.IO.cs
- tests/Microsoft.Data.Analysis.Tests/ArrowIntegrationTests.cs
- tests/Microsoft.Data.Analysis.Tests/DataFrame.IOTests.cs
Needed for Spark integration. Should be a shoo-in.
> Support for Exploded columns types in Arrow and IO scenarios

- Directory.Build.props
- Directory.Build.targets
- README.md
- src/Microsoft.Data.Analysis/Microsoft.Data.Analysis.csproj
This should let us mark individual packages are stable in the future. 
Thanks @safern! 
cc @joperezr @eerhardt @ericstj
> Fix versioning to allow for individual stable packages

- global.json
- tests/Benchmarks/Benchmarks.csproj
Fixing things we missed from the arcade auto update/merge.
> Darc update fail

- README.md
- src/Microsoft.Data.Analysis/Microsoft.Data.Analysis.csproj
Just cleaning up the M.D.A version and a minor update to the README
> Increment version and stop producing stable packages

- Microsoft.Data.Analysis.Interactive/DataFrameKernelExtension.cs
- Microsoft.Data.Analysis.Interactive/Microsoft.Data.Analysis.Interactive.csproj
- corefxlab.sln
- src/Microsoft.Data.Analysis/Microsoft.Data.Analysis.csproj
New Microsoft.Data.Analysis.Interactive project was created (as suggested).
**DataFrame object formatter** was added. By default:
- Paginated at 10 rows per page 
- Max limit is 10.000 rows
cc @eerhardt @pgovind  @colombod @jonsequitur
> Add DataFrame object formatter.

- src/Microsoft.Data.Analysis/DataFrame.IO.cs
- tests/Microsoft.Data.Analysis.Tests/DataFrame.IOTests.cs
I added WriteCsv method (plus some unit tests) to write a DataFrame to CSV file. This solves #2917.
@eerhardt @pgovind I have recreated the PR following Eric's recommendations from #2945. Please review.
> Add WriteCsv plus unit tests.
