demos/CoreClrConsoleApplications/HelloWorld/HelloWorld.cs
Just by looking at the code you can likely guess what gets drawn for Linux ;)
I've left Mac as a todo for someone else who'd like to contribute something beautiful.
Right now, the console app just takes the target platform as a command-line argument.  We can update it later to fall back to a default based on Environment.
=> Add per-platform ANSI art to HelloWorld

demos/CoreClrConsoleApplications/HelloWorld/nuget.config
Some of the packages require CoreFX MyGet feed. In order to make restoring packages work out-of-the-box we need to add a nuget.config file that points to the correct feed.
@KrzysztofCwalina
=> Add missing nuget.config

src/System.Text.Formatting/src/System/InternalHelpers/BufferPool.cs, src/System.Text.Formatting/src/System/Text/Formatting/StreamFormatter.cs, src/System.Text.Formatting/src/System/Text/Formatting/StringFormatter.cs
Though it has so much policy burnt into it. Maybe it's unavoidable.
Also, maybe somebody can look through the lock free Bin implementation. There are never too many eyes looking at code like that.
=> Replaced dummy buffer pool with a more real one

src/System.Text.Formatting/src/System/ReadOnlySpan.cs
It used to return Span<T>, which was a design bug.
=> ReadOnlySpan<T>.Slice now returns ReadOnlySpan<T>

src/System.Text.Formatting/src/System.Text.Formatting.csproj, src/System.Text.Formatting/src/System/ByteSpan.cs
I wish I could use just Span<byte> in all cases.
Unfortunatelly, Span<T> (as implementable currently) is too slow for some tight formatting loops.
We might at some point get a fast Span<T>, and remove this type.
The main problem with Span<T> is that all indexer accessors need to do double pointer arrithmetic (offset from array and index into array)
ByteSpan accessor just needs one pointer offset.
=> Added ByteSpan

src/System.Text.Formatting/src/System/ByteSpan.cs, src/System.Text.Formatting/src/System/Span.cs, src/System.Text.Formatting/src/System/Text/Formatting/PrimitiveFormatters.cs, src/System.Text.Formatting/src/System/Text/Formatting/StringFormatter.cs
I tried to also use ByteSpan for formatting other types, but only in internal implementation.
This resulted in performance regressions, as there was too many ByteSpans created (when public method enters)
and then immediately destroyed (when it terminates).
I think I would have to make ByteSpan public to see the perf wins for small datatypes,
but I am not ready to make it public yet.
=> Changed string formatting APIs to use ByteSpan

demos/LowAllocationWebServer/packages.config, nuget/System.Text.Formatting.nuspec
Nuget does not like version numbers starting with 0, but not being exactly 0.
=> Fixed issue with the nuspec for System.Text.Formatting

src/System.Text.Formatting/src/System.Text.Formatting.csproj, src/System.Text.Formatting/src/System/Text/Formatting/CompositeFormat.cs, src/System.Text.Formatting/tests/CompositeFormattingTests.cs, src/System.Text.Formatting/tests/System.Text.Formatting.Tests.csproj
Composite formatting allows to format based on a template with one or more insertion points, e.g.
var formatter = new StringFormatter();
formatter.Format("{2} - Error {0}. File {1} not found.", 404, "index.html", DateTime.UtcNow);
This is very convinient, but unfortunatelly causes lots of GC heap allocations: the inseterd arguments
are often boxed and sometimes a so called "params-array" needs to be allocated.
This prototype can do composite formatting without any allocation (no boxing and no arrays), but only for
primitive types (ints, strings, chars, DateTime, TimeSpan) and only for up to 5 arguments.
Unfortunately, because not all type in the system implement IBufferFormattable, this API does not
support types that do implement it (yes, it sounds backwards buy I did not mistype that). …
=> Added prototype of composite formatting support

src/System.Text.Formatting/src/System/Text/Formatting/CompositeFormat.cs
This is to prepare it to handle formats and precision
Also, I caved in and I am now handling custom formattable types with boxing. Boxing is done at the end of  AppendUntyped when the value is cast to IBufferFormattable interface.
=> Refactored CompositeFormatReader 

src/System.Text.Formatting/src/System/Text/Formatting/CompositeFormat.cs, src/System.Text.Formatting/src/System/Text/Formatting/ParsedFormat.cs, src/System.Text.Formatting/tests/CompositeFormattingTests.cs
You can now add ":<format>" to the insertion points:
var formatter = new StringFormatter();
formatter.Format("Hello{0:x}{1:X}{2:G}", 10, 255, 3);
Assert.Equal("HelloaFF3", formatter.ToString());
=> Added support for format specifiers in composite format strings

src/System.Text.Formatting/src/System/InternalHelpers/FloatFormatter.cs, src/System.Text.Formatting/src/System/InternalHelpers/IntegerFormatter.cs, src/System.Text.Formatting/src/System/Text/Formatting/CompositeFormat.cs, src/System.Text.Formatting/src/System/Text/Formatting/ParsedFormat.cs, src/System.Text.Formatting/src/System/Text/Formatting/PrimitiveFormatters_float.cs, src/System.Text.Formatting/src/System/Text/Formatting/PrimitiveFormatters_time.cs, src/System.Text.Formatting/src/System/Text/Formatting/PrimitiveFormatters_uuid.cs, src/System.Text.Formatting/tests/ParsedFormatUnitTests.cs, src/System.Text.Formatting/tests/PrimitiveFormattingTests-Guid.cs, src/System.Text.Formatting/tests/PrimitiveFormattingTests-Time.cs
The symbol was represented by an enum, but this prevents 3rd party extensibility
=> I changed Formad.Parsed.Symbol to be a char

demos/LowAllocationWebServer/HttpServer.cs, demos/LowAllocationWebServer/TcpServer.cs
For some reason the previous C# compiler was not complaining about default ctors in structs.
Also, it apparently was running such ctors.
=> Fixed a bug exposed in the recent tools update

src/System.Text.Formatting/src/System/InternalHelpers/IntegerFormatter.cs, src/System.Text.Formatting/src/System/Span.cs, src/System.Text.Formatting/src/System/Text/Formatting/FormattingData.cs
The bug was causing some arrays to be copied twice
=> Bug fix in Span<T>

demos/CoreClrConsoleApplications/HelloWorld/HelloWorld.cs
With FreeBSD now having a functioning corerun-implementation, it obviously needs
to have a FreeBSD-specific greeting in the build-instructions.
=> HelloWorld: Represent FreeBSD.

src/System.IO.FileSystem.Watcher.Polling/src/System/IO/InteropDeclarations.cs, src/System.IO.FileSystem.Watcher.Polling/src/System/IO/PollingWatcher.cs
This improves performance approximatelly by 2x
Now, on my home computer, the node_modules folder (and its subfolders) can be processed in ~35ms
=> Changed to use FindFirstFileExW instead of FindFirstFile

src/System.IO.FileSystem.Watcher.Polling/src/System.IO.FileSystem.Watcher.Polling.csproj, src/System.IO.FileSystem.Watcher.Polling/src/System/IO/Datastructures.cs, src/System.IO.FileSystem.Watcher.Polling/src/System/IO/PathToFileStateHashtable.cs, src/System.IO.FileSystem.Watcher.Polling/src/System/IO/PollingWatcher.cs, src/System.IO.FileSystem.Watcher.Polling/src/packages.config, src/System.IO.FileSystem.Watcher.Polling/tests/packages.config
it's now possible to configure the PollingWatcher.Tracing property to get diagnostic information about the workings of the watcher. For example, 
```c#
var watcher = new PollingWatcher(@"C:\Users\kcwalina\Desktop\FSWTestFolder", true, 1000);
watcher.Tracing.Listeners.Add(new ConsoleTraceListener());
watcher.Tracing.Switch.Level = SourceLevels.All;
watcher.Tracing.TraceInformation("tracing enabled");
watcher.ChangedDetailed += (changes) => {
foreach (var change in changes) {
Console.WriteLine("{0} {1}", change.Path, change.ChangeType);
}
};
watcher.Start();
while (true) { }
```
=> Added better diagnostics

demos/LowAllocationWebServer/HttpServer.cs, demos/LowAllocationWebServer/LowAllocationServer.csproj, demos/LowAllocationWebServer/SampleServer.cs, demos/LowAllocationWebServer/packages.config, nuget/System.Text.Formatting.nuspec, src/System.Text.Formatting/src/System/InternalHelpers/BufferPool.cs, src/System.Text.Formatting/src/System/Text/Formatting/BufferFormatter.cs, src/System.Text.Formatting/src/System/Text/Formatting/StreamFormatter.cs, src/System.Text.Formatting/src/System/Text/Formatting/StringFormatter.cs
In highly concurent scenarios, buffer pool of 10 is not large enough.
This change allows web servers to create custom buffer pools (BufferBin) with custom capacity.
=> Added ability to control the size of buffer pool

dir.props, src/.nuget/packages.Unix.config, src/.nuget/packages.Windows_NT.config
Unfortunately, this breaks System.Numerics.Matrices as this project uses string interpolation which is not supported by the engineering system. This issue will be fixed as a separate commit
=> Synchronized engineering system with corefx

src/System.Drawing.Graphics/src/System.Drawing.Graphics.csproj, src/System.Drawing.Graphics/src/project.json, src/System.Drawing.Graphics/src/project.lock.json, src/System.Drawing.Graphics/tests/System.Drawing.Graphics.Tests.csproj, src/System.Drawing.Graphics/tests/packages.config, src/System.Drawing.Graphics/tests/project.json, src/System.Drawing.Graphics/tests/project.lock.json
This cleans up the packages.config use in the System.Drawing.Graphics projects.  It also converts them to behave as v3 PCLs with a guess at what the targets should be (UWP, DNXCore, and Net46).  I've also added a a dependency on fluent assertions to validate that this works and unblocks you.
/cc @KrzysztofCwalina @tarekgh @axxu @weshaggard
=> Nuget cleanup

src/System.Reflection.Metadata.Cil/src/System.Reflection.Metadata.Cil.csproj, src/System.Reflection.Metadata.Cil/src/packages.config, src/System.Reflection.Metadata.Cil/tests/System.Reflection.Metadata.Cil.Tests.csproj, src/System.Reflection.Metadata.Cil/tests/packages.config
This fixes the build break where the immutable collection package version could not be resolved.
=> Downgrade immutable collections to version 36

dir.props
…lve packages
This enables the build to resolve the System.Reflection.Metadata package.
=> Add the dotnet-corefx feed to the list of feeds used by nuget to resolve packages

src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.cs
These are needed by consumers of the previous Utf8String
=> Added more placeholder members to Utf8String

src/System.Reflection.Metadata.Cil/src/CilAssembly.cs, src/System.Reflection.Metadata.Cil/tests/CilTests.cs, src/System.Reflection.Metadata.Cil/tests/app.config
This fixes dotnet/corefxlab#172 so that CilAssembly can't be disposed twice in order to avoid exceptions.
This was done keeping track of the current dispose status.
cc @AlexGhiondea
=> Fix issue #172 in System.Reflection.Metadata.Cil

src/System.Reflection.Metadata.Cil/src/System.Reflection.Metadata.Cil.csproj, src/System.Reflection.Metadata.Cil/tests/System.Reflection.Metadata.Cil.Tests.csproj
This is a quick fix to ensure the build of corefxlab is not broken by these
projects.
=> Create the BuildAndTest target for the System.Reflection.Metadata.Cil project

demos/dotnet/dotnet/dotnet.cs
The user can specify the dotnetproj file path if they like. Otherwise,
use the one found in the current directory.
=> Allow user to pass in the project file as a command line argument

demos/dotnet/dotnet/README.txt, demos/dotnet/dotnet/dependencies.txt, demos/dotnet/dotnet/dotnet-core.csproj, demos/dotnet/dotnet/dotnet.cs, demos/dotnet/dotnet/dotnet.dotnetproj, demos/dotnet/dotnet/packages.txt, demos/dotnet/dotnet/project.json, demos/dotnet/dotnet/references.txt
Removed support for packages.txt file (use packages listed in .dotnetproj file).
Added a new .csproj file which can be used to build against coreclr.
Removed the /edit command.
=> Removed the support for packages.txt and work towards making dotnet into a CoreCLR app.

src/System.Buffers/src/System.Buffers.csproj, src/System.Buffers/src/System/Buffers/ArrayBufferPool.cs, src/System.Buffers/src/System/Buffers/BufferPool.cs, src/System.Buffers/src/System/ByteSpan.cs, src/System.Buffers/src/System/Span.cs
The field was used to identify the location of the span in a buffer pool
This change removes the field and now the location is computed using memory addresses.
Also, I split the BufferPool.cs file into two: one for native pool and the other for array pool. The code in the new file (ArrayBufferPool.cs) is just copy paste (no changes) from the original file.
=> Removed the need for ID field in ByteSpan

demos/LibuvWithNonAllocatingFormatters/sample/Program.cs, demos/LibuvWithNonAllocatingFormatters/sample/Sample.csproj, demos/LibuvWithNonAllocatingFormatters/src/System.Net.Libuv.csproj, demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Handle.cs, demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Request.cs, demos/LibuvWithNonAllocatingFormatters/src/System/Net/Libuv/Stream.cs
The change elimizates Action<int> and display class allocations.
=> Optimized allocations when disposing UVStream

src/System.Threading.Tasks.Channels/README.md, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.BoundedChannel.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.CaseBuilder.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.EnumerableChannel.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.Observable.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.SerializationChannel.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.SpscUnboundedChannel.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.TaskChannel.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.UnboundedChannel.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.UnbufferedChannel.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/IChannel.cs, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/ValueTask.cs, src/System.Threading.Tasks.Channels/tests/SerializationChannelTests.cs, src/System.Threading.Tasks.Channels/tests/ValueTaskTests.cs
Fix a few warnings generated by running code analysis on the System.Threading.Tasks.Channels library.
=> Fix some analysis warnings in Channels

src/System.Threading.Tasks.Channels/README.md, src/System.Threading.Tasks.Channels/src/System.Threading.Tasks.Channels.csproj, src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.SerializationChannel.cs
- Removed unnecessary ```unsafe``` usage
- Added comments to README about ```ValueTask<T>```
=> Address more PR feedback on System.Threading.Tasks.Channels

README.md, dir.props, nuget/System.Collections.Generic.MultiValueDictionary.nuspec, nuget/pack.bat, nuget/push.bat, src/.nuget/packages.Unix.config, src/.nuget/packages.Windows_NT.config, src/System.Collections.Generic.MultiValueDictionary/System.Collections.sln, src/System.Collections.Generic.MultiValueDictionary/src/Resources/Strings.resx, src/System.Collections.Generic.MultiValueDictionary/src/System.Collections.csproj, src/System.Collections.Generic.MultiValueDictionary/src/System/Collections/Generic/MultiValueDictionary.cs, src/System.Collections.Generic.MultiValueDictionary/src/project.json, src/System.Collections.Generic.MultiValueDictionary/src/project.lock.json, src/System.Collections.Generic.MultiValueDictionary/tests/Generic/MultiValueDictionary/MVD.TestBase.cs, src/System.Collections.Generic.MultiValueDictionary/tests/Generic/MultiValueDictionary/MVD.Tests.cs, src/System.Collections.Generic.MultiValueDictionary/tests/Performance/Perf.MVD.cs, src/System.Collections.Generic.MultiValueDictionary/tests/System.Collections.Tests.csproj, src/System.Collections.Generic.MultiValueDictionary/tests/project.json, src/System.Collections.Generic.MultiValueDictionary/tests/project.lock.json
The MultiValueDictionary is an experimental collection that was first released the summer of 2014 as a Nuget package. This commit releases the source code of the MultiValueDictionary tied into .NET Core with the intention of it being considered as an addition to System.Collections.Generic in CoreFX.
- All code is open sourced from the original package with only changes made to get it functioning. As such, some things will need to be changed to better match the style of CoreFX (e.g. the tests).
- I based the csproj, project.json, folder structure, and strings.resx heavily on that of System.Collections.Generic in CoreFX so that they may be easily merged in the future. This is why Strings.resx has some strings that aren't used by the MVD
- Addition of performance tests required an update of …
=> Initial open-sourcing commit of the MultiValueDictionary

demos/dotnet/dotnet/CscAction.cs, demos/dotnet/dotnet/ProjectPropertiesHelpers.cs, demos/dotnet/dotnet/Settings.cs, demos/dotnet/dotnet/dotnet.cs
They can be referenced as follows:
dotnet.exe /reference:A.dll,B.dll,C.dll
=> Added the ability to explicit reference dlls

src/System.Text.Utf8/src/System.Text.Utf8.csproj, src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.cs, src/System.Text.Utf8/src/project.lock.json, src/System.Text.Utf8/tests/PerformanceTests.cs, src/System.Text.Utf8/tests/RandomTests.cs, src/System.Text.Utf8/tests/System.Text.Utf8.Tests.csproj, src/System.Text.Utf8/tests/project.json, src/System.Text.Utf8/tests/project.lock.json
This will measure Utf8String implemented on ByteSpan.
Perf tested functionalities (IMO sufficient baseline):
-	Construct from string (convert from string to Utf8String)
-	Enumerate CodeUnits forward
-	Enumerate CodePoints forward
-	Enumerate CodePoints backward
-	IndexOf(Utf8CodeUnit) - searching for non-existing character (to make it as long as possible)
-	IndexOf(Utf8CodePoint) - searching for non-existing character (to make it as long as possible)
Each case tested for:
-	String constructed from byte[], string constructed from ByteSpan
-	4 different types of strings: [short (5 characters), ASCII], [short (5 chars), any 16bit Unicode codepoint], [long (50k chars), ASCII], [long (50k chars), any 16bit Unicode codepoint]
=> Perf tests for basic Utf8String functionalities

demos/dotnet/dotnet/ProjectPropertiesHelpers.cs
This is step 1 to make dotnet.exe work with Utf8String literals
=> Add support for dotnet.exe to change csc.exe

netci.groovy
Fixing the groovy script to not call the VS Command Prompt twice. The build.cmd in the branch already opens the VsCmd so we don't need to specify it in the groovy script
/cc @mmitche
=> Fixing the groovy script to not call the VS Command Prompt twice

netci.groovy
Fixing groovy script to not pass 'Debug' or 'Release' for the time being; CoreFxLab is pre-release software and we only need Debug builds at this point in time.
/cc @mmitche; this is to unblock the build
=> Fixing groovy script to not pass 'Debug' or 'Release' for the time being

src/System.Buffers/System.Buffers.sln, src/System.Buffers/tests/System.Buffers.Tests.csproj
Super annoying when one project builds as Debug and second as Release.
=> Fix System.Buffers to allow VS build Release build for test project

src/System.Buffers/src/System/Buffers/BufferBucket.cs, src/System.Buffers/src/System/Buffers/BufferPool.cs
Perf optimization to Lazy initialize the Buffer Buckets by only initializing the bucket when a buffer of that bucket's size has been requested as well as removing the interlocked operations during the spinlock exit
/cc @KrzysztofCwalina
=> Perf optimization to Lazy initialize the Buffer Buckets

src/System.Text.Utf8/tests/PerformanceTests.cs
This is running for too long now to actually be useful when writing code
=> shorten utf8string perf tests to around 1s per test

src/System.Buffers/src/System/Buffers/ManagedBufferPool.cs, src/System.Buffers/src/System/Buffers/NativeBufferBucket.cs, src/System.Buffers/src/System/Buffers/NativeBufferPool.cs
Adding a lazy-loading Shared buffer to both the Managed and Native buffer pools to reduce the boilerplate needed to use the pools if desired.
/cc @KrzysztofCwalina 
#356
=> Adding a lazy-loading Shared buffer to both the Managed and Native pools

src/System.Text.Http/tests/GivenAnHttpHeaders.cs
Re-enabling HTTP tests as their failure seems to have been a one off on Jon's machine. I couldn't repro the issue locally and CI has been passing
=> Re-enabling HTTP tests

src/System.Slices/src/System/Span.cs
In my previous PR I have changed the GetHashCode method. As @GSPP noticed [here](https://github.com/dotnet/corefxlab/pull/455#issuecomment-160470516) I have used the wrong number, 33 instead of 31. 33  is not a prime number, hence the fix.
=> fix for Span: using prime number in hashing function

src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.SpscUnboundedChannel.cs, src/System.Threading.Tasks.Channels/tests/UnboundedChannelTests.cs
Fixes https://github.com/dotnet/corefxlab/issues/478
=> Detect and throw for concurrent reads on SpscUnboundedChannel

src/System.Threading.Tasks.Channels/src/System/Threading/Tasks/Channels/Channel.SpscUnboundedChannel.cs
Fixes https://github.com/dotnet/corefxlab/issues/472
=> Remove unnecessary lock in SpscUnboundedChannel.WaitToWriteAsync

src/System.Text.Formatting/GenerateCompatibilityTests/Program.cs
Fix GenerateCompatibilityTests test code generator to produce compatible code for System.Text.Formatting.Tests, #490.
=> Fix GenerateCompatibilityTests test code generator

src/System.Text.Formatting/tests/CompositeFormattingTests.cs, src/System.Text.Formatting/tests/PrimitiveFormattingTests.cs
Tests should rely on invariant culture or its derivative, because they are dependent on test environment customizations and can fail.
=> Fix dependency on time format of test environment

src/System.Buffers/src/System/Buffers/ManagedBufferPool.cs
The instruction makes debugging of projects, which relate on System.Buffers, quite inconvenient.
=> Remove debugger break instruction

src/System.Time/tests/DateFormattingTests.cs, src/System.Time/tests/TimeOfDayFormattingTests.cs
Tests should rely on invariant culture, because they are dependent on test environment customizations and can fail.
=> Fix dependency on date and time format of test environment

dotnet.targets
Switching the msbuild build target for dotnet cli from the compile command to the build command.
=> Switch msbuild to use dotnet build command

src/System.Slices/src/System/SpanExtensions.cs
SpanExtensions.Read doesn't have to create a Span to read by zero index.
I replaced it with direct reinterpret reading from the slice.
Microbenchmarks show 3.5 - 4 times better perf. Difference in amount of the generated code is huge.
```C#
public static long TestSpan(Span<byte> span)
{
return span.Read<long>();
}
```
This is  TestSpan method after the change:
```ASM
; Assembly listing for method CoreClrTest.Program:TestSpan(struct):long
; Emitting BLENDED_CODE for X64 CPU with SSE2
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  6,  10  )   byref  ->  rcx        
;* V01 tmp0         [V01    ] (  0,   0  )  struct (24) zero-ref    ld-addr-op
;* V02 tmp1 …
```
=> Slices: Reduce complexity of SpanExtensions Read and Write methods

src/System.Slices/src/System/Contract.cs
Issue: https://github.com/dotnet/corefxlab/issues/510 
Two changes reduce size of machine code generated in **each** call site of Span's indexer by 27 bytes and eliminates one comparison and branch:
1. The trick used by array bounds checking
2. Wrapping creation of exception instance in a separate non-inlinable method.
Here is an example:
```C#
public static long TestSpan(Span<long> span, int index)
{
return span[index];
}
```
Before:
```asm
00007FF81D260C70  push        rsi  
00007FF81D260C71  sub         rsp,20h  
00007FF81D260C75  mov         eax,dword ptr [rcx+10h]  
00007FF81D260C78  test        edx,edx  
00007FF81D260C7A  jl          00007FF81D260C9A  
00007FF81D260C7C  cmp         edx,eax  
00007FF81D260C7E  jge         00007FF81D260C9A …
```
=> Slices: Reduce size of code generated for Contract methods.

src/System.Slices/src/System/Span.cs
They are readonly and of immutable types anyway.
=> Slices: Make Span's Object and Offset fields internal

src/System.Slices/src/System/SpanExtensions.cs
For the JIT Span is a not primitive type (it contains a reference) and the generated code  is sometimes suboptimal. The change  is a workaround for one such case.
```C#
public static void TestSpanCast(Span<byte> span)
{
var spanLong = span.Cast<byte, long>();
}
```
After the change:
```ASM
; Assembly listing for method CoreClrTest.Program:TestSpanCast(struct)
; Lcl frame size = 24
G_M62531_IG01:
57                   push     rdi
56                   push     rsi
4883EC18             sub      rsp, 24
488BF1               mov      rsi, rcx
488D3C24             lea      rdi, [rsp]
B906000000           mov      ecx, 6
33C0                 xor      rax, rax
F3AB                 rep stosd 
488BCE               mov      rcx, rsi
G_M62531_IG02:
4C8B01 …
```
=> Slices: Optimize Cast

src/System.Time/src/System/Date.cs, src/System.Time/src/System/DateTimeExtensions.cs, src/System.Time/src/System/DateTimeOffsetExtensions.cs, src/System.Time/src/System/TimeOfDay.cs, src/System.Time/tests/DateFormattingTests.cs, src/System.Time/tests/TimeOfDayFormattingTests.cs
System.DateTime type doesn't have such methods, but it will more convenient if System.Date and System.TimeOfDay types will have ToShortString / ToLongString methods for invariant culture.
=> Add methods ToShortString / ToLongString for invariant culture for System.Time types

src/System.Time/src/System/DateTimeExtensions.cs, src/System.Time/src/System/DateTimeOffsetExtensions.cs
Extension methods names for System.DateTime type, which returns System.Date and System.TimeOfDay types should start with "Get" (or, probably, "To") prefix to highlight that this is an extension method and not a native property. Moreover, Date() extension method name is very similar to Date property name.
=> Improve extension methods names for DateTime type in System.Time

src/System.Text.Utf8/src/System/Text/Utf8/Utf8String.cs
Slice has indexer that does the boundaries check, so there is no need to do this twice.
=> Utf8String: indexer without boundaries check (done by Slice anyway)

package.ps1
The dMMddyy version suffix for our packages does not work well with nuget/VS upgrade experiences,
i.e. a suffix is considered to represent a newer version, if it sorts later in the alphabetical order.
This change aligns the suffix sort order with time.
=> Change package versioning convention to make upgrades easier

src/System.Slices/src/System/Contract.cs, src/System.Slices/src/System/Span.cs, src/System.Slices/src/System/SpanExtensions.cs, src/System.Slices/tests/BasicUnitTests.cs
Issue #537  
Both overloads of Span.Slice method allow to read at negative offsets.
Besides that they lack AggressiveInlining attribute what makes them slow.
I used the following benchmark code:
```C#
public class BenchmarkSlice
{
Span<char> slice;
public BenchmarkSlice()
{
string str = new string('c', 256);
slice = str.Slice();
}
[Benchmark]
public void Slice()
{
var copy = slice;
do
{
copy = copy.Slice(1);
}
while (copy.Length != 0);
}
[Benchmark]
public void SliceWithLength()
{
var copy = slice;
do
{
copy = copy.Slice(1, copy.Length - 1);
}
while (copy.Length != 0);
}
}
```
**Original results (before the change)**
BenchmarkDotNet=v0.8.0.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz, ProcessorCount=4
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit …
=> Slices: Fix oveflows in Span<T>.Slice methods

src/System.Net.Libuv/src/project.json
When we moved to xproj, we stopped copying the native dll.
This change fixes the issue.
=> Add libuv.dll to the output folder when building libuv wrapper

src/System.Buffers/src/System.Buffers.xproj, src/System.Buffers/src/project.json
Renaming System.Buffers nuget package to System.Buffers.Experimental to avoid conflicts with the CoreFX version
This does not update any dependency packages yet; that must be done after this has been merged and a NuGet package uploaded 
@KrzysztofCwalina
=> Renaming System.Buffers nuget package to System.Buffers.Experimental

src/System.Net.Libuv/src/project.json
@KrzysztofCwalina  This is the only instance in CoreFxLab of someone using the Native Slice Pool
=> Moving LibUV code over to use the new Lab's Buffers package

src/System.Text.Json/src/project.json
For some reason CI built passed but one of the dependencies was missing.
Fixing it now.
=> Fixing JSON project build break

NuGet.Config, dir.props, src/System.Buffers/src/System/Buffers/NativeBufferBucket.cs, src/System.Buffers/src/System/Buffers/NativeBufferPool.cs, src/System.Buffers/tests/project.json, src/System.Collections.Generic.MultiValueDictionary/tests/project.json, src/System.CommandLine/tests/project.json, src/System.Drawing.Graphics/src/project.json, src/System.Drawing.Graphics/tests/project.json, src/System.IO.FileSystem.Watcher.Polling/tests/project.json, src/System.Net.Libuv/tests/project.json, src/System.Numerics.Matrices/test/project.json, src/System.Reflection.Metadata.Cil/src/project.json, src/System.Reflection.Metadata.Cil/tests/project.json, src/System.Slices/tests/project.json, src/System.Text.Formatting.Globalization/tests/project.json, src/System.Text.Formatting/tests/project.json, src/System.Text.Http/tests/project.json, src/System.Text.Json/tests/project.json, src/System.Text.Utf8/tests/project.json, src/System.Threading.Tasks.Channels/tests/project.json, src/System.Time/tests/project.json
Making the test projects build and work with dotnet test. I am not adding them back to the build just yet, but a developer can simply run dotnet test from a test folder and the tests are going to be executed. Everything that depends on System.Slices is failing right now, which is why the tests haven't been re-enabled.
=> Making the tests build and work with dotnet test command

src/System.Slices/src/System/PtrUtils.cs, src/System.Slices/src/System/ReadOnlySpan.cs, src/System.Slices/src/System/Span.cs, src/System.Slices/src/System/SpanExtensions.cs
Fixes [Span indexer computes the element offset using Int32 which can overflow](https://github.com/dotnet/corefxlab/issues/516)
*I created this PR instead of [another one](https://github.com/dotnet/corefxlab/pull/528) which I closed because had messed up its commits.*
=> Slices: Fix overflow in PtrUtils.Get/Set

src/System.Text.Formatting/src/System/Text/Formatting/BufferFormatter.cs, src/System.Text.Formatting/src/System/Text/Formatting/StringFormatter.cs, src/System.Text.Formatting/tests/CompositeFormattingTests.cs
Fixes #599
The test got broken when we ported from BufferPool.Resize to Rent/Return.
=> Enabling back DateTime formatting test

dotnet.targets, src/System.Buffers.Experimental/System.Buffers.xproj, src/System.Net.Libuv/copy_libuv.cmd, src/System.Net.Libuv/project.json
Updating dotnet pack to use -b instead of -t. Also fixed buffer project which had the dotnet commands directly in it and fixing the post compile script for libuv, now that we don't support native commands directly in the scripts
=> Updating dotnet pack to use -b instead of -t.

dotnet.targets
We had a regression on dotnet pack where -o and -b together cause pack to not compile the project. Removed the -b option for now to have the project build.
CLI issue: https://github.com/dotnet/cli/issues/1525
=> Update dotnet pack command to not use -b option

src/System.Threading.Tasks.Channels/System/Collections/Concurrent/SingleProducerConsumerQueue.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.AsyncEnumerator.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.BoundedChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.CaseBuilder.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.EnumerableChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.Observable.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.ReaderWriter.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.SerializationChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.SimpleQueue.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.SpscUnboundedChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.TaskChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.UnboundedChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.UnbufferedChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/IDebugEnumerator.cs, tests/System.Threading.Tasks.Channels.Tests/ChannelTests.cs, tests/System.Threading.Tasks.Channels.Tests/SingleProducerSingleConsumerTests.cs, tests/System.Threading.Tasks.Channels.Tests/TestBase.cs
- Use nameof throughout
- Use expression-bodied members in a few places
- Change a few names
- Make SingleProducerSingleConsumerQueue public
=> A few code cleanups on Channels

src/System.CommandLine/System/CommandLine/ArgumentSyntax.cs, src/System.CommandLine/project.json
After printing the help screen System.CommandLine was calling fastfail which tears down the process with an exception.  This caused a popup and looked like an exceptional exit.  Switched the code to use Environment.Exit(), which is now available.  At the same time I also include the code to call Environment.GetCommandLineArgs() to allow the help code to find the app name.
=> Update exit from help output and app name

src/System.Text.Utf8/System/Text/Utf16/Utf16LittleEndianEncoder.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8EncodedCodePoint.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8Encoder.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8String.CodePointEnumerable.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8String.CodePointEnumerator.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8String.CodePointReverseEnumerator.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8String.Enumerator.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8String.cs
Utf8String was created before we had ReadOnlySpan<T> and so it was using Span<T>.
This change moves the implementation to use ReadOnlySpan, as Utf8String is read-only.
=> Moved Utf8String to ReadOnlySpan

src/System.Slices/System/Span.cs, tests/System.Slices.Tests/BasicUnitTests.cs
Once all consuming APIs in the framework support Spans, we won't need this method.
But during prototyping and transition, we need this method to avoid reimplementing the
whole .NET stack.
=> Added an unsafe method to access the array wrapped by Span<T>

src/System.Buffers.Experimental/System/Buffers/Multispan.cs, src/System.Buffers.Experimental/project.json
Multispan.CopyTo should take a T[], not byte[]
=> Fixing #644

src/System.Slices/System/SpanExtensions.cs, tests/System.Slices.Tests/IndexOfTests.cs
It is an implementation of IndexOf method with range check eliminated.
For Span of chars it serves as ordinal IndexOf.
```C#
public static int TestSpanIndexOf(Span<long> span, longvalue)
{
return span.IndexOf(value);
}
```
The generated code for different element types.
**long**:
```ASM
; Assembly listing for method System.SpanExtensions:IndexOf(struct,long):int
; Lcl frame size = 0
8B4110               mov      eax, dword ptr [rcx+16]
4C63C0               movsxd   r8d, eax
4D85C0               test     r8, r8
741C                 je       SHORT G_M9848_IG06
4C8B09               mov      r9, gword ptr [rcx]
488B4108             mov      rax, qword ptr [rcx+8]
4C03C8               add      r9, rax
33C0                 xor      rax, rax …
```
=> Slices: Implement IndexOf for Span<T>

src/System.CommandLine/System/CommandLine/Argument.cs, src/System.CommandLine/System/CommandLine/ArgumentParser.cs, src/System.CommandLine/System/CommandLine/ArgumentSyntax.cs, src/System.CommandLine/System/CommandLine/Enumerable.cs, src/System.CommandLine/System/CommandLine/HelpTextGenerator.cs
Generic virtual methods are pretty expensive for native compilation
scenarios (such as .NET Native). System.CommandLine should be a low
level component and not depend on expensive features so that it can be
used for small command line apps.
Generic virtual methods were used indirectly through LINQ Where and
Select operators.
=> Make System.CommandLine not depend on generic virtual methods

.gitignore, build.cmd, package.cmd, src/System.Slices/re_write_il.cmd
Instead of forcing VsDevCmd.bat to be called up-front in the build scripts, I've made it part of re_write_il.cmd, which is where is is actually required. This means you can build the project regardless of your environment and the postcompile script will automatically correct it before running the tools. This also fixes things like VS (full) and VS Code. Right now you can't build System.Slices successfully in them unless you explicitly start them from a VS dev command prompt (undesirable).
I've also ignored the .vscode folder, it auto-generates some things that I'm not sure we want to check in yet.
=> Simplify scripts

src/System.Text.Utf8/System/Text/Utf8/Utf8String.cs
Now that we have ReadOnlySpan<T>, there is no reason to expose the bytes,
and it allows to avoid copies in many scenarios.
=> Added Bytes property to Utf8String

scripts/install-dotnet.ps1, src/System.Drawing.Graphics/project.json, src/System.Slices/project.json, src/System.Text.Formatting/project.json, src/System.Text.Json/project.json, tests/System.Binary.Tests/project.json, tests/System.Buffers.Experimental.Tests/project.json, tests/System.Collections.Generic.MultiValueDictionary.Tests/project.json, tests/System.CommandLine.Tests/project.json, tests/System.IO.FileSystem.Watcher.Polling.Tests/project.json, tests/System.Net.Libuv.Tests/project.json, tests/System.Numerics.Matrices.Tests/project.json, tests/System.Reflection.Metadata.Cil.Tests/project.json, tests/System.Slices.Tests/project.json, tests/System.Text.Formatting.Globalization.Tests/project.json, tests/System.Text.Formatting.Tests/project.json, tests/System.Text.Http.Tests/project.json, tests/System.Text.Json.Tests/project.json, tests/System.Text.Utf8.Tests/project.json, tests/System.Threading.Tasks.Channels.Tests/project.json, tests/System.Time.Tests/project.json
This updates everything to use the released version of RC2, including the version of the SDK that the CI uses.
There appears to be something I don't understand with regards to how the "compile" item in project.json works. Apparently I need to explicitly exclude stuff even if it doesn't match the "include" globbing pattern.
=> Update to released RC2 packages

src/System.Slices/System/Contract.cs, src/System.Slices/System/PtrUtils.cs, src/System.Slices/System/SpanExtensions.cs, tests/System.Slices.Tests/CastTests.cs, tests/System.Slices.Tests/Tests.cs
When T  <= U we don't pay the cost:
```C#
public static void TestSpanCast(Span<byte> span)
{
var l = span.Cast<byte, long>();
}
```
```ASM
; Assembly listing for method CoreClrTest.Program:TestSpanCast(struct)
; Lcl frame size = 56
57                   push     rdi
56                   push     rsi
4883EC38             sub      rsp, 56
488BF1               mov      rsi, rcx
488D7C2420           lea      rdi, [rsp+20H]
B906000000           mov      ecx, 6
33C0                 xor      rax, rax
F3AB                 rep stosd 
488BCE               mov      rcx, rsi
4C8B01               mov      r8, gword ptr [rcx]
4C8B4908             mov      r9, qword ptr [rcx+8]
8B4110               mov      eax, dword ptr [rcx+16]
99                   cdq …
```
=> Slices: Fix overflow in Cast<T,U>() which happens when  T is larger than U

src/System.Slices/System/MemoryUtils.cs, src/System.Slices/System/SpanEqualsExtensions.cs, src/System.Slices/System/SpanExtensions.cs, src/System.Slices/System/SpanExtensionsTemplate.tt
It is similar to IndexOf impl. The same benefits - shorter code, tighter loop.
Assembly for the long and char instantiations.
```ASM
; Assembly listing for method System.SpanExtensions:SequenceEqual(struct,struct):bool
; Lcl frame size = 0
8B4110               mov      eax, dword ptr [rcx+16]
3B4210               cmp      eax, dword ptr [rdx+16]
7539                 jne      SHORT G_M39316_IG06
8B4110               mov      eax, dword ptr [rcx+16]
4863C0               movsxd   eax, eax
4885C0               test     rax, rax
7428                 je       SHORT G_M39316_IG04
4C8B01               mov      r8, gword ptr [rcx]
488B4908             mov      rcx, qword ptr [rcx+8]
4C03C1               add      r8, rcx
488B0A               mov      rcx, gword ptr [rdx]
488B5208             mov …
```
=> Slices: Faster SequenceEqual<T> implemented in IL

src/System.Slices/System/Contract.cs, src/System.Slices/System/ReadOnlySpan.cs, src/System.Slices/System/Span.cs
Often, I am finding that it's more convenient to use uints for buffers, but then slice methods require cast. These overloads solve the problem.
The casts (from uint to int) are safe because the contract checks above them.
=> Added Slice overloads taking UInt32

src/System.Slices/System/Span.cs, tests/System.Slices.Tests/BasicUnitTests.cs
Fixes https://github.com/dotnet/corefxlab/issues/614
Luckily the check added is a noop for value types.
=> Slices: Don't allow covariant Spans

tests/System.Text.Json.Tests/PerfSmokeTests.cs
Some of the JSON tests have not been very reliable. This small change improves the reliability.
Having said that, maybe we should just remove the memory consumption check (if we still see the failure) and wait for proper harness/CLR-feature to measure memory consumption.
=> Improve reliability of memory consumption test

src/System.Slices/System/ReadOnlySpan.cs, src/System.Slices/System/Span.cs, src/System.Slices/System/SpanExtensions.cs
I microbechmarked the following scenarios.
_The numbers is old vs new in million times per sec._
```C#
TestSpanCtor(array);          // 58 - 77
TestSpanCtor(array, 0, 0);    // 52 - 64
TestArraySlice(array);        // 37 - 67
TestArraySlice(array, 0);     // 37 - 67
TestArraySlice(array, 0, 0);  // 37 - 65
TestStringSlice(str);         // 58 - 68
TestStringSlice(str, 0);      // 57 - 67
TestStringSlice(str, 0, 0);   // 56 - 63
```
```C#
public static void TestSpanCtor(byte[] array)
{
var span = new Span<byte>(array);
ConsumeSlice(span);
}
public static void ConsumeSlice(Span<byte> span)
{
}
```
=> Slices: Inline ctors

src/System.CommandLine/project.json
Would like to use System.CommandLine from .NET 4.5. No code changes, just cross-compile.
=> Add net45 target for System.CommandLine

src/System.Text.Formatting/System/Text/Parsing/InvariantParser_ulong.cs
Overloaded UTF-8 ulong parser method to support byte arrays rather than the (currently unsafe) Utf8String class.
=> UTF-8 ulong parser method now supports byte arrays

NuGet.Config, src/System.Slices/System/PtrUtils.cs, src/System.Slices/System/ReadOnlySpan.cs, src/System.Slices/System/Span.cs, tests/System.Slices.Tests/UsageScenarioTests.cs
@raymcc, for span of bytes, the copy operations will now use cpblk, i.e. 
var source = new ReadOnlySpan<byte>(nativePointer);
var destination = new Span<byte>(managedArray);
source.TryCopyTo(destination);
=> Changed Span<byte> copy routines to use cpblk

demos/LowAllocationWebServer/SampleServer.cs, src/System.Slices/System/Span.cs, src/System.Text.Formatting/System/Text/Formatting/IFormatterExtensions.cs, src/System.Text.Formatting/System/Text/Formatting/PrimitiveFormatters.cs, src/System.Text.Formatting/System/Text/Formatting/SpanFormatter.cs, src/System.Text.Http/System/Text/Http/IFormatterHttpExtensions.cs, tests/System.Text.Formatting.Tests/PrimitiveFormattingTests.cs, tests/System.Text.Http.Tests/GivenIFormatterExtensionsForHttp.cs
I cleaned up some APIs and removed others
The APIs I removed were misleading and need to be redesigned:
1. WriteHeader APIs were forcing all values to be strings. Which means integer values were forcing unnecessary allocations
2. The reservation feature was not working properly if the response buffer got resized later.
The header value reservation buffer would still point to the old response buffer.
I will redesign and add the removed APIs in the future.
=> Cleaned up HTTP formatter

src/System.Slices/System/SpanExtensions.cs
@KrzysztofCwalina
It makes code 8 bytes smaller and better.
With the change `Read<int>()`  60% faster in microbenchmarks. 
And now it is 12 times faster than `BitConverter.ToInt32` when reading from the same memory location and 2 times when going through a 8 MB array (memory access dominates in this case).
```C#
public static long TestSpanRead(Span<byte> span)
{
return span.Read<long>();
}
```
**Before**
```ASM
4883EC28             sub      rsp, 40
488B01               mov      rax, gword ptr [rcx]
488B5108             mov      rdx, qword ptr [rcx+8]
8B4910               mov      ecx, dword ptr [rcx+16]
83F908               cmp      ecx, 8
0F9DC1               setge    cl
0FB6C9               movzx    rcx, cl
85C9                 test     ecx, …
```
=> Slices: Use RequiresInInclusiveRange in SpanExtension::Read and Write methods

demos/LowAllocationWebServer/Framework/HttpServer.cs, demos/LowAllocationWebServer/Framework/SharedData.cs, demos/LowAllocationWebServer/LowAllocationServer.csproj, demos/LowAllocationWebServer/SampleServer.cs
This change allows to write response body first and then write headers. Very useful to be able to write the content length header.
After this commit, the low allocating server is very close to zero allocations for simple JSON post and JSON response.
I don't really like the SharedData APIs/abstraction. I do like the concept. I will think about fixing the abstraction in a subsequent PR.
=> Redesigned how response buffers are being formatted

src/System.Text.Primitives/System/Text/InvariantParser_int.cs, src/System.Text.Primitives/System/Text/InvariantParser_long.cs, src/System.Text.Primitives/System/Text/InvariantParser_sbyte.cs, src/System.Text.Primitives/System/Text/InvariantParser_short.cs
This is just a small fix&emdash;if a signed integer is explicitly positive (i.e. +46) we should still be able to parse it.
=> Added parsing support for explicitly positive signed integers.

src/System.Slices/System/MemoryUtils.cs, src/System.Slices/System/PtrUtils.cs, src/System.Slices/System/ReadOnlySpan.cs, src/System.Slices/System/Span.cs
Fixes #699
`cpblk` can work with managed pointers. This PR exploits that.
[The generated code ](https://gist.github.com/omariom/543db8c8502ca42492e057e02460d685)for Spans of `byte`, ` char`, `DateTime` and `string`.
For the predefined list of primitives it uses `cpblk`, for types not in the list and ref types it loops. The decision is made at JIT time.
@KrzysztofCwalina @adamsitnik
=> Slices: Made copying methods use cpblk without pinning

src/System.Slices/System/ReadOnlySpan.cs
It breaks the immutability guarantees. 
Otherwise methods will still have to defensive copy the array rather than return a static array wrapped in a ReadOnlySpan for fixed items like lookup tables etc as they could be changed by slicing.
Resolves  #735
@jkotas @KrzysztofCwalina
=> Don't Slice ReadOnlySpan to Span

src/System.Text.Primitives/System/Text/InvariantParser_byte.cs, src/System.Text.Primitives/System/Text/InvariantParser_int.cs, src/System.Text.Primitives/System/Text/InvariantParser_long.cs, src/System.Text.Primitives/System/Text/InvariantParser_sbyte.cs, src/System.Text.Primitives/System/Text/InvariantParser_short.cs, src/System.Text.Primitives/System/Text/InvariantParser_uint.cs, src/System.Text.Primitives/System/Text/InvariantParser_ulong.cs, src/System.Text.Primitives/System/Text/InvariantParser_ushort.cs, tests/System.Text.Primitives.Tests/ParserTests.cs, tests/System.Text.Primitives.Tests/Properties/AssemblyInfo.cs, tests/System.Text.Primitives.Tests/System.Text.Primitives.Tests.xproj, tests/System.Text.Primitives.Tests/project.json
Primitive parsing APIs will now return false if overflow occurs (per #443). Also added tests for these cases, which should neatly fulfill #704 for now.
=> Added support for handling integer overflow

tests/System.Text.Primitives.Tests/README.md
Quick fix: earlier version of the README omitted a necessary msbuild command to populate the test repo. This version includes that command.
=> Updated readme to include msbuild info.

src/System.Text.Primitives/System/Text/InvariantParser_byte.cs, src/System.Text.Primitives/System/Text/InvariantParser_int.cs, src/System.Text.Primitives/System/Text/InvariantParser_long.cs, src/System.Text.Primitives/System/Text/InvariantParser_sbyte.cs, src/System.Text.Primitives/System/Text/InvariantParser_short.cs, src/System.Text.Primitives/System/Text/InvariantParser_uint.cs, src/System.Text.Primitives/System/Text/InvariantParser_ulong.cs, src/System.Text.Primitives/System/Text/InvariantParser_ushort.cs
Preconditions raise exceptions when they are invalid. Since we want to avoid exceptions in our code (as it's a TryParse method), I have replaced these with simple if statements that return false if error conditions are met.
=> Removed potential exception throwing preconditions.

src/System.Text.Primitives/System/Text/InvariantParser_byte.cs, src/System.Text.Primitives/System/Text/InvariantParser_double.cs, src/System.Text.Primitives/System/Text/InvariantParser_float.cs, src/System.Text.Primitives/System/Text/InvariantParser_int.cs, src/System.Text.Primitives/System/Text/InvariantParser_long.cs, src/System.Text.Primitives/System/Text/InvariantParser_sbyte.cs, src/System.Text.Primitives/System/Text/InvariantParser_short.cs, src/System.Text.Primitives/System/Text/InvariantParser_ushort.cs
Just a quick fix. Noticed this while implementing the temporary methods.
=> Added MIT license notice to InvariantParser source files that were missing it

src/System.Text.Primitives/System/Text/InvariantParser_bool.cs, tests/System.Text.Primitives.Tests/ParserTests.cs, tests/System.Text.Primitives.Tests/PrimitivesPerfTests.cs
Added boolean support to the InvariantParser. These methods are _not_ prototype methods; I started implementing the prototypes when I realized that booleans were simple enough that I could quickly and easily implement the parsers fully.
I also added unit & perf tests for these methods. Here is a graph of perf gains.
=> Added boolean support to InvariantParser.

tests/System.Text.Primitives.Tests/PrimitivesPerfTests.cs
This was the bug that made it appear that long parsing was significantly worse for ByteStarUnmanaged than for ByteStar or ByteArray.
Before:
After:
Still some investigation necessary (the first three tests have weird baseline values).
=> Fixed bug in InvariantParser_long perf tests.

src/System.Text.Primitives/System/Text/FormattingData.cs, src/System.Text.Primitives/System/Text/InvariantParser_signed.cs, src/System.Text.Primitives/System/Text/InvariantParser_signed.tt, src/System.Text.Primitives/System/Text/InvariantParser_unsigned.cs, src/System.Text.Primitives/System/Text/InvariantParser_unsigned.tt, src/System.Text.Primitives/project.json, tests/System.Text.Primitives.Tests/ParserTests.cs, tests/System.Text.Primitives.Tests/ParserTests.tt, tests/System.Text.Primitives.Tests/PrimitivesPerfTests.cs
This is a big PR, so apologies in advance.
Overview:
* Added a new data structure to `FormattingData`: a parsing [trie](https://en.wikipedia.org/wiki/Trie) (or prefix tree). This structure serves as the inverse of the formatting map that is provided to `FormattingData`.
* As of this commit, this structure is allocated when the `FormattingData` object is created, which means that there is an expensive upfront cost. However, since the trie is navigated using binary search, lookup is extremely cheap, which means we trade off that upfront cost for very performant parsing.
* This means it is optimized for the webserver scenario (initialize my encoding, then parse a bunch of requests)
* However, there are obviously other scenarios that would benefit from slower parsing in favor of not having …
=> Modified the FormattingData class to allow for parsing. Full support for cultural specific parsing.

src/System.Text.Formatting/System/Text/Formatting/BufferFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/IFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/MultispanFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/SpanFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/StreamFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/StringFormatter.cs
@davidfowl, this adds the resize hint. Having said that, I am not sure it's useful. The callers are usually primitive formatters that don't know how large of a buffer the program needs. They only know how much they need for the small number of bytes they write.
=> Added resize hint to IFormatter

src/System.Binary.Base64/System.Binary.Base64.xproj, src/System.Binary.Base64/System/Binary/Base64.cs, src/System.Binary.Base64/project.json, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Binary.Base64.Tests/System.Binary.Base64.tests.xproj, tests/System.Binary.Base64.Tests/project.json
This is not the fastest implementation I can imagine, but at least it's non-allocating, i.e. operated passed in byte buffers.
=> Added non-allocating Base64 encoder/decoder

src/System.Binary.Base64/System/Binary/Base64.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs
cc @davidfowl 
Base64 decoder is shrinking data size when decoding. This makes it possible to easily decode in-place.
Encoding expands the size, and so it will be harder, slower, and will require some creative APIs.
=> Support Decoding Base64 buffers in-place

src/System.Slices/System/ReadOnlySpan.cs, src/System.Slices/System/Span.cs, tests/System.Slices.Tests/EqualityTests.cs, tests/System.Slices.Tests/UsageScenarioTests.cs
Extending the `Span`->`ReadOnlySpan` implicit conversion theme. 
This would allow new apis to only need a single method which would convey intent rather than also requiring array overloads which are ambiguous in intention as the method name is generally reversed in action with the parameter.
e.g. `Stream.Write(ReadOnlySpan<byte> array)` and `Stream.Read(Span<byte> array)`
```csharp
SpanAwareStream s;
byte[] a = new byte[255];
s.Write(a); // conversion to ReadOnlySpan
s.Read(a); // conversion to Span
```
Resolves #734
@KrzysztofCwalina @jkotas @jaredpar
=> Implicit conversion to Span from Array

src/System.CommandLine/System/CommandLine/ArgumentLexer.cs
`ExpandReponseFiles` should be `ExpandResponseFiles` instead.
=> Fix typo in ArgumentLexer function name

src/System.Slices/System/Contract.cs
Throw the exceptions directly from the void method, don't mark as no-inlining
Post https://github.com/dotnet/coreclr/pull/6103 "Do not inline methods that never return" this will give the best result. (As shown in https://github.com/dotnet/coreclr/pull/6634)
It won't inline the exception Throw function, will mark the call to the Throw function as cold code, and won't preform any register prep for the function (push+pop)
=> Improved Exception handling

src/System.Buffers.Experimental/System/Buffers/NativeBufferPool.cs, src/System.Net.Libuv/System/Net/Libuv/Buffer.cs, src/System.Net.Libuv/System/Net/Libuv/Stream.cs, src/System.Slices/System/ReadOnlySpan.cs, src/System.Slices/System/Span.cs, tests/System.Slices.Tests/BasicUnitTests.cs
Added TryGetArrayElseGetBuffer.
The existing APis need to be used together to make the interop safe.
The new API makes it more in the face.
This is how the API should be used:
```csharp
void Interop(Span<Byte> s){
void* p;
ArraySegment<byte> a;
if(s.TryGetArrayOrGetPointer(out a, out p)){
fixed(byte* pB = a.Array){
var pOffset = pB + a.Offset;
DoInterop(pOffset. s.Length);
}
}
else {
DoInterop((byte*)p, s.Length);
}
}
```
This API might be removed altogether when we add proper pinning to spans.
=> Obsoleted UnsafeBuffer and TryGetArray

src/System.Slices/System/ReadOnlySpan.cs, src/System.Slices/System/Span.cs
There are some scenarios that are not covered by the new APIs. 
For example, if the span wraps an array, but the calling code knows the array is already pinned and wants to get the pointer.
=> removed obsolete attributes

src/System.Buffers.Experimental/System/Buffers/ISequence.cs, src/System.Buffers.Experimental/System/Buffers/Multispan.cs, src/System.Buffers.Experimental/System/Buffers/MultispanExtensions.cs, src/System.Buffers.Experimental/project.json, tests/System.Buffers.Experimental.Tests/MultispanUnitTests.cs, tests/System.Reflection.Metadata.Cil.Tests/System.Reflection.Metadata.Cil.Tests.xproj
Added an abstraction that can support various implementations of containers of spans
Added a method that illustrates how to parse UInt32 out of a milti-span
The multispan abstraction (ISequence<T>) allows array based and linked implementations of sequences.
A linked-list like container, would implement the interface as follows:
public T TryGetItem(ref Position position)
{
if (_head != null && position.IsValid && !position.IsEnd)
{
var node = (Node)position.ObjectPosition;
if(node==null) { node = _head; }
var result = node._item;
if (node._next != null)
{
position.ObjectPosition = node._next;
}
else
{
position = Position.End;
}
return result;
}
position = Position.Invalid;
return default(T);
}
=> Expanding support for "multispans"

src/System.Text.Formatting/System/Text/Formatting/IFormatterExtensions.cs
These can be used to implement fully async formatting:
```csharp
public static async Task WriteAsync<TStream>(this TStream stream, T value) where TStream : IStream, IFormatter {
while (true) {
if (stream.TryAppend(value)) { // non-blocking formatter method
await Task.CompletedTask;
break;
}
await stream.FetchMoreBufferSpace(); // method on hypothetical IStream
}
}
```
=> Added non-blocking formatters

README.md
This PR fixes the formatting of generics types in the `MultiValueDictionary` section of the README files since they were being interpreted as HTML. I made all the types in the section inline code blocks for consistency.
=> Fix formatting of generic types in README.md

samples/LowAllocationWebServer/Framework/SharedData.cs, src/System.Slices/System/Buffers/IOutput.cs, src/System.Text.Formatting/System/Text/Formatting/BufferFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/CompositeFormat.cs, src/System.Text.Formatting/System/Text/Formatting/IFormatterExtensions.cs, src/System.Text.Formatting/System/Text/Formatting/ITextOutput.cs, src/System.Text.Formatting/System/Text/Formatting/MultispanFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/SpanFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/StreamFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/StringFormatter.cs, src/System.Text.Http/System/Text/Http/IFormatterHttpExtensions.cs, src/System.Text.Json/System/Text/Json/JsonWriter.cs
I split IFormatter into IOutput and ITextOutput.
IOutput represents a general output stream. ITextOutput represents an output stream of text.
I tried to completely get rid of ITextOutput, but then ran into a significant problem: the "formatters", e.g. StringFormatter, ResponseFormatter were not in control of the encoding. The code calling Append could write partial UTF8 and partial UTF16 to lets say response buffers, and the code managing the buffers would not be able to prevent it. 
Also, I tried to rename Enlarge to Ensure. The problem is that Ensure does not make much sense with the default parameter, yet the default parameter is very useful as the calling code often does not know how much space it needs (it just knows it needs more).
=> Refactored IFormatter based on discussions with the channels team

src/System.Slices/System/Contract.cs, src/System.Slices/System/ReadOnlySpan.cs, src/System.Slices/System/ReadOnlySpanEnumerators.cs, src/System.Slices/System/Span.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8String.Enumerator.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8String.cs, tests/System.Slices.Tests/EqualityTests.cs, tests/System.Slices.Tests/UsageScenarioTests.cs, tests/System.Text.Http.Tests/GivenAnHttpHeaders.cs
@KrzysztofCwalina I have removed it also from Utf8String since it's based on Span as well
=> remove all generic interfaces that put Span<T> in generic arg

src/System.Slices/System/Buffers/Memory.cs, tests/System.Slices.Tests/BasicUnitTests.cs
- Turns out it didn't work after I added the null check
- Added tests
Found this when using it on Channels
=> Fix Memory<T>.Empty

src/System.Buffers.Experimental/System/Buffers/MultispanExtensions.cs, src/System.Slices/System/DebuggerViews.cs, src/System.Slices/System/ReadOnlySpan.cs, src/System.Slices/System/Span.cs, src/System.Slices/System/SpanExtensions.cs, src/System.Text.Formatting/System/Text/Formatting/SequenceFormatter.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8String.cs, tests/System.Slices.Tests/BasicUnitTests.cs, tests/System.Slices.Tests/EqualityTests.cs, tests/System.Slices.Tests/UsageScenarioTests.cs
For consistency with many existing Fx APIs, I renamed:
- TryCopyTo to CopyTo
- CreateArray to ToArray
=> Renamed CreateArray and TryCopyTo

src/System.Text.Utf8/System/Text/UnicodeCodePoint.cs, src/System.Text.Utf8/System/Text/Utf16/Utf16LittleEndianEncoder.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8String.cs, tests/System.Text.Utf8.Tests/Bugs.cs
The existing code was checking if a code point is a surrogate characters, but it should be checking for whether the code point needs a surrogate characters.
Also the encoder was incorrectly computing the high surrogate value.
=> Fixed #869

.gitignore, src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Collections/ReadOnlySpanSequence.cs, src/System.Slices/System/Collections/SpanSequence.cs, src/System.Slices/System/Collections/SpanSequenceExtensions.cs, src/System.Slices/System/Contract.cs, src/System.Slices/System/ReadOnlySpan.cs, src/System.Slices/System/Span.cs, src/System.Slices/System/SpanExtensions.cs, src/System.Slices/System/ThrowHelper.cs
**Issue**
**Fix**
Use Contracts add ThrowHelper, factor out exceptions from main code path
**Result**
Now only the exception throwing branches don't inline (correctly with `FAILED: does not return`)
Pre
```[FAILED: unprofitable inline] Memory`1:.ctor(ref,int,int,long):this```
Post
```[profitable inline] Memory`1:.ctor(ref,int,int,long):this```
Pre ```Memory`1:Slice(int,int):struct:this``` inlines
```asm
Successfully inlined Memory`1:Add(long,int):long (13 IL bytes) (depth 1) [below ALWAYS_INLINE size]
Successfully inlined Unsafe:SizeOf():int (7 IL bytes) (depth 2) [below ALWAYS_INLINE size]
Successfully inlined Memory`1:.ctor(long,int):this (45 IL bytes) (depth 1) [profitable inline]
Successfully inlined Memory`1:Add(long,int):long (13 IL bytes) (depth 1) [below ALWAYS_INLINE size] …
```
=> Make Memory more inlinable

src/System.Slices/System/Buffers/Memory2.cs, src/System.Slices/System/Buffers/MemoryManager.cs, src/System.Slices/System/Buffers/MemoryManagers.cs, src/System.Slices/project.json, tests/System.Slices.Tests/MemoryTests.cs
Memory2\<T\> is a tearing-safe[er] version of Memory\<T\>. 
It supports revocation, i.e. the underlying buffer (MemoryManager\<T\>) can be disposed, which will "poison" all existing copies of Memory2\<T\>. This makes it buffer and object pooling friendly as it is much harder for buggy code to get away with use-after-free bugs (such bugs will almost always result in ObjectDisposedExceptions).   
Also, it supports "reserving" the buffer, i.e. communicating to MemoryManager\<T\> that Memory2\<T\> instance will need the buffer for longer than the lifetime of the current stack frame. This is useful for example when the buffer will be used for an asynchronous call (e.g. async interop call).
The tests illustrate the concepts in detail.
Note that the APIs are not yet hardened for all the races I …
=> Adding a prototype of safe Memory<T>

src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Buffers/MemoryManagers.cs, src/System.Slices/System/Buffers/OwnedMemory.cs, src/System.Slices/System/Buffers/ReadOnlyMemory.cs, tests/System.Slices.Tests/MemoryTests.cs
The new APIs allow the following code:
```c#
{
OwnedArray<byte> memory = new byte[1024];
var span = memory.Span;
span[10] = 10;
Assert.Equal(10, memory.Array[10]);
}
using(var memory = new OwnedNativeMemory(1024)) {
var span = memory.Span;
span[10] = 10;
unsafe { Assert.Equal(10, memory.Pointer[10]); }
}
using (OwnedPinnedArray<byte> memory = new byte[1024]) {
var span = memory.Span;
span[10] = 10;
Assert.Equal(10, memory.Array[10]);
unsafe { Assert.Equal(10, memory.Pointer[10]); }
}
```
=> Added helper APIs to Memory<T>

src/System.Buffers.Experimental/System/Buffers/ManagedBufferPool.cs, src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Buffers/OwnedMemory.cs, src/System.Slices/System/Buffers/ReadOnlyMemory.cs, tests/System.Slices.Tests/MemoryTests.cs
I made TryGetArray methods unsafe to communicate to callers that they need to be careful,
e.g. they should call Reserve(), if they store the array for later
=> Cleaned up Memory<T> APIs

docs/Span.md
1. `Unsafe` → `unsafe`
2. memry → memory
3. missing full stop
=> Small fixes to Span.md

src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Buffers/OwnedMemory.cs, src/System.Slices/System/Buffers/ReadOnlyMemory.cs
I would like to experiment with an OwnedMemory<T> abstraction. This is so we could implement it on T[] and String, and so allow creating Memory<T>/Span<T> out of these without an allocation (for the owned memory wrapper). 
In the past, when we changed OwnedMemory<T>.GetSpan to a virtual method, we saw a significant perf regression in some scenarios. This experiment is using an interface, which because of stub dispatch, might make the performance hit acceptable.
cc: @davidfowl, @jaredpar
=> Preparing for an experiment with OwnedMemory<T>

src/System.Text.Primitives/System/Text/Parsing/InvariantUtf16/InvariantUtf16_UInt32.cs, src/System.Text.Primitives/System/Text/Parsing/InvariantUtf16/InvariantUtf16_bool.cs, src/System.Text.Primitives/System/Text/Parsing/InvariantUtf8/InvariantUtf8_UInt32.cs, src/System.Text.Primitives/System/Text/Parsing/InvariantUtf8/InvariantUtf8_bool.cs, src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_UInt32.cs, src/System.Text.Primitives/System/Text/Parsing/PrimitiveParser2_bool.cs, tests/System.Text.Primitives.Tests/PrimitiveParserBoolTests.cs, tests/System.Text.Primitives.Tests/PrimitiveParserUInt32Tests.cs
Introduce class PrimitiveParser2 with intent for it to replace PrimitiveParser. The class right now contains skeleton implementations of the overloads of TryParseBoolean and TryParseUInt32.
PrimitiveParser2.TryParseBoolean and PrimitiveParser2.TryParseUInt32 are the main overloads. The overloads in PrimitiveParser2.InvariantUtf8 and PrimitiveParser2.InvariantUtf16 are wrappers around the main overloads currently, but could provide performance improvements if separately implemented.
=> Start consolidation and rewriting of System.Text.PrimitiveParser

src/System.Buffers.Experimental/System/Buffers/ArraySegmentExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Multispans/Multispan.cs, src/System.Buffers.Experimental/System/Buffers/Multispans/ReadOnlySpanSequence.cs, src/System.Buffers.Experimental/System/Buffers/Multispans/SequenceExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Multispans/SpanSequence.cs, src/System.Buffers.Experimental/System/Buffers/Multispans/SpanSequenceExtensions.cs, src/System.Text.Formatting/System/Text/Formatting/SequenceFormatter.cs, src/System.Text.Utf8/System/Text/Utf8/Utf8CodeUnit.cs
We will use Memory<T> sequences to represent sequences of buffers. No need to have sequences of spans, which are very complex. 
I will remove these APIs soon (Monday the latest).
=> Obsoleting Multispans/SpanSequences

src/System.Text.Formatting/System/Text/Parsing/SequenceParser.cs
As a side note, this routine is a great illustration of the power of Span<T>. The fact that spans represent arbitrary memory (including stack memory) can be used to process (in this example parse) discontinuous buffers very efficiently and without heap allocations, even if the processed data straddles multiple buffers.
Without Span<T> either the processing code (PrimitiveParser.TryParseUInt32 in this example) needs to be written to handle discontinuous data, which would make such parser complicated and slow, or the routines calling the parser (like this routine) have to allocate contiguous buffer on the heap, or PrimitiveParser has to have unsafe overloads to parse stack allocated arrays.
cc: @davidfowl, @terrajobst, @joshfree
=> Optimized uint sequence parser to never allocate on the GC heap

src/System.Text.Formatting/System/Text/Formatting/OutputFormatter.cs
This type can be used to create ITextOutput out of IOutput.
For example, Channel's WritableBuffer implements IOutput, but not ITextOutput. This API allows to format to WritableBuffer despite the fact that formatters requre ITextOutput:
```c#
WritableBuffer output = ...
var textOutput = new OutputFormatter<WritableBuffer>(output);
textOutput.Append(0xff, 'X');
```
=> Added OutputFormatter

src/System.IO.Pipelines.Text.Primitives/ReadableBufferExtensions.cs, src/System.Text.Formatting/System/Text/Parsing/SequenceParser.cs, src/System.Text.Json.Dynamic/System/Text/Json/JsonDynamicObject.cs, src/System.Text.Json/System/Text/Json/JsonParseObject.cs, src/System.Text.Primitives/System/Text/ParsedFormat.cs
Removed all consumers (except tests) of the InternalParser
cc: @botaberg, @AtsushiKan, @joshfree
=> Ported corfxlab libraries to use the PrimitiveParser

src/System.IO.Pipelines/DefaultWritableBufferExtensions.cs
The Write method currently takes Span<byte> as a parameter.
It should take ReadOnlySpan<byte> as the method does not mutate the contents of the data it writes.
This will enable writing new Utf8String("Hello World!).Bytes, and no technology can succeed without supporting the Hello World. 
cc: @botaberg, @joshfree, @davidfowl, @AtsushiKan
=> Changed DefaultWritableBufferExtensions.Write to take ReadOnlySpan<byte>

README.md
Also changed absolute links to relative.
(The advantage of relative links is that they point to the version of the document for the current commit, even when that's not `master`.)
=> Fixed link to span.md

src/System.IO.Pipelines.Networking.Sockets/SocketListener.cs
When using a system assigned port for the SocketListener. The SocketListener class needs to expose the address of the socket so the caller can obtain the assigned port. I've added a property to expose the endpoint of the socket. If the socket is null, then the property will return a empty endpoint.
=> Expose LocalEndPoint property on SocketListener

docs/specs/memory.md
Some minor fixup:
* Remove trailing whitespace
* Add line breaks to make changes easier to review
* Fix headings
* Escape code
* Fix links
@KrzysztofCwalina 
skip CI please
=> Fix Memory<T> spec

src/System.Text.Primitives/System/Text/Parsing/InvariantUtf8/InvariantUtf8_UInt32.cs, tests/System.Text.Primitives.Tests/PrimitiveParserPerfComparisonTests.cs, tests/System.Text.Primitives.Tests/PrimitiveParserUInt32Tests.cs
Implement PrimitiveParser.InvariantUtf8.TryParseUInt32 span and Hex overloads, and add performance tests for these new implementations. Hex translation from ASCII/Utf8 byte to integer is done by indexing into a static readonly array; suggestions for improvement in this area or others are welcome.
Observations about performance so far:
- Hex parsing takes about the same time per character as parsing in base 10
- Parsing byte* seems to be slightly faster than ReadOnlySpan<byte>, but overall the two are very comparable
I don't have a gist with performance numbers this time around; my hope is that we can get some good analysis going soon.
=> Implement PrimitiveParser.InvariantUtf8.TryParseUInt32 span and Hex overloads

global.json
- After installing both VS 2017 RC and VS2015, you'll end up
with the preview3 and preview2 CLI. Pick a project.json compatible one
(the one that matches the build script)
=> Specify the SDK version in global.json

src/System.IO.Pipelines/IPipelineReader.cs, src/System.IO.Pipelines/PipelineReader.cs, src/System.IO.Pipelines/PipelineReaderWriter.cs, src/System.IO.Pipelines/ReadResult.cs, src/System.IO.Pipelines/UnownedBufferReader.cs, tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs, tests/System.IO.Pipelines.Tests/UnownedBufferReaderFacts.cs
- We need this to support things like graceful shutdown in kestrel
and to support yeilding the await in SignalR (for long polling)
- Unlike a 0 byte write, this is synchronized with the other state
in the PipelineReaderWriter and UnownedBufferReader so there are no
races/clashes
- Added IsCancelled to ReadResult so the caller can see what triggered
the await.
Fixes #1017
TODOs:
- Potentially look at the cancellation token approach as an extension method (less optimized by more idomatic)
- Maybe throw operation cancelled exception?
- Interpret 0 byte write as end of pipeline (more compatible with streams).
/cc @anurse @pakrym @halter73 @benaadams
=> Add support for cancelling the pending ReadAsync call

src/System.IO.Pipelines/IPipelineReader.cs, src/System.IO.Pipelines/PipelineReaderWriter.cs, src/System.IO.Pipelines/UnownedBufferReader.cs, tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs, tests/System.IO.Pipelines.Tests/UnownedBufferReaderFacts.cs
- If CancelPendingRead was called before calling Advance (like on a
background thread),the cancellation would never be observed by the following read.
This change introduces a tri-state that tracks if cancellation was observed by read
before resetting it.
- Added tests
=> This fixes the races with the previous cancellation support

src/System.Binary.Base64/project.json, src/System.Binary/project.json, src/System.Buffers.Experimental/project.json, src/System.Collections.Sequences/project.json, src/System.IO.Pipelines.Compression/project.json, src/System.IO.Pipelines.File/project.json, src/System.IO.Pipelines.Networking.Libuv/project.json, src/System.IO.Pipelines.Networking.Sockets/project.json, src/System.IO.Pipelines.Networking.Windows.RIO/project.json, src/System.IO.Pipelines.Text.Primitives/project.json, src/System.IO.Pipelines/project.json, src/System.Net.Libuv/project.json, src/System.Slices/project.json, src/System.Text.Formatting.Globalization/project.json, src/System.Text.Formatting/project.json, src/System.Text.Http/project.json, src/System.Text.Json.Dynamic/project.json, src/System.Text.Json/project.json, src/System.Text.Primitives/project.json, src/System.Threading.Tasks.Channels/project.json, tests/System.Net.Libuv.Tests/project.json, tests/System.Text.Json.Tests.Dynamic/project.json, tests/System.Text.Json.Tests/project.json, tests/System.Text.Primitives.Tests/project.json
- Turns out downgrades are bad and made it impossible to consume in the
current state outside of corefxlab.
- This PR also minimizes the individual references and uses the latest NetStandard.Library
package for core deps.
Fixes #1018
/cc @KrzysztofCwalina  (sorry bro 😄 )
=> Fix downgrades by updating to the latest corefx packages

src/System.Buffers.Experimental/project.json, src/System.IO.Pipelines.Compression/project.json, src/System.IO.Pipelines.File/project.json, src/System.IO.Pipelines.Networking.Libuv/project.json, src/System.IO.Pipelines.Networking.Sockets/project.json, src/System.IO.Pipelines.Networking.Windows.RIO/project.json, src/System.IO.Pipelines/project.json, src/System.Net.Libuv/project.json, src/System.Slices/project.json, src/System.Text.Encodings.Web.Utf8/project.json, src/System.Text.Json.Dynamic/project.json, src/System.Text.Primitives/project.json, tests/System.Net.Libuv.Tests/project.json, tests/System.Slices.Tests/project.json
- Now that System.Memory and Unsafe have been re-baselined
to stable dependencies, we can go back to using RTM bits for
corefx.
- Now we float for System.Memory and System.CompilerServices.Unsafe
/cc @KrzysztofCwalina 
I'm going go merge this when the CI passes. It'll unblock ASP.NET pulling new bits and will make @KrzysztofCwalina happy 😄
=> Go back to stable versions

src/System.Slices/System/Buffers/ReferenceCounter.cs, tests/System.Slices.Tests/ReferenceCounterTests.cs
ReferenceCounter is a small datastructure to store an manipulate reference counts
It stores counts on per thread basis, which allows us to manipulate the counts without synchronization.
When the count needs to be read, it does need to be tallied up from all the threads.
We compute the tally without synchronizing with the thread-local modifications, and so
there is a possibility of a race here. But, the race is much less likely to occur than today
when Span\<T\> is "checked-out" from Memory\<T\> without incrementing the OwnedMemory\<T\> refcount,
and so it's an improvement. Also, we think we can eliminate the impact of the race at higher level,
i.e. in OwnedMemory\<T\> (at some additional memory barrier cost).
But the performance wins are very large when compared to contended Interlocked …
=> Added ReferenceCounter

src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Buffers/ReadOnlyMemory.cs
cc @grahamehorner, @Tragetaschen, @ahsonkhan
This is addressing the issue described in #1044. I think we cannot return whole buffer from ToString, but I understand how the current behavior might be confusing, and so I added "..." when more items are in the memory than returned from ToString.
Also, note that ultimately we want to use debugger view proxies. Unfortunately they don't yet work with Spans and Memory. I filed a bug and the VS debugger team promised to fix it before the next VS ships.
=> fixes #1044

tests/Benchmarks/E2EPipelineNoIO.cs, tests/Benchmarks/project.json
These are the results I got 
Test Name	Metric	Iterations	Average	stdev	Minimum	Maximum
E2EPipelineTests.TechEmpowerHelloWorldNoIO(numberOfRequests: 1000, concurrentConnections: 1024)	Duration	4	3876.773707	148.4557393	3782.389745	4097.927995
E2EPipelineTests.TechEmpowerHelloWorldNoIO(numberOfRequests: 1000, concurrentConnections: 4096)	Duration	2	15696.70992	176.1692083	15572.13948	15821.28037
E2EPipelineTests.TechEmpowerHelloWorldNoIO(numberOfRequests: 1000, concurrentConnections: 256)	Duration	12	926.6457971	10.91291388	905.5670618	940.7760337
E2EPipelineTests.TechEmpowerJsonNoIO(numberOfRequests: 1000, concurrentConnections: 1024)	Duration	4	4208.268144	22.49119549	4179.787803	4231.541506
E2EPipelineTests.TechEmpowerJsonNoIO(numberOfRequests: 1000, concurrentConnections: 256)	Duration …
=> Added JSON writing to the E2E benchmark

src/System.Text.Primitives/System/Text/Formatting/PrimitiveFormatter_time.cs, tests/System.Text.Formatting.Tests/PrimitiveFormattingTests-Time.cs
This format is used for HTTP response formatting,
and it's been showing in profiles of our E2EPipelineTests.TechEmpowerHelloWorldNoIO benchmark.
After this change, the benchmark went down (elapsed time) from 3876 to 3682.
cc: @davidfowl, @joshfree, @ahsonkhan, @botaberg
=> Oprimized DateTime format 'R' formatting

src/System.Slices/System/Buffers/ReferenceCounter.cs, tests/System.Slices.Tests/ReferenceCounterTests.cs
Rather than storing the count, we use an entry per reference. This
means it is very quick to add a reference, we simple put the object
in the next slot of the array.
Releasing a reference, is a little harder, we scan the array looking
for the entry, once we find it we can collapse the list into a
condensed form, by moving the first element into the gap, and nudging
the first up.
The API has changed to only return a bool for whether a reference
exists or not. We don't care how many references there are. This means
we can short cut several searchs as soon as we find something.
=> Unary ObjectTable for RefCounter

samples/LowAllocationWebServer/Framework/SharedData.cs, src/System.Collections.Sequences/System/Collections/Sequences/ISequence.cs, src/System.Collections.Sequences/System/Collections/Sequences/Position.cs, src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs, src/System.Collections.Sequences/System/Collections/Sequences/SequenceEnumerator.cs, src/System.IO.Pipelines/ReadableBuffer.cs, tests/System.Collections.Sequences.Tests/BasicUnitTests.cs, tests/System.Collections.Sequences.Tests/SampleCollections/Hashtable.cs, tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs, tests/System.Slices.Tests/MemoryTests.cs
I am trying to use ISequence for more multi-segment scenarios and I am finding it too hard to implement.
Once of the reasons is that ISequence was supporting easy foreach style enumeration.
But foreach is not a mainline scenario for ISequence, so I made the support for it optional.
cc: @davidfowl, @joshfree, @shiftylogic, @terrajobst
=> Simplified ISequence<T>

tests/System.Slices.Tests/ReferenceCounterTests.cs
I believe this fixes an intermittent fault on ResizingThreadTableWorks.
The race could be observed by inserting a Thread.Sleep(10) as the first
command of the thread body, then the test fails consistently.
The WaitHandles are now made in sequential code, so there is no race on
adding to the threads list, with other additions, or the wait at the
end of the test.
@KrzysztofCwalina @joshfree does this fix the issue you were observing?
=> Fix race condition in ResizingThreadTableWorks.

docs/specs/memory.md
This probably isn't really important, I just noticed a dead link while digging through the specs :+1:
=> [spec]: Fix broken link to span in memory spec

src/System.CommandLine/README.md, src/System.CommandLine/System/CommandLine/Argument.cs, src/System.CommandLine/System/CommandLine/ArgumentList_1.cs, src/System.CommandLine/System/CommandLine/ArgumentParser.cs, src/System.CommandLine/System/CommandLine/ArgumentSyntax.cs, src/System.CommandLine/System/CommandLine/ArgumentSyntax_Definers.cs, src/System.CommandLine/System/CommandLine/Argument_1.cs, src/System.CommandLine/System/CommandLine/HelpTextGenerator.cs, tests/System.CommandLine.Tests/System/CommandLine/Tests/ArgumentSyntaxTests.cs, tests/System.CommandLine.Tests/System/CommandLine/Tests/HelpTextGeneratorTests.cs
I decided to go a slightly different route with the API than I originally suggested in #520. Instead of providing a value to use for when the option argument is missing, you just specify whether the option requires a value (the default is `true`). Then you can check `Argument.IsSpecified` to see if the reason you got the default value was because the option wasn't specified, or it was but no value was provided. I updated the readme with a clearer explanation.
=> Support for optional option arguments in System.CommandLine

src/System.Threading.Tasks.Channels/README.md, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/BoundedChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/Channel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/ChannelUtilities.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/SingleConsumerUnboundedChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/UnboundedChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/UnbufferedChannel.cs, tests/System.Threading.Tasks.Channels.Tests/UnboundedChannelTests.cs
Previously added AllowSynchronousContinuations to SingleConsumerUnboundedChannel, this adds it to UnboundedChannel as well.  Significant opt-in performance improvement for when continuations are registered off of readers, but at the expense of the producer doing the work instead of the consumer. Also updated the readme and fixed another minor issue.
=> Add AllowSynchronousContinuations support to UnboundedChannel 

src/System.Threading.Tasks.Channels/Properties/Resources.Designer.cs, src/System.Threading.Tasks.Channels/Properties/Resources.resx, src/System.Threading.Tasks.Channels/System/Collections/Generic/Dequeue.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/BoundedChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/CaseBuilder.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/ChannelExtensions.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/ChannelUtilities.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/SingleConsumerUnboundedChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/UnboundedChannel.cs, src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/UnbufferedChannel.cs, tests/System.Threading.Tasks.Channels.Tests/UnboundedChannelTests.cs
Mostly minor.  Use ConcurrentQueue in UnboundedChannel, avoid some unnecessary locking, clean up some code, etc.
=> Some more channels tweaks

src/System.Text.Primitives/System/Text/Parsing/Signed.cs, src/System.Text.Primitives/System/Text/Parsing/Signed.tt, src/System.Text.Primitives/System/Text/Parsing/Unsigned.cs, src/System.Text.Primitives/System/Text/Parsing/Unsigned.tt, tests/System.Text.Primitives.Tests/PrimitiveParserIntegerTests.cs, tests/System.Text.Primitives.Tests/PrimitiveParserIntegerTests.tt
PrimitiveParser's main overloads - those which take EncodingData and TextFormat objects as parameters - are currently failing when given the default values for those objects. This change introduces better behavior. If default(EncodingData) is passed, the parser will default to InvariantUtf8 parsing. If default(TextFormat) is passed, the parser will not interpret the format as having precision, as was the case previously.
This is a fix for Issue #1106.
=> In parsing methods, check for default(EncodingData) and default(TextFormat)

samples/LowAllocationWebServer/Framework/SharedData.cs, src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs, src/System.Collections.Sequences/System/Collections/Sequences/ArrayList.cs, src/System.Collections.Sequences/System/Collections/Sequences/ISequence.cs, src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/SequenceFormatter.cs, src/System.Text.Formatting/System/Text/Parsing/SequenceParser.cs, tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs, tests/System.Collections.Sequences.Tests/BasicUnitTests.cs, tests/System.Collections.Sequences.Tests/SampleCollections/Hashtable.cs, tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs, tests/System.IO.Pipelines.Tests/ReadableBufferFacts.cs
Now that I work more with sequences, I realized how annoying the advance default was. In real scenarios, you almost always want to advance the sequence. And so I am changing the default.
Enumerating sequences got a little bit nicer:
```c#
ArrayList<int> sequence= ...
var position = Position.First;
while (sequence.TryGet(ref position, out var item)) {
Console.WriteLine(item);
}
```
=> Changed sequence default to advance

src/System.Text.Primitives/System/Text/Encoding/Utf16/Utf16TextEncodingLE.cs, src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8TextEncoding.cs, tests/System.Text.Primitives.Tests/Encoding/Utf8EncoderTests.cs, tests/System.Text.Primitives.Tests/EncodingPerfComparisonTests.cs
Fixing implementation to take in little endian UTF16 characters and adjusting tests so they use UTF16 LE bytes.
Switching EncodingPerfComparisonTests to use the TextEncoder.Utf8.TryEncodeFromUtf16 method. It should be 3x slower instead of 7x slower now.
As part of Issue #1091 - Productize Encoding APIs
=> Attempts at improving encoding performance of UTF8.TryEncodeFromUtf16 

src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Buffers.Experimental/System/Buffers/BytesReader.cs, src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs, tests/System.Buffers.Experimental.Tests/BytesReader.cs, tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs
BytesReader can be used to implement higher level parsers (e.g. JSON parsers) of ReadOnlyBytes. 
The reader takes care of efficiently finding delimiters (single-byte or multi-byte) or parsing primitives contained in multi-segmented ReadOnlyBytes, even when the delimiter or the parsed primitive straddles multiple segments.
=> Added BytesReader

samples/LowAllocationWebServer/Framework/HttpServer.cs, samples/LowAllocationWebServer/Framework/Log.cs, samples/LowAllocationWebServer/Framework/RoutingTable.cs, samples/LowAllocationWebServer/SampleRestServer.cs, src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs, src/System.Text.Http/System/Text/Http/HttpRequest.cs, src/System.Text.Http/System/Text/Http/IFormatterHttpExtensions.cs, src/System.Text.Http/System/Text/Http/Obsolete/HttpHeaderBuffer.cs, src/System.Text.Http/System/Text/Http/Obsolete/HttpHeaders.cs, src/System.Text.Http/System/Text/Http/Obsolete/HttpRequestParser.cs, tests/Benchmarks/E2EPipelineNoIO.cs, tests/Benchmarks/Helpers/Server.cs, tests/System.Buffers.Experimental.Tests/BytesReader.cs, tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs, tests/System.Text.Http.Tests/GivenAnHttpHeaders.cs, tests/System.Text.Http.Tests/GivenIFormatterExtensionsForHttp.cs, tests/System.Text.Http.Tests/HttpRequestTests.cs
The existing HTTP parser (HttpRequest.Parse) cannot parse payloads arriving in multiple buffers.
This change adds the ability to parse requests arriving in multiple-buffers. It uses BytesReader added yesterday to parse the HTTP payload.
The old single segment parser was moved to System.Text.Http.SingleSegment. I will remove it completely later.
=> Added Multi-Segment HTTP Parser

src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8Encoder.cs, tests/System.Text.Primitives.Tests/Encoding/Utf8EncoderTests.cs
- removed redundant op
- removed comment, correction validated
- changed back typo in test
=> Minor changes/fixes of typos/etc.

scripts/PerfHarness/PerfHarness.cs, scripts/PerfHarness/project.json, src/System.IO.Pipelines/BufferSegment.cs, src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Buffers/OwnedMemory.cs, src/System.Slices/System/Buffers/ReadOnlyMemory.cs, src/System.Slices/System/Buffers/ReferenceCounter.cs, tests/System.Slices.Tests/MemoryTests.cs, tests/System.Slices.Tests/ReferenceCounterTests.cs, tests/System.Slices.Tests/project.json
Main changes
* Made Reference Count value not directly accessible, only whether it is zero or not.  
* Added a setting for whether reservations should use:
* Interlocked Reference Counting (slow),
* Reference Counter (almost safe), or
* Nothing (unsafe).
* Added a simple performance test for reservations that does parameter sweep. 
Minor tidying to 
* Remove unused Reserve method.
* Make DisposableReservations be able to return the Span, as in the design doc.
=> OwnedMemory tidy and performance testing

src/System.Text.Http/System/Text/Http/HttpRequest.cs, tests/System.Text.Http.Tests/HttpRequestTests.cs
I am porting samples to new multi-segment parsers and I discovered some APIs missing.
I need them to finish the port.
=> Added some APIs to HTTP parser

src/System.Text.Formatting/System/Text/Formatting/IOutputExtensions.cs, src/System.Text.Formatting/System/Text/Formatting/ITextOutputExtensions.cs, src/System.Text.Json.Dynamic/System/Text/Json/JsonDynamicObject.cs, src/System.Text.Json.Dynamic/project.json, src/System.Text.Primitives/System/Text/Formatting/PrimitiveFormatter_uuid.cs, src/System.Text.Primitives/System/Text/TextEncoding.cs, tests/System.Text.Formatting.Tests/CustomTypeFormatting.cs
Removing this variant force people to think about whether they really want to encode a single character. We could consider an extension method outside System.Text.Primitives core code base. For now, most of the users were in prototypes, tests, or somewhere that wrapping the "unsafe" portion was easy.
=> Remove the single char variant of TryEncode from TextEncoder

src/System.Time/project.json
This updates the `System.Time` package to include a NET45 target.  It also removes the dependency on the full `NETStandard.Library`, and instead targets the minimum versions of the specific dependencies needed.
Note that reducing to a lower netstandard version is not possible, because APIs like `IXmlSerializable` are not available until netstandard 1.3.
=> Update System.Time to target NET45 also

samples/EchoService/EchoService.csproj, samples/EchoService/Properties/AssemblyInfo.cs, samples/LibuvWithNonAllocatingFormatters/LibuvWithNonAllocatingFormatters.csproj, samples/LibuvWithNonAllocatingFormatters/Properties/AssemblyInfo.cs, samples/LowAllocationWebServer/LowAllocationWebServer.csproj, samples/QotdService/Properties/AssemblyInfo.cs, samples/QotdService/QotdService.csproj, samples/System.IO.Pipelines.Samples/Properties/AssemblyInfo.cs, samples/System.IO.Pipelines.Samples/System.IO.Pipelines.Samples.csproj
- The conversion added GenerateRuntimeConfigurationFiles=false which
breaks all running samples. This change removes that and cleans up
the sample project files.
- The samples should be running again
- Also reduce the AssemblyInfo.cs of various samples to remove
auto-generated content
=> Clean up samples csproj files and made them work

src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8Encoder.cs, tests/System.Text.Primitives.Tests/Encoding/Utf8EncoderTests.cs
As part of Issue #1091 - Make encoding between UTF8 and UTF16 (both ways) fast
Using DangerousGetPinnableReference() to get a pointer to the input and output spans to see if we can 
get improvements in performance.
**==============Here are the latest results:==============**
In all cases, there is a 2-4x performance gain over using Span IndexOf.
Comparing to System.Text.Encoding, the ASCII range encoding is still much slower, but all other ranges are on-par.
**Note:** I haven't run the corefxlab tests in VS 2017 yet, but I confirmed the correctness of the encoding in a stand-alone console app. I couldn't open the solution and wasn't sure how to run them using CLI.
***==============Previous entries (no longer relevant, please ignore)==============***
~~In all cases, there is a ~~2-4x~~ 15% …
=> Unsafe Utf8Encoder.TryEncode from Utf16 - performance increase

src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Buffers/OwnedMemory.cs, src/System.Slices/System/Buffers/ReadOnlyMemory.cs, tests/System.Buffers.Experimental.Tests/BytesReader.cs
At the standup today, we talked about how accessing Span from Memory from Memory from OwnedMemory shows in profiles. I spent some thine looking at what we do in these code paths, and there are some obvious inefficiencies.  
a) Getting Span from Memory first creates a full Span for the OwnedMemory and then slices the Span to get Span corresponding to Memory's subrange. This change eliminates this slicing.
b) Getting Memory from OwnedMemory is done by passing OwnedMemory to Memory ctor. The ctor then gets Span out of OwnedMemory to determine the length of itself. This change eliminates the need to get the Span by calling a different Memory ctor that explicitly takes length parameter.
Unfortunately I cannot compare perf wins as out perf benchmarks for pipelines (Benchmarks.dll) are currently …
=> Optimized Memory<T> Access

corefxlab.sln, src/System.CommandLine/System/CommandLine/ArgumentLexer.cs, tests/System.CommandLine.Tests/System/CommandLine/Tests/ArgumentLexerTests.cs
Fixes #1164 
This fixes the issue where ':' was preferred as the option/argument separator even when there was a '=' earlier in the string.
=> Fix arguments with = before :

src/System.IO.Pipelines.File/FileReader.cs, src/System.IO.Pipelines.Networking.Libuv/UvTcpConnection.cs, src/System.IO.Pipelines.Networking.Sockets/SocketConnection.cs, src/System.IO.Pipelines.Networking.Windows.RIO/RioTcpConnection.cs, src/System.IO.Pipelines/IPipelineWriter.cs, src/System.IO.Pipelines/Pipe.cs, src/System.IO.Pipelines/PipelineWriter.cs, tests/System.IO.Pipelines.Tests/PipelineWriterFacts.cs
- For better symmetry between reading and writing, the Writing
task was removed IPipelineWriter.
- FlushAsync returns a bool when awaited which the producer can use to
stop producing. False means the consumer is complete.
/cc @benaadams
=> Removed Writing task from IPipelineWriter

src/System.IO.Pipelines.Compression/Interop/Interop.zlib.Windows.cs, src/System.IO.Pipelines.Networking.Libuv/Interop/SockAddr.cs
When we know an array is not null or empty at the point where `fixed` is used, we can reduce the number of branches (and IL size of the method body) by using the address of the first element.
Based on the discussion here: https://github.com/dotnet/corefx/pull/15432#discussion_r97684916
Related:
- https://github.com/dotnet/coreclr/pull/9115
- https://github.com/dotnet/coreclr/pull/9188
- https://github.com/dotnet/corefx/pull/15597
- https://github.com/dotnet/corert/pull/2668
=> Avoid unnecessary branches when fixing non-null/empty arrays

src/System.IO.Pipelines.Networking.Libuv/Internal/LibuvAwaitable.cs, src/System.IO.Pipelines.Networking.Libuv/Interop/UvWriteReq.cs, src/System.IO.Pipelines.Networking.Libuv/UvTcpConnection.cs
Not 100% sure about the perf throughput of this change yet, various a bit on my machine. It also reduces writing in parallel but that can be brought back by not awaiting the task. We can also have a maximum concurrency level if we want to restrict the amount of outstanding writes (like Kestrel does).
/cc @halter73 @pakrym @benaadams
=> Await writes so natural back pressure is applied

src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs, tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs
cc: @shiftylogic, @ahsonkhan, @davidfowl 
Added more through tests for slicing
Found a bug and fixed it
Optimized slicing to empty ROBs
=> Improvements to ReadOnlyBytes

src/System.Buffers.Experimental/System/Buffers/OwnedMemory.cs, src/System.Slices/System/Buffers/OwnedMemory.cs, tests/System.Buffers.Experimental.Tests/MemoryTests.cs
The finalizer could fail if the object had got into a bad state due
to Reservation having been leaked. This occured in the test due
to trying to dispose an object while having reservations. This is
a possible fix, but it may be better to decide on how finalization
and Dispose should interact.
There are a few questions about the right error model:
* Should we raise an error if a Release is on an object that has been 
attempted to be freed? Or should that succeed.  Currently, if fails, 
but I think this might be a bad idea. 
* Should finalization of an object potentially raise an exception if it 
has effectively been leaked?
@KrzysztofCwalina @joshfree @davidfowl
=> Finalizer issue with OwnedNativeMemory

tests/Benchmarks/Benchmarks.csproj, tests/System.Binary.Base64.Tests/System.Binary.Base64.Tests.csproj, tests/System.Binary.Tests/System.Binary.Tests.csproj, tests/System.Buffers.Experimental.Tests/System.Buffers.Experimental.Tests.csproj, tests/System.Collections.Generic.MultiValueDictionary.Tests/System.Collections.Generic.MultiValueDictionary.Tests.csproj, tests/System.Collections.Sequences.Tests/System.Collections.Sequences.Tests.csproj, tests/System.CommandLine.Tests/System.CommandLine.Tests.csproj, tests/System.Drawing.Graphics.Tests/System.Drawing.Graphics.Tests.csproj, tests/System.IO.FileSystem.Watcher.Polling.Tests/System.IO.FileSystem.Watcher.Polling.Tests.csproj, tests/System.IO.Pipelines.Tests/System.IO.Pipelines.Tests.csproj, tests/System.Net.Libuv.Tests/System.Net.Libuv.Tests.csproj, tests/System.Numerics.Matrices.Tests/System.Numerics.Matrices.Tests.csproj, tests/System.Reflection.Metadata.Cil.Tests/System.Reflection.Metadata.Cil.Tests.csproj, tests/System.Slices.Tests/System.Slices.Tests.csproj, tests/System.Text.Encodings.Web.Utf8.Tests/System.Text.Encodings.Web.Utf8.Tests.csproj, tests/System.Text.Formatting.Globalization.Tests/System.Text.Formatting.Globalization.Tests.csproj, tests/System.Text.Formatting.Tests/System.Text.Formatting.Tests.csproj, tests/System.Text.Http.Tests/System.Text.Http.Tests.csproj, tests/System.Text.Json.Tests.Dynamic/System.Text.Json.Tests.Dynamic.csproj, tests/System.Text.Json.Tests/System.Text.Json.Tests.csproj, tests/System.Text.Primitives.Performance.Tests/System.Text.Primitives.Performance.Tests.csproj, tests/System.Text.Primitives.Tests/System.Text.Primitives.Tests.csproj, tests/System.Threading.Tasks.Channels.Tests/System.Threading.Tasks.Channels.Tests.csproj, tests/System.Time.Tests/System.Time.Tests.csproj
- This resolves the VS issue and now all tests run in VS.
You should now be able to click Run All Tests in the Test Explorer and they will run to completion rather than aborting mid way (especially for System.Buffers.Experimental.Tests).
=> Updating the Microsoft.NET.Test.Sdk to a newer version

tests/System.Text.Primitives.Tests/Encoding/Utf8EncoderTests.cs
Issue #1211 
Specifically removing:
TestEncodingInputBufferMaxSize() 
TestEncodingOutputBufferMaxSize()
=> Removing Memory Intensive Tests

src/System.Slices/System/SpanExtensions.cs, src/System.Slices/System/SpanExtensions_comparisons.cs, src/System.Slices/System/SpanExtensions_text.cs, src/System.Text.Http/System/Text/Http/Obsolete/HttpHeaderBuffer.cs
~~I am surprised CI has been passing so far given I get build failures locally without this change.~~
**Edit:** I am getting these errors locally since I am using the new version of System.Memory package which contains the changes. Since this package isn't published to myget, the CI does not use the new version (and the old version doesn't have this change).
For example:
System\SpanExtensions_text.cs(52,20): error CS0103: The name 'ReadOnlySpanExtensions' does not exist in the current context [C:\Users\ahkha\Documents\GitHub\Fork\corefxlab\src\System.Slices\System.Slices.csproj]
=> Renaming ReadOnlySpanExtensions to SpanExtensions

scripts/PerfHarness/PerfHarness.csproj, src/System.Buffers.Experimental/System.Buffers.Experimental.csproj, src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, tests/Benchmarks/Benchmarks.csproj, tests/Benchmarks/IndexOf.cs, tests/System.Buffers.Experimental.Tests/VectorizedOperations.cs, tests/System.Text.Formatting.Tests/System.Text.Formatting.Tests.csproj
IndexOf is very commonly used in parsers. This PR is the first stab at implementing vectorized IndexOf operating over Span<T>. 
I added a simple benchmark, and it shows that vectorized IndexOf is ~3x faster than the sequential IndexOf for searching items far into the buffer. It is significantly slower if the searched for item is at index 0. The break even point is around index 30.
Test Name            /                            Average	[time]
IndexOfBench.VectorizedIndexOf	  0.091765931	
IndexOfBench.SpanIndexOf	          0.29441888	
Note, that I tried to implement a hybrid algorithm, i.e. sequential for indexes 0-32 and then vectorized. Unfortunately the overhead of the branch, slicing, etc. was so high that it almost nullified the gains for indexes 0-30 and then made perf slightly …
=> Added SIMD-based IndexOf

src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Buffers/OwnedMemory.cs, src/System.Slices/System/Buffers/ReadOnlyMemory.cs
Change causes `OwnedMemory``1.get_Memory` to evaporate from the stack traces
4th param for instance call is passed via stack rather than reg; so cut memory op by looking it up later, rather than precall; and spilling a param to stack; `0` is also implied by this .`ctor` so doesn't need to be passed.
(this `RCX`, owner `RDX`, id `R8`, index `R9`, length `stack`) 
=> (this `RCX`, owner `RDX`, length `R8`) 
It is an extremely hot function
=> Reduce implied param passing

src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs
from https://github.com/dotnet/corefx/pull/16222
Not quite sure how to interpret the benchmark results (from corefxlab\scripts\PerfHarness) but they suggest is x4.5 - x6 faster than `.IndexOf` for everything except length = 0
Likely want to verify it by someone who understands how the benchmarks work; might all be the same length and 0 is higher as its jitting
=> Faster IndexOfVectorized

src/System.Text.Primitives/System/Text/Encoding/Internal/ParsingTrie.cs
@KrzysztofCwalina @ahsonkhan @joshfree
=> Fix for TextEncoder crash when used in .NET Core 2.0

src/System.IO.Pipelines.Text.Primitives/ReadableBufferExtensions.cs, src/System.IO.Pipelines/BufferSegment.cs, src/System.IO.Pipelines/ReadCursor.cs, src/System.IO.Pipelines/ReadableBuffer.cs, src/System.IO.Pipelines/ReadableBufferReader.cs, src/System.IO.Pipelines/ThrowHelper.cs, tests/System.IO.Pipelines.Tests/ReadableBufferReaderFacts.cs
- Added GetAsciiString extension method on `Span<byte>`
- Store the `Memory<byte>` on BufferSegment
- Removed unused read cursor out param on TryGetBuffer
- Remove bounds check from internal readable buffer ctor
- Fixed Cursor property on ReadableBufferReader
- Added ReadableBufferReader.Skip
/cc @benaadams @halter73 @pakrym
=> Various changes related to Kestrel updates

src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Buffers/OwnedMemory.cs, src/System.Slices/System/Buffers/ReadOnlyMemory.cs, tests/Benchmarks/IndexOf.cs, tests/System.Buffers.Experimental.Tests/MemoryTests.cs
We want to get to baseline performance first before adding pooling checks/diagnostics. This change:
- makes Memory<T> smaller and so passing it by value and construction cheaper
- makes get_Span, TryGetPointer, TryGetArray cheaper as they won’t have to pass the ID and do ID checks
- makes diagnosing use after return bugs harder
```
Method |       Mean |    StdDev |     Median | Scaled | Scaled-StdDev |        RPS | Allocated |
------------------------- |----------- |---------- |----------- |------- |-------------- |----------- |---------- |
ParsePlaintext |  2.0345 us | 0.0546 us |  2.0456 us |   1.00 |          0.00 | 491,511.89 |     105 B |
ParsePipelinedPlaintext |  1.8487 us | 0.0524 us |  1.8607 us |   0.91 |          0.03 | 540,916.50 |     105 B |
ParseLiveAspNet |  9.5836 us | …
```
=> Removed Memory._id

src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Buffers/ReadOnlyMemory.cs
I reran the benchmarks several times and consistently ParsePlaintext improves but ParsePipelinedPlaintext degrades a bit. Possibly it's because my "before" is not really before this change but rather after my previous change (removal of ID). Possibly some changes to that got merged separately changed the baseline.  I would redo the baseline for more complex change, but I think this is a clear improvement, so I think we should just merge. Any other opinions?
```
Method |       Mean |    StdDev |     Median | Scaled | Scaled-StdDev |        RPS | Allocated |
------------------------- |----------- |---------- |----------- |------- |-------------- |----------- |---------- |
ParsePlaintext |  1.9474 us | 0.0695 us |  1.9281 us |   1.00 |          0.00 | 513,500.72 |     105 B | …
```
=> improved performance of Memory.get_Empty

src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, tests/System.Buffers.Experimental.Tests/VectorizedOperations.cs
Based on some simple micro-benchmarks, using TryIndicesOf vs IndexOf+Slice in a loop is anywhere from 3x faster (for finding elements 8 bytes apart) to 8x faster (for elements ~120 bytes apart).
=> Basic implementation of vectorized TryIndicesOf

src/System.IO.Pipelines/MemoryEnumerator.cs, src/System.IO.Pipelines/ReadCursorOperations.cs, src/System.IO.Pipelines/System.IO.Pipelines.csproj, tests/System.IO.Pipelines.Performance.Tests/ReadCursorOperationsThroughput.cs
There's likely a gain and a loss here since we're using the `MemoryEnumerator` to look at the data. Will measure the differences.
=> Faster seek implementation using span.IndexOfVectorized

scripts/PerfHarness/PerfHarness.csproj, tests/Benchmarks/Benchmarks.csproj, tests/System.Binary.Base64.Tests/System.Binary.Base64.Tests.csproj, tests/System.Slices.Tests/System.Slices.Tests.csproj, tests/System.Text.Primitives.Performance.Tests/System.Text.Primitives.Performance.Tests.csproj
- only tests marked as benchmark will now run during perf testing
Example, for System.Slices.Tests:
> Running 90 Benchmarks out of 402 Xunit Facts...
=> Updating xunit.perf.api package

src/System.IO.Pipelines/MemoryEnumerator.cs, src/System.IO.Pipelines/ReadableBufferReader.cs, tests/System.IO.Pipelines.Tests/ReadableBufferReaderFacts.cs
- Use SegmentEnumerator instead of MemoryEnumerator in
the ReadableBufferReader
- Slice Span instead of Memory
- Renamed _currentMemory to _currentSpan
Fixes #1261
/cc @shiftylogic
=> Fixed issue with ReadableBufferReader reporting incorrect cursor

.gitignore, scripts/PerfHarness/run.bat, src/System.IO.Pipelines.Text.Primitives/ReadableBufferExtensions.cs, src/System.Text.Primitives/System/Text/Encoding/Ascii/PrimitiveEncoder_ascii.cs, tests/Benchmarks/Benchmarks.csproj, tests/Benchmarks/GetAsciiStringBench.cs, tests/System.Text.Primitives.Tests/Encoding/PrimitiveEncoderTests_ascii.cs
I tried to make it into a TryDecode method, but it was 5% slower for some strings.
Maybe we can try one more time once we have Kestrel benchmarks at goal and stable.
cc: @shiftylogic, @davidfowl, @ahsonkhan 
Also, i tried to make it into a nested PrimitiveEncoder.Ascii class, but we don't support extension methods on nested types.
=> Moved optimized ASCII encoder to System.Text.Primitives

src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.IO.Pipelines/ReadCursorOperations.cs
When the search space < Vector length the jump over the vector code dominates; so add an early loop for shorter lengths.
@KrzysztofCwalina I think this resolves the issue you were seeing?
/cc @davidfowl
=> Improve Vectorized IndexOf for < Vector length

samples/System.IO.Pipelines.Samples/HttpClient/LibuvHttpClientHandler.cs, samples/System.IO.Pipelines.Samples/HttpServer/RequestHeaderDictionary.cs, src/System.IO.Pipelines.Extensions/DefaultReadableBufferExtensions.cs, src/System.IO.Pipelines.Extensions/ReadableBufferExtensionsExtensions.cs, src/System.IO.Pipelines/ReadableBuffer.cs, tests/System.IO.Pipelines.Tests/ReadableBufferFacts.cs, tests/System.IO.Pipelines.Tests/SocketsFacts.cs, tests/System.IO.Pipelines.Tests/WritableBufferFacts.cs
- Make first computed to save some room
- Move Equals and StartsWith to extensions
/cc @benaadams I took the computed first from https://github.com/dotnet/corefxlab/pull/1277/files
=> ReadableBuffer cleanup and changes

tests/System.IO.Pipelines.Performance.Tests/ReadCursorOperationsThroughput.cs
Perf tests to show the patterns we're using in kestrel to traverse a `ReadableBuffer`:
|                                       Method |      Mean |    StdErr |    StdDev |    Median |              RPS |
|--------------------------------------------- |---------- |---------- |---------- |---------- |----------------- |
|                                SeekPlainText | 0.2854 ns | 0.0029 ns | 0.0160 ns | 0.2868 ns | 3,504,029,261.31 |
|            SeekPlainTextReadableBufferReader | 0.1547 ns | 0.0014 ns | 0.0075 ns | 0.1534 ns | 6,462,042,969.75 |
|                       SeekPlainTextPipelined | 3.7484 ns | 0.0977 ns | 0.5352 ns | 3.5305 ns |   266,779,616.57 |
|   SeekPlainTextPipelinedReadableBufferReader | 1.4455 ns | 0.0614 ns | 0.3360 ns | 1.3614 ns |   691,821,417.11 |
| …
=> Added more seek tests for newlines

src/System.IO.Pipelines/Pipe.cs, src/System.IO.Pipelines/PipeOperationState.cs, src/System.IO.Pipelines/ReadCursor.cs, tests/System.IO.Pipelines.Performance.Tests/Program.cs
1. Expand locks instead of interlocked
2. Avoid double locking
3. Inline `Read` so we don't copy big struct around
=> Improve pipe throughput

src/System.IO.Pipelines.Compression/CompressionPipelineExtensions.cs, src/System.IO.Pipelines.File/FileReader.cs, src/System.IO.Pipelines.Networking.Libuv/Interop/UvWriteReq.cs, src/System.IO.Pipelines.Text.Primitives/ReadableBufferExtensions.cs, src/System.Net.Libuv/System/Net/Libuv/Stream.cs, src/System.Slices/System/Buffers/Memory.cs, src/System.Slices/System/Buffers/MemoryHandle.cs, src/System.Slices/System/Buffers/PinnedMemoryHandle.cs, src/System.Slices/System/Buffers/ReadOnlyMemory.cs
Proposal to address issue #1287 
- Added API (similar to `GCHandle`) for scoped access to internal pointers of `Memory<T>` and `ReadOnlyMemory<T>`.
- Partially ported to the new `GetPinnedMemoryHandle` API.
CC @KrzysztofCwalina @davidfowl @jkotas @mjp41
=> Added PinnedMemoryHandle<T> to replace TryGetPointer

src/System.IO.Pipelines.Networking.Libuv/UvTcpConnection.cs
Following the discussion in #1298
This is a really simple code change to remove the call to `TryGetPointer` in `UvTcpConnection`. It looks like the semantics are _similar_, but I don't think I'm fully following where that memory comes from and when it gets cleaned up, so want to make sure I'm not missing something important.
It probably also has a slight performance penalty.
I don't expect this is correct yet, just a starting point. Once this one's sorted I'll look at the RIO impl.
=> Remove TryGetPointer call from UvTcpConnection

tests/System.Buffers.Primitives.Tests/MemoryTests.cs, tests/System.IO.Pipelines.Tests/ReadableBufferFacts.cs
This change removes `TryGetPointer` from the System.IO.Pipelines.Tests, and replaces it with `MemoryHandle` and `Span.DangerousGetPinnableReference`.
There is now only a single place left that is using `TryGetPointer` (in RioTcpConnection).
=> Replace TryGetPointer with MemoryHandle in tests

scripts/build.ps1
- NuGet computes dependency versions from the assets file
so specify the right version on restore to see if that
fixes things.
- Also pass the property to build for good measure
=> Attempt to fix version staggering again

src/System.IO.Pipelines.Extensions/System.IO.Pipelines.Extensions.csproj, src/System.IO.Pipelines.Networking.Libuv/UvThread.cs, src/System.IO.Pipelines/PipeOptions.cs, src/System.IO.Pipelines/System.IO.Pipelines.csproj, src/System.IO.Pipelines/Testing/BufferUtilities.cs, tests/System.IO.Pipelines.Tests/SocketsFacts.cs
- Remove System.Linq dependency
- Remove dependency on ValueTask in the core API
- Throw error from UvThread.Stop if we're blocking the
uv thread trying to unwind.
- Fix the SocketsFacts so we don't end up on the libuv
thread in the test after PingClient
=> Some pipelines cleanup

src/System.Binary/System/Binary/UnsafeUtilities.cs
Now that all Read<T>/Write<T> methods are in System.Binary, we can make UnsafeUtilities internal
=> Made UnsafeUtilities internal

src/System.Buffers.Primitives/System/SpanExtensions.cs, src/System.IO.Pipelines/ReadCursorOperations.cs
To reflect what they do more correctly
Resolves https://github.com/dotnet/corefxlab/issues/1352
/cc @ahsonkhan
=> Rename IndexOf overloads to IndexOfAny

src/System.Text.Json/System/Text/Json/JsonParser.cs
Somehow we got to a place where we have StartsWith(this ReadOnlySpan\<byte\>, ReadOnlySpan\<byte\>); in both SpanExtensions and SpanExtensionsLabs.
I think @ahsonkhan's PR will fix it, but it needs to be resolved.
=> fixes a build break

src/System.IO.Pipelines/Pipe.cs
`GetResult` calls `ObserveCancellation` that modifies state. Decreases performance but we need it.
Before:
```
Method |        Mean |    StdErr |     StdDev |          RPS |
------------------------ |------------ |---------- |----------- |------------- |
ParseLiveAspNetTwoTasks | 291.2868 ns | 2.0583 ns | 11.2738 ns | 3,433,043.01 |
ParseLiveAspNetInline | 204.2358 ns | 2.8546 ns | 15.6355 ns | 4,896,300.75 |
```
After:
```
Method |        Mean |    StdErr |     StdDev |          RPS |
------------------------ |------------ |---------- |----------- |------------- |
ParseLiveAspNetTwoTasks | 326.4556 ns | 3.3105 ns | 18.1321 ns | 3,063,203.49 |
ParseLiveAspNetInline | 237.0526 ns | 3.8329 ns | 20.9937 ns | 4,218,472.53 |
```
@davidfowl
=> Expand locking in GetResult methods

src/System.IO.Pipelines/WritableBuffer.cs, src/System.IO.Pipelines/WritableBufferWriter.cs, tests/System.IO.Pipelines.Performance.Tests/PipeThroughput.cs, tests/System.IO.Pipelines.Tests/PipeLengthTests.cs, tests/System.IO.Pipelines.Tests/WritableBufferWriterFacts.cs
Comparison with writefast that kestrel uses:
```
Method |        Mean |    StdErr |     StdDev |          RPS |
------------------------------------------------ |------------ |---------- |----------- |------------- |
WriteFastPlaintextResponse | 519.8520 ns | 6.5837 ns | 36.0603 ns | 1,923,624.52 |
WriteableBufferWriterWriteFastPlaintextResponse | 374.1911 ns | 6.0379 ns | 33.0709 ns | 2,672,431.50 |
```
/cc @benaadams
=> Add WritableBufferWriter for fast writes

src/System.Text.Http.Parser/HttpParser.cs, src/System.Text.Http.Parser/System.Text.Http.Parser.csproj, tests/Benchmarks/Benchmarks.csproj, tests/Benchmarks/HttpParserBench.cs
After I added inner itterations, the results are more realistic:
Test Name                               | Metric                | Iterations |    AVERAGE |    STDEV.S |        MIN |        MAX
:--------------------------------------- |:--------------------- |:----------:| ----------:| ----------:| ----------:| ----------:
HttpParserBench.HttpParserReadableBytes | Duration              |    101     |      0.159 |      0.743 |      0.081 |      7.555
HttpParserBench.HttpParserReadableBytes | Instructions Retired  |    101     | 1.009E+006 | 3.768E+006 | 6.000E+005 | 3.850E+007
HttpParserBench.HttpParserReadableBytes | Branch Mispredictions |    101     |   4542.099 |  35810.853 |      0.000 | 3.604E+005
HttpParserBench.HttpParserReadableBytes | Cache Misses          |    101     | …
=> Added support for ReadOnlyBytes to HttpParser

src/System.Buffers.Experimental/System/Buffers/BytesReader.cs
- BytesReader reports that it's empty when it isn't because of https://github.com/dotnet/coreclr/issues/10481.
This seems to work around the problem for now.
This is blocking our move to .NET Core 2.0 move in SignalR https://github.com/aspnet/SignalR/pull/338
/cc @anurse
=> Work around a JIT bug

src/System.Buffers.Experimental/System/Buffers/BytesReader.cs, src/System.Text.Http.Parser/HttpParser.cs, src/System.Text.Http.Parser/IHttpHeadersHandler.cs, src/System.Text.Http.Parser/IHttpRequestLineHandler.cs, tests/Benchmarks/HttpParserBench.cs, tests/System.Text.Http.Parser.Tests/HttpParserTests.cs
Note that the parser does not yet handle headers straddling spans. It will throw NotImplementedException in such case. I will add this capability later.
The parser is slightly faster than the ReadableBuffer parser, but I need to implement straddling headers and possibly removal of white space trailing header values, so I will refrain form publishing benchmarks for now.
The ReadableBuffer does more than one pass over bytes in some cases. This parser is single pass. But the ReadableBuffer used vectorized operations for searching some delimiters; this parser is sequential only.
Also, I improved performance tests to make results more consistent, but increasing inner iterations and unrolling the inner loop.
Lastly, I changed the handler callbacks to take ReadOnlySpan<byte> instead of taking …
=> Added ability to parse headers represented  by ReadOnlyBytes

src/System.IO.Pipelines.Networking.Windows.RIO/Internal/RioThread.cs, src/System.IO.Pipelines.Networking.Windows.RIO/RioTcpConnection.cs
Part of #1298
Moves the `GetSegmentFromMemory` method into the `RioThread` and uses `Pin` instead of `TryGetPointer`. I think it's safe to not keep the `MemoryHandle` around because we verify the memory is from a `Slab` in the memory pool using its address, which we know is pinned.
So now it's `RioThread`s responsibility to make sure its buffers are pinned, which is better because it's the one creating the `MemoryPool`.
I'm not sure about error handling, if it turns out the memory isn't from a known slab then the RIO buffer id is `IntPtr.Zero`, but we're not explicitly dealing with this.
=> Remove TryGetPointer from RioTcpConnection

src/System.IO.Pipelines/ReadableBuffer.cs, tests/System.IO.Pipelines.Tests/ReadableBufferFacts.cs
This API is useful for receiving data from the network to be added to a Pipe. Network APIs accept buffers and fill those buffers to some extent. This API allows the user to allocate a number of buffers, pass them to a receive API and then Append the filled ranges to a Pipe via WritableBuffer.Append(ReadableBuffer).
https://github.com/dotnet/corefxlab/issues/1233
@davidfowl @benaadams
=> Add ReadableBuffer.Create(OwnedBuffer<byte>, offset, length)

docs/specs/span.md
- Added backticks around mentions of `Span<T>` and other code such as `_relocatableObject` (in which case the `_` is currently interpreted as [emphasis](https://daringfireball.net/projects/markdown/syntax.php#em)).
- Added `[here]` text to links as that was done elsewhere in the document already.
- Added space before headers so they are properly recognised as such.
=> Improved Markdown formatting and readability

src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, tests/System.Buffers.Experimental.Tests/StringSliceTests.cs, tests/System.Buffers.Experimental.Tests/TestHelpers.cs
Moving over from System.Memory.dll as part of #1314 / #1292.
Removed here: https://github.com/dotnet/corefx/pull/17407
=> Adding extension method Slice on string which returns ReadOnlySpan<char>

src/System.Buffers.Primitives/System/SpanExtensions_array.cs, tests/System.Buffers.Primitives.Tests/BasicUnitTests.cs, tests/System.Buffers.Primitives.Tests/UsageScenarioTests.cs
As part of: https://github.com/dotnet/corefxlab/issues/1314 / https://github.com/dotnet/corefxlab/issues/1292
Being added in this PR: https://github.com/dotnet/corefx/pull/17783
cc @shiftylogic, @davidfowl
=> Removing array CopyTo span as it is being added to SpanExtensions

tests/System.Text.Primitives.Tests/PrimitiveParserUInt32PerfTests.cs
Fixing some tests that were previously skipped because Span was used as a generic type within List<T>.
cc @shiftylogic, @botaberg, @davidfowl
=> Cannot use Span as a generic type

src/System.Text.Formatting/System/Text/Formatting/CompositeFormat.cs, src/System.Text.Http/System/Text/Http/HttpRequest.cs, src/System.Text.Http/System/Text/Http/IFormatterHttpExtensions.cs, src/System.Text.Json/System/Text/Json/JsonParser.cs, tests/Benchmarks/E2EPipelineNoIO.cs, tests/System.Text.Formatting.Tests/CompositeFormattingTests.cs, tests/System.Text.Http.Tests/GivenAnHttpHeaders.cs, tests/System.Text.Http.Tests/GivenIFormatterExtensionsForHttp.cs, tests/System.Text.Http.Tests/HttpRequestTests.cs, tests/System.Text.Json.Tests.Dynamic/JsonDynamicObjectTests.cs, tests/System.Text.Json.Tests/JsonObjectTests.cs, tests/System.Text.Primitives.Tests/Encoding/RandomTests.cs, tests/System.Text.Primitives.Tests/Encoding/TypeConstraintsTests.cs
Re-enabling tests that were disabled during migration to net core 2.0 here: https://github.com/dotnet/corefxlab/pull/1401
- Utf8String cannot be used as a generic in `Nullable<T>`.
- Cannot use Utf8String as a static.
- Cannot box Utf8String by calling GetType on it.
-  Cannot use Span or Utf8String as a static + removing a duplicate test.
-  Cannot cast Utf8String as an object.
- Removing tests (commenting out) around JsonDynamicObject and HttpHeadersSingleSegment.
Opened issues to address change requests to these types since they need to be redesigned.
- JsonDynamicObject / JsonLazyDynamicObject - #1434
- HttpHeadersSingleSegment - #1435
- Utf8String CodePointReverseEnumerator / CodePointEnumerator / CodePointEnumerable - #1235
cc @shiftylogic, @KrzysztofCwalina
=> Fixing use of Span/Utf8String in tests

NuGet.Config, scripts/build.ps1, tools/common.props, tools/dependencies.props
- ~**Using msbuild to build the solution (instead of dotnet cli) <= do we want to do this?**~
- Adding a new myget feed for roslyn
- Including a package reference to Microsoft.Net.Compilers in all the projects
- Adding RoslynVersion property
From @VSadov: 
> As a first step we are using 2.3.0-rdonly-ref-61530-07 here.
NOTE: This compiler version does not implement any checks for Span<T>. That will come in the next change.
cc @KrzysztofCwalina, @shiftylogic, @VSadov. @joshfree
=> Referencing and using custom C# compiler from roslyn myget feed

samples/System.IO.Pipelines.Samples/HttpClient/LibuvHttpClientHandler.cs, samples/System.IO.Pipelines.Samples/HttpServer/HttpConnection.cs, src/System.Text.Http.Parser/HttpParser.cs, tests/Benchmarks/Helpers/Server.cs, tests/System.Buffers.Primitives.Tests/EqualityTests.cs, tools/dependencies.props
The new version is
https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.Net.Compilers/2.3.0-rdonly-ref-61607-04
The new version enforces the following rules:
- `Span<T>` and `ReadonlySpan<T>` are stack-only types. (no boxing, invalid use in async, etc...)
- `Span<T>` and `ReadonlySpan<T>` cannot be passed via a writeable parameter.
There were several violations that I fixed.
NOTE: we are not yet validating the usage of span-containing structs. There could be more indrect violations of stack safety through that.
=> Switching to the new toolset compiler.

docs/specs/nativesized.md
F# is affected by this design proposal.
nb. When a .NET design proposal affects F#, please add an entry at https://github.com/fsharp/fslang-suggestions/issues/562 or just link F# contributors in to the discussion.
=> Add F# design link

tests/System.Text.Primitives.Tests/Encoding/Utf8EncoderTests.cs
cc @KrzysztofCwalina. @shiftylogic, @jorive
Resolving the warnings that become visible on dotnet run.
D:\GitHub\Fork\corefxlab\scripts\PerfHarness>`..\..\dotnet\dotnet.exe run -c Release --assembly System.Text.Primitives.Tests --perf:typenames System.Text.Primitives.Tests.EncodingPerfComparisonTests`
> Non-serializable data ('System.Object[]') found for 'System.Text.Utf8.Tests.Utf8EncoderTests.UTF16ToUTF8EncodingTestForReadOnlySpanOfChar'; falling back to single test case.
Non-serializable data ('System.Object[]') found for 'System.Text.Utf8.Tests.Utf8EncoderTests.TryEncodeFromUnicodeMultipleCodePoints'; falling back to single test case.
Non-serializable data ('System.Object[]') found for 'System.Text.Utf8.Tests.Utf8EncoderTests.TryDecodeToUnicodeMultipleCodePoints'; falling back to …
=> TextEncoder Utf8/Utf16 is not serializable.

tests/System.Text.Primitives.Tests/Formatting/GuidTests.cs
Necessary for getting CoreFxLab working in VS again.
=> Removing unused culture info for Guid::ToString

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/OwnedBuffer.cs, src/System.Buffers.Experimental/System/Buffers/BufferManager.cs, src/System.Buffers.Experimental/System/Buffers/OwnedNativeBuffer.cs, src/System.Buffers.Experimental/System/Buffers/OwnedPinnedBuffer.cs, src/System.Buffers.Primitives/System/Buffers/DisposableReservation.cs, src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs, src/System.Buffers.Primitives/System/Internal/ManagedBufferPool.cs, src/System.Buffers.Primitives/System/Internal/OwnedArray.cs, src/System.Buffers.Primitives/System/Internal/OwnerEmptyMemory.cs, src/System.IO.Pipelines/MemoryPoolBlock.cs, src/System.IO.Pipelines/UnownedBuffer.cs, tests/System.Buffers.Primitives.Tests/MemoryTests.cs, tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
Abstracted lifetime management (reference counting) out of OwnedBuffer\<T\>.
Added a subclass ReferenceCountedBuffer for interlocked-based reference counting.
Other subclasses, can use whatever they want for lifetime management.
After this change, OwnedBuffer has just one field left (_disposed) which can be removed quite easily (at the cost of making it more tedious to implement IDisposable on subclasses.  
cc: @mjp41, @davidfowl, @ahsonkhan, @shiftylogic
=> Abstraced OwnedBuffer lifetime management

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/OwnedBuffer.cs, src/System.Buffers.Experimental/System/Buffers/BufferManager.cs, src/System.Buffers.Experimental/System/Buffers/OwnedNativeBuffer.cs, src/System.Buffers.Experimental/System/Buffers/OwnedPinnedBuffer.cs, src/System.Buffers.Primitives/System/Buffers/Buffer.cs, src/System.Buffers.Primitives/System/Buffers/BufferHandle.cs, src/System.Buffers.Primitives/System/Buffers/DisposableReservation.cs, src/System.Buffers.Primitives/System/Buffers/IRetainable.cs, src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs, src/System.Buffers.Primitives/System/Buffers/ReferenceCountedBuffer.cs, src/System.Buffers.Primitives/System/Internal/ManagedBufferPool.cs, src/System.Buffers.Primitives/System/Internal/OwnedArray.cs, src/System.Buffers.Primitives/System/Internal/OwnerEmptyMemory.cs, src/System.IO.Pipelines/BufferSegment.cs, src/System.IO.Pipelines/MemoryPoolBlock.cs, src/System.IO.Pipelines/UnownedBuffer.cs, tests/System.Buffers.Primitives.Tests/MemoryTests.cs, tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
This change allows the called of BufferHandle ctor to decide how GCHandle is constructed. For example, permamently pinned buffers can use default GCHandle and array based buffers can create single GCHandle per OwnedBuffer which gets released when reference count goes to zero.
The main changes are in BufferHandle.Create/ctor
cc: @davidfowl, @shiftylogic
=> Simplified BufferHandle and Pinning

tests/System.Text.Primitives.Tests/Encoding/RandomTests.cs
Resolves this discrepancy between VS test discovery/run and command line:
------ Discover test started ------
[xUnit.net 00:00:00.5287380]   Discovering: System.Text.Primitives.Tests
[xUnit.net 00:00:02.2739751]   Discovered:  System.Text.Primitives.Tests
A test with the same name 'System.Text.Primitives.Tests.Utf8StringTests.StringEqualsWithThreeArgs (7b20df66ebc54d70aa2f6290cb0e75c08e639f33)' already exists. This test is not added to the test window.
A test with the same name 'System.Text.Primitives.Tests.Utf8StringTests.StringEqualsWithThreeArgs (7b20df66ebc54d70aa2f6290cb0e75c08e639f33)' already exists. This test is not added to the test window.
A test with the same name 'System.Text.Primitives.Tests.Utf8StringTests.TryComputeEncodedBytesShouldMatchEncoding_Utf8 …
=> Removing duplicate test cases and fixing typo in Text.Primitives.Tests.

src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8Encoder.cs, tests/System.Text.Primitives.Tests/Encoding/Utf8Utf16ConversionTests.cs
* We don't support fallback like the CLR does, so that code was deleted.
* We decode as much as we can and return what we consumed, so there are minor tweaks.
* Passes all existing tests, which cover scenarios like output buffer too small, partial decode and retry from point we stopped, etc.
* Added some random decoding tests for utf-8 => utf-16 scenarios across several code point ranges.
=> Port CLR utf8-to-utf16 decode implementation

scripts/PerfHarness/run.bat, src/System.Buffers.Primitives/System/Buffers/Buffer.cs, src/System.Buffers.Primitives/System/Buffers/DisposableReservation.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs, tests/Benchmarks/E2EPipelineNoIO.cs, tests/System.Buffers.Experimental.Tests/MemoryTests.cs, tests/System.Buffers.Primitives.Tests/MemoryTests.cs
DisposableReservation returned from ReadOnlyBuffer.Reserve could be used to create r/w Span<T>. 
One way to resolve the issue was to create ReadOnlyDisposableReservation, but this would just add to the complexity of lifetime management.
I opted into removing DisposableReservation.Span. DisposableReservation is now just a way to call retain and release on owned buffers. To get spans, the calling code needs to call Buffer.Span or ReadOnlyBuffer.Span. These properties always give spans with the appropriate r/w access.
I also simplified the benchmarks I use to verify that we don't regress pipelines performance.
cc: @mjp41, @ahsonkhan, @shiftylogic, @davidfowl
=> Fixed r/w hole in DisposableReservation

docs/specs/span.md
Simple fix for titles that were not rendering correctly due to malformed markup syntax.
=> Fix formatting of titles.

tests/System.Buffers.Primitives.Tests/MemoryTests.cs
The test that used these helpers got removed in #1499 (https://github.com/dotnet/corefxlab/pull/1499#discussion_r113267515).
=> Remove unused helpers in Buffer.Primitives.Tests.MemoryTests.

src/System.IO.Pipelines.Extensions/UnownedBufferReader.cs
Discovered when pooling BufferSegments in https://github.com/dotnet/corefxlab/pull/1360
Isn't a problem currently as they just get GC'd eventually; but is a problem if they get pooled as something else updates the buffer and then its no longer empty.
/cc @davidfowl
=> Remove dangling ref from UnownedBufferReader

src/System.Text.Primitives/System/Text/Encoding/Utf16/Utf16LittleEndianEncoder.cs, src/System.Text.Primitives/System/Text/Encoding/Utf16/Utf16TextEncoderLE.cs, src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8Encoder.cs, src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8TextEncoder.cs, src/System.Text.Primitives/System/Text/TextEncoder.cs
Specifically for encoding/decoding `ReadOnlySpan<uint> utf32`
=> Renaming charactersWritten/Consumed to codePointsWritten/Consumed.

scripts/PerfHarness/README.md, tests/System.Text.Primitives.Tests/Encoding/EncodeIntoUtf8Tests.cs, tests/System.Text.Primitives.Tests/Encoding/TextEncoderTestHelper.cs, tests/System.Text.Primitives.Tests/EncodingPerfTestsUsingTextEncoder.cs
cc @shiftylogic 
- Added a concrete example to PerfHarness readme.
- Removing redundant constants definition and using TextEncoderConstants.
- Removing redundant GenerateString methods and using TextEncoderTestHelper.
- Renamed variables named temp.
=> Cleaning up text encoder tests code redundancy.

scripts/PerfHarness/PerfHarness.cs, scripts/PerfHarness/PerfHarness.csproj
From https://github.com/dotnet/corefxlab/pull/1481
cc @mgravell, @shiftylogic 
Also, removing System.Buffers.Primitives.Tests from PerfHarness since it no longer contains any benchmark tests.
=> Perf tests must be run as an admin, catch the exception and fail safely

src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8Encoder.cs, tests/System.Text.Primitives.Tests/Encoding/EncodeIntoUtf8Tests.cs
cc @shiftylogic, @jkotas, @KrzysztofCwalina.
Fixes issue #1524 and #1525.
=> Adding span.isempty checks to encoders. Fixes #1524, #1525.

src/System.Buffers.Primitives/System/Buffers/OwnedArray.cs, src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs, src/System.Buffers.Primitives/System/Buffers/ReferenceCountedBuffer.cs, tests/System.Buffers.Primitives.Tests/BufferReferenceTesting.cs, tests/System.Buffers.Primitives.Tests/BufferReferenceTests.cs, tests/System.Buffers.Primitives.Tests/MemoryTests.cs
OwnedBuffer semantics are quite complicated. This PR creates a set of reusable tests that can be run on subclasses of OwnedBuffer to ensure that the subclasses implement OwnedBuffer correctly.
For now:
1. The reference tests are run on OwnedBuffer implementations in System.Text.Primitives and its test project. We should try to run them on implementations in System.IO.Pipelines
2. I just refactored existing tests, but we can add more new tests to the suite.
While developing this change, I discovered two bugs (non-conforming implementations):
1. AsSpan was throwing NullReferenceException, instead of ObjectDisposedException
2. AutoDisposeBuffers was inconsistent in how it implements retain/release
The first issues was trivial to fix.
I fixed the second one by removing Retain from …
=> Added OwnedBuffer reference tests

src/System.Buffers.Primitives/System/Buffers/OwnedArray.cs, src/System.Buffers.Primitives/System/Buffers/ReferenceCountedBuffer.cs, tests/System.Buffers.Primitives.Tests/BufferReferenceTesting.cs, tests/System.Buffers.Primitives.Tests/BufferReferenceTests.cs, tests/System.Buffers.Primitives.Tests/MemoryTests.cs
Added more tests to the reference suite.
Found a couple of bugs and fixed them.
The most interesting observation is that after an ownedbuffer is disposed, the implementations are free to throw any exception type from various operations. I was trying to make the implementation to always throw ObjectDisposedException, but this would result in additional, often duplicative, checks.
@mjp41,  @davidfowl, @ahsonkhan, @shiftylogic,  @joshfree
=> Added more OwnedBuffer reference tests

tests/System.Text.Primitives.Tests/Encoding/EncodeIntoUtf8Tests.cs, tests/System.Text.Primitives.Tests/Encoding/ITextEncoderTest.cs, tests/System.Text.Primitives.Tests/Encoding/TextEncoderTestHelper.cs
Testing combinations of input (0 to 30) and output (0 to 4x input) span sizes for encoding to increase code coverage.
For example, adds coverage for: https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8Encoder.cs#L837-L855
```C#
if (pAllocatedBufferEnd - pTarget <= 0)
goto NeedMore;
```
And:
https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Primitives/System/Text/Encoding/Utf8/Utf8Encoder.cs#L874-L878
```C#
if (ch > HIGH_SURROGATE_END)
{
// low without high -> bad
goto NeedMore;
}                    
```
cc @shiftylogic, @KrzysztofCwalina
=> Adding encoder test to increase coverage.

src/System.IO.Pipelines/Pipe.cs, tests/System.IO.Pipelines.Tests/PipePoolTests.cs
`_commitHead` is last block so when returning multiple blocks comparison with `_readHead` would fail and `_commitHead`  would not be reset.
=> Prevent commit head from being disposed and not reset

src/System.Binary.Base64/System.Binary.Base64.csproj, src/System.Binary.Base64/System/Binary/Base64.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Binary.Base64.Tests/PerformanceTests.cs
**Note:** For Decode, the baseline allocates (hence the large performance difference) since we don't have a non-allocating FromBase64CharArray API to compare against.
cc @KrzysztofCwalina, @shiftylogic 
**To do:**
- Add public static int ComputeDecodedLength(int inputLength)
- Optimize EncodeInPlace
- Optimize DecodeInPlace
- Add more performance & functional tests.
=> Optimize Base64 encode and decode methods

src/System.Binary.Base64/System/Binary/Base64.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/StringFormatter.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Binary.Base64.Tests/PerformanceTests.cs
cc @KrzysztofCwalina, @shiftylogic 
~Partially fixes https://github.com/dotnet/corefxlab/issues/1238 (To do - `Consider changing the APIs to Try`)~
Fixes #1238
Adding error checks so that we can properly handle invalid input came at a perf cost (which is expected). Relative to the baseline, we are still significantly faster (mainly because we don't allocate).
=> Add ComputeDecodedLength and handle invalid input to Decode

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/OwnedBuffer.cs
From PR #1569: https://github.com/dotnet/corefxlab/pull/1569/files
cc @KrzysztofCwalina
=> Fixing typo from PR #1569, adding throw keyword.

src/System.Binary.Base64/System/Binary/Base64Decoder.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Binary.Base64.Tests/PerformanceTests.cs
The performance gain mainly comes from the optimizations that were done for the Decoder **(see https://github.com/dotnet/corefxlab/pull/1586#issue-232772292, and https://github.com/dotnet/corefxlab/pull/1555#issue-229548969)**.
- indexing into the span by ref instead of the indexer (for read and write)
- saving operations on the redundant padding calc/branch
- using an optimized Decode helper function that does fewer bit shift operations
- this change is actually even faster than the previous (relatively speaking) since the previous one wouldn't check for invalid input bytes but this one does
**Open question:**
Should we change the signature of DecodeInPlace to follow Transform?
i.e.
```C#
public TransformationStatus DecodeInPlace(Span<byte> buffer, out int bytesConsumed, out int …
```
=> Fixing DecodeInPlace and optimizing it.

src/System.Buffers.Primitives/System/Internal/ManagedBufferPool.cs, tests/System.Buffers.Primitives.Tests/BufferReferenceTesting.cs
I changed BufferPool's OwnedBuffer to auto-dispose after refcount drops to zero.
When a buffer is renter, its ref count is zero, but unless somebody increments it and then decrements it, the buffer won't be disposed. And so the proper usage is:
```c#
var owned = _pool.Rent();
using(var handle = owned.Buffer.Retain()){
PassToConsumer(owned.Buffer);
} 
...
void PassToConsumer(Buffer<byte> buffer){
_handle = buffer.Retain(); // this needs to be disposed when PassToConsumer is done with the buffer
...
}
```
@davidfowl, @ahsonkhan, @shiftylogic, @joshfree
=> Made BufferPool buffers 'auto-dispose'

src/System.Binary.Base64/System/Binary/Base64.cs, src/System.Binary.Base64/System/Binary/Base64Decoder.cs, src/System.Binary.Base64/System/Binary/Base64Encoder.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Binary.Base64.Tests/PerformanceTests.cs
cc @KrzysztofCwalina. @shiftylogic 
**API shape changed to:**
```C#
namespace System.Binary.Base64 {
public static class Base64 {
public static readonly ITransformation Decoder;
public static readonly ITransformation Encoder;
public static int ComputeDecodedLength(ReadOnlySpan<byte> source);
public static int ComputeEncodedLength(int sourceLength);
public static TransformationStatus Decode(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesConsumed, out int bytesWritten);
public static TransformationStatus DecodeInPlace(Span<byte> buffer, out int bytesConsumed, out int bytesWritten);
public static TransformationStatus Encode(ReadOnlySpan<byte> source, Span<byte> destination, out int bytesConsumed, out int bytesWritten);
public static bool EncodeInPlace(Span<byte> buffer, int …
```
=> Changing Base64 to the public static class model

build.sh, tests/System.Binary.Base64.Tests/BasicUnitTests.cs
Right now the build script exits with 0 (success) even if there are test failures for Linux and OSX.
This change makes sure that the script exits with the right error code (non-zero if test projects failed).
See https://ci.dot.net/job/dotnet_corefxlab/job/master/job/ubuntu16.04_debug_prtest/161/ from https://github.com/dotnet/corefxlab/pull/1554
18:15:51 Test execution time: 7.1188 Seconds
18:15:51 [0;31m** Build failed. 10 projects failed to build or test. **[0m
18:15:51 [0;31m    tests/System.Text.Json.Tests/System.Text.Json.Tests.csproj[0m
18:15:51 [0;31m    tests/System.Text.Http.Parser.Tests/System.Text.Http.Parser.Tests.csproj[0m
18:15:51 [0;31m    tests/System.IO.Pipelines.Tests/System.IO.Pipelines.Tests.csproj[0m
18:15:51 [0;31m …
=> CI should indicate error when test projects fail on linux and mac

build.sh
Clean up changes:
- Double quote to prevent globbing and word splitting [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086).
- The surrounding quotes actually unquote this. Remove or escape them [SC2027](https://github.com/koalaman/shellcheck/wiki/SC2027).
- read without -r mangle backslashes [SC2162](https://github.com/koalaman/shellcheck/wiki/SC2162).
cc @shiftylogic, @KrzysztofCwalina
=> Fixing quotation usage in build script

build.sh, scripts/build.ps1, scripts/install-dotnet.ps1, scripts/install-dotnet.sh
The URLs for pulling down .NET Core installs changed for 2.1. This is PR is preparation for that.
NOTE: This is not strictly necessary right now, but will become necessary to get PR #1554 to pass CI once the CLI issues are fixed.
=> Patching build scripts for new blob storage URLs

src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs, src/System.IO.Pipelines/BufferSegment.cs, src/System.IO.Pipelines/MemoryPool.cs, src/System.IO.Pipelines/MemoryPoolBlock.cs, src/System.IO.Pipelines/System.IO.Pipelines.csproj, src/System.Text.Http.Parser/System.Text.Http.Parser.csproj, tests/System.IO.Pipelines.Tests/MemoryPoolTests.cs, tests/System.IO.Pipelines.Tests/PipeCompletionCallbacksTests.cs, tests/System.IO.Pipelines.Tests/PipePoolTests.cs, tests/System.IO.Pipelines.Tests/PipeResetTests.cs, tests/System.IO.Pipelines.Tests/PipeTest.cs, tests/System.IO.Pipelines.Tests/UnownedBufferReaderFacts.cs
- Assert MemoryPoolBlocks don't get finalized in all debug builds
I found this issue when enabling BLOCK_LEASE_TRACKING and running Kestrel's functional test project.
=> Fix race in BufferSegment and MemoryPoolBlock

src/System.Buffers.Primitives/System/Buffers/Buffer.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs, src/System.Buffers.Primitives/System/Runtime/BufferPrimitivesThrowHelper.cs, tests/System.Buffers.Primitives.Tests/BasicUnitTests.cs, tests/System.Buffers.Primitives.Tests/CtorArray.cs, tests/System.Buffers.Primitives.Tests/CtorArrayReadOnlyBuffer.cs, tests/System.Buffers.Primitives.Tests/SliceReadOnlyBufferTests.cs, tests/System.Buffers.Primitives.Tests/SliceTests.cs, tests/System.Buffers.Primitives.Tests/TestHelpers.cs
- Making `internal Buffer(T[] array, int index, int length)` public
- Adding constructors (similar to Span):
- public Buffer(T[] array)
- public Buffer(T[] array, int start)
- public Buffer(T[] array, int start, int length)
- Adding tests for all scenarios.
- Same with ReadOnlyBuffer\<T\>
=> Adding Buffer<T> constructors that takes an array

src/System.IO.Compression.Brotli/System/IO/Compression/Brotli/BrotliNative.cs, src/System.IO.Compression.Brotli/System/IO/Compression/Brotli/BrotliStream.cs, src/System.IO.Compression.Brotli/System/IO/Compression/Brotli/Decoder.cs, src/System.IO.Compression.Brotli/System/IO/Compression/Brotli/Encoder.cs, src/System.IO.Compression.Brotli/System/Interop/Interop.Brotli.cs, src/System.IO.Compression.Brotli/System/Interop/Library.OSX.cs, src/System.IO.Compression.Brotli/System/Interop/Library.Unix.cs, src/System.IO.Compression.Brotli/System/Interop/Library.Windows.cs, tests/System.IO.Compression.Tests/BrotliPerfomanceTests.cs
The result for static Decompress is awful and I don't understand what can be wrong. 
and to compare with DeflateStream:
As We can see the compress is slower, but decompress is faster (InnerIterationCount = 10000). 
Thus, I should optimize both Compress and Decompress realization and understand why static realizations are so much worse than simple.
=> Br performance test

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/OwnedBuffer.cs, src/System.Binary.Base64/System/Binary/Base64.cs, src/System.Binary.Base64/System/Binary/Base64Decoder.cs, src/System.Binary.Base64/System/Binary/Base64Encoder.cs, src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Buffers.Experimental/System/Buffers/BufferManager.cs, src/System.Buffers.Experimental/System/Buffers/OwnedNativeBuffer.cs, src/System.Buffers.Experimental/System/Buffers/OwnedPinnedBuffer.cs, src/System.Buffers.Primitives/System/Buffers/Buffer.cs, src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs, src/System.Buffers.Primitives/System/Buffers/Transformation.cs, src/System.Buffers.Primitives/System/Internal/ManagedBufferPool.cs, src/System.Buffers.Primitives/System/Internal/OwnedArray.cs, src/System.IO.Pipelines/MemoryPoolBlock.cs, src/System.IO.Pipelines/UnownedBuffer.cs, tests/System.Buffers.Experimental.Tests/MemoryTests.cs, tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs
- TryGetArray(out ArraySegment<byte> buffer) => TryGetArray(out ArraySegment<byte> arraySegment)
- Moving Buffer\<T\> & ReadOnlyBuffer\<T\> to System namespace (from System.Buffers)
- interface ITransformation => abstract class Transformation
cc @shiftylogic, @KrzysztofCwalina
=> Changing ITransformation to abstract class and TryGetArray arg rename

tests/System.IO.Compression.Tests/BrotliPrimitivesTests.cs, tests/System.IO.Compression.Tests/BrotliStreamTests.cs
Filed an issue: https://github.com/dotnet/corefxlab/issues/1611
cc @Vedin, @shiftylogic, @KrzysztofCwalina
=> Skipping brotli tests that are failing in VS.

src/System.Buffers.Primitives/System/Buffers/Buffer.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs, tests/System.Buffers.Primitives.Tests/BufferEqualityTests.cs, tests/System.Buffers.Primitives.Tests/TestHelpers.cs
=> Fixing implementation of Buffers.Equals(obj) and adding tests.

src/System.Text.Primitives/System/Text/Encoding/Internal/ParsingTrie.cs
List.Sort seems to be comparing the same item (as this and other) sometimes during List.Sort
This means that the tie validation logic (which was done in the comparer) could sometimes fail.
This PR moves the validation after the array is sorted with a comparer that never fails.
=> Fixed a small bug in Trie creation logic

tools/dependencies.props
Microsoft.NETCore.Compilers 2.6.0-rdonly-ref-61822-03
This build brings bug fixes and support for ref extension methods -
Ex:   ` public static void Ext(ref this MyStruct self, int arg) `
The corresponding VSIX is at:
https://dotnet.myget.org/F/roslyn/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7-2.6.0.6182203.vsix
Diret link:
https://dotnet.myget.org/F/roslyn/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7-2.6.0.6182203.vsix
=> New toolset compiler

tools/dependencies.props
This will still have all the 7.2 features, but will not match the most recent VSIX
It seems like we brought in a race condition via the last integration and it affects this repo more than any other.
=> downgrading compiler version temporarily

src/System.Text.Primitives/System/Text/Formatting/Internal/TimeFormatter.Utf16.cs, src/System.Text.Primitives/System/Text/Formatting/Internal/TimeFormatter.Utf8.cs, src/System.Text.Primitives/System/Text/Formatting/PrimitiveFormatter.Time.cs, tests/System.Text.Primitives.Tests/Formatting/TimeTests.cs
This format is needed to produce Azure authentication tokens. When the tokens are created, they need lowercase RFC1123 representation of the current time.
=> Added 'l' format to DateTime formatting

src/System.Buffers.Primitives/System/Buffers/Buffer.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs, tests/System.Buffers.Primitives.Tests/BufferEqualityTests.cs
Removing '==' and '!=' operators on Buffer\<T\> and ReadOnlyBuffer\<T\>
=> Removing equality operators on Buffer

tools/dependencies.props
The new version is:
2.6.0-rdonly-ref-61829-12
The difference from the previous one is bug fixes.
The corresponding VSIX is:
https://dotnet.myget.org/F/roslyn/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7-2.6.0.6182912.vsix
=> Updating to a new toolset compiler.

src/System.Text.Formatting.Globalization/System/Text/Formatting/FormattingDataProvider.cs, src/System.Text.Http.Parser/HttpUtilities.cs, src/System.Text.Json/System/Text/Json/JsonWriter.cs, src/System.Text.Primitives/System/Text/Encoding/Encoders.Utf16.cs, src/System.Text.Primitives/System/Text/Encoding/Encoders.Utf32.cs, src/System.Text.Primitives/System/Text/Encoding/Encoders.Utf8.cs, src/System.Text.Primitives/System/Text/Encoding/SymbolTable.Utf16.cs, src/System.Text.Primitives/System/Text/Encoding/SymbolTable.cs, src/System.Text.Primitives/System/Text/Formatting/FloatFormatter.cs, src/System.Text.Utf8String/System/Text/Utf8String.cs, tests/System.Text.Json.Tests/JsonReaderTests.cs, tests/System.Text.Primitives.Tests/Encoding/EncodeIntoUtf8Tests.cs, tests/System.Text.Primitives.Tests/Encoding/Performance/PerfTests.Span.cs, tests/System.Text.Primitives.Tests/Encoding/Utf8EncoderTests.cs, tests/System.Text.Primitives.Tests/Encoding/Utf8Utf16ConversionTests.cs, tests/System.Text.Primitives.Tests/RandomTests.cs, tests/System.Text.Primitives.Tests/TestHelper.cs, tests/System.Text.Utf8String.Tests/RandomTests.cs
* UtfXx.ConvertFromUtfYy => UtfYy.ToUtfXx
* UtfXx.ComputeEncodedBytesFromUtfYy => UtfYy.ToUtfXxLength
* Added UtfXx.FromUtfYy variants that route directly to corresponding UtfYy.ToUtfXx version.
* Filled out the public method header comment blocks on the encoders.
NOTE: None of the implementations changed. They were just shifted around in the 3 encoder implementation files. All other changes are just patching to the new APIs.
@ahsonkhan @KrzysztofCwalina
=> Encoder Design Changes

src/System.IO.Pipelines.Text.Primitives/ReadableBufferExtensions.cs, src/System.Text.Primitives/System/Text/Encoding/Ascii/PrimitiveEncoder_ascii.cs, tests/Benchmarks/GetAsciiStringBench.cs, tests/System.Text.Http.Parser.Tests/HttpParserBasicTests.cs, tests/System.Text.Http.Parser.Tests/HttpParserTests.cs, tests/System.Text.Primitives.Tests/PrimitiveEncoderTests_ascii.cs
Renamed PrimitiveEncoding to Ascii and placed the type in System.Text.Encoders.
cc: @shiftylogic, @ahsonkhan, @joshfree
=> Made Ascii 'encoding' APIs consistent with other encodings

src/System.IO.Pipelines/WritableBuffer.cs
The current implementation often results in very small segments. The new implementation will ensure that segments are never smaller than 256 bytes.
@davidfowl
=> Fixed a bug in the IOutput implementation of WritableBuffer

corefxlab.sln, src/System.Azure.Experimental/System.Azure.Experimental.csproj, src/System.Azure.Experimental/System/Azure/Authentication.cs, src/System.Azure.Experimental/System/Azure/Sha256.Unix.cs, src/System.Azure.Experimental/System/Azure/Sha256.Windows.cs, tests/System.Azure.Experimental.Tests/AuthenticationTests.cs, tests/System.Azure.Experimental.Tests/System.Azure.Experimental.Tests.csproj
This adds a new corfxlab project where we want to experiment with building blocks for Azure SDK.
The initial commit contains an API to general CosmosDB authentication header without allocations.
The currently recommended way to generate the headers is described at https://docs.microsoft.com/en-us/rest/api/documentdb/access-control-on-documentdb-resources
The following is a result of a micro benchmark run comparing the currently recommended methods and the experimental corfxlab API:
| Method            | Mean    | Error      | StdDev   | Scaled | Gen 0 | Allocated |
|-------------------|---------:|----------:|----------:|-------:|-------:|----------:|
| SignatureGenerate | 2.236 us | 0.0009 us | 0.0007 us |   0.36 |      - |       0 B |
| MsdnSample        | 6.292 us | 0.0051 us | 0.0045 …
=> Added System.Azure.Experimental Project

src/System.IO.Compression.Brotli/System.IO.Compression.Brotli.csproj
It would be nice in the `System.IO.Compression.Brotli` library to downgrade .NET Standard version from 1.4 to 1.1. In general, class libraries which target a lower [.NET Platform Standard](https://github.com/dotnet/standard/blob/master/docs/versions.md) version, can be loaded by the largest number of existing platforms. Key libraries are still targeted on .NET Standard 1.1  (e.g., [`System.IO.Compression`](https://www.nuget.org/packages/System.IO.Compression/)).
=> System.IO.Compression.Brotli: .NET Standard 1.4 -> 1.1

src/System.Azure.Experimental/System.Azure.Experimental.csproj, src/System.Azure.Experimental/System/Azure/Authentication.cs, src/System.Text.Encodings.Web.Utf8/System.Text.Encodings.Web.Utf8.csproj, src/System.Text.Encodings.Web.Utf8/UrlEncoder.cs, tests/System.Azure.Experimental.Tests/AuthenticationTests.cs
Made the API resilient to small output buffer size
Also, moved URI encoding to System.Text.Encodings.Web.Utf8
=> GenerateStorageSignature changed to TryWriteStorageSignature

src/System.Azure.Experimental/System.Azure.Experimental.csproj, src/System.Azure.Experimental/System/Azure/Authentication.cs, src/System.Azure.Experimental/System/Azure/CosmosDbAuthorizationHeader.cs, src/System.Azure.Experimental/System/Azure/Key.cs, src/System.Azure.Experimental/System/Azure/StorageAccessSignature.cs, tests/System.Azure.Experimental.Tests/AuthenticationTests.cs
Added CosmosDbAuthorizationHeader implementing IBufferFormattable, which makes it easy to write to various formattable buffers (as one of the tests illustrates).
@joshfree, @ahsonkhan, @shiftylogic
=> Added CosmosDbAuthorizationHeader

docs/specs/priority-queue.md
Modifying the API proposal to reflect the last suggestion by @Joe4evr: *IsEmpty is not a method anymore, but a property*.
Link to the discussion (and specific request for this PR): [#574](https://github.com/dotnet/corefx/issues/574#issuecomment-308609496).
=> Update priority queue proposal (IsEmpty -> property)

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/OwnedBuffer.cs, src/System.Buffers.Experimental/System/Buffers/BufferManager.cs, src/System.Buffers.Experimental/System/Buffers/OwnedNativeBuffer.cs, src/System.Buffers.Experimental/System/Buffers/OwnedPinnedBuffer.cs, src/System.Buffers.Primitives/System/Buffers/Buffer.cs, src/System.Buffers.Primitives/System/Buffers/OwnedBuffer.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs, src/System.Buffers.Primitives/System/Internal/ManagedBufferPool.cs, src/System.Buffers.Primitives/System/Internal/OwnedArray.cs, src/System.IO.Pipelines/MemoryPoolBlock.cs, src/System.IO.Pipelines/UnownedBuffer.cs, tests/System.Buffers.Experimental.Tests/MemoryTests.cs, tests/System.IO.Pipelines.Tests/PipePoolTests.cs, tests/System.IO.Pipelines.Tests/ReadableBufferFacts.cs
Remove offset from OwnedBuffer.Pin
Addresses part of https://github.com/dotnet/corefxlab/issues/1711
cc @davidfowl, @KrzysztofCwalina, @shiftylogic
=> Remove offset from OwnedBuffer.Pin

tests/System.IO.Pipelines.Tests/SocketsFacts.cs, tests/System.IO.Pipelines.Tests/System.IO.Pipelines.Tests.csproj
cc @shiftylogic, @pakrym, @davidfowl 
- Disabling the test on linux - issue #1687 
- Fixing so that previously marked #if Windows tests run on windows.
=> Only run test that are failing on Linux, on Windows and Mac

src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs, tests/System.Text.Primitives.Tests/Parsing/PrimitiveParserIntegerTests.cs
Also remove duplicate test cases
cc @KrzysztofCwalina
=> Remove use of Span ctor(T[], int) which no longer exists

src/System.Text.Http.Parser/HttpParser.cs, src/System.Text.Http.Parser/IHttpParser.cs, src/System.Text.Http/System/Text/Http/Obsolete/HttpHeaderBuffer.cs, src/System.Text.Http/System/Text/Http/Obsolete/HttpRequestParser.cs, src/System.Text.Json/System/Text/Json/JsonReader.cs, tools/dependencies.props
Version 2.6.0-rdonly-ref-62106-01
Now includes:
- support for stackallocated spans and 
- escape analysis to make sure spans that refer to local data do not outlive the referenced data.
The corresponding VSIX is at 
https://dotnet.myget.org/feed/roslyn/package/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7/2.6.0.6210601
=> Updating to new toolset compiler.

src/System.Numerics.Tensors/System.Numerics.Tensors.csproj, src/System.Numerics.Tensors/System.Numerics.Tensors.sln, src/System.Numerics.Tensors/System/Numerics/ArrayUtilities.cs, src/System.Numerics.Tensors/System/Numerics/DenseTensor.cs, src/System.Numerics.Tensors/System/Numerics/SparseTensor.cs, src/System.Numerics.Tensors/System/Numerics/Tensor.Operations.cs, src/System.Numerics.Tensors/System/Numerics/Tensor.Operations.tt, src/System.Numerics.Tensors/System/Numerics/Tensor.cs, src/System.Numerics.Tensors/System/Numerics/TensorArithmetic.cs, src/System.Numerics.Tensors/System/Numerics/TensorArithmetic.tt, src/System.Numerics.Tensors/System/Numerics/TensorTemplate.ttinclude, tests/System.Numerics.Tensors.Tests/TensorTests.cs
This is a large refactoring of the tensors library to support different layouts.
Right now this library is still a work-in-progress, but this moves us closer to the feature set we want to have in the prototype.
The old tensor type became DenseTensor and I've created a basic SparseTensor which uses the dictionary-of-keys (DOK) storage that's convenient for building out a sparse tensor.
=> Add sparse tensors

src/System.Binary/System/Binary/BufferReader.cs, src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs
Kestrel actually treats this a fatal build break which makes it
annoying to copy code over for testing.
Then again, so does corefx...
=> Fix some ill-formatted XML comments.

src/System.IO.Pipelines.Extensions/Gate.cs
[MulticastDelegate.Equals](https://github.com/dotnet/coreclr/blob/888b7a94f7b684f988110b9f0b8f3f6ea49746e1/src/mscorlib/src/System/MulticastDelegate.cs#L57-L132) is a chunky non-inlinable function to call just to test for reference equality
=> Use ReferenceEquals not Equals for delegate ref equals

src/System.Azure.Experimental/System/Azure/CosmosDbAuthorizationHeader.cs, src/System.Azure.Experimental/System/Azure/Key.cs, src/System.Azure.Experimental/System/Azure/StorageAccessSignature.cs, src/System.Binary.Base64/System/Binary/Base64.cs, src/System.Binary.Base64/System/Binary/Base64Decoder.cs, src/System.Binary.Base64/System/Binary/Base64Encoder.cs, src/System.Buffers.Primitives/System/Buffers/BufferDecoder.cs, src/System.Buffers.Primitives/System/Buffers/BufferEncoder.cs, src/System.Buffers.Primitives/System/Buffers/Transformation.cs, tests/System.Binary.Base64.Tests/Base64TestHelper.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Binary.Base64.Tests/PerformanceTests.cs
The new APIs are as follows:
```c#
public static class Base64 {
public static readonly BufferDecoder Utf8ToBytesDecoder;
public static readonly BufferEncoder BytesToUtf8Encoder;
public static OperationStatus BytesToUtf8(ReadOnlySpan<byte> bytes, Span<byte> utf8, out int consumed, out int written);
public static OperationStatus BytesToUtf8InPlace(Span<byte> buffer, int bytesLength, out int written);
public static int BytesToUtf8Length(int bytesLength);
public static OperationStatus Utf8ToBytes(ReadOnlySpan<byte> utf8, Span<byte> bytes, out int consumed, out int written);
public static OperationStatus Utf8ToBytesInPlace(Span<byte> buffer, out int consumed, out int written);
public static int Utf8ToBytesLength(ReadOnlySpan<byte> utf8);
}
```
@ahsonkhan, @shiftylogic, @terrajobst, @joshfree
=> Changing Base64 APIs to follow same pattern as text encoders

tools/dependencies.props
- minor bug fixes
- recent merge from Roslyn master   
- should be running on 2.0 
The corresponding VSIX is:  
https://dotnet.myget.org/F/roslyn/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7-2.6.0.6211106.vsix
=> Updating toolset compiler.

src/System.Text.Http.Parser/HttpParser.cs
This is part of converging the Kestrel and CoreFxLab
parsers. Kestrel expects this information for logging
and also expects it to be pay-for-play.
=> Add detailed parse error strings.

src/System.Numerics.Tensors/System.Numerics.Tensors.csproj, src/System.Numerics.Tensors/System/Numerics/CompressedSparseTensor.cs, src/System.Numerics.Tensors/System/Numerics/DenseTensor.cs, src/System.Numerics.Tensors/System/Numerics/SparseTensor.cs, src/System.Numerics.Tensors/System/Numerics/Tensor.cs, src/System.Numerics.Tensors/System/Numerics/TensorArithmetic.cs, src/System.Numerics.Tensors/System/Numerics/TensorArithmetic.tt, tests/System.Numerics.Tensors.Tests/TensorTests.cs
Adds a layout for CompressedSparseTensors supporting both CSR and CSC formats.
/cc @mellinoe
=> Add compressed sparse tensor layout

src/System.Threading.Tasks.Channels/System/Threading/Tasks/Channels/ReadableChannel.cs
Fix for issue #1761
Avoid removing the observer when channel is being completed.
=> Don't remove observer when the channel is completed

src/System.Text.Primitives/System/Text/Formatters/Utf16.cs, src/System.Text.Primitives/System/Text/Formatters/Utf8.cs, tests/System.Text.Primitives.Tests/Formatting/BooleanTests.cs, tests/System.Text.Primitives.Tests/Formatting/FloatTests.cs
The implementation is quite naive; we will improve it overtime. Getting this particular overload to be fast/non-allocating is not lower priority. I filed #1765 to track this.
cc: @ahsonkhan, @joshfree, @shiftylogic
=> Added Decimal formatting

src/System.Text.Http.Parser/HttpParser.cs, tests/System.Text.Http.Parser.Tests/HttpParserTests.cs, tests/System.Text.Http.Parser.Tests/System.Text.Http.Parser.Tests.csproj
This migrates over this fix here:
https://github.com/aspnet/KestrelHttpServer/commit/547ad80a272c94861453ae50daaa5f9addb0cc8f
and addresses the last test failure from the Kestrel ingestion
experiment:
ParseRequestLineSplitBufferWithoutNewLineDoesNotUpdateConsumed()
=> Port over fix for ParseRequestLineSplit...DoesNotUpdateConsumed() test

scripts/package.ps1
The nuget.exe at the previous url is really old (2.8.60717.93) and package publishing is failing incorrectly due to "File contains corrupted data." error.
This updates the nuget.exe to a newer version.
Also added an exit code check and the -NoNewWindow flag so that logs can be visible and the CI will catch the failures in the future.
cc @dagood, @shiftylogic, @KrzysztofCwalina
=> Update to new nuget.exe and add logging and process exit code check.

scripts/PerfHarness/PerfHarness.csproj, src/System.Binary/System/Binary/BufferReader_BE.cs, src/System.Binary/System/Binary/BufferReader_LE.cs, src/System.Binary/System/Binary/BufferWriter.cs, src/System.Binary/System/Binary/UnsafeUtilities.cs, tests/System.Binary.Tests/BufferReaderTests.cs, tests/System.Binary.Tests/BufferWriterTests.cs
Related to: https://github.com/dotnet/corefx/issues/24144#issuecomment-330638602
> - BigEndian/LittleEndian the T should be constrained to our single value primitive types, perhaps just use an overload for each of those instead of a T. 
- Adding safe ReverseEndianness primitive APIs to UnsafeUtilities (should move to helper class)
- Adding non-generic {Try}ReadBE & LE and {Try}WriteBE & LE
- Removed generic TryReadBE & LE and TryWriteBE & LE
- Fixed implementation of ReverseEndianness to no longer use Unsafe.Write and Unsafe.Read which improves performance significantly:
**Note:** Piplines uses the generic [ReadBE & LE and WriteBE & LE](https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines.Extensions/ReadWriteExtensions.cs#L39). Should we move them there?
cc @davidfowl …
=> Adding non-generic {Try}Read/Write BE & LE methods

src/System.Binary/System/Binary/BufferReader.cs, src/System.Binary/System/Binary/BufferReader_BE.cs, src/System.Binary/System/Binary/BufferReader_LE.cs, src/System.Binary/System/Binary/BufferWriter.cs, src/System.Binary/System/Binary/UnsafeUtilities.cs, src/System.IO.Pipelines.Extensions/ReadWriteExtensions.cs
The generic reads don't work for types other than basic ints. For example, it does not make sense to reverse a multi field struct.
Also, I added public Reverse per API review suggestion from @stephentoub 
@ahsonkhan, @joshfree, @shiftylogic, @stephentoub, @davidfowl
=> Removed Generic ReadLE/BE methods

src/System.Text.Http.Parser/HttpParser.cs, src/System.Text.Http.Parser/IHttpParser.cs, src/System.Text.Json/System/Text/Json/JsonReader.cs
"ref readonly" is the only variant that will be supported once we switch to the new toolset compiler.
We had two ways to express the same thing, some people find it confusing, so support for "in" is being removed.
=> replace "in" with "ref readonly"

scripts/package.ps1
This fix resolves the recent nightly build failures due to error in pushing packages  of the same version.
> Response status code does not indicate success: 409 (The package could not be uploaded. The package "BrotliNative 0.0.1" already exists. Overwriting existing packages is forbidden according to the package retention settings for this feed.).
The rest of the packages get published as expected.
For now, the "Creating NuGet packages from nuspec." step is unnecessary (since we only have Brotli nuspec in the external directory), but I decided to keep the scaffolding for future additions.
cc @dotnet/corefxlab-contrib
=> Skipping the packaging (and hence pushing) of BrotliNative.

scripts/update-dependencies.ps1
The update-dependencies project requires Microsoft.NETCore.App 2.0.0.
The build task that creates PRs to update our dependencies was failing otherwise.
Alternatively, we could target netcoreapp2.1 instead:
https://github.com/dotnet/corefxlab/blob/master/scripts/update-dependencies/update-dependencies.csproj#L5
2017-09-18T18:41:21.9077388Z   Restore completed in 3.07 sec for E:\A\_work\1261\s\scripts\update-dependencies\update-dependencies.csproj.
2017-09-18T18:41:21.9546151Z Invoking App E:\A\_work\1261\s\scripts\update-dependencies\update-dependencies.csproj...
2017-09-18T18:41:26.4553981Z It was not possible to find any compatible framework version
2017-09-18T18:41:26.4553981Z The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
2017-09-18T18:41:26.4553981Z …
=> Installing 2.0.0 version of the shared framework for update dependencies

tests/System.Text.Http.Parser.Tests/System.Text.Http.Parser.Tests.csproj
Since nuget apparently needs me to do its job for it,
I'll add the package references to humor it so I can
do a --self-contained "dotnet publish" without the
scads of NU1605 errors.
=> Fix errors on selfcontained publish on HttpParser tests.

tests/System.Text.Primitives.Tests/System.Text.Primitives.Tests.csproj
At least nuget has an excuse for missing this one - this
is an assembly that's loaded by Reflection inside the bowels
of xunit. Not that I plan to run benchmarks in the self-contained
setup but without this, you can't even skip the benchmark
tests since xunit.performance.execution.dll is the one
that contains the Discoverer class that tells you
that [Benchmark] is a "Benchmark" trait.
=> Add missing PackageReference to System.Text.Primitives.Tests

tools/dependencies.props
new toolset compiler - 2.6.0-beta1-62126-01
This was a "special" build, so there is no public VSIX for this.
The old one should be ok, for most scenarios.
When `VS 15.5 preview1` is available it will match this compiler feature-wise by default.
=> New toolset compiler - 2.6.0-beta1-62126-01

src/System.Binary/System/Binary/BufferReader.cs, src/System.IO.Pipelines.Extensions/ReadWriteExtensions.cs
Notes from System.Binary API review:
1)	Add Reverse overload for byte & sbyte (which is a no-op).
- This is a no-op and added only for consistency. This allows the caller to read a struct of numeric primitives and reverse each field rather than having to skip byte/sbyte fields.
2)	Remove the generic Reverse API. **Edit**: Moved to Pipelines ReadWriteExtensions
3)	The rest of the APIs are fine to move to corefx as is to System.Buffers dll (and namespace)
cc @dotnet/corefxlab-contrib, @pakrym, @davidfowl
=> Removing the generic Reverse API and adding no-op byte overloads.

tests/System.Text.Http.Parser.Tests/System.Text.Http.Parser.Tests.csproj, tests/System.Text.Primitives.Tests/System.Text.Primitives.Tests.csproj
Reverting https://github.com/dotnet/corefxlab/pull/1780 & https://github.com/dotnet/corefxlab/pull/1788.
These recent changes are causing NuGet warnings during build:
D:\GitHub\Fork\corefxlab\tests\System.Text.Primitives.Tests\System.Text.Primitives.Tests.csproj : warning NU1604: Project dependency System.IO.FileSystem does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.
D:\GitHub\Fork\corefxlab\tests\System.Text.Primitives.Tests\System.Text.Primitives.Tests.csproj : warning NU1701: Package 'System.IO.FileSystem 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project. …
=> Fixing NU1701 and NU1604 build warnings caused by recent changes

src/System.Numerics.Tensors/System/Numerics/CompressedSparseTensor.cs, src/System.Numerics.Tensors/System/Numerics/DenseTensor.cs, src/System.Numerics.Tensors/System/Numerics/SparseTensor.cs, src/System.Numerics.Tensors/System/Numerics/Tensor.cs, tests/System.Numerics.Tensors.Tests/TensorTests.cs
Tensor represents a multi-dimensional API over something that's backed by single dimensional
data (memory).  Most implementations deal in the single-dimension and need to convert to
it (and back) often.  To avoid this add single-dimensional accessors and prefer them.
/cc @eerhardt
=> Add single-dimensional accessors to Tensor

tests/System.Text.Primitives.Tests/Parsing/PrimitiveParserIntegerTests.cs
Finally took the time to track down why a test exercising
these high performance apis was taking so much longer
than any other test.
I don't think parsing a 2gb long string is a common enough
scenario to justify a 28,000% tax on every test cycle.
Regressions are caught much faster when people are incented
to run tests regularly.
=> Cut STP.Tests run time from 2.33 minutes to 0.5 seconds

.gitignore, build.sh, scripts/build.ps1, scripts/update-dependencies.ps1, src/System.IO.Pipelines.Extensions/ReadWriteExtensions.cs
Temporary workaround for https://github.com/dotnet/corefx/issues/24402 (related: https://github.com/dotnet/cli/issues/7726)
- Renaming the folder from dotnet to dotnetcli (following corefx).
- Making generic Reverse API private (since it is not used anywhere else).
This will unblock:
https://github.com/dotnet/corefxlab/pull/1787
> Failure to restore a package: Failed to restore packages.
@dotnet/corefxlab-contrib
=> Rename dotnet folder to dotnet cli to workaround corefx #24402

tests/System.Text.Http.Parser.Tests/System.Text.Http.Parser.Tests.csproj, tests/System.Text.Primitives.Tests/System.Text.Primitives.Tests.csproj, tests/System.Threading.Tasks.Channels.Tests/System.Threading.Tasks.Channels.Tests.csproj
Correct was to update the property name to reflect
the rename in 0d8bd06a84a0d1987cc6e3a229042a356564a3cf.
=> Reapply selfcontained publishing fixes.

docs/roadmap.md, docs/specs/encoding.md, docs/specs/memory.md, docs/specs/nativesized.md, docs/specs/parsing.md, docs/specs/pipelines-io.md, docs/specs/priority-queue.md, docs/specs/span.md, docs/workitems.md
I was reading through the documentation and noticed a few misspelled words.  Fixed them as I noticed them.  Thanks for the great documentation.  Please let me know if I can help in any other way.
=> Documentation naming fixes, spelling fixes, line length standardization.

src/System.Binary.Base64/System/Binary/Base64Decoder.cs, src/System.Binary.Base64/System/Binary/Base64Encoder.cs, tests/System.IO.Pipelines.Performance.Tests/Enumerators.cs, tests/System.IO.Pipelines.Performance.Tests/PipeThroughput.cs, tests/System.IO.Pipelines.Performance.Tests/ReadCursorOperationsThroughput.cs
cc @pakrym, @dotnet/corefxlab-contrib
=> Remove obsolete Base64 APIs and use new BenchmarkDotNet attribute

src/System.Text.Http.Parser/HttpParser.cs, src/System.Text.Http.Parser/IHttpParser.cs, src/System.Text.Json/System/Text/Json/JsonReader.cs, src/System.Text.Utf8String/System/Text/Utf8String.cs, tools/dependencies.props
This brings support for the final syntax of "ref readonly" and some bug fixes.
Noticeable changes:
- use `in` at declaration of "in" parameters, not `ref readonly`
- `ref` comes before `partial` when declaring partial ref structs.
- unboxing conversions for ref-like types are statically rejected as impossible to succeed
The corresponding VSIX to match these compiler bits with IDE experience is -
https://dotnet.myget.org/F/roslyn/vsix/0b48e25b-9903-4d8b-ad39-d4cca196e3c7-2.6.0.6221102.vsix
=> Switching to the new toolset compiler - 2.6.0-beta2-62211-02

src/System.Numerics.Tensors/System.Numerics.Tensors.csproj, src/System.Numerics.Tensors/System.Numerics.Tensors.sln
We don't actually use Buffers.Primitives now that Memory (previously Buffer) has been moved into System.Memory.
=> Tensors should only depend on System.Memory (not Buffers.Primitives)

src/System.Binary.Base64/System.Binary.Base64.csproj, src/System.Binary.Base64/System/Binary/Base64Encoder.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Binary.Base64.Tests/PerformanceTests.cs
Related to https://github.com/dotnet/corefx/issues/24568
The new BytesToUtf8 API that takes in a ParsedFormat was added as a proof of concept to showcase that an encoder with line break capabilities can be built on top of the existing API.
cc @dotnet/corefxlab-contrib
=> Add Base64 encoder with ParsedFormat and isFinalBlock bool

src/System.Azure.Experimental/System/Azure/CosmosDbAuthorizationHeader.cs, src/System.Azure.Experimental/System/Azure/Sha256.Unix.cs, src/System.Azure.Experimental/System/Azure/Sha256.Windows.cs, src/System.Azure.Experimental/System/Azure/StorageAccessSignature.cs, src/System.Text.Primitives/System/Buffers/IWritable.cs
I am working on a prototype of self-advancing reader/writer APIs. 
This is just a preparatory work:
1. Adds IWritable interface similar to IBufferFormattable that allows custom types to write themselves to buffers as binary data.
2. Sha256 is an example of such self-writable type.
3. Changed Sha256 so it can write to buffers of equal or larger size. Before this PR the buffer had to be exact size.
CC: @ahsonkhan, @GrabYourPitchforks, @joshfree
=> Preparing APIs for Span ReaderWriter

src/System.Binary.Base64/System/Binary/Base64Decoder.cs, src/System.Binary.Base64/System/Binary/Base64Encoder.cs, src/System.Buffers.Primitives/System/Buffers/BufferDecoder.cs, src/System.Buffers.Primitives/System/Buffers/BufferEncoder.cs, src/System.Buffers.Primitives/System/Buffers/Transformation.cs, src/System.Text.Encodings.Web.Utf8/Utf8BufferEncoder.cs, tests/System.Text.Encodings.Web.Utf8.Tests/UnescapeUrlPathInPlaceTests.cs
The idea is that Writer.Write method can take in IBufferTransformation to additional transform the date being written.  For example, the following code writes Base64 encoded hash to a buffer:
```c#
Span<byte> buffer = stackalloc byte[256];
var writer = new Utf8SpanWriter(buffer);
Sha256 hash = Sha256.Create(key, data);
writer.Write(hash, Base64.Encoder); // the encoder implements IBufferTransformation
```
CC: @joshfree, @ahsonkhan, @GrabYourPitchforks
=> Added an abstraction for in-place transformations

build.sh, scripts/build.ps1
This will override the global install of the dotnet cli and use the repo-specific version.
See https://github.com/dotnet/corefx/issues/24698#issuecomment-337794414 for more info.
cc @dotnet/corefxlab-contrib
=> Set the DOTNET_MULTILEVEL_LOOKUP env variable in the build script.

scripts/PerfHarness/run.bat, src/System.Azure.Experimental/System.Azure.Experimental.csproj, src/System.Azure.Experimental/System/Azure/CosmosDbAuthorizationHeader.cs, src/System.Buffers.Experimental/System/Buffers/SpanWriter.cs, src/System.Text.Primitives/System/Text/Encoders/Ascii/Ascii_casing.cs, tests/Benchmarks/AzureBench.cs, tests/Benchmarks/Benchmarks.csproj, tests/System.Azure.Experimental.Tests/AuthenticationTests.cs
Added a prototype of byref SpanWriter and rewrote CosmosDB authentication token generation routine using the new writer (see CosmosDbAuthorizationHeader.TryWrite2). The rewritten routine is much much simpler and the perfromance regression is pretty much insignificant (2% in instructions retired; no detectable change in time elapsed). 
Note that CosmosDbAuthorizationHeader.TryWrite2 is 3x faster than the [MSDN prescribed way of generating the header](https://docs.microsoft.com/en-us/rest/api/documentdb/access-control-on-documentdb-resources). Also, it does not allocate any GC heap memory; MSDN routine allocates 2KB per header.
See the following benchmark results. "Raw" is [the complicated generation routine using low level primitive …
=> Added SpanWriter

src/System.Threading.Tasks.Channels/README.md, src/System.Threading.Tasks.Channels/System/IO/Channels/BoundedChannel.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/BoundedChannelFullMode.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/Channel.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/ChannelClosedException.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/ChannelOptions.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/ChannelReader.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/ChannelUtilities.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/ChannelWriter.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/Channel_1.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/Channel_2.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/IDebugEnumerator.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/Interactor.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/SingleConsumerUnboundedChannel.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/UnboundedChannel.cs, src/System.Threading.Tasks.Channels/System/IO/Channels/UnbufferedChannel.cs, tests/System.Threading.Tasks.Channels.Tests/BoundedChannelTests.cs, tests/System.Threading.Tasks.Channels.Tests/ChannelClosedExceptionTests.cs, tests/System.Threading.Tasks.Channels.Tests/ChannelTestBase.cs, tests/System.Threading.Tasks.Channels.Tests/ChannelTests.cs, tests/System.Threading.Tasks.Channels.Tests/TestBase.cs, tests/System.Threading.Tasks.Channels.Tests/TestExtensions.cs, tests/System.Threading.Tasks.Channels.Tests/UnboundedChannelTests.cs, tests/System.Threading.Tasks.Channels.Tests/UnbufferedChannelTests.cs
Just changing the namespace (again).
=> Rename System.IO.Channels to System.Threading.Channels

src/System.Binary.Base64/System/Binary/Base64Decoder.cs, src/System.Binary.Base64/System/Binary/Base64Encoder.cs, src/System.Buffers.Primitives/System/Buffers/Transformation.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Binary.Base64.Tests/PerformanceTests.cs
Made some changes to the Base64 APIs based on https://github.com/dotnet/corefx/issues/24568#issuecomment-338833370.
Also updated DecodeFromUtf8InPlace to take in `dataLength` as arg and no longer return `out consumed`. This also means it will never return NeedsMoreData.
**Note:**
Since our IBufferOperation hasn't been updated to include isFinalBlock (along with the encoder/decoders that implement it), I have disabled the Pipe test.
cc @KrzysztofCwalina, @GrabYourPitchforks
=> Update Base64 impl to support isFinalBlock = false

samples/QotdService/Program.cs, src/System.Text.Http/System/Text/Http/Obsolete/HttpHeaders.cs, src/System.Text.Http/System/Text/Http/Obsolete/HttpRequestParser.cs, src/System.Text.Json.Dynamic/System/Text/Json/JsonDynamicObject.cs, src/System.Text.Json/System/Text/Json/JsonParser.cs, src/System.Text.Primitives/System/Text/Encoders/Unicode/Unicode.cs, src/System.Text.Utf8String/System/Text/Utf8Helper.cs, src/System.Text.Utf8String/System/Text/Utf8Span.cs, src/System.Text.Utf8String/System/Text/Utf8String.cs, tests/System.Text.Http.Tests/GivenAnHttpHeaders.cs, tests/System.Text.Utf8String.Tests/TestHelper.cs, tests/System.Text.Utf8String.Tests/Utf8Span.RandomTests.cs, tests/System.Text.Utf8String.Tests/Utf8String.RandomTests.cs
More cleanup. Mainly, I removed methods that operate on code units, streamlined Utf8String implementations by delegating to Utf8Span, and optimized some methods, e.g. ToString, LastIndexOf
cc: @ahsonkhan, @GrabYourPitchforks, @joshfree, @ianhays
=> More Utf8Span/String cleanup

src/System.Azure.Experimental/System/Azure/CosmosDbAuthorizationHeader.cs, src/System.Azure.Experimental/System/Azure/StorageAccessSignature.cs, src/System.Buffers.Experimental/System/Buffers/SpanWriter.cs, src/System.Text.Primitives/System/Text/Encoders/Ascii/Ascii_casing.cs, tests/System.Buffers.Experimental.Tests/SpanWriterTests.cs, tests/System.Buffers.Experimental.Tests/System.Buffers.Experimental.Tests.csproj
I added the ability to pass multiple transformations when writing to SpanWriter, e.g.
```c#
ReadOnlySpan<IBufferTransformation> transformations = ...
var writer = new SpanWriter(buffer);
writer.Write("Hello", default, transformations);
```
@ahsonkhan, @joshfree, @GrabYourPitchforks
=> SpanWriter now supports multiple transformations

scripts/package.ps1
Related to https://github.com/dotnet/corefxlab/pull/1866
This will override the global install of the dotnet cli and use the repo-specific version.
See https://github.com/dotnet/corefx/issues/24698#issuecomment-337794414 for more info.
cc @dotnet/corefxlab-contrib
=> Set the DOTNET_MULTILEVEL_LOOKUP env variable in the package script

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/OwnedBuffer.cs, src/System.Buffers.Experimental/System/Buffers/BytesReader.cs, src/System.Buffers.Experimental/System/Buffers/IReadOnlyBufferList.cs, src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs, src/System.Text.Http/System/Text/Http/HttpRequest.cs, tests/System.Buffers.Experimental.Tests/BytesReader.cs, tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs
In addition changed the ReadOnlyBytes.Length to long.
cc: @ahsonkhan, @pakrym, @davidfowl
The current perf results (from HttpParserBench) are even better (30% better). I think the main difference is from less cache misses as in ReadOnlyBytes data is more localized (less references to follow to get to the first segment)
Test Name                         | Metric                                        | Iterations |    AVERAGE 
:--------------------------------- |:--------------------------------------------- |:----------:| ----------: 
HttpParserBench.FullRequestRb     | Duration                                      |    100     |     17.497
HttpParserBench.FullRequestRb     | Instructions Retired                          |    100     | 1.391E+008
HttpParserBench.FullRequestRb     | Branch …
=> Added always available Length to ReadOnlyBytes

scripts/PerfHarness/README.md, tools/dependencies.props
We get capabilities to collect new metrics (and customize which metrics we want to see) with the latest package of xunit.performance.
Example:
> --perf:collect default+BranchMispredictions+CacheMisses+InstructionRetired+gcapi
cc @jorive, @KrzysztofCwalina
=> Update xunit.perf to newer version and update README

src/System.Time/System/Date.cs
Uses the three-part `GetDatePart` function, copied from the `System.DateTime` implementation in coreclr.
=> Improve perf of Date.AddMonths

src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs, tests/Benchmarks/HttpParserBench.cs
Added benchmarks measuring the performance of calling int based ROB parser APIs and then translating the into to cursors. 
here are the perf results:
Benchmark                       | Metric               | Unit  |    Average 
:------------------------------------- |:-------------------- |:-----:| ----------:
HttpParserBench.FullRequestRb         | Duration             | msec  |     12.503 
HttpParserBench.FullRequestRb         | Instructions Retired | count | 1.446E+008 
HttpParserBench.FullRequestRb         | Cache Misses         | count |   7331.840 
HttpParserBench.FullRequestRob        | Duration             | msec  |      8.324 
HttpParserBench.FullRequestRob        | Instructions Retired | count | 1.058E+008 
HttpParserBench.FullRequestRob        | Cache Misses         | count | …
=> Added HTTP parser benchmarks simulating parsing with cursors

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/BufferSequence.cs, samples/LowAllocationWebServer/LowAllocationWebServerLibrary/ReadWriteBytes.cs, src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Buffers.Experimental/System/Buffers/ReadOnlyBytes.cs, src/System.Collections.Sequences/System.Collections.Sequences.csproj, src/System.Collections.Sequences/System/Collections/Sequences/ArrayList.cs, src/System.Collections.Sequences/System/Collections/Sequences/Position.cs, src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs, src/System.Collections.Sequences/System/Collections/Sequences/SequenceEnumerator.cs, src/System.IO.Pipelines.Extensions/ReadableBufferSequence.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/SequenceFormatter.cs, src/System.Text.Http.Parser/HttpParser.cs, tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs, tests/System.Collections.Sequences.Tests/BasicUnitTests.cs, tests/System.Collections.Sequences.Tests/SampleCollections/Hashtable.cs, tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs
Common usage examples:
1. Calling ISequence\<T\>
```c#
ISequence<T> collection = ...
Position position = default;
while (collection.TryGet(ref position, out int item)) {
Console.WriteLine(item);
}
```
2. Array-based data structure implementation, e.g. [ResizableArray\<T\>](https://github.com/dotnet/corefxlab/blob/master/src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs#L107)
```c#
public bool TryGet(ref Position position, out T item, bool advance = true)
{
int index = (int)position;
if (index < _count) {
item = _array[index];
if (advance) { position += 1; }
return true;
}
item = default;
position = Position.End;
return false;
}
```
3. Linked List implementation, e.g. [LinkedContainer\<T\>](https://github.com/dotnet/corefxlab/blob/master/tests/System.Collection …
=> Finished Position Cleanup

tools/dependencies.props
Updating to the latest Roslyn as a pre-stage test to putting this version in dotnet/buildtools.
=> Update Roslyn to 2.6.0-beta3-62316-02

src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadOnlyBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadWriteBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/SequenceExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Text/BytesReader.cs, tests/System.Buffers.Experimental.Tests/SequenceExtensionsTests.cs
This adds the ability to parse ints out of memory sequences. There are two overloads: one returns number of consumed bytes, the other returns a Position of the first unconsumed byte. The later overload is not optimized, but for now I just wanted to validate that there are no fundamental issues with the representation of memory sequences when it comes to parsing. I will measure perf and optimize the methods in a subsequent PR.
cc: @davidfowl, @halter73, @terrajobst, @ahsonkhan
=> Added Sequence TryParseInt32

src/System.Buffers.Experimental/System/Buffers/Sequences/ReadOnlyBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/SequenceExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Text/BytesReader.cs, src/System.Collections.Sequences/System/Collections/Sequences/Position.cs, tests/Benchmarks/BytesReaderBench.cs, tests/System.Buffers.Experimental.Tests/BytesReaderTests.cs, tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs
+ lots of API changes to BytesReader to:
1. Make it work with arbitrary sequences
2. Make it Position based, as opposed to index based
@ahsonkhan, @davidfowl
Note: there is lots of NYI code paths (and probably bugs). I just want to first get the model to a stable state before I implement all the code paths.
=> Changed BytesReader to a by-ref struct

src/System.Buffers.Experimental/System/Buffers/Text/BytesReader.cs, tests/Benchmarks/BytesReaderBench.cs, tests/System.Buffers.Experimental.Tests/BytesReaderTests.cs
I also added perf tests comparing BytesReader to raw Utf8Formatter and to ReadableBufferReader (raw APIs). All three are in the same ballpark, which is good! ... especially considering that BytesReader is doing an additional check that it important for parsing straddling buffers.
Benchmarks.dll                                  | Metric               | Unit  | Average 
:----------------------------------------------- |:-------------------- |:-----:|----------:
BytesReaderBench.ParseInt32BytesReader          | Duration             | msec  |      1.056 
BytesReaderBench.ParseInt32BytesReader          | Instructions Retired | count | 1.495E+007 
BytesReaderBench.ParseInt32BytesReader          | Cache Misses         | count |   1478.656 
BytesReaderBench.ParseInt32ReadableBufferReader | …
=> Added BytesReader.TryRead(out int)

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/BufferSequence.cs, samples/LowAllocationWebServer/LowAllocationWebServerLibrary/HttpServer.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/MemoryList.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadOnlyBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadWriteBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/SequenceExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Text/BytesReader.cs, src/System.Collections.Sequences/System/Collections/Sequences/Position.cs, src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs, src/System.IO.Pipelines.Extensions/ReadableBufferSequence.cs, src/System.Text.Http.Parser/HttpParser.cs, tests/Benchmarks/BytesReaderBench.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Buffers.Experimental.Tests/BytesReaderTests.cs, tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs, tests/System.Buffers.Experimental.Tests/SequenceExtensionsTests.cs, tests/System.Collections.Sequences.Tests/SampleCollections/Hashtable.cs, tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs, tests/System.Text.Http.Parser.Tests/HttpParserBasicTests.cs
1. Changed representation of ```ReadOnlyBytes``` and ```ReadWriteBytes``` to a representation that can store either ```byte[]```, or ```IMemoryList<byte>```, or ```OwnedMemory<byte>``` (to be implemented).
2. Made ```Position``` immutable.
```ReadOnlyBytes._start``` is now either ```IMemoryList<byte>```, or ```byte[]```, or ```OwnedMemory<byte>```.
if ```_start``` is ```byte[]``` or ```OwnedMemory<byte>```, ```_startIndex``` is the lower (inclusive) index, and the ```_endIndex``` is the upper (exclusive) index of a single segment buffer. Otherwise, ```_start``` is the first ```IMemoryList```, ```_end``` is the last ```IMemoryList``` of potentially multi-segment buffer.
Note, that there are some NotImplementedExceptions in this code. We will be unifying ReadOnlyBytes with ReadableBuffer …
=> ReadOnlyBytes based on "cursors"

samples/System.IO.Pipelines.Samples/Libuv/RawLibuvHttpClientSample.cs, samples/System.IO.Pipelines.Samples/Rio/RawRioHttpClientSample.cs, samples/System.IO.Pipelines.Samples/Rio/RioHttpServer.cs, samples/System.IO.Pipelines.Samples/SampleBase/RawHttpClientSampleBase.cs, samples/System.IO.Pipelines.Samples/Socket/RawSocketHttpClientSample.cs, samples/System.IO.Pipelines.Samples/Socket/SocketHttpClientHandler.cs, samples/System.IO.Pipelines.Samples/Socket/SocketHttpServer.cs, src/System.Buffers.Experimental/System/Buffers/Native/NativeMemoryPool.cs, src/System.Buffers.Primitives/System/Buffers/Pooling/ArrayMemoryPool.cs, src/System.Buffers.Primitives/System/Buffers/Pooling/MemoryPool.cs, src/System.IO.Pipelines.Networking.Libuv/UvThread.cs, src/System.IO.Pipelines.Networking.Sockets/SocketConnection.cs, src/System.IO.Pipelines.Networking.Sockets/SocketListener.cs, src/System.IO.Pipelines.Networking.Windows.RIO/Internal/Pool/MemoryPool.cs, src/System.IO.Pipelines.Networking.Windows.RIO/Internal/Pool/MemoryPoolBlock.cs, src/System.IO.Pipelines.Networking.Windows.RIO/Internal/Pool/MemoryPoolSlab.cs, src/System.IO.Pipelines.Networking.Windows.RIO/Internal/Pool/PipelinesThrowHelper.cs, src/System.IO.Pipelines.Networking.Windows.RIO/Internal/Pool/SpanLiteralExtensions.cs, src/System.IO.Pipelines.Networking.Windows.RIO/Internal/RioThread.cs, src/System.IO.Pipelines/System/Buffers/MemoryPool.cs, src/System.IO.Pipelines/System/Buffers/MemoryPoolBlock.cs, src/System.IO.Pipelines/System/Buffers/MemoryPoolSlab.cs, src/System.IO.Pipelines/System/IO/Pipelines/Pipe.cs, src/System.IO.Pipelines/System/IO/Pipelines/PipeOptions.cs, tests/Benchmarks/Helpers/Listener.cs, tests/System.IO.Pipelines.Extensions.Tests/PipelineReaderWriterFacts.cs, tests/System.IO.Pipelines.Extensions.Tests/ReadableBufferFacts.cs
This is an experiment in making pipelines pooling into a true abstraction, i.e. pipelines use MemoryPool<byte> instead of MemoryPool concrete class. The only usage of the concrete class is to create the default instances.
@davidfowl, @pakrym, @ahsonkhan, any thoughts?
=> Pipelines Pool Abstraction

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/BufferSequence.cs, src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/MemoryList.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadOnlyBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadWriteBytes.cs, src/System.Buffers.Primitives/System/Collections/IMemoryList.cs, src/System.IO.Pipelines/System/IO/Pipelines/BufferSegment.cs, src/System.IO.Pipelines/System/IO/Pipelines/ReadCursorOperations.cs, src/System.IO.Pipelines/System/IO/Pipelines/ReadableBuffer.cs, tests/System.Buffers.Experimental.Tests/SequenceExtensionsTests.cs
- Renamed Rest to Next
- Removed interfaces it extended
- Removed CopyTo
- Updated pipelines to use this (shared) interface
@pakrym, @ahsonkhan, @joshfree
=> Changed IMemoryList based on Pipelines API Review

src/System.Buffers.Experimental/System/Range.cs, tests/System.Buffers.Experimental.Tests/RangeTests.cs
I added some helpers and overrode ToString to make it easier to work with ranges.
Renamed Last to End as "Last" is confusing given the value is exclusive.
@ahsonkhan, @joshfree, @eerhardt, @jcouv
=> Added IsValid, Bind, and BindToValid. Renamed Last to End

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/TcpConnectionFormatter.cs, src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Text/BufferWriter_sequence.cs, src/System.Buffers.Primitives/System/Buffers/IOutput.cs, src/System.Collections.Sequences/System/Collections/Sequences/Position.cs, src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs, src/System.IO.Pipelines.Extensions/WritableBufferOutput.cs, src/System.IO.Pipelines.Text.Primitives/PipelineTextOutput.cs, src/System.Text.Formatting/System/Text/Formatting/CompositeFormat.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/ArrayFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/OutputFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/SequenceFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/StreamFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/StringFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/IOutputExtensions.cs, src/System.Text.Formatting/System/Text/Formatting/ITextOutputExtensions.cs, src/System.Text.Http/System/Text/Http/IFormatterHttpExtensions.cs, src/System.Text.Json/System/Text/Json/JsonWriter.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Buffers.Experimental.Tests/BufferWriterTests_sequence.cs
cc: @pakrym, @davidfowl, @joshfree, @ahsonkhan 
Changing IOutput.Span to GetSpan to communicate that repeatedly getting the span might be expensive.
=> Cleaned up IOutput based on API review

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/BufferSequence.cs, src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/MemoryList.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadOnlyBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadWriteBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/SequenceExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Text/BufferReader.cs, src/System.Collections.Sequences/System/Collections/Sequences/Position.cs, src/System.IO.Pipelines.Extensions/ReadableBufferSequence.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/SequenceFormatter.cs, src/System.Text.Http.Parser/HttpParser.cs, tests/Benchmarks/HttpParserBench.cs, tests/System.Buffers.Experimental.Tests/BytesReaderTests.cs, tests/System.Buffers.Experimental.Tests/ReadOnlyBytesTests.cs, tests/System.Buffers.Experimental.Tests/SequenceExtensionsTests.cs, tests/System.Collections.Sequences.Tests/SampleCollections/Hashtable.cs, tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs, tests/System.IO.Pipelines.Extensions.Tests/ReadableBufferFacts.cs, tests/System.Text.Http.Parser.Tests/HttpParserBasicTests.cs
cc: @pakrym, @davidfowl, @joshfree, @ahsonkhan 
When sequences move to end default(Position) is returned from TryGet
Before calling ISequence<T>.TryGet for the first time, the calling code has to call ISequence<T>.First, as default position no longer mean the first item (necessarily)
APIs like buffer.PositionOf(byte value) return Position? (nullable). They return null if value is not found
All these changes were requested by @pakrym to allow him to use Position in pipelines instead of ReadCursor.
=> Removed Position.End

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/BufferSequence.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/MemoryList.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadOnlyBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadWriteBytes.cs, src/System.Buffers.Experimental/System/Buffers/Text/BufferReader.cs, src/System.Collections.Sequences/System/Collections/Sequences/Position.cs, src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs, tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs
cc: @pakrym, @joshfree, @davidfowl
=> Simplified Position API

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/TcpServer.cs, samples/System.Numerics.Tensors.Samples/TensorSamples/Access.cs, samples/System.Numerics.Tensors.Samples/TensorSamples/MutateSparse.cs, samples/System.Numerics.Tensors.Samples/TensorSamples/PreAllocate.cs, samples/System.Numerics.Tensors.Samples/TensorSamples/ReversePInvoke.cs, samples/System.Numerics.Tensors.Samples/TensorSamples/WrapNativeMemory.cs, src/System.Azure.Experimental/System/Azure/Sha256.Windows.cs, src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Text/BufferWriter_sequence.cs, src/System.IO.Compression.Brotli/System/IO/Compression/Brotli.cs, src/System.IO.Pipelines.File/FileReader.cs, src/System.IO.Pipelines.Text.Primitives/ReadableBufferExtensions.cs, src/System.IO.Pipelines/System/IO/Pipelines/WritableBufferWriter.cs, src/System.Net.Libuv/System/Net/Libuv/Stream.cs, src/System.Text.Http.Parser/HttpParser.cs, src/System.Text.Http.Parser/HttpUtilities.cs, src/System.Text.Json/System/Text/Json/JsonReader.cs, src/System.Text.Json/System/Text/Json/JsonWriter.cs, src/System.Text.Primitives/System/Text/Encoders/Ascii/Ascii_encoding.cs, src/System.Text.Primitives/System/Text/Encoders/Utf16.cs, src/System.Text.Primitives/System/Text/Encoders/Utf32.cs, src/System.Text.Primitives/System/Text/Encoders/Utf8.cs, src/System.Text.Primitives/System/Text/Encoders/Utf8Util.Validation.cs, src/System.Text.Primitives/System/Text/Formatters/Utf16Formatter_guid.cs, src/System.Text.Primitives/System/Text/Formatters/Utf16Formatter_ints.cs, src/System.Text.Primitives/System/Text/Formatters/Utf16Formatter_time.cs, src/System.Text.Primitives/System/Text/SymbolTable/SymbolTable_utf16.cs, tests/System.IO.Pipelines.Extensions.Tests/ReadableBufferFacts.cs
**Part of:**
https://github.com/dotnet/corefx/issues/25412
https://github.com/dotnet/corefx/issues/25615
**Depends on the following to go through first:**
https://github.com/dotnet/corefx/pull/25961 (and subsequent consumption of CoreFx libraries in CoreFxLab)
> Cannot use method 'MemoryMarshal.GetReference<byte>(ReadOnlySpan<byte>)' as a ref or out value because it is a readonly variable
I didn't find any uses of DangerousTryGetArray to remove.
Following the staging plan from here: https://github.com/dotnet/corefx/issues/23881#issuecomment-343767740
Doing it this way will avoid the need for complex staging or things being on the floor for extensive periods of time.
cc @jkotas, @stephentoub, @KrzysztofCwalina, @davidfowl, @pakrym, @joshfree, @eerhardt
=> Remove use of DangerousGetPinnableReference and use Memory.GetReference instead

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/BufferSequence.cs, src/System.Buffers.Experimental/System/Buffers/BufferExtensions.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/BufferList.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadOnlyBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadWriteBytes.cs, src/System.Buffers.Primitives/System/Buffers/OutputWriter.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer_helpers.cs, src/System.Buffers.Primitives/System/Collections/IBufferList.cs, src/System.IO.Pipelines.Extensions/DefaultReadableBufferExtensions.cs, src/System.IO.Pipelines/System/IO/Pipelines/BufferSegment.cs, src/System.Text.Http.Parser/HttpParser.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Buffers.Experimental.Tests/BytesReaderTests.cs, tests/System.Buffers.Experimental.Tests/SequenceExtensionsTests.cs, tests/System.Buffers.Primitives.Tests/BufferSegment.cs, tests/System.Buffers.Primitives.Tests/BufferUtilities.cs, tests/System.Buffers.Primitives.Tests/ReadOnlyBufferFactory.cs, tests/System.Buffers.Primitives.Tests/ReadableBufferFacts.cs, tests/System.Buffers.Primitives.Tests/ReadableBufferReaderFacts.cs, tests/System.IO.Pipelines.Performance.Tests/PipeThroughput.cs, tests/System.IO.Pipelines.Performance.Tests/ReadCursorOperationsThroughput.cs, tests/System.IO.Pipelines.Tests/BackpressureTests.cs, tests/System.IO.Pipelines.Tests/PipelineReaderWriterFacts.cs, tests/System.IO.Pipelines.Tests/SeekTests.cs, tests/System.IO.Pipelines.Tests/WritableBufferWriterFacts.cs, tests/System.Text.Http.Parser.Tests/HttpParserBasicTests.cs
1. Make `ReadOnlyBuffer(Position, Position)` private.
2. Rename `IMemoryList<T>` to `IBufferList`.
3. Remove `CreatePosition` from `Enumerable`.
4. Remove multi-byte seek methods
5. Rename `Seek` to `PositionOf` and change signature.
6. Rename `Move` to `Seek`
7. Add `ReadOnlyBuffer(IEnumerable<Memory<byte>>)` constructor
=> Another set of API review changes

src/System.IO.Pipelines/System/IO/Pipelines/Pipe.cs, src/System.IO.Pipelines/System/IO/Pipelines/PipeOptions.cs, tests/System.IO.Pipelines.Tests/PipePoolTests.cs
So it can work with pools that return exact buffer size that was requested.
=> Add MinimumSegmentSize

src/System.Buffers.Experimental/System/Buffers/Sequences/ReadOnlyBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/ReadWriteBytes.cs, src/System.Buffers.Experimental/System/Buffers/Sequences/SequenceExtensions.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBufferReader.cs, src/System.Buffers.Primitives/System/Buffers/ReadOnlyBuffer_helpers.cs, src/System.Buffers.Primitives/System/Collections/ISequence.cs, src/System.Buffers.Primitives/System/Collections/Position.cs, src/System.Collections.Sequences/System/Collections/Sequences/ArrayList.cs, src/System.Collections.Sequences/System/Collections/Sequences/ResizableArray.cs, src/System.IO.Pipelines.Extensions/ReadableBufferSequence.cs, src/System.IO.Pipelines/System/IO/Pipelines/Pipe.cs, tests/System.Collections.Sequences.Tests/SampleCollections/Hashtable.cs, tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs
=> Removed operator+ from Position

src/System.Buffers.Experimental/System/Buffers/Sequences/ReadOnlyBytes.cs, src/System.Buffers.Primitives/System/Collections/Position.cs, tests/System.Collections.Sequences.Tests/SampleCollections/LinkedContainer.cs
@pakrym, @davidfowl, @terrajobst, @joshfree, @ahsonkhan
=> Removed Position.Get

src/System.IO.Pipelines.Networking.Sockets/SocketConnection.cs, src/System.IO.Pipelines/System.IO.Pipelines.csproj, src/System.IO.Pipelines/System/Threading/InlineScheduler.cs, src/System.IO.Pipelines/System/Threading/Scheduler.cs, src/System.IO.Pipelines/System/Threading/TaskRunScheduler.cs, src/System.IO.Pipelines/System/Threading/ThreadPoolScheduler.cs
Scheduler Devirtualization
* Seal internal types `TaskRunScheduler` and `InlineScheduler`
* Maintain shared `TaskRunScheduler` and `InlineScheduler` in derived typed members; rather than base type
* Expose via base type property that will devirtualize on inlining when the Jit sees the derived types (as type is maintained above, and derived type is sealed) https://github.com/dotnet/coreclr/pull/15766
Resolves: https://github.com/dotnet/corefxlab/issues/2027
Fast Fire-and-Forget Tasks for `TaskRunScheduler`
* Queue directly to `ThreadPool`; when available, rather than have the extra overhead of a `Task` which is ignored.
* On netcoreapp2.1 use `QueueUserWorkItem(preferLocal: true)` which is lower contention and more closely matches `Task` behaviour dotnet/corefx#12442
* If the `Action` …
=> Scheduler improvements

src/System.Text.Primitives/System/Text/Encoders/Utf8Validator.cs, tests/System.Text.Primitives.Tests/Encoding/Utf8UtilTests.Validation.cs, tests/System.Text.Primitives.Tests/Encoding/Utf8ValidatorTests.cs, tests/System.Text.Primitives.Tests/TestHelper.cs
Introduces a type that can perform streaming validation of UTF-8 byte sequences. This is intended to be a drop-in replacement for existing streaming validators such as the one that exists at https://github.com/dotnet/corefx/blob/5617d3996c8cb1c3d3332f6c03dd5f3bf785623f/src/System.Net.WebSockets/src/System/Net/WebSockets/ManagedWebSocket.cs#L1326. This type also demonstrates how some of the primitives (such as inspecting the first sequence or getting the index of the first invalid sequence) hanging off of `Utf8Utility` can be used.
The type is currently a mutable struct, 4 bytes in length. This should provide respectable performance on all platforms and avoids allocations. Alternative designs can be considered if it's too difficult to consume this type.
=> Add streaming UTF8 validator

src/System.IO.Pipelines/System/Threading/Scheduler.cs
Seeing how these fields are `private` and are not mutated, they can be `readonly`.
=> Make scheduler private fields readonly

src/System.Text.Primitives/System/Text/Formatters/Utf16Formatter_time.cs
This test was consistently failing on my Mac when I tried to repro the memory corruption. My Mac ended up with non-standard timezone offset somehow. This code was not handling non-standard timezone offsets correctly. I have just copied the logic from matching productized corefx utf8 formatter.
=> Fix date formatting

src/System.Buffers.Experimental/System/Buffers/Native/NativeMemoryPool.cs, src/System.IO.Pipelines.Networking.Windows.RIO/Internal/Pool/MemoryPool.cs, src/System.IO.Pipelines/System/Buffers/MemoryPool.cs
Leftover change from https://github.com/dotnet/corefxlab/pull/2086/files#r164603501
=> Using a private constant for the minimumBufferSize to indicate use default

src/System.Azure.Experimental/System/Azure/Key.cs, src/System.Azure.Experimental/System/Azure/StorageAccessSignature.cs, src/System.Buffers.Experimental/RemoveTranstomation.cs, src/System.Buffers.Experimental/System/Buffers/Text/BufferWriter_ints.cs, src/System.Text.Http.Parser/HttpParser.cs, src/System.Text.Http.Parser/IHttpResponseLineHandler.cs, src/System.Text.Http/System.Text.Http.csproj, src/System.Text.Http/System/Text/Http/BufferWriterHttpExtensions.cs
These are dependencies needed by AzCopy sample. I will add tests in a subsequent PR.
=> Added some APIs needed by my AzCopy Sample

samples/AzCopyCore/AzCopyCore.sln, samples/AzCopyCore/AzCopyCore/AzCopyCore.csproj, samples/AzCopyCore/AzCopyCore/Program.cs, samples/AzCopyCore/AzCopyCore/SocketClient.cs, samples/AzCopyCore/AzCopyCore/StorageClient.cs, samples/AzCopyCore/AzCopyCore/StorageRequests.cs, samples/AzCopyCore/AzCopyCore/temp/Extensions.cs
@joshfree, @davidfowl, @JeffreyRichter, @ahsonkhan, @shiftylogic, @terrajobst, @davidsh, @stephentoub, @rmkerr 
@Davidsh, @rmkerr, you might want to take a look how this sample avoids lots of allocations during requests and responses, e.g. only headers the code cares about are parsed. Of course, the programming model is not as convinient as HttpClient, but if you want to optimize as the cost of usability, such API might be quite nice. See ```StorageResponse``` struct for details. Similarly, headers writing (in request) is done with close to zero allocations, see ```GetFileRequest``` struct.
=> AzCopy-like sample using non-allocating APIs and pipelines

tests/System.IO.Pipelines.Extensions.Tests/SocketsFacts.cs
Testing to see if these tests still fail on linux.
See:
https://github.com/dotnet/corefxlab/issues/1533#issuecomment-363945987
https://github.com/dotnet/corefxlab/issues/1687
cc @pakrym, @davidfowl
=> Re-enabling SocketFacts tests on linux

src/System.Numerics.Tensors/System/Numerics/Tensor.cs, src/System.Text.Http.Parser/HttpParser.cs, tests/System.Numerics.Tensors.Tests/TensorSliceTests.cs
Leftover changes from https://github.com/dotnet/corefxlab/pull/2111 to address the feedback.
cc @davidfowl, @eerhardt
=> Add null check to Tensor indexer and change which ToSpan method to call.

src/System.Buffers.Primitives/System/Buffers/OutputWriter.cs, tests/System.IO.Pipelines.Tests/PipeWriterTests.cs
Currently every Write and Advance call makes a virtual call to Pipe and also Slices the underlining Memory; mostly defeating the purpose of using the Span.
This leads to the explosion of calls to `BufferSegment.set_End` via virtual `Advance` from writing output headers (once per name, once per value):
Change to only Advance when `Commit()` is called or the Span runs out of space. 
`Commit()` must be called after a set of Writing to "flush" (Advance) any buffered data to pipe
/cc @davidfowl
=> Reduce OutputWriter's virtual calls and Memory slicing

tests/System.IO.Pipelines.Extensions.Tests/ReadableBufferFacts.cs, tests/System.Text.Http.Parser.Tests/HttpParserBasicTests.cs
Re-enable the tests that were disabled in https://github.com/dotnet/corefxlab/pull/2142.
cc @davidfowl, @benaadams, @pakrym
=> Re-enable previously disabled tests since there was a package update

src/System.Buffers.ReaderWriter/System/Buffers/Writer/BufferWriter_writable.cs, tests/System.Buffers.ReaderWriter.Tests/BasicUnitTests.cs
@ahsonkhan reported that AzCopyCore does not work on newer versions of our packages. I debugged the issue and found the culprit. The BufferWriter.WriteBytes overload that takes Memory and a transformation was not properly transforming the written bytes.
=> Bug fix in BufferWriter

samples/AzCopyCore/AzCopyCore/AzCopyCore.csproj, samples/AzCopyCore/AzCopyCore/Helpers/CommandLine.cs, samples/AzCopyCore/AzCopyCore/HttpClient.cs, samples/AzCopyCore/AzCopyCore/Program.cs, samples/AzCopyCore/AzCopyCore/SocketPipe.cs, samples/AzCopyCore/AzCopyCore/StorageClient.cs, samples/AzCopyCore/AzCopyCore/StorageRequests.cs
- updated the sample to new packages and runtime
- refactored HTTP code into a separate wrapper for IDuplexPipe
- small resulting renames
=> AzCopyCore updates

samples/AzCopyCore/AzCopyCore/Program.cs, samples/AzCopyCore/AzCopyCore/SocketPipe.cs
cc @KrzysztofCwalina 
- Saves 4832 bytes of allocation when processing 100 files.
- Cleaned up the logging, otherwise, the console was getting flooded with empty lines.
FYI, with the recent CoreRT package update, the natively compiled exe is throwing an exception at run-time:
```text
Unhandled Exception: System.InvalidOperationException: Cannot call Set on a null context
at AzCopyCore!<BaseAddress>+0x13e749
at AzCopyCore!<BaseAddress>+0x13deb7
at AzCopyCore!<BaseAddress>+0x13d89f
```
=> Use Path.Join to avoid allocations and fix logging.

tests/System.IO.Pipelines.Extensions.Tests/WritableBufferFacts.cs
Because defaults were added.
https://github.com/dotnet/corefxlab/issues/2157
=> Reenable tests that were hitting unexpected backpressure

src/System.Text.Formatting/System/Text/Formatting/Formatters/ArrayFormatter.cs
Regression observed in JsonWriter performance test: https://github.com/dotnet/corefxlab/pull/2254
**The following PR caused the regression:** https://github.com/dotnet/corefxlab/pull/2047 / https://github.com/dotnet/corefxlab/commit/4bf5f6a527c109c888a78ff8b2593ee631f33126 - Jan 17, 2018
Was there a particular reason we went through `Memory<byte>` to get the span? I am now getting the Span directly. If this is correct, we should make similar changes to all implementations of ITextBufferWriter (for example [BufferWriterFormatter](https://github.com/dotnet/corefxlab/blob/master/src/System.Text.Formatting/System/Text/Formatting/Formatters/BufferWriterFormatter.cs#L10)).
This change improves JsonWriter performance by roughly 70% (before - 115 ms, after - 67 ms).
cc @pakrym, @KrzysztofCwalina, …
=> Fix ITextBufferWriter performance regression: ArrayFormatter.GetSpan should not go through GetMemory

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/TcpConnectionFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/BufferWriterFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/SequenceFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/StreamFormatter.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/StringFormatter.cs, tests/System.Binary.Base64.Tests/BasicUnitTests.cs, tests/System.Buffers.Experimental.Tests/BufferWriterTests_sequence.cs
Related PR: https://github.com/dotnet/corefxlab/pull/2255
cc @pakrym, @KrzysztofCwalina, @davidfowl, @JeremyKuhne
=> Fix IBufferWriter: GetSpan should not go through GetMemory

tests/Benchmarks/System.Text.Utf8/Utf8StringPerf.cs
This re-introduces the descriptive strings to the benchmark tests. Also cleaned up the enumeration test to make sure the JIT can't optimize away the enumerator.
=> Clean up Utf8StringPerf benchmark

tests/Benchmarks/Program.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs
Added StringReader based test and making it the baseline since that is a more fair comparison (for UTF-16 input). The StringReader is faster than StreamReader. Keeping the StreamReader based test (which is slower) since that is required for UTF-8 encoded input.
Comparing to the StringReader, JsonLab is 2-3x faster instead of 4x shown previously (when compared to StreamReader).
cc @KrzysztofCwalina, @joshfree
=> Add back Serializer Benchmarks and update JsonReaderPerf tests to use StringReader

src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, tests/Benchmarks/JsonStrings.Designer.cs, tests/Benchmarks/JsonStrings.resx, tests/Benchmarks/System.Text.JsonLab/Comparison/JsonReader/JsonReaderComparison.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs, tests/System.Text.JsonLab.Tests/Resources/TestJson.Designer.cs, tests/System.Text.JsonLab.Tests/Resources/TestJson.resx, tests/System.Text.JsonLab.Tests/System.Text.JsonLab.Tests.csproj
**See the raw results here:** https://gist.github.com/ahsonkhan/4f8dbb517e701e84c2f6d1385afff2e1
**Conclusions:**
- JsonLab Reader is 2.5-3.7x faster than Json.NET Reader, in general, across the board.
- JsonLab Reader is better at reading UTF-8 than UTF-16 when compared to Json.NET Reader (Json.NET is forced to use StreamReader which is slower than StringReader)
- When returning a copy of the data, JsonLab Reader allocates 1.1x of the input json size for UTF-8 and 2.2x for UTF-16. Json.NET Reader ends up allocating 6-7x of the input json size for both UTF-8 and UTF-16 (32 bytes more in the case of UTF-16 due to the allocation of a new StringReader).
**EmptyLoop just goes through the entire json using each reader, without accessing any value or token:**
```C#
public void …
```
=>  Add JsonReaderTests and update benchmarks with different json string inputs.

tests/Benchmarks/Benchmarks.csproj, tests/Benchmarks/System.Text.JsonLab/Comparison/JsonDeserializer/JsonDeserializerComparison_FromString.cs, tests/Benchmarks/System.Text.JsonLab/Comparison/JsonReader/JsonReaderComparison.cs, tests/Benchmarks/System.Text.JsonLab/Comparison/JsonSerializer/JsonSerializerComparison_ToString.cs
- Added Reference to nuget package.
- Added Utf16 Version to Serializer and Deserializer Comparison. I postfixed the name with Utf16 as this is consistent with my own tests and it's easier to add an Utf8 version later.
- Added both Utf8/Utf16 versions to JsonReaderComparison.
Benchmark results are in #2288 and below
<details>
**JsonReaderComparison**
``` ini
BenchmarkDotNet=v0.10.14.534-nightly, OS=Windows 10.0.17134
Intel Core i7-4790K CPU 4.00GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
Frequency=3906248 Hz, Resolution=256.0001 ns, Timer=TSC
.NET Core SDK=2.1.300-rtm-008823
[Host]     : .NET Core 2.1.0-rtm-26509-04 (CoreCLR 4.6.26509.03, CoreFX 4.6.26509.03), 64bit RyuJIT
DefaultJob : .NET Core 2.1.0-rtm-26509-04 (CoreCLR 4.6.26509.03, CoreFX 4.6.26509.03), 64bit RyuJIT
```
| …
=> Add SpanJson to Benchmarks

tools/common.props, tools/dependencies.props
Also includes a workaround where latest netcore compiler doesn't work in VS, use the one built in to VS instead if compiling from the IDE. I've confirmed that command-line build continues to work correctly, and we can now build and run tests from within VS2017 using the latest language features.
This PR replaces https://github.com/dotnet/corefxlab/pull/2161.
@agocke, we also tried the below props, but it resulted in errors at build time (only within the IDE).
```xml
<ItemGroup Condition="'$(MSBuildRuntimeType)' == 'Core'">
<PackageReference Include="Microsoft.NETCore.Compilers" Version="$(RoslynVersion)" PrivateAssets="All" />
</ItemGroup>
<ItemGroup Condition="'$(MSBuildRuntimeType)' == 'Full'">
<PackageReference Include="Microsoft.Net.Compilers" Version="$(RoslynVersion)" …
```
=> Update Roslyn compiler to latest, language version to latest

src/System.Buffers.ReaderWriter/System/Buffers/Writer/BufferWriter_writable.cs, tools/common.props
Leftover change from https://github.com/dotnet/corefxlab/pull/2161
=> Remove unnecessary cast now that we are targeting C# 7.3 with latest compiler

src/System.Buffers.Experimental/System/Range.cs, tests/Benchmarks/System/RangeEnumeration.cs, tests/Benchmarks/System/RangePerf.cs
Addresses #2312 
Not sure there's much more to do here.
The results:
``` ini
BenchmarkDotNet=v0.10.14.534-nightly, OS=Windows 10.0.16299.431 (1709/FallCreatorsUpdate/Redstone3)
Intel Core i7-7600U CPU 2.80GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
Frequency=2835936 Hz, Resolution=352.6173 ns, Timer=TSC
.NET Core SDK=2.1.300
[Host]     : .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT
DefaultJob : .NET Core 2.1.0 (CoreCLR 4.6.26515.07, CoreFX 4.6.26515.06), 64bit RyuJIT
```
|      Method | Length |         Mean |       Error |      StdDev |
|------------ |------- |-------------:|------------:|------------:|
| **Enumeration** |     **10** |     **21.23 ns** |   **0.0559 ns** |   **0.0496 ns** |
| **Enumeration** |    **100** |    **199.84 ns** | …
=> Add a benchmark for Range enumeration

tests/Benchmarks/System.Buffers.Experimental/RangeEnumeration.cs
Related to https://github.com/dotnet/corefxlab/pull/2336.
Also added regular `for loop` baseline.
``` ini
BenchmarkDotNet=v0.10.14.534-nightly, OS=Windows 10.0.16299.431 (1709/FallCreatorsUpdate/Redstone3)
Intel Xeon CPU E5-1620 v2 3.70GHz, 1 CPU, 8 logical and 4 physical cores
Frequency=3604597 Hz, Resolution=277.4235 ns, Timer=TSC
.NET Core SDK=2.2.100-preview1-008958
[Host]     : .NET Core 2.1.0-rtm-26515-03 (CoreCLR 4.6.26515.03, CoreFX 4.6.26515.03), 64bit RyuJIT
DefaultJob : .NET Core 2.1.0-rtm-26515-03 (CoreCLR 4.6.26515.03, CoreFX 4.6.26515.03), 64bit RyuJIT
```
|           Method | Length |          Mean |       Error |      StdDev | Scaled | ScaledSD |
|----------------- |------- |--------------:|------------:|------------:|-------:|---------:|
|   **RegularForLoop** | …
=> Move RangeEnumeration benchmark to appropriate folder.

src/System.Buffers.ReaderWriter/System/Buffers/Writer/BufferWriterT.cs, src/System.Buffers.ReaderWriter/System/Buffers/Writer/BufferWriterT_strings.cs, src/System.Text.Formatting/System/Text/Formatting/Formatters/ArrayFormatter.cs, src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs, src/System.Text.JsonLab/System/Text/Json/JsonWriterHelper.cs, tests/Benchmarks/System.Text.JsonLab/JsonWriterPerf.cs, tests/System.Text.JsonLab.Tests/JsonWriterTests.cs
- Add `BufferWriter.Write(byte)`
- General code clean up (use of var, explicitly add private keyword, etc.).
- Move static fields and methods to their own helper class.
- Add ArrayOnly performance test.
cc @JeremyKuhne, @adamsitnik 
Establishing a clean base-line for future changes:
``` ini
BenchmarkDotNet=v0.10.14.534-nightly, OS=Windows 10.0.14393.2312 (1607/AnniversaryUpdate/Redstone1)
Frequency=3328123 Hz, Resolution=300.4697 ns, Timer=TSC
.NET Core SDK=2.2.100-preview1-009015
[Host]     : .NET Core 2.2.0-preview1-26609-02 (CoreCLR 4.6.26606.04, CoreFX 4.6.26606.04), 64bit RyuJIT
Job-UYYLEA : .NET Core 2.2.0-preview1-26609-02 (CoreCLR 4.6.26606.04, CoreFX 4.6.26606.04), 64bit RyuJIT
InvocationCount=32768 …
```
=> Move statics to a separate class and add JsonWriter perf test.

samples/LowAllocationWebServer/Shared/SampleServer.cs, src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs, tests/Benchmarks/System.IO.Pipelines/E2E.cs, tests/Benchmarks/System.Text.JsonLab/JsonWriterPerf.cs, tests/System.Text.JsonLab.Tests/JsonWriterTests.cs
**TODO:** Add helper factory convenience methods.
Related previous PRs: https://github.com/dotnet/corefxlab/pull/2358 / https://github.com/dotnet/corefxlab/pull/2366 / https://github.com/dotnet/corefxlab/pull/2369
**I want to isolate changes and make them one at a time only. The previous PRs introduced BufferWriter/etc. which makes analysis more difficult.**
I measured the following implementations of `IBufferWriter<byte>`:
- class (ArrayFormatter)
- struct (make ArrayFormatter a struct)
- struct wrapper around a class (ArrayFormatterWrapper)
**Conclusion:**
If JsonWriter is generic, and `IBufferWriter<byte>` is implemented as a struct wrapper around a class, we get the best performance (~10% improvement compared to non-generic JsonWriter where `IBufferWriter<byte>` is a class, and ~25% …
=> Make JsonWriter generic to avoid struct boxing

samples/LowAllocationWebServer/Shared/SampleServer.cs, src/System.Buffers.ReaderWriter/System/Buffers/Writer/BufferWriterT.cs, src/System.Buffers.ReaderWriter/System/Buffers/Writer/BufferWriterT_strings.cs, src/System.Text.JsonLab/System.Text.JsonLab.csproj, src/System.Text.JsonLab/System/Text/Json/JsonThrowHelper.cs, src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs, tests/Benchmarks/Benchmarks.csproj, tests/Benchmarks/System.IO.Pipelines/E2E.cs, tests/Benchmarks/System.Text.JsonLab/JsonWriterPerf.cs, tests/System.Buffers.ReaderWriter.Tests/BasicUnitTests.cs, tests/System.Text.JsonLab.Tests/JsonWriterTests.cs
Borrows most of the changes from https://github.com/dotnet/corefxlab/pull/2366, and supersedes https://github.com/dotnet/corefxlab/pull/2358
- Utilizing BufferWriter to cache the span being written to and add the Flush method.
- Keeping a single type for now, as it will only support UTF-8 (will remove UTF-16 support later).
- Reducing the JsonWriter struct size by utilizing the highest bit of _indent for _firstItem bool.
- Fix typo in BufferWriter.Write(byte)
**TODO:** Add helper factory convenience methods.
**Let me know if I missed anything. Any suggestions to reduce the overhead further are welcome :)**
- ~10% regression for hello world (overhead of creating BufferWriter and no benefit from caching the span)
- ~7% improvement for writing larger json payload, say 10-50 elements …
=>  Cache the span by using BufferWriter<T> within JsonWriter<T>

tests/Benchmarks/System.Text.JsonLab/JsonWriterPerf.cs
``` ini
BenchmarkDotNet=v0.10.14.534-nightly, OS=Windows 10.0.14393.2312 (1607/AnniversaryUpdate/Redstone1)
Frequency=3328126 Hz, Resolution=300.4694 ns, Timer=TSC
.NET Core SDK=2.1.301
[Host]     : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
DefaultJob : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
```
|                         Method | Formatted | size |         Mean |      Error |     StdDev |       Median |  Gen 0 | Allocated |
|------------------------------- |---------- |----- |-------------:|-----------:|-----------:|-------------:|-------:|----------:|
|  **WriterSystemTextJsonArrayOnly** |     **False** |    **1** |     **75.61 ns** | …
=>  Add UTf8Json library to JsonWriter performance benchmarks

src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs, src/System.Text.JsonLab/System/Text/Json/JsonWriterHelper.cs, tests/Benchmarks/System.Text.JsonLab/JsonWriterPerf.cs
``` ini
BenchmarkDotNet=v0.10.14.534-nightly, OS=Windows 10.0.14393.2312 (1607/AnniversaryUpdate/Redstone1)
Frequency=3328126 Hz, Resolution=300.4694 ns, Timer=TSC
.NET Core SDK=2.1.301
[Host]     : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
DefaultJob : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
```
**BEFORE (master):**
|                         Method | Formatted | size |         Mean |       Error |      StdDev | Allocated |
|------------------------------- |---------- |----- |-------------:|------------:|------------:|----------:|
|  **WriterSystemTextJsonArrayOnly** |     **False** |    **1** |     **72.55 ns** |   **0.8945 ns** |   **0.7469 …
=> Optimize JsonWriter APIs by using the TryWrite approach

tests/Benchmarks/System.IO.Pipelines/E2E.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs, tests/Benchmarks/System.Text.JsonLab/JsonWriterPerf.cs, tools/dependencies.props
Also, fixed typo in benchmark from https://github.com/dotnet/corefxlab/pull/2378.
=> Update version of BenchmarkDotNet to consume latest fixes

tests/Benchmarks/Benchmarks.csproj
A few packages in the json benchmark were updated recently.
Notable changes:
- Jil 2.16.0 fixes a bug in the packaging related to .NET Core
- SpanJson is stable
Performance differences are not really there, deserialization in SpanJson is 20-30% faster now, for comparison.
<details>
``` ini
BenchmarkDotNet=v0.10.14.534-nightly, OS=Windows 10.0.17134
Intel Core i7-4790K CPU 4.00GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
Frequency=3906256 Hz, Resolution=255.9996 ns, Timer=TSC
.NET Core SDK=2.1.301
[Host]     : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
DefaultJob : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT
```
**Old** 
***JsonSerializerComparison_FromString_IndexViewModel*** 
|        Method |      Mean |     Error | …
=> Update JSON benchmark nuget packages

samples/LowAllocationWebServer/Shared/SampleServer.cs, src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs, tests/Benchmarks/System.IO.Pipelines/E2E.cs, tests/Benchmarks/System.Text.JsonLab/JsonWriterPerf.cs, tests/System.Text.JsonLab.Tests/JsonWriterTests.cs
Also added helper factory method. However, if you don't use var, it ends up increasing how much you have to type. With use of var, you can avoid having to specify the generic type. Given our coding guidelines though, the static helper isn't very useful. Thoughts?
```C#
var json = new Utf8JsonWriter<ArrayFormatterWrapper>(formatter, prettyPrint: false);
var json = Utf8JsonWriter.Create(output, prettyPrint: false);
Utf8JsonWriter<ArrayFormatterWrapper> json = Utf8JsonWriter.Create(output, prettyPrint: false);
```
cc @GrabYourPitchforks, @benaadams
=> Rename JsonWriter to Utf8JsonWriter and add skeleton for UTF-8 specific overloads

tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs
``` ini
BenchmarkDotNet=v0.10.14.683-nightly, OS=Windows 10.0.17713
.NET Core SDK=2.2.100-preview1-009015
DefaultJob : .NET Core 2.1.2 (CoreCLR 4.6.26628.05, CoreFX 4.6.26629.01), 64bit RyuJIT
```
|                             Method | IsUTF8Encoded |   TestCase |         Mean |      Error |     StdDev |       Median |  Gen 0 | Allocated |
|----------------------------------- |-------------- |----------- |-------------:|-----------:|-----------:|-------------:|-------:|----------:|
|   **ReaderSystemTextJsonLabEmptyLoop** |          **True** |  **BasicJson** |    **485.22 ns** |   **9.660 ns** |  **22.770 ns** |    **479.89 …
=> Adding Utf8Json to Json Reader performance tests

src/System.Devices.Gpio/System.Devices.Gpio.Samples/Bme280.cs, src/System.Devices.Gpio/System.Devices.Gpio.Samples/LiquidCrystal.cs, src/System.Devices.Gpio/System.Devices.Gpio.Samples/Program.cs, src/System.Devices.Gpio/System.Devices.Gpio/GpioDriver.cs, src/System.Devices.Gpio/System.Devices.Gpio/Pin.cs, src/System.Devices.Gpio/System.Devices.Gpio/PinEvent.cs, src/System.Devices.Gpio/System.Devices.Gpio/PinMode.cs, src/System.Devices.Gpio/System.Devices.Gpio/PinNumberingScheme.cs, src/System.Devices.Gpio/System.Devices.Gpio/PinValue.cs, src/System.Devices.Gpio/System.Devices.Gpio/PinValueChangedEventArgs.cs, src/System.Devices.Gpio/System.Devices.Gpio/SpiConnectionSettings.cs, src/System.Devices.Gpio/System.Devices.Gpio/SpiDevice.cs, src/System.Devices.Gpio/System.Devices.Gpio/SpiMode.cs, src/System.Devices.Gpio/System.Devices.Gpio/UnixSpiDevice.cs
BME280 sensor allows to read pressure, humidity and temperature data. It supports both SPI and I2C serial protocols. The later is not yet supported by the current implementation.
I have also added an integrated sample that displays the data read from the sensor to an LCD using both SPI and GPIO pins.
=> Adding Bme280 class and samples using SPI and LCD

src/System.Devices.Gpio/System.Devices.Gpio.Samples/Bme280.cs, src/System.Devices.Gpio/System.Devices.Gpio.Samples/LiquidCrystal.cs, src/System.Devices.Gpio/System.Devices.Gpio.Samples/Program.cs, src/System.Devices.Gpio/System.Devices.Gpio/I2cConnectionSettings.cs, src/System.Devices.Gpio/System.Devices.Gpio/I2cDevice.cs, src/System.Devices.Gpio/System.Devices.Gpio/RaspberryPiDriver.cs, src/System.Devices.Gpio/System.Devices.Gpio/SpiConnectionSettings.cs, src/System.Devices.Gpio/System.Devices.Gpio/UnixDriver.cs, src/System.Devices.Gpio/System.Devices.Gpio/UnixI2CDevice.cs, src/System.Devices.Gpio/System.Devices.Gpio/UnixSpiDevice.cs
This PR adds support for I2C serial protocol.
It also extends the Bme280 sensor API to allow I2C in addition to SPI.
=> I2C support and samples using Bme280 sensor and LCD

src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, src/System.Text.JsonLab/System/Text/Json/JsonConstants.cs, src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, tests/System.Buffers.ReaderWriter.Tests/BytesReaderTests.cs
- Fixed potential integer overflow in BufferReader
- Also added initial implementations of some APIs from https://github.com/dotnet/corefxlab/issues/2408.
``` ini
BenchmarkDotNet=v0.10.14.683-nightly, OS=Windows 10.0.17713
.NET Core SDK=2.2.100-preview1-009015
DefaultJob : .NET Core 2.1.2 (CoreCLR 4.6.26628.05, CoreFX 4.6.26629.01), 64bit RyuJIT
```
|                                            Method |   TestCase |            Mean |         Error |        StdDev |          Median | Scaled | ScaledSD |  Gen 0 | Allocated |
|-------------------------------------------------- |----------- …
=>  Fix typo in TryReadUntill and optimize it and JsonReader for the common case

src/System.Text.JsonLab/System/Text/Json/JsonConstants.cs, src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, src/System.Text.JsonLab/System/Text/Json/JsonTokenType.cs, tests/System.Text.JsonLab.Tests/JsonParserTests.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
**Before (master):**
|                               Method |   TestCase |          Mean |        Error |       StdDev | Allocated |
|------------------------------------- |----------- |--------------:|-------------:|-------------:|----------:|
| **ReaderSystemTextJsonLabSpanEmptyLoop** |  **BasicJson** |     **544.87 ns** |    **10.637 ns** |    **15.921 ns** |       **0 B** |
| **ReaderSystemTextJsonLabSpanEmptyLoop** | **HelloWorld** |      **63.93 ns** |     **2.413 ns** |     **2.015 ns** |       **0 B** |
| **ReaderSystemTextJsonLabSpanEmptyLoop** |   **Json400B** |     **818.72 ns** |    **16.023 ns** |    **17.810 ns** |       **0 B** |
| **ReaderSystemTextJsonLabSpanEmptyLoop** |  **Json400KB** | **867,947.02 ns** | **9,080.293 ns** | **7,089.295 ns** |       **0 B** |
| …
=> Switch from case to if statements in JsonReader and code cleanup

src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs, tests/System.Text.JsonLab.Tests/JsonWriterTests.cs
Fixes https://github.com/dotnet/corefxlab/issues/1640
**TODO:** Optimize search for nested escaped quotes.
Also write null instead of an empty string if WriteAttribute() with null string value.
=> Expose JsonReader depth, add Skip, and fix reading strings with embedded quotes

src/System.Devices.Gpio/System.Devices.Gpio.Samples/System.Devices.Gpio.Samples.csproj, src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
Initial depth was set incorrectly for the multi-segment case.
Adding several tests borrowed from SignalR, mainly from the [HandshakeProtocolTests](https://github.com/aspnet/SignalR/blob/651b39bc901bac7767fb19af6fcb256a9730e258/test/Microsoft.AspNetCore.SignalR.Common.Tests/Internal/Protocol/HandshakeProtocolTests.cs#L12).
=> Fix bugs in JsonReader and add tests from SignalR

src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, tests/Benchmarks/System.Buffers/Reader_Search.cs, tests/System.Buffers.ReaderWriter.Tests/BytesReaderTests.cs
Move the methods to instance and optimize. I did not optimize the TryReadUntil that takes a Span delimiter yet.
For a single segment single delimiter I can get about 25% gain. The cost of comparing multiple delimiters eats a greater portion of the time pretty rapidly. I think were pretty close to optimal here (i.e. most of the time is in IndexOf/Any).
**Before (single segment)**
```
Method |       Mean |     Error |    StdDev |
---------------------------------- |-----------:|----------:|----------:|
TryReadUntil_Span_OneSegment |   179.8 us |  3.220 us |  2.854 us |
TryReadUntilAny_2_Span_OneSegment |   633.3 us |  6.364 us |  5.953 us |
TryReadUntilAny_5_Span_OneSegment | 3,116.2 us | 16.157 us | 15.113 us |
```
**After (single segment)**
```
Method |       Mean |     Error |    StdDev …
```
=> Optimize TryReadUntil

src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_binary.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_text.cs, src/System.Text.Http/System/Text/Http/Parser/HttpParser.cs, src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, tests/Benchmarks/System.Buffers/Reader.cs, tests/Benchmarks/System.Buffers/Reader_Binary.cs, tests/Benchmarks/System.Buffers/Reader_Construction.cs, tests/Benchmarks/System.Buffers/Reader_ParseInt.cs, tests/Benchmarks/System.Buffers/Reader_Search.cs, tests/System.Buffers.ReaderWriter.Tests/BufferReaderTests.cs, tests/System.Buffers.ReaderWriter.Tests/BytesReaderTests.cs, tests/System.Buffers.ReaderWriter.Tests/ReadableBufferReaderFacts.cs
Making the constructor public cuts the construction time by about a third.
Tweak UnreadSpan to inline and give back the current span if at the start.
Skip out on getting the next memory from the sequence if we're single segment.
Cuts 5-10% off of some of the perf tests.
Also change terms to Span from Segment. It was mentally taxing to juggle Span/Segment/Sequence/SequencePosition.
cc: @benaadams, @mgravell, @Drawaes, @davidfowl
=> Constructor work & perf tweaks

src/System.Text.JsonLab/System/Text/Json/JsonParseObject.cs, src/System.Text.JsonLab/System/Text/Json/JsonParser.cs, src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, src/System.Text.JsonLab/System/Text/Json/JsonThrowHelper.cs, tests/Benchmarks/System.Buffers/Reader_Construction.cs, tests/Benchmarks/System.Buffers/Reader_Search.cs, tests/Benchmarks/System.Text.JsonLab/JsonParserPerf.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs, tests/System.Text.JsonLab.Tests/JsonObjectTests.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs, tests/System.Text.JsonLab.Tests/JsonTestHelper.cs, tests/System.Text.JsonLab.Tests/Resources/TestJson.Designer.cs, tests/System.Text.JsonLab.Tests/Resources/TestJson.resx
- Use ThrowHelper
- Fix use of var
- Add JsonTestHelper
- Add JsonObject TryGetChild and Remove APIs
``` ini
BenchmarkDotNet=v0.10.14.683-nightly, OS=Windows 10.0.17713
.NET Core SDK=3.0.100-alpha1-20180720-2
Job-JGLELY : .NET Core 2.1.2 (CoreCLR 4.6.26628.05, CoreFX 4.6.26629.01), 64bit RyuJIT
```
|                  Method |        TestCase |            Mean |           Error |        StdDev | Scaled | ScaledSD |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|------------------------ |---------------- |----------------:|----------------:|--------------:|-------:|---------:|---------:|-------- …
=> Add json parsing performance tests and code clean up

src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, src/System.Text.JsonLab/System/Text/Json/JsonReader.cs
- Split IsNext fast and slow paths.
- The general purpose SkipPastAny is too slow (mainly due to IndexOf) for the special case of JsonReader. We almost always only have to skip a single character, and that ends up being the space character (0x20). The loop based approach works best here (since the first check is almost always true the first time).
**Performance of the JsonReader is now back to baseline.**
**Performance of SkipWhiteSpace**
1) Use SkipPastAny: 15-50% regression
|               Method | NumberOfWhiteSpace |      Mean |     Error |    StdDev | Scaled | ScaledSD | Allocated |
|--------------------- |------------------- |----------:|----------:|----------:|-------:|---------:|----------:|
| **SkipWhiteSpaceBefore** |                  **0** |  **75.80 ns** | **0.3412 ns** | …
=> Revert use of SkipPastAny in SkipWhiteSpace and optimize BufferReader.IsNext

src/System.Text.Primitives/System/Text/Encoders/Ascii/Ascii_casing.cs, tests/Benchmarks/System.Text.Primitives/AsciiCasing.cs
Below are results of the changes suggested in #1738. The first run has the change for Ascii.ToLowerInPlace() which is why you'll notice a discrepancy.
```
// * Summary *
BenchmarkDotNet=v0.10.14.683-nightly, OS=Windows 10.0.17134.191 (1803/April2018Update/Redstone4)
Intel Core i7-7820HQ CPU 2.90GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
Frequency=2835933 Hz, Resolution=352.6176 ns, Timer=TSC
.NET Core SDK=2.1.400
DefaultJob : .NET Core 2.1.2 (CoreCLR 4.6.26628.05, CoreFX 4.6.26629.01), 64bit RyuJIT
Method |                 Text |      Mean |     Error |    StdDev |
-------------------- |--------------------- |----------:|----------:|----------:|
AsciiToLowerInPlace |           /plaintext | …
```
=> Ascii Casing Optimization

src/System.Reflection.TypeLoader/src/System/Reflection/TypeLoading/General/NetStandardBridge.cs, tests/System.Reflection.TypeLoader.Tests/System.Reflection.TypeLoader.Tests.csproj, tests/System.Reflection.TypeLoader.Tests/src/Tests/CustomAttributes/DllImportTests.cs
CoreFxLab is now consuming the netcoreapp contracts
that expose the TypeInfo constructor so remove the
"derive from TypeDelegator" hack for that version of
the build.
Also, fix a test that was broken on netstandard runs
(not currently built in corefxlab) in the last change.
=> Remove TypeDelegator hack for netcoreapp2.2 build.

samples/LowAllocationWebServer/Shared/SampleServer.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, src/System.Text.JsonLab.Dynamic/System/Text/Json/JsonLazyDynamicObject.cs, src/System.Text.JsonLab/System/Text/Json/CustomDb.cs, src/System.Text.JsonLab/System/Text/Json/CustomStack.cs, src/System.Text.JsonLab/System/Text/Json/DbRow.cs, src/System.Text.JsonLab/System/Text/Json/JsonObject.cs, src/System.Text.JsonLab/System/Text/Json/JsonParser.cs, src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, src/System.Text.JsonLab/System/Text/Json/JsonThrowHelper.cs, src/System.Text.JsonLab/System/Text/Json/StackRow.cs, tests/Benchmarks/System.Text.JsonLab/JsonParserChangeEntryPerf.cs, tests/Benchmarks/System.Text.JsonLab/JsonParserEnumeratePerf.cs, tests/Benchmarks/System.Text.JsonLab/JsonParserPerf.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs, tests/System.Text.JsonLab.Tests/JsonObjectTests.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs, tests/System.Text.JsonLab.Tests/Resources/TestJson.resx
- Add SkipPastAny overloads.
- Add SkipPastSlow which advances 1 at a time.
- Add back static JsonObject.Parse method.
- Break out the db functionality from JsonParser into a new CustomDb type.
- Add a union column in DbRow that stores more info during parsing.
- Use a static byte array for the initial stack space.
- Add JsonParserEnumeratePerf benchmark. Experiments with attempting amortized O(n) enumeration of arrays was only beneficial for large json objects. We should revisit this change.
- Add compact (no whitespace/formatting) json payloads to benchmarks.
- Add parser benchmark mode where we rebuild the json string from the parsing loop.
- Change JsonReader implementation to optimize the zero-space cases.
``` ini
BenchmarkDotNet=v0.10.14.683-nightly, OS=Windows 10.0.17713
Intel Core …
```
=> Optimize JsonReader and JsonParser, and update design for cleaner lifetime semantics

src/System.Reflection.TypeLoader/src/System/Reflection/TypeLoading/Types/RoDefinitionType.cs
Since the underlying api support didn't exist yet,
we had to write this blind. With predictable results.
=> Fix handling of signature types in MakeGenericType

src/System.Text.JsonLab/System/Text/Json/JsonObject.cs, src/System.Text.JsonLab/System/Text/Json/JsonWriter.cs, tests/Benchmarks/System.Text.JsonLab/JsonParserEnumeratePerf.cs, tests/Benchmarks/System.Text.JsonLab/JsonParserPerf.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs, tests/Benchmarks/System.Text.JsonLab/JsonWriteObjectPerf.cs
- Also fixed possible integer overflow in JsonObject enumerator
``` ini
BenchmarkDotNet=v0.10.14.683-nightly, OS=Windows 10.0.17738
.NET Core SDK=3.0.100-alpha1-20180720-2
Job-HSTSEQ : .NET Core 2.1.2 (CoreCLR 4.6.26628.05, CoreFX 4.6.26629.01), 64bit RyuJIT
```
|                 Method | IsDataCompact |        TestCase |            Mean |            Error |           StdDev | Scaled | ScaledSD |    Gen 0 |    Gen 1 | Allocated |
|----------------------- |-------------- |---------------- |----------------:|-----------------:|-----------------:|-------:|---------:|---------:|---------:|------- …
=> Add JsonWriteObject perf tests and cleanup use of var

src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs, tests/Benchmarks/System.Text.JsonLab/JsonWriterPerf.cs
**20-40% improvement from master for the multi-segment case.**
- Ported over several of the recent single-segment optimizations for the mutli-segment case.
- Optimized certain BufferReader APIs.
- Pass BufferReader around by ref instead.
- It may be possible to improve the performance of the ConsumeStringUtf8MultiSegment implementation a bit.
The multi-segment case is now roughly 15-30% slower than the single-segment case (as long as the JSON payload is sufficiently large for the boundary crossing to get amortized). If, however, a small payload (like hello world, i.e. less than 256 bytes) is split into 1+ segments, it will be costly.
Removing the use of BufferReader and using ReadOnlySequence directly only saves about 10% in most cases (and hence not worth it). This is similar to the …
=> Optimize JsonReader for the multi-segment case

tests/Benchmarks/Benchmarks.csproj, tools/dependencies.props
BDN version update is required because I had to add .NET Core 3.0 to the frameworks which BDN recognizes and supports (https://github.com/dotnet/BenchmarkDotNet/commit/2e398c89561b3b1c89ec64b94f656ae20236efd1)
=> Port Benchmarks to .NET Core 3.0

src/System.Text.JsonLab/System/Text/Json/CustomStack.cs, src/System.Text.JsonLab/System/Text/Json/JsonParser.cs, src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderMaxDepthPerf.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
~5% perf regression due to extra checks in Start/End Object and Array.
``` ini
BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17744
.NET Core SDK=3.0.100-alpha1-009460
Job-MVZRDK : .NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT
```
|                               Method | Depth |         Mean |         Error |        StdDev | Scaled | ScaledSD |   Gen 0 | Allocated |
|------------------------------------- |------ |-------------:|--------------:|--------------:|-------:|---------:|--------:|----------:|
|      **ReaderNewtonsoftReaderEmptyLoop** |     **1** |    **465.29 …
=> Add ability to set MaxDepth to JsonReader beyond 64 using stack

src/System.Text.JsonLab/System/Text/Json/JsonReader.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs
Also removed unnecessary Depth check and cached InObject (turning it into a field): 
https://github.com/dotnet/corefxlab/pull/2483#discussion_r218522745
https://github.com/dotnet/corefxlab/pull/2483#discussion_r218519322
~5% improvement when data is "compact"
+ Changed stack from int to bool to save space. No need to store 4 bytes (int), when 1 is sufficient (bool).
``` ini
BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17744
.NET Core SDK=3.0.100-alpha1-009460
DefaultJob : .NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT
```
**Before:**
|                               Method | IsDataCompact | …
=>  Mark json data as readonly and remove the need to slice it while reading

src/System.Numerics.Tensors/System.Numerics.Tensors.csproj
To make it easier to consume the Tensors library, so users only need to add 1 myget feed (the corefxlab feed) to use it.
=> Pin the Memory version used by Tensors.

src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, tests/System.Buffers.Experimental.Tests/BufferFactory.cs, tests/System.Buffers.ReaderWriter.Tests/Reader_SkipDelimiter.cs
This allows you to handle escaping. Unescaping would be considered the callers responsibility. We could combine `TryReadToInternal` if we introduce additional condition checks.
=> Add a skip delimiter overload to TryReadTo

tests/Benchmarks/Benchmarks.csproj, tests/Benchmarks/System.Text.JsonLab/JsonReaderMultiSegmentPerf.cs, tests/System.Buffers.Experimental.Tests/BufferFactory.cs
As you would expect, the larger the segment size, the better the performance. 4 KB is a reasonable size. There is a 5-10% regression if you use a smaller size like 1KB.
**The multi-segment case is 50% slower than the single segment case, even with 8 KB buffers (ideally this should be under 10% as seen here: https://github.com/dotnet/corefxlab/issues/2511).**
Issue to try to improve performance: https://github.com/dotnet/corefxlab/issues/2509
``` ini
BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17754
.NET Core SDK=3.0.100-alpha1-009460
Job-KGUDKK : .NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT …
```
=> Measure multi-segment reading versus single-segment reading for various segment sizes

src/System.Text.JsonLab/System/Text/Json/JsonConstants.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
Fixes https://github.com/dotnet/corefxlab/issues/2497
This appears more often in debug. For example, the first Debug.Assert call allocates 64 bytes.
=> Remove tests that measure allocations on current thread since it isn't reliable

src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, src/System.Buffers.ReaderWriter/System/ThrowHelper.cs, src/System.Text.JsonLab/System/Text/Json/JsonReaderState.cs, src/System.Text.JsonLab/System/Text/Json/Utf8JsonReader_MultiSegment.cs, tests/System.Buffers.ReaderWriter.Tests/Reader_ReadTo.cs, tests/System.Buffers.ReaderWriter.Tests/Reader_Rewind.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
BufferReader does not provide a reset/recovery mechanism which results in the new re-entrant JsonReader tests to fail.
For example, if I see the start of a property name (i.e. `"`), I advance past the quote and call ConsumeString, which ends up calling `if (reader.TryReadTo(out ReadOnlySpan<byte> value, JsonConstants.Quote, (byte)'\\', advancePastDelimiter: true))`
However, if that returns false because we don't have all the data yet, I need to undo the advance I did (to move the cursor back before the first `"`).
To work around this, I have to copy the BufferReader before advancing to rollback the change. This results in significant perf regression. **How can I do this in a sane way while still using the BufferReader APIs?**
**TODO:** Add more test cases (especially for invalid data with …
=> Add rich error messaging and re-entrant support for multi-segment json

src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, src/System.Text.JsonLab/ExceptionStrings.Designer.cs, src/System.Text.JsonLab/ExceptionStrings.resx, src/System.Text.JsonLab/System/Text/Json/InternalJsonTokenType.cs, src/System.Text.JsonLab/System/Text/Json/JsonConstants.cs, src/System.Text.JsonLab/System/Text/Json/JsonReaderHelper.cs, src/System.Text.JsonLab/System/Text/Json/JsonReaderState.cs, src/System.Text.JsonLab/System/Text/Json/JsonThrowHelper.cs, src/System.Text.JsonLab/System/Text/Json/Utf8JsonReader.cs, src/System.Text.JsonLab/System/Text/Json/Utf8JsonReader_MultiSegment.cs, tests/System.Buffers.ReaderWriter.Tests/Reader_ReadTo.cs, tests/System.Buffers.ReaderWriter.Tests/Reader_Rewind.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
**TODO:**
- Should we just ignore comments or should we support users actually reading the comment values?
=>  Add support for allowing comments within Json while reading

src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, tests/Benchmarks/System.Buffers/Reader_Search.cs, tests/System.Buffers.ReaderWriter.Tests/ReaderBasicTests.cs, tests/System.Buffers.ReaderWriter.Tests/ReaderBytesTests.cs, tests/System.Buffers.ReaderWriter.Tests/Reader_ReadTo.cs
Fix moving past empty sequences.
Fix span advance to advancePastDelimiter handling.
Add IsLastSegment.
Add 4x faster Position property.
Add a variety of tests.
=> Change skip* to advance*.

src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_binary.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_text.cs, tests/Benchmarks/System.Buffers/Reader.cs, tests/Benchmarks/System.Buffers/Reader_ParseInt.cs, tests/System.Buffers.ReaderWriter.Tests/ReaderBytesTests.cs, tests/System.Buffers.ReaderWriter.Tests/Reader_ParseFloatingPoint.cs, tests/System.Buffers.ReaderWriter.Tests/Reader_ParseInteger.cs, tests/System.Buffers.ReaderWriter.Tests/Reader_ParseStruct.cs
- Move delegate creation to internal methods
- Add internal Advance for current span and tweak GetNextSpan
- Flip logic in binary read (now 15% faster)
=> Remove consumed from parse methods (per API review feedback)

src/System.Text.JsonLab/System/Text/Json/JsonReaderOptions.cs, src/System.Text.JsonLab/System/Text/Json/Utf8JsonReader.cs, src/System.Text.JsonLab/System/Text/Json/Utf8JsonReader_MultiSegment.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
- 15-25% regression for default case (extra option checks)
- 40-50% regression if JsonReaderOptions.TrackPositionAsCodePoints is enabled
**Master:**
Method | TestCase | Mean
-- | -- | --
ReadJsonEmptyLoop | BasicJson | 487.7
ReadJsonEmptyLoop | HelloWorld | 94.53
ReadJsonEmptyLoop | Json400B | 1,184.25
ReadJsonEmptyLoop | Json400KB | 842,661.75
ReadJsonEmptyLoop | Json40KB | 77,793.18
ReadJsonEmptyLoop | Json4KB | 6,013.05
**This PR:**
Method | TestCase | Mean | Scaled
-- | -- | -- | --
ReadJsonEmptyLoop | BasicJson | 610.4 | 1
ReadJsonTrackCodePoints | BasicJson | 727.2 | 1.19
  |   |   |  
ReadJsonEmptyLoop | HelloWorld | 114.5 | 1
ReadJsonTrackCodePoints | HelloWorld | 146.3 | 1.29
  |   |   |  
ReadJsonEmptyLoop | Json400B | 947.6 | 1
ReadJsonTrackCodePoints | Json400B | 1,165.60 | …
=> Add JsonReaderOption to track position by UTF-8 code points

src/System.Text.JsonLab/System/Text/Json/Utf8JsonReader_MultiSegment.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderMultiSegmentPerf.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs, tests/System.Text.JsonLab.Tests/System.Text.JsonLab.Tests.csproj
``` ini
BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17763
.NET Core SDK=3.0.100-alpha1-009667
Job-QGLHAV : .NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT
```
|                        Method |  TestCase | segmentSize |        Mean |         Error |      StdDev |   Gen 0 | Allocated |
|------------------------------ |---------- |------------ |------------:|--------------:|------------:|--------:|----------:|
|          **MultiSegmentSequence** | **Json400KB** |        **1000** | **2,229.47 us** | **1,979.0869 us** | **514.0605 us** | **11.7188** |   **52056 B** |
| …
=>  Add benchmark to test multi-segment reading using span-based JsonReader

src/System.Text.JsonLab/System/Text/Json/Utf8JsonReader.cs, src/System.Text.JsonLab/System/Text/Json/Utf8JsonReaderStream.cs, tests/Benchmarks/System.Text.JsonLab/JsonReaderPerf.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs, tests/System.Text.JsonLab.Tests/JsonTestHelper.cs
- ~10-15% overhead for streams for payloads that aren't too small (say over 500 bytes).
``` ini
BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17763
.NET Core SDK=3.0.100-alpha1-009667
Job-CMDZZD : .NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT
```
|                                     Method | IsDataCompact |        TestCase |           Mean |         Error |        StdDev | Scaled | ScaledSD |  Gen 0 | Allocated |
|------------------------------------------- |-------------- |---------------- |---------------:|--------------:|--------------:|-------:|---------:|-------:| …
=>  Prototype stream wrapper around JsonReader to provide stream support

scripts/update-dependencies/Program.cs, src/System.Memory.Polyfill/System.Memory.Polyfill.csproj, tools/dependencies.props
From https://github.com/dotnet/corefx/pull/32967#issuecomment-432334823
=> Pin System.Memory and System.Buffers to last OOB version and no longer update them

src/System.Text.JsonLab/System/Text/Json/JsonReaderException.cs, src/System.Text.JsonLab/System/Text/Json/JsonReaderOptions.cs, src/System.Text.JsonLab/System/Text/Json/Utf8JsonReader.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
Essentially reverts https://github.com/dotnet/corefxlab/pull/2540.
Gain back ~20%.
``` ini
BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17763
.NET Core SDK=3.0.100-alpha1-009701
DefaultJob : .NET Core 2.1.3 (CoreCLR 4.6.26725.06, CoreFX 4.6.26725.05), 64bit RyuJIT
```
**Before:**
|                               Method | IsDataCompact |   TestCase |           Mean |         Error |        StdDev |         Median | Scaled | ScaledSD | Allocated |
|------------------------------------- |-------------- |----------- |---------------:|--------------:|--------------:|---------------:|-------:|---------:|----------:|
| …
=> Remove JsonReaderOption to track position by UTF-8 code points

tools/dependencies.props
The preview version of pipelines is not in corfxlab myget not on nuget.org. This means adding System.Buffers.ReaderWriter to a project fails, unless the project has pipelines myget feed (which is not common or intuitive). Since ReaderWriter (nor any components in corfxlab) needs preview of pipelines, I am dropping the pipelines dependency to the officially released on nuget.org.
=> dropped to released version of piplelines

samples/LowAllocationWebServer/LowAllocationWebServerLibrary/HttpServer.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader.cs, src/System.Buffers.ReaderWriter/System/Buffers/Reader/BufferReader_search.cs, src/System.Buffers.ReaderWriter/System/ThrowHelper.cs, src/System.Text.Http/System.Text.Http.csproj, src/System.Text.Http/System/Text/Http/Parser/HttpParser.cs, src/System.Text.Http/System/Text/Http/Parser/HttpUtilities.cs, tests/Benchmarks/System.Buffers/Reader_Construction.cs, tests/Benchmarks/System.Text.Http.Parser/HttpParser.cs, tests/System.Text.Http.Tests/HttpParserBasicTests.cs, tests/System.Text.Http.Tests/HttpParserTests.cs
- Optimize Header parser BufferReader usage
- Optimize reader TryReadToAny for two items
- Optimize reader TryRead<T>
Goal here is to make sure the reader is working well for the parser.
**Parser before**
```
Method |      Mean |     Error |    StdDev |
------------ |----------:|----------:|----------:|
RequestLine |  69.73 ns | 0.3118 ns | 0.2917 ns |
Headers | 147.80 ns | 0.6158 ns | 0.5459 ns |
FullRequest | 230.65 ns | 0.6696 ns | 0.6264 ns |
```
**Parser after (no new reader aggressive inlining)**
```
Method |      Mean |     Error |    StdDev |
------------ |----------:|----------:|----------:|
RequestLine |  66.01 ns | 0.2759 ns | 0.2581 ns |
Headers | 151.10 ns | 0.6065 ns | 0.5673 ns |
FullRequest | 227.00 ns | 0.9968 ns | 0.9324 ns |
```
Slightly slower reading just the headers, …
=> Change HttpParser header parsing to span

.gitignore, src/Microsoft.Experimental.Collections/Microsoft.Experimental.Collections.csproj, tests/Benchmarks/Benchmarks.csproj, tests/Benchmarks/Program.cs, tools/dependencies.props
With this change you can temporarily add `[EtwProfiler]` on your benchmark class to get an ETW file. You may need to add `using BenchmarkDotNet.Diagnostics.Windows.Configs;`
Also enabled symbols on the benchmark project for release. It's already done in Microsoft.Experimental.Collections.csproj
=> Update Benchmark.NET version to use EtwProfiler

src/System.Text.Encodings.Web.Utf8/UrlEncoder.cs, tests/Benchmarks/System.Text.Encodings.Web.Utf8/UrlEncoderPerf.cs, tests/System.Text.Encodings.Web.Utf8.Tests/UnescapeUrlPathInPlaceTests.cs, tests/System.Text.Encodings.Web.Utf8.Tests/UnescapeUrlPathTests.cs, tools/common.props
The APIs that were marked as obsolete in this PR: https://github.com/dotnet/corefxlab/pull/1741 can now be made internal (as implementation detail).
Fixes the remainder of the warnings: https://github.com/dotnet/corefxlab/issues/2585#issuecomment-441385409
```text
Build succeeded.
0 Warning(s)
0 Error(s)
```
cc @danmosemsft
=> Change obsolete Encodings.Web.Utf8 APIs to internal and fix warnings.

src/System.IO.FileSystem.Watcher.Polling/System/IO/PollingFileSystemWatcher.cs, tests/System.IO.FileSystem.Watcher.Polling.Tests/DerivedTests.cs, tests/System.IO.FileSystem.Watcher.Polling.Tests/SerializableTests.cs, tests/System.IO.FileSystem.Watcher.Polling.Tests/UnitTests.cs, tests/System.Text.JsonLab.Tests/HeapableJsonReaderTests.cs, tests/System.Text.JsonLab.Tests/JsonReaderStreamTests.cs, tests/System.Text.JsonLab.Tests/JsonReaderTests.cs
This should, hopefully, resolve the intermittent test failures we have been seeing in CI (especially for Ubuntu). The Json tests, in total, now allocate < 2 GB (instead of ~7).
Addressing:
https://github.com/dotnet/corefxlab/pull/2600#issuecomment-441402322
https://github.com/dotnet/corefxlab/pull/2596#issuecomment-440608860
As an added bonus they also take less time to complete now (< 2 minutes instead of ~4).
cc @danmosemsft
=> Disable, remove, or fix JSON tests that consume too much memory.

src/Microsoft.Experimental.Collections/Microsoft/Collections/Extensions/OrderedDictionary.KeyCollection.cs, src/Microsoft.Experimental.Collections/Microsoft/Collections/Extensions/OrderedDictionary.cs, tests/Microsoft.Experimental.Collections.Tests/Microsoft/Collections/Extensions/OrderedDictionaryTests.cs
Removed unnecessary GetAt, GetValue, SetAt, and SetValue methods as the indexers work, even in the case where TKey is an int as you can still call the key indexer by specifying the key parameter name.
=> Few OrderedDictionary Updates

NuGet.Config, scripts/package.ps1, src/Microsoft.Experimental.Collections/Microsoft.Experimental.Collections.csproj, tools/common.props, tools/dependencies.props, tools/sign.proj, tools/signing/sign.depproj, tools/signing/sign.proj, tools/signing/sign.targets
Add targets to be able to sign packages and its contents in order to be able to push experimental or preview packages to nuget.org
This is based on arcade's Microsoft.DotNet.SignTool package.
I will test the build definition before merging.
=> Add Signing in order to be able to publish packages to nuget

tools/common.props
PackageLicenseUrl is being deprecated and in all other repos we use PackageLicenseFile and put both, LICENSE and THIRD-PARTY-NOTICES files in our packages.
=> Fix packages to be compliant with nuget's requirements

src/Microsoft.Data/ArrowStringColumn.cs, src/Microsoft.Data/BaseColumn.cs, src/Microsoft.Data/PrimitiveColumn.cs, src/Microsoft.Data/PrimitiveColumnContainer.cs, src/Microsoft.Data/StringColumn.cs, tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
This allows for things like XPlot to be able to show charts using code like:
```C#
BaseColumn column = ...;
Chart.Plot(
new Graph.Histogram()
{
x = column,
nbinsx = bins
},
new Layout.Layout()
{
title = column.Name
}
).Display();
```
=> Implement IEnumerable<T> on PrimitiveColumn.

corefxlab.sln, src/Microsoft.Data/ArrowStringColumn.cs, src/Microsoft.Data/DataFrame.cs, src/Microsoft.Data/DataFrameBuffer.cs, src/Microsoft.Data/GroupBy.cs, src/Microsoft.Data/PrimitiveColumn.cs, src/Microsoft.Data/PrimitiveColumnArithmetic.cs, src/Microsoft.Data/PrimitiveColumnArithmetic.tt, src/Microsoft.Data/PrimitiveColumnComputations.cs, src/Microsoft.Data/PrimitiveColumnComputations.tt, src/Microsoft.Data/PrimitiveColumnContainer.cs, src/Microsoft.Data/ReadOnlyDataFrameBuffer.cs, tests/Benchmarks/Benchmarks.csproj, tests/Benchmarks/Microsoft.Data.DataFrame/DataFrameBinaryOps.cs, tests/Benchmarks/Microsoft.Data.DataFrame/DataFrameComputations.cs, tests/Benchmarks/Microsoft.Data.DataFrame/DataFrameFunctions.cs, tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
More work towards dotnet/corefx#26845
Added benchmarks for BinaryOps, Computations, Indexing, Sort, GroupBy, Joins and Merges
Perf improvements in GroupBy and Computations.
Minor API additions in GroupBy to enable the benchmarks
I decided to bundle the benchmarks and perf improvements together here because the perf improvement changes are straightforward.
=> Benchmarks and Perf improvements

src/Microsoft.Data/ArrowStringColumn.cs, src/Microsoft.Data/DataFrame.IO.cs, src/Microsoft.Data/DataFrame.Join.cs, src/Microsoft.Data/PrimitiveColumn.Sort.cs, src/Microsoft.Data/PrimitiveColumn.cs, src/Microsoft.Data/PrimitiveColumnContainer.cs, src/Microsoft.Data/StringColumn.cs, tests/Microsoft.Data.DataFrame.Tests/DataFrame.IOTests.cs, tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
Perf work towards dotnet/corefx#26845. 
Most of the changes are related to caching the Span<T> instead of randomly accessing Memory<T> every iteration. Some algorithms(for ex: Merge) need random access, so there's not much we can do there.
=> Perf improvements in Clone, Sort, Merge and ReadCsv

src/Microsoft.Data/Microsoft.Data.DataFrame.csproj
This is necessary so other strong named libraries can consume the DataFrame library.
=> Enable Strong Naming in DataFrame library

src/Microsoft.Data/ArrowStringColumn.cs, src/Microsoft.Data/DataFrameBuffer.cs, src/Microsoft.Data/PrimitiveColumn.Sort.cs, src/Microsoft.Data/PrimitiveColumn.cs, src/Microsoft.Data/PrimitiveColumnContainer.cs, src/Microsoft.Data/ReadOnlyDataFrameBuffer.cs, src/Microsoft.Data/StringColumn.cs, src/Microsoft.Data/strings.Designer.cs, src/Microsoft.Data/strings.resx, tests/Microsoft.Data.DataFrame.Tests/BufferTests.cs
Simple PR: 
GetBuffers and GetReadOnlyBuffers APIs on PrimitiveColumn and StringColumn to get at the underlying buffers.
There's no equivalent on ArrowStringColumn, since it stores data across 3 buffers.
=> APIs to get at the underlying buffers

src/Microsoft.Data/PrimitiveColumn.cs, tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.IDataView.cs, tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
Match the TextLoader and DatabaseLoader behavior in ML.NET. When a float or double is `null`, we use NaN. And for other types use `default(T)`.
=> Fix IDataView implementation for null values.

src/Microsoft.Data/BaseColumn.BinaryOperations.cs, src/Microsoft.Data/BaseColumn.BinaryOperations.tt, src/Microsoft.Data/BaseColumn.BinaryOperators.cs, src/Microsoft.Data/BaseColumn.BinaryOperators.tt, src/Microsoft.Data/PrimitiveColumn.BinaryOperations.cs, src/Microsoft.Data/PrimitiveColumn.BinaryOperations.tt, src/Microsoft.Data/PrimitiveColumn.cs, src/Microsoft.Data/PrimitiveColumnContainer.cs, src/Microsoft.Data/StringColumn.BinaryOperations.cs, src/Microsoft.Data/StringColumn.cs, tests/Microsoft.Data.DataFrame.Tests/DataFrameTests.cs
Binary comparisons always return a PrimitiveColumn<bool>
PrimitiveColumn constructor with IEnumerable<T?>
Should be an easy review
=> Fix https://github.com/dotnet/corefxlab/issues/2735

src/Microsoft.Data/ArrowStringColumn.cs, tests/Microsoft.Data.DataFrame.Tests/ArrowIntegrationTests.cs
Fix a bug in `ArrowStringColumn.AsArrowArray`.
Required for the Spark work.
=> Empty ArrowStringColumn->Arrow column

src/Microsoft.Data/PrimitiveColumnContainer.cs, src/Microsoft.Data/PrimitiveDataFrameColumn.Sort.cs, src/Microsoft.Data/ReadOnlyDataFrameBuffer.cs, src/Microsoft.Data/strings.Designer.cs, src/Microsoft.Data/strings.resx, tests/Microsoft.Data.DataFrame.Tests/ArrayComparer.cs, tests/Microsoft.Data.DataFrame.Tests/ArrowIntegrationTests.cs, tests/Microsoft.Data.DataFrame.Tests/BufferTests.cs
Fixes issues around NullCount when we encounter Arrow data(C# Arrow doesn't populate it's NullBitMapBuffer if NullCount is 0)
This patch contains half the changes from https://github.com/dotnet/corefxlab/pull/2730/.
=> Fix NullCount bugs

src/Microsoft.Data.Analysis/DataFrame.cs, src/Microsoft.Data.Analysis/DataFrameColumn.cs, src/Microsoft.Data.Analysis/PrimitiveDataFrameColumn.cs, src/Microsoft.Data.Analysis/strings.Designer.cs, src/Microsoft.Data.Analysis/strings.resx, tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
Adds an Info method
The Description method was always calling `Max` on `PrimitiveDataFrameColumn<T>`. If `T` was a struct (such as `DateTime` where `Max` may not be well defined), we return `null` instead of throwing.
=> Fix the Description method to not throw

src/Microsoft.Data.Analysis/DataFrame.IO.cs, src/Microsoft.Data.Analysis/DataFrame.cs, tests/Microsoft.Data.Analysis.Tests/DataFrame.IOTests.cs, tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
At the moment, we ignore dataTypes if it passed in to `LoadCsv`. This patch lets us use `dataTypes` and also read in the input file just once when the data types are known. If dataTypes is `null`, we don't read the full file twice now. Instead, we rely on the `DataFrame.Append` method to append values as we read them. 
`dataTypes` can still have structs or user defined types. We just throw in such cases.
=> Use dataTypes if it passed in to LoadCsv

src/Microsoft.Data.Analysis/DataFrame.IO.cs, tests/Microsoft.Data.Analysis.Tests/BufferTests.cs, tests/Microsoft.Data.Analysis.Tests/DataFrameTests.IDataView.cs, tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs, tests/Microsoft.Data.Analysis.Tests/Microsoft.Data.Analysis.Tests.csproj
Fixing by passing in an encoding and a default buffer size.
Also, get our tests running on .NET Framework.
Fix #2783
=> DataFrame.LoadCsv throws an exception on projects targeting < netcore3.0

src/Microsoft.Data.Analysis/PrimitiveColumnContainer.cs, src/Microsoft.Data.Analysis/PrimitiveDataFrameColumn.cs, tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
For issue #2805.
This PR adds an `Apply<TResult>` method to `PrimitiveDataFrameColumn` that takes a `Func<T?, TResult?>` and returns a new column with the new type.
Example usage (taken from the written unit test):
```csharp
int[] values = { 1, 2, 3, 4, 5 };
var col = new PrimitiveDataFrameColumn<int>("Ints", values);
PrimitiveDataFrameColumn<double> newCol = col.Apply(i => i + 0.5d);
```
=> Add Apply<TResult>method to PrimitiveDataFrameColumn

src/Microsoft.Data.Analysis/DataFrameColumn.cs, tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
I added static factory methods only for the constructor overloads where type inference is possible. 
I experimented with adding overloads for all constructors, but for the overloads where `values` are not provided it didn't feel helpful. It seemed weird to do `DataFrameColumn.Create("foo")` and get back `StringDataFrameColumn`. (Also seemed like a bad idea because it would preclude adding any other "special" DataFrameColumn types in the future).
I also thought it would be inconsistent to allow `DataFrameColumn.Create<int>("Foo")` but not have any counterpart for `String`. Please let me know if you disagree, if so I can add the other overloads back in.
=> Added static factory methods to DataFrameColumn 

Directory.Build.props
A change about a year ago (acc1d8fcc07e48e971170897e683ab202e491afe) changed the preview version identifier from `-preview2-<date>-#` to `-e<date>-#`, which means packages that haven't bumped their version have been producing newer packages with "lower" versions than the build on 2019-01-17.
This change bumps the default package version from 0.1.1 to 0.1.2, which will put all newer builds on top.  Packages that don't use the default version are unaffected.
=> Bump the package version so the builds are sorted right

corefxlab-base.yml, eng/Tests.ruleset, eng/Versions.props, tests/ALCProxy.Tests/ALCProxy.Tests.csproj, tests/ALCProxy.Tests/ALCProxyTests.cs, tests/Benchmarks/Benchmarks.csproj, tests/Directory.Build.props, tests/System.Buffers.Primitives.Tests/UsageScenarioTests.cs, tests/System.Memory.Polyfill.Tests/System.Memory.Polyfill.Tests.csproj
I think this is all we needed. Putting this up to test what happens in a public build
=> Pass in -ci and -test to CI

src/Microsoft.Data.Analysis/DataFrame.IO.cs, src/Microsoft.Data.Analysis/strings.Designer.cs, src/Microsoft.Data.Analysis/strings.resx, tests/Microsoft.Data.Analysis.Tests/DataFrame.IOTests.cs
We were dropping the column names when `DataTypes` was being passed in to `LoadCsv`. 
I suggest looking at the diff with whitespace turned off
=> Fix https://github.com/dotnet/corefxlab/issues/2906

src/Microsoft.Data.Analysis/DataFrame.IO.cs, src/Microsoft.Data.Analysis/DataFrame.cs, tests/Microsoft.Data.Analysis.Tests/DataFrame.IOTests.cs
Fixes #2915 
Instead of falling back to a `StringDataFrameColumn`, we now deduce the column type correctly and append a `null` value to whatever the column type becomes.
=> Improve LoadCsv to handle null values when deducing the column types

src/Microsoft.Data.Analysis/Microsoft.Data.Analysis.csproj
Sets the property back to false. The property should be left untouched. The right way to make a stable package is to set the DotNetFinalVersionKind property.
=> Revert "Create a 0.4.0 package (#2918)"

src/Microsoft.Data.Analysis/DataFrameColumnCollection.cs, tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
**Issue**
> If a DataFrame has 1 column of Length 0, and I insert a new column of Length > 0, InsertColumn should throw. It doesn't at the moment.
**Solution**
I have included an IF statement that will throw an exception if a new column of a length > 0 is inserted into a DataFrame that already has a column(s) that are of length 0. I have also included a test for this scenario.
=> resolution for #2746

src/System.Web.Compatibility/NotSupported.Exclude.txt, src/System.Web.Compatibility/Strings.Designer.cs, src/System.Web.Compatibility/Strings.resx, src/System.Web.Compatibility/System/Web/Routing/RequestContext.cs, src/System.Web.Compatibility/System/Web/Routing/RouteData.cs, src/System.Web.Compatibility/System/Web/Routing/RouteValueDictionary.cs, src/System.Web.Compatibility/System/Web/Routing/StopRoutingHandler.cs, tests/System.Web.Compatibility.Tests/RequestContextTests.cs, tests/System.Web.Compatibility.Tests/RouteDataTests.cs, tests/System.Web.Compatibility.Tests/StopRoutingHandlerTests.cs
The source was ported from desktop / reference-source.  Made minor cleanups.
Tests illustrate what was enabled.  Note the couple places where we can't exercise API's because we can't actually construct the types that they accept as parameters. cc @mjsabby
=> Add a few types to System.Web compat assembly

src/Microsoft.Data.Analysis/DataFrame.cs, src/Microsoft.Data.Analysis/DataFrameColumnCollection.cs, tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
Fixes https://github.com/dotnet/corefxlab/issues/2934
This change brings back the column name indexer on `DataFrame`. I modified a couple test cases to test the new getter and setter.
cc @Hamaze
=> ColumnName indexer on DataFrame

src/Microsoft.Data.Analysis/ArrowStringDataFrameColumn.cs, tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
**Issue**
FillNulls is not implemented for the ArrowStringDataFrameColumn Class.
**Solution**
I have followed guidance from @pgovind and implemented the FillNulls method when inPlace is false. This method does not yet work for inPlace: true. In the event that inPlace is true the method will throw a NotSupportedException.
A test case has been included.
Kind Regards,
Ramon
Fixes: #2756
=> Implement FillNulls() for ArrowStringDataFrameColumn with inPlace: false

src/Microsoft.Data.Analysis/DataFrame.cs, src/Microsoft.Data.Analysis/strings.Designer.cs, src/Microsoft.Data.Analysis/strings.resx, tests/Microsoft.Data.Analysis.Tests/DataFrameTests.cs
**Issue**
> The Sample method in DataFrame (code here) does not check if an index was already generated by rand. Most of the time I get duplicate rows because of it.
**Solution**
I have amended the Sample method to implement the Fisher-Yates shuffle so that the sample returned is unique and still random. Additions also include a new string resource so that an exception is throw if the sample size requested is greater than the number of rows. Tests for row uniqueness and the exception being thrown have been included also.
Kind Regards,
Ramon
Fixes: #2806
=> Prevent DataFrame.Sample() method from returning duplicated rows

src/Microsoft.Data.Analysis/DataFrame.IO.cs, tests/Microsoft.Data.Analysis.Tests/DataFrame.IOTests.cs
Fix for https://github.com/dotnet/corefxlab/issues/2979
Technically, one could specify the column types in `LoadCsv`, but I think this behavior of defaulting to a `StringDataFrameColumn` makes the API behave better.
=> Missing values default to a `StringDataFrameColumn`

src/Microsoft.Data.Analysis/DataFrame.Arrow.cs, src/Microsoft.Data.Analysis/Microsoft.Data.Analysis.csproj, tests/Microsoft.Data.Analysis.Tests/ArrayComparer.cs, tests/Microsoft.Data.Analysis.Tests/ArrowIntegrationTests.cs
2 things going on in this PR:
1. Update `FromArrowRecordBatch` just in case we have a `RecordBatch` with a `StructArray` in it. We'll flatten out the `StructArray` into a regular `DataFrame`. Once this goes in, I'll open another PR to update the version number for MDA.
2. Update the Arrow dependency to the latest version. This will prevent accidental "API not found" errors at runtime in the dotnet-spark repo. 
**OLD**
The following methods on `DataFrameColumn` are being made public:
1. GetArrowField
2. GetMaxRecordBatchLength
3. ToArrowArray
These 3 methods are the ones we need to support Spark 3.0.
There is an argument to be made here that these APIs should remain protected. The alternative we have here is to update just the existing `DataFrame.ToArrowRecordBatches()` method to return a …
=> Update FromArrowRecordBatches for dotnet-spark

src/Microsoft.Data.Analysis/DataFrame.IO.cs, tests/Microsoft.Data.Analysis.Tests/ArrowIntegrationTests.cs, tests/Microsoft.Data.Analysis.Tests/DataFrame.IOTests.cs
Fixes https://github.com/dotnet/corefxlab/issues/2984
=> Implement DataFrame.LoadCsvFromString

src/Microsoft.Data.Analysis/TextFieldParser.cs, tests/Microsoft.Data.Analysis.Tests/TextFieldParserTests.cs
I have the whole thing working locally, but I split it up for easier review. This PR is part 1 of 2. This part sets up the TextFieldParser class with configurations for delimited/fixed-width files and implements reading the lines into memory. 
Part 2 will implement `public ReadFields()` that will parse the lines that are read in and return individual fields from each line.
=> Support for delimited/fixed-width fields in a text file
